// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/Accessor ../../../../../core/byteSizeEstimations ../../../../../core/maybe ../../../../../core/accessorSupport/decorators/property ../../../../../core/has ../../../../../core/accessorSupport/ensureType ../../../../../core/Logger ../../../../../core/accessorSupport/decorators/subclass ../../../../../geometry/support/aaBoundingRect ../../../../../layers/graphics/featureConversionUtils ../../../../../layers/graphics/data/BoundsStore ../../../../../rest/query/operations/query ./FeatureServiceTileCache".split(" "),
function(p,r,t,A,w,k,u,J,K,L,B,q,C,D,E,F){function G(l){return l.reduce((f,d)=>{var a=d.geometry;if(k.isNone(a))a=0;else{var b=w.estimateFixedArraySize(a.lengths,4);a=32+w.estimateFixedArraySize(a.coords,8)+b}d=32+a+w.estimateAttributesObjectSize(d.attributes);return f+d},0)}p.FeatureServiceTileStore=function(l){function f(a){a=l.call(this,a)||this;a.tileInfo=null;a.extent=null;a.maximumByteSize=10485760;a.tileBounds=new D.BoundsStore;a.tiles=new F.FeatureServiceTileCache;a.refCounts=new Map;a.tileFeatureCounts=
new Map;a.tmpBoundingRect=q.create();return a}r._inheritsLoose(f,l);var d=f.prototype;d.add=function(a,b){const c=[];for(const e of b)0===this.referenceFeature(e.objectId)&&c.push(e);this.addTileStorage(a,new Set(b.map(({objectId:e})=>e)),G(b));this.featureStore.addMany(c);this.tiles.applyByteSizeLimit(this.maximumByteSize,e=>this.removeTileStorage(e))};d.destroy=function(){this.clear();this.tileFeatureCounts.clear()};d.clear=function(){this.featureStore.clear();this.tileBounds.clear();this.tiles.clear();
this.refCounts.clear()};d.refresh=function(){this.clear();this.tileFeatureCounts.clear()};d.processEdits=function(a,b,c){this.processEditsDelete(a.deletedFeatures.concat(a.updatedFeatures));return this.processEditsRefetch(a.addedFeatures.concat(a.updatedFeatures),b,c)};d.addTileStorage=function(a,b,c){this.tiles.set(a.id,new H(a,b,c));this.tileBounds.set(a.id,a.extent);this.tileFeatureCounts.set(a.id,b.size)};d.remove=function({id:a}){(a=this.tiles.get(a))&&this.removeTileStorage(a)};d.removeTileStorage=
function(a){const b=[];for(const c of a.objectIds)1===this.unreferenceFeature(c)&&b.push(c);this.featureStore.removeManyById(b);a=a.data.id;this.tiles.delete(a);this.tileBounds.delete(a)};d.processEditsDelete=function(a){this.featureStore.removeManyById(a);for(const [,b]of this.tiles){for(const c of a)b.objectIds.delete(c);this.tileFeatureCounts.set(b.data.id,b.objectIds.size)}for(const b of a)this.refCounts.delete(b)};d.processEditsRefetch=function(){var a=r._asyncToGenerator(function*(b,c,e){b=
(yield c(b,e)).features;const {hasZ:g,hasM:h}=this.featureStore;for(const n of b)b=C.getBoundsOptimizedGeometry(this.tmpBoundingRect,n.geometry,g,h),k.isNone(b)||this.tileBounds.forEachInBounds(b,m=>{m=this.tiles.get(m);this.featureStore.add(n);m.objectIds.has(n.objectId)||(m.objectIds.add(n.objectId),this.referenceFeature(n.objectId),this.tileFeatureCounts.set(m.data.id,m.objectIds.size))})});return function(b,c,e){return a.apply(this,arguments)}}();d.process=function(a,b=()=>!0){if(k.isNone(this.tileInfo)||
!a.extent||k.isSome(this.extent)&&!q.intersects(q.fromExtent(this.extent,this.tmpBoundingRect),a.extent)||this.tiles.has(a.id))return new x(a);const c=this.createTileTree(a,this.tileInfo);this.simplify(c,b,null,0,1);return this.collectMissingTiles(a,c,this.tileInfo)};d.getFeatureCount=function(a){a=this.tileFeatureCounts.get(a.id);return null!=a?a:0};d.fetchCount=function(){var a=r._asyncToGenerator(function*(b,c,e,g){const h=this.tileFeatureCounts.get(b.id);if(null!=h)return h;c=yield E.executeQueryForCount(c,
e,g);this.tileFeatureCounts.set(b.id,c.data.count);return c.data.count});return function(b,c,e,g){return a.apply(this,arguments)}}();d.createTileTree=function(a,b){const c=new y(a.level,a.row,a.col);b.updateTileInfo(c,1);this.tileBounds.forEachInBounds(a.extent,e=>{e=this.tiles.get(e).data;this.tilesAreRelated(a,e)&&this.populateChildren(c,e,b,this.tileFeatureCounts.get(e.id)||0)});return c};d.tilesAreRelated=function(a,b){if(!a||!b)return!1;if(a.level===b.level)return a.row===b.row&&a.col===b.col;
const c=a.level<b.level,e=c?a:b;a=c?b:a;b=1<<a.level-e.level;return Math.floor(a.row/b)===e.row&&Math.floor(a.col/b)===e.col};d.populateChildren=function(a,b,c,e){var g=b.level-a.level-1;if(0>g)a.isLeaf=!0;else{var h=b.row>>g,n=b.col>>g;g=(h-(a.row<<1)<<1)+(n-(a.col<<1));var m=a.children[g];k.isSome(m)?this.populateChildren(m,b,c,e):(h=new y(a.level+1,h,n),c.updateTileInfo(h,1),a.children[g]=h,this.populateChildren(h,b,c,e))}};d.simplify=function(a,b,c,e,g){const h=g*g;if(a.isLeaf)return b(this.getFeatureCount(a),
g)?0:(this.remove(a),k.isSome(c)&&(c.children[e]=null),h);g/=2;const n=g*g;let m=0;for(let v=0;v<a.children.length;v++){const z=a.children[v];m+=k.isSome(z)?this.simplify(z,b,a,v,g):n}0===m?this.mergeChildren(a):.18751>1-m/h&&(this.purge(a),k.isSome(c)&&(c.children[e]=null),m=h);return m};d.mergeChildren=function(a){const b=new Set;let c=0;this.forEachLeaf(a,e=>{const g=this.tiles.get(e.id);if(g){c+=g.byteSize;for(const h of g.objectIds)b.has(h)||(b.add(h),this.referenceFeature(h));this.remove(e)}});
this.addTileStorage(a,b,c);a.isLeaf=!0;a.children[0]=a.children[1]=a.children[2]=a.children[3]=null;this.tileFeatureCounts.set(a.id,b.size)};d.forEachLeaf=function(a,b){for(const c of a.children)k.isNone(c)||(c.isLeaf?b(c):this.forEachLeaf(c,b))};d.purge=function(a){if(!k.isNone(a))if(a.isLeaf)this.remove(a);else for(let b=0;b<a.children.length;b++)this.purge(a.children[b]),a.children[b]=null};d.collectMissingTiles=function(a,b,c){a=new I(c,a,this.extent);this.collectMissingTilesRecurse(b,a,1);return a.info};
d.collectMissingTilesRecurse=function(a,b,c){if(!a.isLeaf)if(a.hasChildren){c/=2;for(let e=0;e<a.children.length;e++){const g=a.children[e];k.isNone(g)?b.addMissing(a.level+1,(a.row<<1)+((e&2)>>1),(a.col<<1)+(e&1),c):this.collectMissingTilesRecurse(g,b,c)}}else b.addMissing(a.level,a.row,a.col,c)};d.referenceFeature=function(a){const b=(this.refCounts.get(a)||0)+1;this.refCounts.set(a,b);return 1===b?0:2};d.unreferenceFeature=function(a){const b=(this.refCounts.get(a)||0)-1;if(0===b)return this.refCounts.delete(a),
1;0<b&&this.refCounts.set(a,b);return 2};r._createClass(f,[{key:"debugInfo",get:function(){return Array.from(this.tiles.values()).map(({data:a})=>({data:a,featureCount:this.tileFeatureCounts.get(a.id)||0}))}},{key:"test",get:function(){return{tiles:Array.from(this.tiles.values()).map(a=>`${a.data.id}:[${Array.from(a.objectIds)}]`),featureReferences:Array.from(this.refCounts.keys()).map(a=>`${a}:${this.refCounts.get(a)}`)}}}]);return f}(A);t.__decorate([u.property({constructOnly:!0})],p.FeatureServiceTileStore.prototype,
"featureStore",void 0);t.__decorate([u.property()],p.FeatureServiceTileStore.prototype,"tileInfo",void 0);t.__decorate([u.property()],p.FeatureServiceTileStore.prototype,"extent",void 0);t.__decorate([u.property()],p.FeatureServiceTileStore.prototype,"maximumByteSize",void 0);p.FeatureServiceTileStore=t.__decorate([B.subclass("esri.views.interactive.snapping.featureSources.featureServiceSource.FeatureServiceTileStore")],p.FeatureServiceTileStore);let H=function(l,f,d){this.data=l;this.objectIds=f;
this.byteSize=d},y=function(){function l(f,d,a){this.level=f;this.row=d;this.col=a;this.isLeaf=!1;this.extent=null;this.children=[null,null,null,null]}r._createClass(l,[{key:"hasChildren",get:function(){return!this.isLeaf&&(k.isSome(this.children[0])||k.isSome(this.children[1])||k.isSome(this.children[2])||k.isSome(this.children[3]))}}]);return l}(),x=function(){function l(f,d=[]){this.missingTiles=d;this.coveredArea=this.fullArea=0;this.coveredArea=this.fullArea=q.area(f.extent)}l.prototype.prepend=
function(f){this.missingTiles=f.missingTiles.concat(this.missingTiles);this.coveredArea+=f.coveredArea;this.fullArea+=f.fullArea};return l}(),I=function(){function l(f,d,a){this.tileInfo=f;this.extent=null;this.info=new x(d);k.isSome(a)&&(this.extent=q.fromExtent(a))}l.prototype.addMissing=function(f,d,a,b){f={id:null,level:f,row:d,col:a};this.tileInfo.updateTileInfo(f,1);!k.isSome(f.extent)||k.isSome(this.extent)&&!q.intersects(this.extent,f.extent)||(this.info.missingTiles.push({data:f,resolution:b}),
this.info.coveredArea-=q.area(f.extent))};return l}();p.ProcessResult=x;Object.defineProperty(p,"__esModule",{value:!0})});