// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../Graphic ../../../core/Accessor ../../../core/arrayUtils ../../../core/Collection ../../../core/Error ../../../core/lang ../../../core/Logger ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/ensureType ../../../core/has ../../../core/accessorSupport/decorators/subclass ../../../rest/support/AttachmentQuery".split(" "),function(g,k,C,h,u,y,v,D,E,l,J,K,F,G){function z(w,p,e){H.error(new v(w,
p,e))}const H=E.getLogger("esri.widgets.FeatureTable.support.FeatureStore");h=function(w){function p(b){b=w.call(this,b)||this;b._loaded=!1;b._loadError=!1;b._loading=!1;b._editOperationQueue=[];b._queryOperationQueue=[];b._objectIds=new y;b._hasStaleCache=!1;b.count=0;b.failures=new y;b.itemCache=new y;b.relatedRecordsEnabled=!1;return b}g._inheritsLoose(p,w);var e=p.prototype;e.destroy=function(){this.layer=null;this.itemCache&&this.itemCache.destroy();this.failures&&this.failures.destroy();this._set("itemCache",
null)};e.load=function(){var b=g._asyncToGenerator(function*(){this._reset();const {layer:a}=this;if(!a)return Promise.resolve();this._loading=!0;this.notifyChange("state");try{yield a.when(),yield this._syncLayerInfo(),this._loading=!1,this._loaded=!0,this.notifyChange("state")}catch(c){throw this._reset(),this._loadError=!0,this.notifyChange("state"),z("store:load-error","An error ocurred.",{error:c}),c;}});return function(){return b.apply(this,arguments)}}();e.addItems=function(){var b=g._asyncToGenerator(function*(a){});
return function(a){return b.apply(this,arguments)}}();e.fetchItems=function(){var b=g._asyncToGenerator(function*(a){const {page:c,pageSize:d}=a;a=c*d;const f=a+d,{layer:n,state:m}=this;if(!n||"loaded"!==m)return Promise.resolve([]);this.notifyChange("querying");a=yield this._query({start:a,num:f,page:c,pageSize:d});this.notifyChange("state");return a});return function(a){return b.apply(this,arguments)}}();e.query=function(){var b=g._asyncToGenerator(function*(a){const {layer:c,state:d}=this;if(!c||
"loaded"!==d)return[];this.notifyChange("querying");a=yield this._query(a);this.notifyChange("state");return a});return function(a){return b.apply(this,arguments)}}();e.removeItemAt=function(){var b=g._asyncToGenerator(function*(a){});return function(a){return b.apply(this,arguments)}}();e.reset=function(){var b=g._asyncToGenerator(function*(){this._reset()});return function(){return b.apply(this,arguments)}}();e.updateItem=function(){var b=g._asyncToGenerator(function*(a){return this._update(a)});
return function(a){return b.apply(this,arguments)}}();e.getItemByObjectId=function(b){const {itemCache:a,layer:{objectIdField:c}}=this;return a.find(d=>d.feature.attributes[c]===b)};e.getLocalItemAt=function(b){return this.itemCache.getItemAt(b)};e.getItemAt=function(b){return Promise.resolve(this.itemCache.getItemAt(b))};e.getObjectIdIndex=function(b){const {itemCache:a,layer:{objectIdField:c}}=this;return a.findIndex(d=>d.feature.attributes[c]===b)};e._reset=function(){this.itemCache.removeAll();
this.failures.removeAll();this._editOperationQueue=[];this._queryOperationQueue=[];this._loadError=this._loaded=this._loading=this._hasStaleCache=!1;this._set("count",0);this._objectIds.removeAll();this.notifyChange("querying");this.notifyChange("syncing");this.notifyChange("state")};e._getIdsFromFeatures=function(b){return b.map(a=>a.attributes[this.layer.objectIdField])};e._toFeatureData=function(b,a){const {layer:{objectIdField:c}}=this;return b.map(d=>{var {attributes:f}=d;f=f[c];return{objectId:f,
feature:d,attachments:a?a[f]:null,relatedRecords:null}})};e._update=function(){var b=g._asyncToGenerator(function*(a){const {layer:c}=this,{operations:d}=c.capabilities;if(!d.supportsUpdate||"wfs"===c.type||"imagery"===c.type)throw new v("store:update-error","Update is not supported.");const {index:f,name:n,value:m}=a;a=yield this.getItemAt(f);if(!a||!a.feature)throw new v("store:update-error","Feature with provided 'objectId' not found.");const {feature:x}=a,q=D.clone(x.attributes);q[n]=m;a=new C({attributes:q});
const t=c.applyEdits({updateFeatures:[a]}).then(r=>{const {updateFeatureResults:A}=r,B=A.find(I=>!!I.error);if(B)throw B.error;-1<this._editOperationQueue.indexOf(()=>t)&&A&&A.length&&(x.attributes=q);return r});return this._queueEditOperation(()=>t)});return function(a){return b.apply(this,arguments)}}();e._query=function(){var b=g._asyncToGenerator(function*(a){const {refresh:c}=a;if(!0===c)return this.itemCache.removeAll(),this._syncLayerInfo().then(()=>this._queryFeatureData(a));this._hasStaleCache&&
(yield this._updateIds(),this._hasStaleCache=!1);return this._queryFeatureData(a)});return function(a){return b.apply(this,arguments)}}();e._queryFeatureData=function(){var b=g._asyncToGenerator(function*(a){var c=this;return this._queueQueryOperation(g._asyncToGenerator(function*(){const {features:d}=yield c._queryFeatures(a);var f=c._getIdsFromFeatures(d);f=yield c._queryAttachments(f);return c._toFeatureData(d,f)||[]}))});return function(a){return b.apply(this,arguments)}}();e._syncLayerInfo=function(){var b=
g._asyncToGenerator(function*(){yield this._updateCount();yield this._updateIds()});return function(){return b.apply(this,arguments)}}();e._updateCount=function(){var b=g._asyncToGenerator(function*(){yield this._queryCount().then(a=>this._set("count",a))});return function(){return b.apply(this,arguments)}}();e._updateIds=function(){var b=g._asyncToGenerator(function*(){var a,c,d;null!=(a=this.layer)&&null!=(c=a.capabilities)&&null!=(d=c.query)&&d.supportsPagination||(this._objectIds.removeAll(),
yield this._queryObjectIds().then(f=>this._objectIds.addMany(f)))});return function(){return b.apply(this,arguments)}}();e._queryCount=function(){const {filterGeometry:b,layer:a,returnGeometry:c}=this,d=a.createQuery();d.geometry=b;d.returnGeometry=c;d.where=this._getWhere();return a.queryFeatureCount(d)};e._queryObjectIds=function(){const {filterGeometry:b,layer:a,orderByFields:c,returnGeometry:d}=this,{capabilities:{query:{supportsCacheHint:f,supportsOrderBy:n}}}=a;if("geojson"===a.type||"wfs"===
a.type||"imagery"===a.type)return Promise.resolve([]);const m=a.createQuery();m.geometry=b;m.outFields=[a.objectIdField];m.returnGeometry=d;m.where=this._getWhere();n&&(m.orderByFields=c);f&&(m.cacheHint=!0);return a.queryObjectIds(m)};e._queryFeatures=function(){var b=g._asyncToGenerator(function*(a){const {layer:c}=this;if(!c.capabilities.operations.supportsQuery)return Promise.reject(new v("store:query-error","Layer does not support query operation."));const {filterGeometry:d,layer:{capabilities:{query:{supportsCacheHint:f,
supportsOrderBy:n,supportsPagination:m}}},orderByFields:x,returnGeometry:q}=this,{start:t,pageSize:r}=a;a=c.createQuery();a.returnGeometry=q;m?(a.start=t,a.num=r,a.where=this._getWhere()):a.objectIds=this._getObjectIdsForPage(t,r);n&&(a.orderByFields=x);d&&(a.geometry=d);f&&(a.cacheHint=!0);return c.queryFeatures(a)});return function(a){return b.apply(this,arguments)}}();e._getObjectIdsForPage=function(b,a){const c=this._objectIds.toArray();return c.length>=b+a?c.slice(b,b+a):c.slice(b)};e._queryAttachments=
function(b){const {attachmentsEnabled:a,layer:c}=this,{capabilities:{data:{supportsAttachment:d},operations:{supportsQueryAttachments:f}}}=c;return a&&d&&f&&"geojson"!==c.type&&"wfs"!==c.type&&"imagery"!==c.type?c.queryAttachments(new G({objectIds:b,where:this._getWhere()})):Promise.resolve(null)};e._queueQueryOperation=function(b){this._queryOperationQueue.push(b);this.notifyChange("querying");return b().then(a=>-1<this._queryOperationQueue.indexOf(b)?(this.itemCache.addMany(a),a):[]).catch(a=>{z("store:query-error",
"An error ocurred.",{error:a});const c={error:a,retry:()=>{this.failures.remove(c);this._queueQueryOperation(b)},cancel:()=>this.failures.remove(c)};this.failures.add(c);return[]}).then(a=>{u.remove(this._queryOperationQueue,b);this.notifyChange("querying");return a})};e._queueEditOperation=function(b){this._editOperationQueue.push(b);this.notifyChange("syncing");return b().then(()=>{u.remove(this._editOperationQueue,b);this.notifyChange("syncing")}).catch(a=>{z("store:edit-error","An error ocurred.",
{error:a});const c={error:a,retry:()=>{this.failures.remove(c);this._queueEditOperation(b)},cancel:()=>this.failures.remove(c)};this.failures.add(c);u.remove(this._editOperationQueue,b);this.notifyChange("syncing");throw a;})};e._getWhere=function(){return this.where||this.layer.definitionExpression||"1\x3d1"};g._createClass(p,[{key:"attachmentsEnabled",set:function(b){this._reset();this._set("attachmentsEnabled",b);this.notifyChange("state")}},{key:"filterGeometry",set:function(b){this._reset();
this._set("filterGeometry",b);this.notifyChange("state")}},{key:"layer",set:function(b){this._reset();this._set("layer",b);this.notifyChange("state")}},{key:"orderByFields",get:function(){return this._get("orderByFields")||[]},set:function(b){u.equals(b,this.orderByFields)||(this.itemCache.removeAll(),this._hasStaleCache=!0,this._set("orderByFields",b))}},{key:"querying",get:function(){return 0<this._queryOperationQueue.length}},{key:"returnGeometry",set:function(b){this._reset();this._set("returnGeometry",
b);this.notifyChange("state")}},{key:"state",get:function(){const {layer:b,_loaded:a,_loadError:c,_loading:d}=this;return c?"error":!b||this.get("layer.loadError")?"disabled":d?"loading":"loaded"===this.get("layer.loadStatus")&&a?"loaded":"ready"}},{key:"syncing",get:function(){return 0<this._editOperationQueue.length}},{key:"where",get:function(){return this._get("where")||null},set:function(b){this._reset();this._set("where",b);this.notifyChange("state")}}]);return p}(h);k.__decorate([l.property()],
h.prototype,"attachmentsEnabled",null);k.__decorate([l.property({readOnly:!0})],h.prototype,"count",void 0);k.__decorate([l.property({readOnly:!0})],h.prototype,"failures",void 0);k.__decorate([l.property()],h.prototype,"filterGeometry",null);k.__decorate([l.property({readOnly:!0})],h.prototype,"itemCache",void 0);k.__decorate([l.property({value:null})],h.prototype,"layer",null);k.__decorate([l.property()],h.prototype,"orderByFields",null);k.__decorate([l.property({readOnly:!0})],h.prototype,"querying",
null);k.__decorate([l.property()],h.prototype,"relatedRecordsEnabled",void 0);k.__decorate([l.property({value:!1})],h.prototype,"returnGeometry",null);k.__decorate([l.property({readOnly:!0})],h.prototype,"state",null);k.__decorate([l.property({readOnly:!0})],h.prototype,"syncing",null);k.__decorate([l.property()],h.prototype,"where",null);return h=k.__decorate([F.subclass("esri.widgets.FeatureTable.support.FeatureStore")],h)});