// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../geometry ../../../../../core/Evented ../../../../../core/has ../../../../../core/maybe ../../../../../core/accessorSupport/diffUtils ../../../../../geohash/GeohashTree ../../../../../geohash/geohashUtils ../../../../../geometry/support/Ellipsoid ../../../../../geometry/support/spatialReferenceUtils ../../../../../layers/graphics/featureConversionUtils ../../../../../layers/graphics/OptimizedFeature ../../../../../layers/graphics/OptimizedGeometry ../../../../../layers/graphics/data/projectionSupport ../../../engine/webgl/definitions ../Store2D ./FeatureSetReaderJSON ../../../../../geometry/SpatialReference".split(" "),
function(H,B,J,Q,K,w,L,R,C,x,S,M,N,T,D,p,U,V,E){let O=function(y){function q(b,a,c,d,e){a=new T([],[a,c]);b=y.call(this,a,d,null,b)||this;b.geohashBoundsInfo=e;return b}B._inheritsLoose(q,y);q.create=function(b,a,c,d,e,g,l,m){a=new q(a,c,d,g,l);a.displayId=b.createDisplayId(!0);a.referenceId=m;a.tileLevel=e;return a};var f=q.prototype;f.update=function(b,a,c,d,e,g){this.geometry.coords[0]=b;this.geometry.coords[1]=a;this.tileLevel=c;this.attributes=d;this.geohashBoundsInfo=e;this.referenceId=null;
this.referenceId=g;return this};f.toJSON=function(){return{objectId:this.objectId,referenceId:1===this.attributes.cluster_count?this.referenceId:null,attributes:{...this.attributes,clusterId:this.objectId},geometry:{x:this.geometry.coords[0],y:this.geometry.coords[1]}}};B._createClass(q,[{key:"count",get:function(){return this.attributes.cluster_count}}]);return q}(N.OptimizedFeatureWithGeometry);J=function(y){function q(b,a,c){var d=y.call(this,b,c)||this;d.events=new Q;d._geohashLevel=0;d._tileLevel=
0;d._aggregateValueRanges={};d._aggregateValueRangesChanged=!1;d._geohashBuf=[];d._clusters=new Map;d._tiles=new Map;d.geometryInfo=b.geometryInfo;d._spatialReference=a;d._projectionSupportCheck=D.checkProjectionSupport(a,E.WGS84);d._bitsets.geohash=c.getBitset(c.createBitset());d._bitsets.inserted=c.getBitset(c.createBitset());return d}B._inheritsLoose(q,y);var f=q.prototype;f.updateSchema=function(){var b=B._asyncToGenerator(function*(a,c){const d=this._schema;try{yield y.prototype.updateSchema.call(this,
a,c),yield this._projectionSupportCheck}catch(g){}const e=L.diff(d,c);if(!c||w.isNone(e)&&!a.source&&!a.storage.filters)d&&(a.mesh=!0);else{if(L.hasDiff(e,"params.fields")||!this._tree||a.source)this._tree=new R.GeohashTree(this._statisticFields),this._rebuildTree(),K("esri-2d-update-debug")&&console.debug("Aggregate mesh needs update due to tree changing");K("esri-2d-update-debug")&&console.debug("Applying Update - ClusterStore:",e);a.targets[c.name]=!0;a.mesh=!1;this._aggregateValueRanges={}}});
return function(a,c){return b.apply(this,arguments)}}();f.clear=function(){this._rebuildTree()};f.sweepFeatures=function(b,a){this._bitsets.inserted.forEachSet(c=>{b.has(c)||(c=a.lookupByDisplayIdUnsafe(c),this._remove(c))})};f.sweepClusters=function(b,a,c){this._clusters.forEach((d,e)=>{d&&d.tileLevel!==c&&(b.releaseDisplayId(d.displayId),a.unsetAttributeData(d.displayId),this._clusters.delete(e))})};f.onTileData=function(b,a,c,d,e=!0){if(!this._schema||w.isNone(a.addOrUpdate))return a;var g=this._getTransforms(b,
this._spatialReference);{const l=a.addOrUpdate.getCursor();for(;l.next();)this._update(l,d)}if(a.status.mesh||!e)return a;d=[];this._getClustersForTile(d,b,this._schema.params.clusterRadius,c,g);a.addOrUpdate=V.FeatureSetReaderJSON.fromOptimizedFeatures(d,"esriGeometryPoint");a.addOrUpdate.attachStorage(c);a.end=!0;for(g=a.addOrUpdate.getCursor();g.next();)d=g.getDisplayId(),this._bitsets.computed.unset(d),this.setComputedAttributes(c,g,d,b.scale);this._aggregateValueRangesChanged&&a.end&&(this.events.emit("valueRangesChanged",
{valueRanges:this._aggregateValueRanges}),this._aggregateValueRangesChanged=!1);return a};f.onTileUpdate=function({added:b,removed:a}){b.length&&(this._tileLevel=b=b[0].level,this._setGeohashLevel(b));if(this._schema){var c=this._schema.params.clusterRadius;a.forEach(d=>{this._tiles.delete(d.key.id);this._markTileClustersForDeletion(d,c)})}};f.getAggregate=function(b){let a=null;this._clusters.forEach(c=>{c&&c.displayId===b&&(a=c.toJSON())});return a};f.getAggregates=function(){const b=[];this._clusters.forEach(a=>
{a&&a.tileLevel===this._tileLevel&&b.push(a.toJSON())});return b};f.getDisplayId=function(b){return(b=this._clusters.get(b))?b.displayId:null};f.getFeatureDisplayIdsForAggregate=function(b){b=this._clusters.get(b);if(!b)return[];b=b.geohashBoundsInfo;return this._tree.getRegionDisplayIds(b.xLL,b.yLL,b.xTR,b.yTR,b.level)};f.getDisplayIdForReferenceId=function(b){let a;this._clusters.forEach(c=>{c&&c.referenceId===b&&(a=c.displayId)});return a};f.getAggregateValueRanges=function(){return this._aggregateValueRanges};
f.forEach=function(b){this._clusters.forEach((a,c)=>{a&&b(a,c)})};f.size=function(){let b=0;this.forEach(a=>b++);return b};f._rebuildTree=function(){this._bitsets.computed.clear();this._bitsets.inserted.clear();this._tree&&this._tree.clear()};f._remove=function(b){const a=b.getDisplayId(),c=b.getXHydrated(),d=b.getYHydrated(),e=this._geohashBuf[2*a],g=this._geohashBuf[2*a+1];this._bitsets.inserted.has(a)&&(this._bitsets.inserted.unset(a),this._tree.removeCursor(b,c,d,e,g,this._geohashLevel))};f._update=
function(b,a){const c=b.getDisplayId(),d=this._bitsets.inserted;a=a.isVisible(c);var e=d.has(c);a!==e&&(a?(a=b.getXHydrated(),e=b.getYHydrated(),this._setGeohash(c,a,e)&&(this._tree.insertCursor(b,c,a,e,this._geohashBuf[2*c],this._geohashBuf[2*c+1],this._geohashLevel),d.set(c))):this._remove(b))};f._setGeohash=function(b,a,c){if(this._bitsets.geohash.has(b))return!0;const d=this._geohashBuf;if(this._spatialReference.isWebMercator)a=a/x.earth.radius*57.29577951308232,C.setGeohashBuf(d,b,57.29577951308232*
(Math.PI/2-2*Math.atan(Math.exp(-c/x.earth.radius))),a-360*Math.floor((a+180)/360),12);else{c=D.project({x:a,y:c},this._spatialReference,E.WGS84);if(!c)return!1;C.setGeohashBuf(d,b,c.y,c.x,12)}this._bitsets.geohash.set(b);return!0};f._getClustersForTile=function(b,a,c,d,e,g=!0){var l=this._schema.params.clusterPixelBuffer,m=2*c;c=this._getGeohashLevel(a.key.level);const z=Math.ceil(2**a.key.level*p.TILE_SIZE/m);var t=Math.ceil(l/m)+0,r=Math.ceil(p.TILE_SIZE/m);const {row:F,col:u}=a.key;var h=Math.floor(u*
p.TILE_SIZE/m)-t;m=Math.floor(F*p.TILE_SIZE/m)-t;l=h+r+2*t;t=m+r+2*t;for(r=a.tileInfoView.getLODInfoAt(a.key.level);h<=l;h++)for(let A=m;A<=t;A++){var k=h;r.wrap&&(k=0>h?h+z:h%z);const I=r.wrap&&0>h,G=r.wrap&&h%z!==h;k=this._lookupCluster(d,r,a.key.level,k,A,c);if(w.isSome(k)){var n=w.andThen(e,v=>I?v.left:G?v.right:v.tile);if((!g||!w.isNone(n))&&k.count&&w.isSome(n)&&g){const v=k.geometry.clone();let P=k.attributes;v.coords[0]=M.quantizeX(n,v.coords[0]);v.coords[1]=M.quantizeY(n,v.coords[1]);1===
k.count&&w.isSome(k.referenceId)&&(P={...k.attributes,referenceId:k.referenceId});n=new N["default"](v,P);n.displayId=k.displayId;b.push(n)}}}};f._getGeohashLevel=function(b){return Math.min(Math.ceil(b/2+2),12)};f._setGeohashLevel=function(b){b=this._getGeohashLevel(b);b=1*(Math.floor(b/1)+1)-1;this._geohashLevel!==b&&(this._geohashLevel=b,this._rebuildTree(),this._bitsets.geohash.clear())};f._getTransforms=function(b,a){const c={originPosition:"upperLeft",scale:[b.resolution,b.resolution],translate:[b.bounds[0],
b.bounds[3]]};a=S.getInfo(a);if(!a)return{tile:c,left:null,right:null};const [d,e]=a.valid;return{tile:c,left:{...c,translate:[e,b.bounds[3]]},right:{...c,translate:[d-e+b.bounds[0],b.bounds[3]]}}};f._getClusterId=function(b,a,c){return(b&15)<<28|(a&16383)<<14|c&16383};f._markForDeletion=function(b,a,c){b=this._getClusterId(b,a,c);this._clusters.delete(b)};f._getClusterBounds=function(b,a,c){var d=this._schema.params.clusterRadius,e=2*d;a=c%2?a*e:a*e-d;const g=c*e;d=a+e;c=2**b.level*p.TILE_SIZE;b.wrap&&
0>a&&(a=0);b.wrap&&d>c&&(d=c);c=g/p.TILE_SIZE;d/=p.TILE_SIZE;e=(g-e)/p.TILE_SIZE;a=b.getXForColumn(a/p.TILE_SIZE);c=b.getYForRow(c);d=b.getXForColumn(d);b=b.getYForRow(e);return[a,c,d,b]};f._lookupCluster=function(b,a,c,d,e,g){const l=this._getClusterId(c,d,e),m=this._clusters.get(l),[z,t,r,F]=this._getClusterBounds(a,d,e);var u={x:z,y:t};e={x:r,y:F};var h=d=a=0,k=0;if(this._spatialReference.isWebMercator)a=u.x/x.earth.radius*57.29577951308232,a-=360*Math.floor((a+180)/360),d=57.29577951308232*(Math.PI/
2-2*Math.atan(Math.exp(-u.y/x.earth.radius))),h=e.x/x.earth.radius*57.29577951308232,h-=360*Math.floor((h+180)/360),k=57.29577951308232*(Math.PI/2-2*Math.atan(Math.exp(-e.y/x.earth.radius)));else{d=D.project(u,this._spatialReference,E.WGS84);e=D.project(e,this._spatialReference,E.WGS84);if(!d||!e)return null;a=d.x;d=d.y;h=e.x;k=e.y}u={geohashX:0,geohashY:0};e={geohashX:0,geohashY:0};C.setGeohashXY(u,d,a,g);C.setGeohashXY(e,k,h,g);d=u.geohashX;h=u.geohashY;k=e.geohashX;e=e.geohashY;a={xLL:d,yLL:h,
xTR:k,yTR:e,level:g};e=this._tree.getRegionStatistics(d,h,k,e,g);const {count:n,xTotal:A,yTotal:I,referenceId:G}=e;g=n?A/n:0;d=n?I/n:0;if(0===n)return this._clusters.set(l,null),null;e={cluster_count:n,...e.attributes};b=w.isSome(m)?m.update(g,d,c,e,a,G):O.create(b,l,g,d,c,e,a,G);0===n&&(b.geometry.coords[0]=(z+r)/2,b.geometry.coords[1]=(t+F)/2);this._clusters.set(l,b);this._updateAggregateValueRangeForCluster(b,b.tileLevel);return b};f._updateAggregateValueRangeForCluster=function(b,a){const c=this._aggregateValueRanges[a]||
{minValue:Infinity,maxValue:0},d=c.minValue,e=c.maxValue;c.minValue=Math.min(d,b.count);c.maxValue=Math.max(e,b.count);this._aggregateValueRanges[a]=c;if(d!==c.minValue||e!==c.maxValue)this._aggregateValueRangesChanged=!0};f._markTileClustersForDeletion=function(b,a){var c=2*a;a=Math.ceil(p.TILE_SIZE/c);const {row:d,col:e}=b.key,g=Math.floor(e*p.TILE_SIZE/c);c=Math.floor(d*p.TILE_SIZE/c);for(let l=g;l<g+a;l++)for(let m=c;m<c+a;m++)this._markForDeletion(b.key.level,l,m)};return q}(U.Store2D);H.ClusterInfo=
O;H.ClusterStore=J;Object.defineProperty(H,"__esModule",{value:!0})});