// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../renderers/ClassBreaksRenderer ../../renderers/DictionaryRenderer ../../renderers/DotDensityRenderer ../../renderers/HeatmapRenderer ../../renderers/Renderer ../../renderers/SimpleRenderer ../../renderers/UniqueValueRenderer ../../renderers/support/jsonUtils ../../core/Error ../../core/maybe ../heuristics/outline ../heuristics/sizeRange ./support/utils ../support/adapters/support/layerUtils ../../chunks/location".split(" "),function(u,m,
E,F,G,H,I,x,J,K,g,n,y,z,h,k,p){function A(a){return q.apply(this,arguments)}function q(){q=m._asyncToGenerator(function*(a){if(!a||!a.layer)throw new g("location-renderer:missing-parameters","'layer' parameter is required");a={...a};a.symbolType=a.symbolType||"2d";var b=k.createLayerAdapter(a.layer,k.featureCapableLayerTypes);a.layer=b;if(!b)throw new g("location-renderer:invalid-parameters","'layer' must be one of these types: "+k.getLayerTypeLabels(k.featureCapableLayerTypes).join(", "));const d=
n.isSome(a.signal)?{signal:a.signal}:null;yield b.load(d);b=b.geometryType;a.outlineOptimizationEnabled="polygon"===b?a.outlineOptimizationEnabled:!1;a.sizeOptimizationEnabled="point"===b||"multipoint"===b||"polyline"===b?a.sizeOptimizationEnabled:!1;if("mesh"===b)a.symbolType="3d-volumetric",a.colorMixMode=a.colorMixMode||"replace",a.edgesType=a.edgesType||"none";else{if("3d-volumetric-uniform"===a.symbolType&&"point"!==b)throw new g("location-renderer:not-supported","3d-volumetric-uniform symbols are supported for point layers only");
if(-1<a.symbolType.indexOf("3d-volumetric")&&(!a.view||"3d"!==a.view.type))throw new g("location-renderer:invalid-parameters","'view' parameter should be an instance of SceneView when 'symbolType' parameter is '3d-volumetric' or '3d-volumetric-uniform'");}return a});return q.apply(this,arguments)}function B(a,b){return r.apply(this,arguments)}function r(){r=m._asyncToGenerator(function*(a,b){let d=a.locationScheme,e=null;var c=null;c=yield h.getBasemapInfo(a.basemap,a.view);e=n.isSome(c.basemapId)?
c.basemapId:null;c=n.isSome(c.basemapTheme)?c.basemapTheme:null;if(d)return{scheme:p.cloneScheme(d),basemapId:e,basemapTheme:c};if(a=p.getSchemes({basemap:e,basemapTheme:c,geometryType:b,worldScale:-1<a.symbolType.indexOf("3d-volumetric"),view:a.view}))d=a.primaryScheme,e=a.basemapId,c=a.basemapTheme;return{scheme:d,basemapId:e,basemapTheme:c}});return r.apply(this,arguments)}function t(){t=m._asyncToGenerator(function*(a){var b=yield A(a);const d=b.layer.geometryType;a=yield B(b,d);const e=a.scheme;
if(!e)throw new g("location-renderer:insufficient-info","Unable to find location scheme");const {view:c,layer:v,signal:w}=b,[f,l]=yield Promise.all([b.outlineOptimizationEnabled?y({view:c,layer:v,signal:w}):null,b.sizeOptimizationEnabled?z({view:c,layer:v,signal:w}):null]),C=f&&f.opacity;b=new x({symbol:h.createSymbol(d,{type:b.symbolType,color:e.color,size:h.getSymbolSizeFromScheme(e,d),outline:h.getSymbolOutlineFromScheme(e,d,C),meshInfo:{colorMixMode:b.colorMixMode,edgesType:b.edgesType}})});f&&
f.visualVariables&&f.visualVariables.length&&(b.visualVariables=f.visualVariables.map(D=>D.clone()));l&&l.minSize&&(b.visualVariables?b.visualVariables.push(l.minSize):b.visualVariables=[l.minSize]);return{renderer:b,locationScheme:p.cloneScheme(e),basemapId:a.basemapId,basemapTheme:a.basemapTheme}});return t.apply(this,arguments)}u.createRenderer=function(a){return t.apply(this,arguments)};Object.defineProperty(u,"__esModule",{value:!0})});