// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../core/arrayUtils ../../../core/mathUtils ../../../core/maybe ../../../geometry/support/aaBoundingBox ../support/buffer/glUtil ./PatchGeometryFactory ./TerrainConst ./TextureFader ./TileOverlayData ./tileUtils ../webgl-engine/lib/DefaultVertexAttributeLocations ../../webgl/BufferObject ../../webgl/VertexArrayObject".split(" "),function(q,u,v,w,m,x,y,r,z,A,B,C,D,t,E){let F=function(){function p(){this.geometryInfo=new r.PatchGeometry;
this.intersectionData=null;this._textureRef=new A(()=>this.tile.surface.textureFadeDuration);this.overlay=new B}var g=p.prototype;g.init=function(a){this.tile=a;this.clear();a=this.geometryInfo;a.indices=null;a.vertexAttributes=null;x.empty(a.boundingBox);a.numSurfaceIndices=0;a.numSkirtIndices=0;a.numWithoutSkirtIndices=0;a.numVertsPerRow=0;this.intersectionData=null;this.geometryState={numVertsPerRow:0,samplerData:null,clippingArea:null,wireframe:!1};this.localOrigin=null;this.overlay.clear()};
g.clear=function(){this.releaseGeometry();this.releaseTexture();this._textureRef.clear()};g.updateGeometry=function(a,b){if(!this._updateGeometryState(b))return!1;this._releaseGeometry();this._createGeometry(a);return!0};g.releaseGeometry=function(){return this._releaseGeometry()?(this.geometryState={numVertsPerRow:0,samplerData:null,clippingArea:null,wireframe:!1},!0):!1};g.ensureTexture=function(a,b){m.isSome(this._texture)&&this._texture.descriptor.width!==a&&this.releaseTexture();m.isNone(this._texture)&&
(this._texture=b(),this.tile.setMemoryDirty());return this._texture};g.releaseTexture=function(){m.isSome(this._texture)&&(this._texture.release(),this._texture=null,this.tile.setMemoryDirty())};g._updateGeometryState=function(a){const b=this._getElevationInfo();var e=this.tile.level,c=8>e?this.tile.numSubdivisionsAtLevel[e]+1:2;b.samplerData&&(c=this.tile.maxTesselation,c=w.clamp((c>>Math.max(e-b.maxTileLevel,z.ELEVATION_DESIRED_RESOLUTION_LEVEL-(this.tile.vlevel-e)))+1,2,c+1));e=this.tile.clippingArea;
if(!this.tile.intersectsClippingArea||this.tile.isWithinClippingArea)e=null;const d=this.geometryState;let f=!1;d.numVertsPerRow!==c&&(d.numVertsPerRow=c,f=!0);b.changed&&(d.samplerData=b.samplerData,f=!0);v.equals(d.clippingArea,e)||(d.clippingArea=e,f=!0);d.wireframe!==a&&(d.wireframe=a,f=!0);return f};g._createGeometry=function(a){this.tile.createGeometry(this.geometryState,this.localOrigin);const b=this.geometryInfo.vertexAttributes,e=this.geometryInfo.indices,c=a.gl;this._vao=new E(a,D.Default3D,
{geometry:y.glLayout(b.layout)},{geometry:t.createVertex(a,c.STATIC_DRAW,b.buffer)},t.createIndex(a,c.STATIC_DRAW,e))};g._releaseGeometry=function(){if(!this._vao)return!1;this._vao.dispose();this._vao=null;r.releaseGeometry(this.geometryInfo);return!0};g.setTextureReference=function(a,b=0){a!==this._texture&&this.releaseTexture();this._textureRef.push(a,b)};g._getElevationInfo=function(){const a=this.geometryState.samplerData,b=this.tile.layerInfo[0],e=b.length;let c=Array(e),d=0;var f=0;let n=!1;
for(let l=0;l<e;l++){var h=b[l];if(h.upsampleInfo){h=h.upsampleInfo.tile;var k=h.layerInfo[0][l].data;k=k&&k.samplerData;a&&a[d]===k||(n=!0);c[d++]=k;f=Math.max(f,h.lij[0])}else h.data&&(k=this.tile.surface.layerViewByIndex(l,0),C.fallsWithinLayer(this.tile,k.layer,!1)&&(f=h.data,a&&a[d]===f.samplerData||(n=!0),c[d++]=f.samplerData,f=this.tile.lij[0]))}a&&a.length!==d&&(n=!0);0<d?c.length=d:c=null;return{changed:n,samplerData:c,maxTileLevel:f}};u._createClass(p,[{key:"vao",get:function(){return this._vao}},
{key:"textureReference",get:function(){return this._textureRef.current}},{key:"nextTextureReference",get:function(){return this._textureRef.next}},{key:"textureFadeFactor",get:function(){return this._textureRef.fadeFactor}},{key:"textureIsFading",get:function(){return this._textureRef.isFading}},{key:"estimatedGeometryMemoryUsage",get:function(){return this.geometryInfo.indices.byteLength+this.geometryInfo.vertexAttributes.byteLength}},{key:"textureDescriptor",get:function(){return m.isSome(this._texture)?
this._texture.descriptor:null}},{key:"test",get:function(){return{hasTexture:null!=this._texture}}}]);return p}();q.PatchRenderData=F;Object.defineProperty(q,"__esModule",{value:!0})});