// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/vec2 ../../chunks/vec2f64 ../../chunks/vec3 ../../chunks/vec3f64 ../../chunks/vec4 ../../chunks/vec4f64 ../../geometry/Point".split(" "),function(k,n,l,p,g,r,m,h){let t=function(){function f(a){this.spatialReference=a}var c=f.prototype;c.createVector=function(){return this.tag(l.create())};c.pointToVector=function(a){return this.tag(l.fromValues(a.x,a.y))};c.arrayToVector=function(a){return this.tag(l.fromValues(a[0],a[1]))};c.vectorToArray=function(a){return[a[0],a[1]]};
c.pointToArray=function(a){return[a.x,a.y]};c.vectorToPoint=function(a,b=new h){b.x=a[0];b.y=a[1];b.z=void 0;b.m=void 0;b.spatialReference=this.spatialReference;return b};c.arrayToPoint=function(a,b=new h){b.x=a[0];b.y=a[1];b.z=void 0;b.m=void 0;b.spatialReference=this.spatialReference;return b};c.vectorToDehydratedPoint=function(a,b={x:void 0,y:void 0,z:void 0,m:void 0,hasZ:void 0,hasM:void 0,spatialReference:void 0,type:"point"}){b.x=a[0];b.y=a[1];b.z=void 0;b.m=void 0;b.hasZ=!1;b.hasM=!1;b.spatialReference=
this.spatialReference;return b};c.lerp=function(a,b,d,e){return n.lerp(e,a,b,d)};c.addDelta=function(a,b,d){a[0]+=b;a[1]+=d};c.distance=function(a,b){return n.distance(a,b)};c.getZ=function(a,b){return b};c.hasZ=function(){return!1};c.getM=function(a,b){return b};c.hasM=function(){return!1};c.clone=function(a){return this.tag(l.fromArray(a))};c.copy=function(a,b){return n.copy(b,a)};c.fromXYZ=function(a){return this.tag(l.fromValues(a[0],a[1]))};c.toXYZ=function(a,b=0){return g.fromValues(a[0],a[1],
b)};c.tag=function(a){return a};return f}(),q=function(){function f(a,b){this.valueType=a;this.spatialReference=b}var c=f.prototype;c.createVector=function(){return this.tag(g.create())};c.pointToVector=function(a){return this.tag(g.fromValues(a.x,a.y,0===this.valueType?a.z:a.m))};c.arrayToVector=function(a){return this.tag(g.fromValues(a[0],a[1],a[2]||0))};c.vectorToArray=function(a){return[a[0],a[1],a[2]]};c.pointToArray=function(a){return 0===this.valueType?[a.x,a.y,a.z]:[a.x,a.y,a.m]};c.vectorToPoint=
function(a,b=new h){b.x=a[0];b.y=a[1];b.z=0===this.valueType?a[2]:void 0;b.m=1===this.valueType?a[2]:void 0;b.spatialReference=this.spatialReference;return b};c.arrayToPoint=function(a,b=new h){b.x=a[0];b.y=a[1];b.z=0===this.valueType?a[2]:void 0;b.m=1===this.valueType?a[2]:void 0;b.spatialReference=this.spatialReference;return b};c.vectorToDehydratedPoint=function(a,b={x:void 0,y:void 0,z:void 0,m:void 0,hasZ:void 0,hasM:void 0,spatialReference:void 0,type:"point"}){const d=0===this.valueType,e=
1===this.valueType;b.x=a[0];b.y=a[1];b.z=d?a[2]:void 0;b.m=e?a[2]:void 0;b.hasZ=d;b.hasM=e;b.spatialReference=this.spatialReference;return b};c.lerp=function(a,b,d,e){return p.lerp(e,a,b,d)};c.addDelta=function(a,b,d,e){a[0]+=b;a[1]+=d;0===this.valueType&&(a[2]+=e)};c.distance=function(a,b){return 0===this.valueType?p.distance(a,b):n.distance(a,b)};c.getZ=function(a,b){return 0===this.valueType?a[2]:b};c.hasZ=function(){return 0===this.valueType};c.getM=function(a,b){return 1===this.valueType?a[2]:
b};c.hasM=function(){return 1===this.valueType};c.clone=function(a){return this.tag(g.fromArray(a))};c.copy=function(a,b){return p.copy(b,a)};c.fromXYZ=function(a,b=0,d=0){return this.tag(g.fromValues(a[0],a[1],0===this.valueType?2<a.length?a[2]:b:d))};c.toXYZ=function(a,b=0){return this.tag(g.fromValues(a[0],a[1],0===this.valueType?a[2]:b))};c.tag=function(a){return a};return f}(),u=function(){function f(a){this.spatialReference=a}var c=f.prototype;c.createVector=function(){return this.tag(m.create())};
c.pointToVector=function(a){return this.tag(m.fromValues(a.x,a.y,a.z,a.m))};c.arrayToVector=function(a){return this.tag(m.fromValues(a[0],a[1],a[2]||0,a[3]||0))};c.vectorToArray=function(a){return[a[0],a[1],a[2],a[3]]};c.pointToArray=function(a){return[a.x,a.y,a.z,a.m]};c.vectorToPoint=function(a,b=new h){b.x=a[0];b.y=a[1];b.z=a[2];b.m=a[3];b.spatialReference=this.spatialReference;return b};c.arrayToPoint=function(a,b=new h){b.x=a[0];b.y=a[1];b.z=a[2];b.m=a[3];b.spatialReference=this.spatialReference;
return b};c.vectorToDehydratedPoint=function(a,b={x:void 0,y:void 0,z:void 0,m:void 0,hasZ:void 0,hasM:void 0,spatialReference:void 0,type:"point"}){b.x=a[0];b.y=a[1];b.z=a[2];b.m=a[3];b.hasZ=!0;b.hasM=!0;b.spatialReference=this.spatialReference;return b};c.lerp=function(a,b,d,e){return r.lerp(e,a,b,d)};c.addDelta=function(a,b,d,e){a[0]+=b;a[1]+=d;a[2]+=e};c.distance=function(a,b){return p.distance(a,b)};c.getZ=function(a){return a[2]};c.hasZ=function(){return!0};c.getM=function(a){return a[3]};c.hasM=
function(){return!0};c.clone=function(a){return this.tag(m.fromArray(a))};c.copy=function(a,b){return r.copy(b,a)};c.fromXYZ=function(a,b=0,d=0){return this.tag(m.fromValues(a[0],a[1],2<a.length?a[2]:b,d))};c.toXYZ=function(a){return g.fromValues(a[0],a[1],a[2])};c.tag=function(a){return a};return f}();k.CoordinateHelper2D=t;k.CoordinateHelper3D=q;k.CoordinateHelper4D=u;k.createCoordinateHelper=function(f,c,a){return f&&c?new u(a):c?new q(1,a):f?new q(0,a):new t(a)};Object.defineProperty(k,"__esModule",
{value:!0})});