// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/Accessor ../../core/Logger ../../core/maybe ../../core/promiseUtils ../../core/accessorSupport/decorators/property ../../core/has ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ../DOMContainer ./ManipulatorCollection".split(" "),function(c,h,d,m,n,p,k,e,v,w,q,r,t){const f=n.getLogger("esri.views.interactive.InteractiveToolBase");c.InteractiveToolBase=function(l){function g(a){a=
l.call(this,a)||this;a.toolState="pending";a.completed=!1;a.manipulators=new t.ManipulatorCollection;a.updating=!1;a.automaticManipulatorSelection=!0;a._editableFlags=new Map([[1,!0],[0,!0]]);a._creationStartedResolver=k.createResolver();a._creationFinishedResolver=k.createResolver();return a}h._inheritsLoose(g,l);var b=g.prototype;b.attach=function(){if(this.attached)f.warn("Tool is already attached. Ignoring attach request.");else{this.manipulators.attach();this.onAttach();if(this.visible)this.onShow();
this._set("attached",!0)}};b.detach=function(){if(this.attached){if(this.visible)this.onHide();this.onDetach();this.manipulators.detach();this._set("attached",!1)}else f.error("Tool isn't currently attached. Ignoring detach request.")};b.activate=function(){p.isNone(this.view)?f.error("Can't activate tool if view is not defined."):this.active?f.warn("Tool is already active, ignoring activation request."):(r.isDOMContainer(this.view)&&this.view.focus(),this.onActivate())};b.deactivate=function(){if(this.active)this.onDeactivate();
else f.warn("Tool is not active, ignoring deactivation request.")};b.handleInputEvent=function(a){if(this.attached)this.onInputEvent(a);else f.warn("handleInputEvent() called on detached tool")};b.handleInputEventAfter=function(a){if(this.attached)this.onInputEventAfter(a);else f.warn("handleInputEventAfter() called on detached tool")};b.destroy=function(){this.manipulators.destroy();this._set("view",null);this._set("completed",!1)};b.setEditableFlag=function(a,u){this._editableFlags.set(a,u);this.manipulators.isToolEditable=
this.internallyEditable;this._updateManipulatorAttachment();0===a&&this.notifyChange("editable");this.onEditableChange()};b.getEditableFlag=function(a){return this._editableFlags.get(a)};b.whenCreationStarted=function(){return this._creationStartedResolver.promise};b.when=function(){return this._creationFinishedResolver.promise};b.rejectCreation=function(a){"pending"!==this.toolState&&"creating"!==this.toolState||this._creationStartedResolver.resolve(this);this._creationFinishedResolver.reject(a)};
b.onActivate=function(){};b.onDeactivate=function(){};b.onAttach=function(){};b.onDetach=function(){};b.onShow=function(){};b.onHide=function(){};b.onEditableChange=function(){};b.onInputEvent=function(a){};b.onInputEventAfter=function(a){};b.startToolCreation=function(){if("pending"===this.toolState)this._creationStartedResolver.resolve(this),this.toolState="creating";else throw Error(`Unexpected tool state ${this.toolState}`);};b.finishToolCreation=function(){switch(this.toolState){case "pending":this.startToolCreation();
case "creating":this.created||this._creationFinishedResolver.resolve(this);this.toolState="created";break;case "created":break;default:throw Error(`Unexpected tool state ${this.toolState}`);}};b.complete=function(){this.finishToolCreation();this._set("completed",!0)};b._show=function(){this._updateManipulatorAttachment();this.onShow()};b._hide=function(){this._updateManipulatorAttachment();this.onHide()};b._updateManipulatorAttachment=function(){this.attached&&this.visible?this.manipulators.attach():
this.manipulators.detach()};h._createClass(g,[{key:"active",get:function(){return null!=this.view&&this.view.activeTool===this}},{key:"visible",set:function(a){this._set("visible",a);!a&&this.active&&(this.view.activeTool=null);this.attached&&(a?this._show():this._hide())}},{key:"editable",get:function(){return this.getEditableFlag(0)},set:function(a){this.setEditableFlag(0,a)}},{key:"attached",get:function(){return this._get("attached")}},{key:"created",get:function(){return"created"===this.toolState}},
{key:"cursor",get:function(){return null}},{key:"internallyEditable",get:function(){return this.getEditableFlag(0)&&this.getEditableFlag(1)}}]);return g}(m);d.__decorate([e.property()],c.InteractiveToolBase.prototype,"toolState",void 0);d.__decorate([e.property({constructOnly:!0})],c.InteractiveToolBase.prototype,"view",void 0);d.__decorate([e.property({readOnly:!0})],c.InteractiveToolBase.prototype,"active",null);d.__decorate([e.property({value:!0})],c.InteractiveToolBase.prototype,"visible",null);
d.__decorate([e.property({value:!0})],c.InteractiveToolBase.prototype,"editable",null);d.__decorate([e.property({value:!1,readOnly:!0})],c.InteractiveToolBase.prototype,"attached",null);d.__decorate([e.property({readOnly:!0})],c.InteractiveToolBase.prototype,"created",null);d.__decorate([e.property({readOnly:!0})],c.InteractiveToolBase.prototype,"completed",void 0);d.__decorate([e.property({readOnly:!0})],c.InteractiveToolBase.prototype,"manipulators",void 0);d.__decorate([e.property({readOnly:!0})],
c.InteractiveToolBase.prototype,"updating",void 0);d.__decorate([e.property()],c.InteractiveToolBase.prototype,"cursor",null);d.__decorate([e.property()],c.InteractiveToolBase.prototype,"automaticManipulatorSelection",void 0);c.InteractiveToolBase=d.__decorate([q.subclass("esri.views.interactive.InteractiveToolBase")],c.InteractiveToolBase);Object.defineProperty(c,"__esModule",{value:!0})});