// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../intl ../../../core/Error ../../../core/lang ../../../core/Logger ../../../core/maybe ../../../core/unitUtils ../../../geometry/Polygon ./geometryUtils ../../../intl/substitute ../../../intl/date".split(" "),function(F,Q,ja,w,R,S,T,U,V,J,W,X){function K(a,c){const {filter:b,withinViewEnabled:f}=a;a=c&&c.extent;return b&&b.geometry||(f&&a?a:void 0)}function L(a){return G.apply(this,arguments)}function G(){G=Q._asyncToGenerator(function*(a){a&&
(yield a.load())});return G.apply(this,arguments)}function M(a){var c,b,f;return null!=(c=null==a?void 0:null==(b=a.capabilities)?void 0:null==(f=b.query)?void 0:f.supportsPagination)?c:!1}function N(a){var c,b,f,h;return null!=(c=null==a?void 0:null==(b=a.fieldsIndex)?void 0:null==(f=b.fields)?void 0:null==(h=f.find(l=>"string"===l.type))?void 0:h.name)?c:""}function B(a,c){return a&&c?c.every(b=>!!a.getField(b)):!1}function Y(a,c,b){let f=null;({codedValues:a}=a);a&&a.some(h=>{var l=h.name;l=b?
l:l.toLowerCase();return(b?c:c.toLowerCase())===l?(f=h.code.toString(),!0):!1});return f}function C(a,c){return(c=c&&c.where)?`(${a}) AND (${c})`:a}function Z({currentTerm:a,field:c,filter:b,exactMatch:f,url:h,type:l}){var d=c.type;c=c.name;if("string"===d||"date"===d||"global-id"===d){if(d=h=aa.test(h))a:{for(d=0;d<a.length;d++)if(255<a.charCodeAt(d)){d=!0;break a}d=!1}d=d?"N":"";if(f&&"search"===l)return C(`${c} = ${d}'${a}'`,b);l=h?c:`UPPER(${c})`;a=h?a:a.toUpperCase();return C(`${l} LIKE ${d}${f?
`'${a}%'`:`'%${a}%'`}`,b)}return"oid"===d||"small-integer"===d||"integer"===d||"single"===d||"double"===d?(f=Number(a),isNaN(f)?null:C(`${c} = ${f}`,b)):C(`${c} = ${a}`,b)}function O({searchTerm:a,layer:c,searchFields:b,filter:f,exactMatch:h,type:l}){const {definitionExpression:d,url:p}=c;let n="";a&&b&&b.forEach(g=>{var k=c.getField(g);g=((g="function"===typeof c.getFieldDomain&&c.getFieldDomain(g))&&"coded-value"===g.type?Y(g,a,h):null)||a||null;null!==g&&(k=Z({currentTerm:g,field:k,filter:f,exactMatch:h,
url:p,type:l}))&&(n+=n?` OR (${k})`:`(${k})`)});return d?`(${d}) AND (${n})`:n}function ba(a,c){let b=null;({codedValues:a}=a);a&&a.length&&a.some(f=>f.code===c?(b=f.name,!0):!1);return b}function ca(a,c){return a[Object.keys(a).find(b=>b.toLowerCase()===c.toLowerCase())]}function P(a,c,b){const f=a.sourceLayer,{attributes:h}=a;a="function"===typeof f.getFieldDomain&&f.getFieldDomain(b);return c?W.substitute(c,h):b&&h?(c=f.getField(b),b=ca(h,b),null==b?"":a&&"coded-value"===a.type?ba(a,b):"date"===
(null==c?void 0:c.type)?X.formatDate(new Date(b)):"number"===typeof b?b.toString():"string"!==typeof b?"":b.trim()):""}function da(a,c,b,f){return a.features.map(h=>{var l=h.sourceLayer,{attributes:d}=h;({objectIdField:l}=l);d=d[l];return h={text:P(h,c.suggestionTemplate,f),key:d,sourceIndex:b}})}function ea(a,c,b,f,h,l,d){return a.features.map(p=>{{var n=p.clone();var g=p.sourceLayer;g=(g=g&&g.objectIdField)&&p.attributes[g];const A=P(p,b.searchTemplate,h);var k=J.createExtentFromGeometry(n.geometry,
c,l);k="number"===typeof d?J.scaleExtent(R.clone(k),c,d):k;p=p.clone();T.isSome(k)&&(p.geometry=V.fromExtent(k));n={extent:k,target:p,feature:n,key:g,name:A,sourceIndex:f}}return n})}const aa=/https?:\/\/services.*\.arcgis\.com/i,fa=/(?:\{([^}]+)\})/g,x=S.getLogger("esri.widgets.Search.support.layerSearchUtils");F.getResults=function(a,c){const {exactMatch:b=!1,location:f,maxResults:h,spatialReference:l,source:d,sourceIndex:p,suggestResult:n,view:g}=a,{layer:k,filter:A,zoomScale:D}=d,y=g&&g.scale,
t=K(d,g),q=c&&c.signal;return L(k).then(()=>{const e=k.popupTemplate;return e?e.getRequiredFields(k.fieldsIndex):null}).then(e=>{var m,z;const {objectIdField:E,returnZ:H}=k,u=d.displayField||d.layer.displayField||N(d.layer);if(!k.getField(u))throw x.error("invalid-field: displayField is invalid."),new w("getResults():invalid-field","displayField is invalid.");e=e&&e.length?e:[u];const r=d.outFields||e;e=r&&-1!==r.indexOf("*");-1!==r.indexOf(E)||e||r.push(E);if(!e&&!B(k,r))throw x.error("invalid-field: outField is invalid."),
new w("getResults():invalid-field","outField is invalid.");e=k.createQuery();var {orderByFields:v}=d;v&&(e.orderByFields=v);l&&(e.outSpatialReference=l,v=1/U.getMetersPerUnitForSR(l))&&(e.maxAllowableOffset=v);v="mesh"===k.geometryType||"multipatch"===k.geometryType;const ha=(null==(m=k.capabilities)?void 0:null==(z=m.data)?void 0:z.supportsZ)&&!v;e.returnZ=ha&&!1!==H;e.returnGeometry=!0;e.multipatchOption=v?"xyFootprint":null;r&&(e.outFields=r);if(f)e.geometry=f;else if(n.key)e.objectIds=[n.key];
else{m=d.searchFields||[u];if(!B(k,m))throw x.error("invalid-field: search field is invalid."),new w("getResults():invalid-field","search field is invalid.");M(k)&&(e.num=h);t&&(e.geometry=t);if(!n.text.trim())return[];const {prefix:I="",suffix:ia=""}=d;z=`${I}${n.text}${ia}`.replace(/'/g,"''");m=O({searchTerm:z,layer:k,searchFields:m,filter:A,exactMatch:b,type:"search"});if(!m)return[];e.where=m}return k.queryFeatures(e,{signal:q}).then(I=>ea(I,g,d,p,u,y,D))})};F.getSuggestions=function(a,c){const {source:b,
spatialReference:f,view:h,suggestTerm:l,maxSuggestions:d,sourceIndex:p,exactMatch:n}=a,{layer:g,filter:k}=b,A=c&&c.signal,D=K(b,h);return L(g).then(()=>{if(!M(g))return[];const y=b.displayField||b.layer.displayField||N(b.layer);var t=b.searchFields||[y];const q=[];b.suggestionTemplate?b.suggestionTemplate.replace(fa,(u,r)=>{q.push(r);return u}):q.push(y);var e=q&&-1!==q.indexOf("*");-1!==q.indexOf(g.objectIdField)||e||q.push(g.objectIdField);var m=!!g.getField(y);e=e||B(g,q);const z=B(g,t);if(!m)throw x.error("invalid-field: displayField is invalid."),
new w("getSuggestions():invalid-field","displayField is invalid.");if(!e)throw x.error("invalid-field: outField is invalid."),new w("getSuggestions():invalid-field","outField is invalid.");if(!z)throw x.error("invalid-field: search field is invalid."),new w("getSuggestions():invalid-field","search field is invalid.");m=g.createQuery();({orderByFields:e}=b);e&&(m.orderByFields=e);m.outSpatialReference=f;m.returnGeometry=!1;m.num=d;m.outFields=q;D&&(m.geometry=D);if(!l.trim())return[];const {prefix:E=
"",suffix:H=""}=b;e=`${E}${l}${H}`.replace(/'/g,"''");t=O({searchTerm:e,layer:g,searchFields:t,filter:k,exactMatch:n,type:"suggest"});if(!t)return[];m.where=t;return g.queryFeatures(m,{signal:A}).then(u=>da(u,b,p,y))})};Object.defineProperty(F,"__esModule",{value:!0})});