// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../geometry ../../Graphic ../../intl ../../symbols ../../core/Handles ../../core/maybe ../../core/unitFormatUtils ../../core/unitUtils ../../core/watchUtils ../../core/accessorSupport/decorators/property ../../core/has ../../core/accessorSupport/ensureType ../../core/Logger ../../core/accessorSupport/decorators/subclass ../../geometry/geometryEngine ../../geometry/projection ../../geometry/support/geodesicUtils ../../layers/GraphicsLayer ../../layers/GroupLayer ../../views/draw/Draw ../../views/interactive/dragEventPipeline ../../views/interactive/GraphicManipulator ../../views/interactive/InteractiveToolBase ../../intl/messages ../../intl/locale ../../geometry/Point ../../symbols/SimpleFillSymbol ../../symbols/SimpleLineSymbol ../../symbols/TextSymbol ../../symbols/Font ../../symbols/SimpleMarkerSymbol ../../geometry/Polyline ../../geometry/SpatialReference ../../geometry/Polygon".split(" "),
function(x,D,p,k,z,fa,ha,Q,y,u,G,H,q,ia,ja,ka,R,l,h,g,I,S,T,E,U,V,J,W,K,X,Y,Z,aa,L,M,A,ba){function ca(b,d,f,a){const e=new L({style:"circle",color:a.handleColor,size:a.handleWidth,outline:{type:"simple-line",width:0}});a=new L({style:"circle",color:a.handleColor,size:1.5*a.handleWidth,outline:{type:"simple-line",width:0}});b=new z({geometry:b,symbol:e});return new U.GraphicManipulator({view:d,layer:f,graphic:b,focusedSymbol:a})}function N(b,d,f){if(2===b.length)return b=new M({paths:b,spatialReference:d}),
d.isGeographic?g.isSupported(d)?d=g.geodesicDensify(b,1E5):(b=h.project(b,A.WGS84),b=g.geodesicDensify(b,1E5),d=h.project(b,d)):d.isWebMercator?d=l.geodesicDensify(b,1E5,"meters"):l.planarLength(b,"meters")>=f?(b=h.project(b,A.WGS84),b=g.geodesicDensify(b,1E5),d=h.project(b,d)):d=b,{measurement:null,fillGeometry:null,outlineGeometry:d};b.push(b[0]);var a=new M({paths:[b],spatialReference:d}),e=new ba({rings:[b],spatialReference:d});let c=b=null;if(d.isGeographic)if(g.isSupported(d)){b=g.geodesicDensify(a,
1E5);c=g.geodesicDensify(e,1E5);c=l.simplify(c);if(!c)return null;e=g.geodesicLengths([a],"meters")[0];a=g.geodesicAreas([c],"square-meters")[0]}else{b=A.WGS84;a=h.project(a,b);e=h.project(e,b);b=g.geodesicDensify(a,1E5);c=g.geodesicDensify(e,1E5);c=l.simplify(c);if(!c)return null;e=g.geodesicLengths([a],"meters")[0];a=g.geodesicAreas([c],"square-meters")[0];b=h.project(b,d);c=h.project(c,d)}else if(d.isWebMercator){b=l.geodesicDensify(a,1E5,"meters");c=l.geodesicDensify(e,1E5,"meters");c=l.simplify(c);
if(!c)return null;e=l.geodesicLength(a,"meters");a=l.geodesicArea(c,"square-meters")}else{const m=l.planarLength(a,"meters");if(m>=f){b=A.WGS84;a=h.project(a,b);e=h.project(e,b);b=g.geodesicDensify(a,1E5);c=g.geodesicDensify(e,1E5);c=l.simplify(c);if(!c)return null;e=g.geodesicLengths([a],"meters")[0];a=g.geodesicAreas([c],"square-meters")[0];b=h.project(b,d);c=h.project(c,d)}else{b=a;c=l.simplify(e);if(!c)return null;e=m;a=l.planarArea(c,"square-meters")}}return{measurement:{geometry:c,area:a,perimeter:e},
fillGeometry:c,outlineGeometry:b}}function F(b){if(!b)return!1;const {isGeographic:d,isWebMercator:f,isWGS84:a}=b;return d&&!a&&!g.isSupported(b)||!d&&!f}function O(b,d,f){if(!d||!b)return null;const a={area:null,perimeter:null},{area:e,perimeter:c}=d;switch(f){case "metric":a.area=u.formatMetricArea(b,e,"square-meters");break;case "imperial":a.area=u.formatImperialArea(b,e,"square-meters");break;default:d=G.convertUnit(e,"square-meters",f),a.area=u.formatDecimal(b,d,f)}if(f=da(f))switch(f){case "metric":a.perimeter=
u.formatMetricLength(b,c,"meters");break;case "imperial":a.perimeter=u.formatImperialLength(b,c,"meters");break;default:d=G.convertUnit(c,"meters",f),a.perimeter=u.formatDecimal(b,d,f)}else a.perimeter="";return a}function da(b){switch(b){case "metric":return"metric";case "imperial":return"imperial";case "square-inches":return"inches";case "square-feet":return"feet";case "square-yards":return"yards";case "square-miles":return"miles";case "square-us-feet":return"us-feet";case "square-meters":return"meters";
case "square-kilometers":return"kilometers";case "acres":return"imperial";case "ares":case "hectares":return"metric";case "square-millimeters":return"millimeters";case "square-centimeters":return"centimeters";case "square-decimeters":return"decimeters";default:return null}}k=function(b){function d(){var a=b.apply(this,arguments)||this;a._drawActive=!1;a._handles=new Q;a._graphicsLayer=new I;a._manipulatorLayer=new I;a._groupLayer=new S({layers:[a._graphicsLayer,a._manipulatorLayer],listMode:"hide",
visible:!1});a._vertices=[];a.geodesicDistanceThreshold=1E5;a.measurement=null;a.measurementLabel=null;return a}D._inheritsLoose(d,b);var f=d.prototype;f.initialize=function(){var a=this;J.fetchMessageBundle("esri/core/t9n/Units").then(e=>{this.messages=e});this._handles.add(W.onLocaleChange(D._asyncToGenerator(function*(){a.messages=yield J.fetchMessageBundle("esri/core/t9n/Units")})));this.startToolCreation()};f.destroy=function(){this._draw=y.destroyMaybe(this._draw);this._handles=y.destroyMaybe(this._handles);
this._graphicsLayer=y.destroyMaybe(this._graphicsLayer);this._manipulatorLayer=y.destroyMaybe(this._manipulatorLayer)};f.onActivate=function(){this._drawActive||0!==this._vertices.length||this._startSketch()};f.onAttach=function(){const a=this.view;this._draw=new T({view:a});a.map.add(this._groupLayer);a.focus();this._handles.add([H.init(this,["unit","geodesicDistanceThreshold","palette","messages"],()=>{0<this._vertices.length&&this._updateGraphics()}),H.init(this,"view.spatialReference",e=>{F(e)&&
!h.isLoaded()&&h.load()})]);this.finishToolCreation()};f.onDetach=function(){const {map:a}=this.view;this._draw.view=null;this._draw=y.destroyMaybe(this._draw);a.remove(this._groupLayer);this._handles.removeAll();this._graphicsLayer.removeAll();this._manipulatorLayer.removeAll();this._set("measurement",null);this._set("measurementLabel",null)};f.onShow=function(){this._groupLayer.visible=!0};f.onHide=function(){this._groupLayer.visible=!1};f.reset=function(){this._vertices=[];this._graphicsLayer.removeAll();
this._set("measurement",null);this._set("measurementLabel",null);this._draw.reset();this._drawActive=!1;this._updateSketch([])};f._startSketch=function(){this._drawActive=!0;const a=this._draw.create("polyline",{mode:"click"});a.on("vertex-add vertex-update vertex-remove cursor-update undo redo".split(" "),e=>this._updateSketch(e.vertices));a.on("draw-complete",()=>this._stopSketch())};f._stopSketch=function(){3>this._vertices.length?(this.reset(),this._startSketch()):(this.manipulators.forEach(a=>
{a.manipulator.interactive=!0}),this._drawActive=!1,this.complete())};f._updateSketch=function(a){if(!F(this.view.spatialReference)||h.isLoaded())if(2>a.length)this._vertices=[],this.manipulators.removeAll(),this._graphicsLayer.removeAll();else{this.finishToolCreation();for(var e=this.view.spatialReference;this._vertices.length>a.length;){var {manipulatorId:c}=this._vertices.pop();this.manipulators.remove(c)}for(let n=this._vertices.length;n<a.length;n++){const [v,B]=a[n];c=new K({x:v,y:B,spatialReference:e});
c=ca(c,this.view,this._manipulatorLayer,this.palette);var m=this.manipulators.add(c);E.createManipulatorDragEventPipeline(c,(C,ea)=>{ea.next(E.screenToMap(this.view)).next(E.dragGraphic(C.graphic,2)).next(()=>{const P=C.graphic.geometry;this._vertices[n].coord=[P.x,P.y];this._updateGraphics()})});this._vertices.push({manipulatorId:m,coord:[v,B]})}c=this._vertices.length-1;m=this._vertices[c];var [r,t]=a[c];if(m.coord[0]!==r||m.coord[1]!==t)m.coord=[r,t],a=new K({x:r,y:t,spatialReference:e}),this.manipulators.findById(m.manipulatorId).graphic.geometry=
a;var w=this._drawActive?this._vertices[c].manipulatorId:null;this.manipulators.forEach(n=>{n.manipulator.interactive=null==w||n.id!==w});this._updateGraphics()}};f._updateGraphics=function(){var a=this._vertices.map(v=>v.coord);if(a=N(a,this.view.spatialReference,this.geodesicDistanceThreshold)){var {measurement:e,fillGeometry:c,outlineGeometry:m}=a;this._set("measurement",e);a=e?O(this.messages,e,this.unit):null;this._set("measurementLabel",a);if(c||m){var {graphics:r}=this._graphicsLayer;if(3===
r.length){var t=r.getItemAt(0);var w=r.getItemAt(1);var n=r.getItemAt(2)}else{const {fillColor:v,pathColor:B,pathWidth:C}=this.palette;t=new z({symbol:new X({color:v,outline:null})});w=new z({symbol:new Y({color:B,width:C})});n=new z({symbol:new Z({color:[255,255,255,1],font:new aa({size:14,family:"sans-serif"}),haloColor:[0,0,0,.5],haloSize:2})});r.removeAll();r.addMany([t,w,n])}t.geometry=c;w.geometry=m;n.geometry=null==c?void 0:c.centroid;n.symbol.text=null==a?void 0:a.area}}};D._createClass(d,
[{key:"cursor",get:function(){return this._drawActive?"crosshair":null}},{key:"editable",set:function(a){this._set("editable",a);a||this._draw.reset()}}]);return d}(V.InteractiveToolBase);p.__decorate([q.property()],k.prototype,"_drawActive",void 0);p.__decorate([q.property()],k.prototype,"cursor",null);p.__decorate([q.property({value:!0})],k.prototype,"editable",null);p.__decorate([q.property({type:Number})],k.prototype,"geodesicDistanceThreshold",void 0);p.__decorate([q.property({readOnly:!0})],
k.prototype,"measurement",void 0);p.__decorate([q.property({readOnly:!0})],k.prototype,"measurementLabel",void 0);p.__decorate([q.property()],k.prototype,"messages",void 0);p.__decorate([q.property()],k.prototype,"palette",void 0);p.__decorate([q.property()],k.prototype,"unit",void 0);p.__decorate([q.property({constructOnly:!0})],k.prototype,"view",void 0);k=p.__decorate([R.subclass("esri.widgets.AreaMeasurement2D.AreaMeasurement2DTool")],k);x.createAreaMeasurementInfo2D=N;x.createAreaMeasurementLabel=
O;x["default"]=k;x.isSupported=function(b){return null!=b&&(!F(b)||h.isSupported())};Object.defineProperty(x,"__esModule",{value:!0})});