// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../geometry ../../rasterRenderers ../../request ../../core/Logger ../../core/maybe ../../core/accessorSupport/decorators/aliasOf ../../core/has ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/property ../../core/accessorSupport/decorators/subclass ../../geometry/support/spatialReferenceUtils ../support/arcgisLayerUrl ../support/commonProperties ../support/DimensionalDefinition ../support/RasterJobHandler ../support/TileInfo ../support/rasterFunctions/vectorFieldUtils ../../renderers/support/rasterRendererHelper ../../renderers/support/RasterSymbolizer ../../geometry/Extent ../../geometry/SpatialReference".split(" "),
function(r,l,f,L,x,y,z,n,p,M,N,h,A,B,C,D,t,E,u,F,m,G,H,I){const v=z.getLogger("esri.layers.mixins.ImageryTileMixin");r.ImageryTileMixin=e=>{e=function(w){function q(){var a=w.apply(this,arguments)||this;a._rasterJobHandler={instance:null,refCount:0,connectionPromise:null};a.bandIds=null;a.copyright=null;a.fullExtent=null;a.interpolation="nearest";a.raster=null;a.rasterInfo=null;a.sourceJSON=null;a.spatialReference=null;a.tileInfo=null;a.symbolizer=null;return a}l._inheritsLoose(q,w);var g=q.prototype;
g.convertVectorFieldData=function(){var a=l._asyncToGenerator(function*(b,c){if(n.isNone(b))return null;const d=this._rasterJobHandler.instance,k=this.rasterInfo.dataType;return d?d.convertVectorFieldData({pixelBlock:b,dataType:k},c):F.convertVectorFieldData(b,k)});return function(b,c){return a.apply(this,arguments)}}();g.updateRenderer=function(){var a=l._asyncToGenerator(function*(){if(this.loaded&&JSON.stringify(this._cachedRendererJson)!==JSON.stringify(this.renderer)){var b=this._rasterJobHandler.instance;
b&&(this.symbolizer.rendererJSON=m.normalizeRendererJSON(this.renderer.toJSON()),this.symbolizer.bind(),yield b.updateSymbolizer(this.symbolizer),this._cachedRendererJson=this.renderer.toJSON())}});return function(){return a.apply(this,arguments)}}();g.applyRenderer=function(){var a=l._asyncToGenerator(function*(b,c){var d=b&&b.pixelBlock;if(!(n.isSome(d)&&d.pixels&&0<d.pixels.length))return null;yield this.updateRenderer();d=this._rasterJobHandler.instance;const {bandIds:k}=this;return d?yield d.symbolize({...b,
simpleStretchParams:c,bandIds:k}):this.symbolizer.symbolize({...b,simpleStretchParams:c,bandIds:k})});return function(b,c){return a.apply(this,arguments)}}();g.getTileUrl=function(a,b,c){return"RasterTileServer"===this.raster.datasetFormat?`${this.url}/tile/${a}/${b}/${c}`:""};g.getCompatibleTileInfo=function(a,b,c=!1){if(!this.loaded)return null;if(c&&a.equals(this.spatialReference))return this.tileInfo;c=B.getInfo(a);return u.create({size:256,spatialReference:a,origin:c?{x:c.origin[0],y:c.origin[1]}:
{x:b.xmin,y:b.ymax}})};g.getCompatibleFullExtent=function(a){return this.loaded?this._compatibleFullExtent&&this._compatibleFullExtent.spatialReference.equals(a)?this._compatibleFullExtent:this._compatibleFullExtent=this.raster.computeExtent(a):null};g.fetchTile=function(){var a=l._asyncToGenerator(function*(b,c,d,k={}){if(k.requestAsImageElement)return b=this.getTileUrl(b,c,d),y(b,{responseType:"image",query:{sliceId:this._sliceId,...this.refreshParameters,...this.raster.ioConfig.customFetchParameters},
signal:k.signal}).then(J=>J.data);yield this._initJobHandler();const K="raster-shaded-relief"===this.renderer.type?{cols:1,rows:1}:null;this.multidimensionalDefinition&&(k={multidimensionalDefinition:this.multidimensionalDefinition,sliceId:this._sliceId,buffer:K,...k});return this.raster.fetchTile(b,c,d,k)});return function(b,c,d){return a.apply(this,arguments)}}();g.fetchPixels=function(){var a=l._asyncToGenerator(function*(b,c,d,k){yield this._initJobHandler();this.multidimensionalDefinition&&(k=
{multidimensionalDefinition:this.multidimensionalDefinition,sliceId:this._sliceId,...k});return this.raster.fetchPixels(b,c,d,k)});return function(b,c,d,k){return a.apply(this,arguments)}}();g.identify=function(a,b={}){this.multidimensionalDefinition&&!b.multidimensionalDefinition&&(b={...b,multidimensionalDefinition:this.multidimensionalDefinition});return this.raster.identify(a,b)};g.increaseRasterJobHandlerUsage=function(){this._rasterJobHandler.refCount++};g.decreaseRasterJobHandlerUsage=function(){this._rasterJobHandler.refCount--;
0>=this._rasterJobHandler.refCount&&this._shutdownJobHandler()};g.hasStandardTime=function(){var a;const b=this.rasterInfo.multidimensionalInfo;if(!n.isSome(b)||"standard-time"!==this.rasterInfo.dataType)return!1;const c=null==(a=this.multidimensionalDefinition[0])?void 0:a.variableName;return b.variables.some(d=>d.name===c&&d.dimensions.some(k=>"StdTime"===k.name))};g.getStandardTimeValue=function(a){return(new Date(864E5*(a-25569))).toString()};g._configDefaultSettings=function(){this._configDefaultInterpolation();
this._configDefaultSlice();this._configDefaultRenderer()};g._initJobHandler=function(){if(null!=this._rasterJobHandler.connectionPromise)return this._rasterJobHandler.connectionPromise;const a=new E;this._rasterJobHandler.connectionPromise=a.initialize().then(()=>{this._rasterJobHandler.instance=a;this.raster.rasterJobHandler=a;this.renderer&&this.updateRenderer()}).catch(()=>null);return this._rasterJobHandler.connectionPromise};g._shutdownJobHandler=function(){this._rasterJobHandler.instance&&this._rasterJobHandler.instance.destroy();
this._rasterJobHandler.instance=null;this._rasterJobHandler.connectionPromise=null;this._rasterJobHandler.refCount=0;this.raster.rasterJobHandler=null};g._configDefaultInterpolation=function(){if(null==this.interpolation){var a;const b=m.getDefaultInterpolation(this.rasterInfo,this.raster.tileType,null==(a=this.sourceJSON)?void 0:a.defaultResamplingMethod);this._set("interpolation",b)}};g._configDefaultSlice=function(){const {multidimensionalInfo:a}=this.raster.rasterInfo;if(n.isSome(a)){if(!this.multidimensionalDefinition){const b=
a.variables[0],c=[];b.dimensions.forEach(d=>{c.push(new t({variableName:b.name,dimensionName:d.name,values:d.hasRegularIntervals?d.extent[0]:d.values[0],isSlice:!0}))});this.multidimensionalDefinition=c}this._sliceId=this.raster.getSliceIndex(this.multidimensionalDefinition)}};g._configDefaultRenderer=function(){const a=this.raster.rasterInfo;this.bandIds||(this.bandIds=m.getDefaultBandCombination(a));if(!this.renderer){var b,c;this.renderer=m.createDefaultRenderer(a,{bandIds:this.bandIds,variableName:null==
(b=this.multidimensionalDefinition)?void 0:null==(c=b[0])?void 0:c.variableName})}this.symbolizer?(this.symbolizer.rendererJSON=m.normalizeRendererJSON(this.renderer.toJSON()),this.symbolizer.rasterInfo=a):this.symbolizer=new G({rendererJSON:this.renderer.toJSON(),rasterInfo:a});this.symbolizer.bind()||v.warn("imagery-tile-mixin","The given renderer is not supported by the layer.")};l._createClass(q,[{key:"multidimensionalDefinition",set:function(a){this.raster&&(this._sliceId=this.raster.getSliceIndex(a));
this._set("multidimensionalDefinition",a)}},{key:"url",set:function(a){this._set("url",C.sanitizeUrl(a,v))}},{key:"renderer",set:function(a){this._set("renderer",a);this.updateRenderer()}}]);return q}(e);f.__decorate([h.property()],e.prototype,"_cachedRendererJson",void 0);f.__decorate([h.property()],e.prototype,"_sliceId",void 0);f.__decorate([h.property()],e.prototype,"_compatibleFullExtent",void 0);f.__decorate([h.property()],e.prototype,"_rasterJobHandler",void 0);f.__decorate([h.property()],
e.prototype,"bandIds",void 0);f.__decorate([h.property()],e.prototype,"copyright",void 0);f.__decorate([h.property({type:H}),p.aliasOf("rasterInfo.extent")],e.prototype,"fullExtent",void 0);f.__decorate([h.property()],e.prototype,"interpolation",void 0);f.__decorate([h.property()],e.prototype,"ioConfig",void 0);f.__decorate([h.property({type:[t]})],e.prototype,"multidimensionalDefinition",null);f.__decorate([h.property()],e.prototype,"raster",void 0);f.__decorate([h.property({readOnly:!0}),p.aliasOf("raster.rasterInfo")],
e.prototype,"rasterInfo",void 0);f.__decorate([h.property()],e.prototype,"sourceJSON",void 0);f.__decorate([h.property({type:I}),p.aliasOf("rasterInfo.spatialReference")],e.prototype,"spatialReference",void 0);f.__decorate([h.property({type:u}),p.aliasOf("rasterInfo.storageInfo.tileInfo")],e.prototype,"tileInfo",void 0);f.__decorate([h.property(D.url)],e.prototype,"url",null);f.__decorate([h.property({types:x.rasterRendererTypes})],e.prototype,"renderer",null);f.__decorate([h.property()],e.prototype,
"symbolizer",void 0);return e=f.__decorate([A.subclass("esri.layers.ImageryTileMixin")],e)};Object.defineProperty(r,"__esModule",{value:!0})});