// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define(["exports","../../chunks/_rollupPluginBabelHelpers","../../core/screenUtils","../../chunks/mat4f32","./colorMatrixFunctions"],function(g,l,n,m,h){function f(b,c,a){return b+(c-b)*a}function k(b){return Math.round(1E3*n.px2pt(b))/1E3}let p=function(){function b(a,d,e){this.strength=a;this.radius=d;this.threshold=e;this.type="bloom"}var c=b.prototype;c.interpolate=function(a,d,e){this.strength=f(a.strength,d.strength,e);this.radius=f(a.radius,d.radius,e);this.threshold=f(a.threshold,d.threshold,
e)};c.clone=function(){return new b(this.strength,this.radius,this.threshold)};c.toJSON=function(){return{type:"bloom",radius:k(this.radius),strength:this.strength,threshold:this.threshold}};return b}(),q=function(){function b(a){this.radius=a;this.type="blur"}var c=b.prototype;c.interpolate=function(a,d,e){this.radius=Math.round(f(a.radius,d.radius,e))};c.clone=function(){return new b(this.radius)};c.toJSON=function(){return{type:"blur",radius:k(this.radius)}};return b}(),r=function(){function b(a,
d){this.type=a;this.amount=d;if("invert"===this.type||"grayscale"===this.type||"sepia"===this.type)this.amount=Math.min(this.amount,1)}var c=b.prototype;c.interpolate=function(a,d,e){this.amount=f(a.amount,d.amount,e);this._updateMatrix()};c.clone=function(){return new b(this.type,this.amount)};c.toJSON=function(){return{type:this.type,amount:this.amount}};c._updateMatrix=function(){const a=this._colorMatrix||m.create();switch(this.type){case "brightness":this._colorMatrix=h.brightness(a,this.amount);
break;case "contrast":this._colorMatrix=h.contrast(a,this.amount);break;case "grayscale":this._colorMatrix=h.grayscale(a,this.amount);break;case "invert":this._colorMatrix=h.invert(a,this.amount);break;case "saturate":this._colorMatrix=h.saturate(a,this.amount);break;case "sepia":this._colorMatrix=h.sepia(a,this.amount)}};l._createClass(b,[{key:"colorMatrix",get:function(){this._colorMatrix||this._updateMatrix();return this._colorMatrix}}]);return b}(),u=function(){function b(a,d,e,t){this.offsetX=
a;this.offsetY=d;this.blurRadius=e;this.color=t;this.type="drop-shadow"}var c=b.prototype;c.interpolate=function(a,d,e){this.offsetX=f(a.offsetX,d.offsetX,e);this.offsetY=f(a.offsetY,d.offsetY,e);this.blurRadius=f(a.blurRadius,d.blurRadius,e);this.color[0]=Math.round(f(a.color[0],d.color[0],e));this.color[1]=Math.round(f(a.color[1],d.color[1],e));this.color[2]=Math.round(f(a.color[2],d.color[2],e));this.color[3]=f(a.color[3],d.color[3],e)};c.clone=function(){return new b(this.offsetX,this.offsetY,
this.blurRadius,[...this.color])};c.toJSON=function(){const a=[...this.color];a[3]*=255;return{type:"drop-shadow",xoffset:k(this.offsetX),yoffset:k(this.offsetY),blurRadius:k(this.blurRadius),color:a}};return b}(),v=function(){function b(a){this.angle=a;this.type="hue-rotate"}var c=b.prototype;c.interpolate=function(a,d,e){this.angle=f(a.angle,d.angle,e);this._updateMatrix()};c.clone=function(){return new b(this.angle)};c.toJSON=function(){return{type:"hue-rotate",angle:this.angle}};c._updateMatrix=
function(){const a=this._colorMatrix||m.create();this._colorMatrix=h.rotateHue(a,this.angle)};l._createClass(b,[{key:"colorMatrix",get:function(){this._colorMatrix||this._updateMatrix();return this._colorMatrix}}]);return b}(),w=function(){function b(a){this.amount=a;this.type="opacity";this.amount=Math.min(this.amount,1)}var c=b.prototype;c.interpolate=function(a,d,e){this.amount=f(a.amount,d.amount,e)};c.clone=function(){return new b(this.amount)};c.toJSON=function(){return{type:"opacity",amount:this.amount}};
return b}();g.BloomEffect=p;g.BlurEffect=q;g.ColorMatrixEffect=r;g.DropShadowEffect=u;g.HueRotateEffect=v;g.OpacityEffect=w;g.isColorMatrixEffect=function(b){return"colorMatrix"in b};Object.defineProperty(g,"__esModule",{value:!0})});