// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define(["exports"],function(ab){var N={exports:{}};(function(bb,za){za=function(){var Aa="undefined"!==typeof document&&document.currentScript?document.currentScript.src:void 0;return function(O){function cb(a){return f.locateFile?f.locateFile(a,D):D+a}function P(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ba)return Ba.decode(a.subarray(b,c));for(d="";b<c;){var g=a[b++];if(g&128){var h=a[b++]&63;if(192==(g&224))d+=String.fromCharCode((g&31)<<6|h);else{var k=a[b++]&63;g=224==
(g&240)?(g&15)<<12|h<<6|k:(g&7)<<18|h<<12|k<<6|a[b++]&63;65536>g?d+=String.fromCharCode(g):(g-=65536,d+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else d+=String.fromCharCode(g)}return d}function Ca(a,b,c,d){if(!(0<d))return 0;var g=c;d=c+d-1;for(var h=0;h<a.length;++h){var k=a.charCodeAt(h);if(55296<=k&&57343>=k){var l=a.charCodeAt(++h);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|
k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-g}function Da(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function db(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&X[c];)++c;c<<=1;if(32<c-a&&Ea)return Ea.decode(v.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var g=K[a+2*d>>1];if(0==g)break;c+=String.fromCharCode(g)}return c}
function eb(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var g=0;g<c;++g){var h=a.charCodeAt(g);K[b>>1]=h;b+=2}K[b>>1]=0;return b-d}function fb(a){return 2*a.length}function gb(a,b){for(var c=0,d="";!(c>=b/4);){var g=r[a+4*c>>2];if(0==g)break;++c;65536<=g?(g-=65536,d+=String.fromCharCode(55296|g>>10,56320|g&1023)):d+=String.fromCharCode(g)}return d}function hb(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var g=0;g<a.length;++g){var h=
a.charCodeAt(g);if(55296<=h&&57343>=h){var k=a.charCodeAt(++g);h=65536+((h&1023)<<10)|k&1023}r[b>>2]=h;b+=4;if(b+4>c)break}r[b>>2]=0;return b-d}function ib(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function jb(a,b){0<a%b&&(a+=b-a%b);return a}function Fa(a){ma=a;f.HEAP8=B=new Int8Array(a);f.HEAP16=K=new Int16Array(a);f.HEAP32=r=new Int32Array(a);f.HEAPU8=v=new Uint8Array(a);f.HEAPU16=X=new Uint16Array(a);f.HEAPU32=E=new Uint32Array(a);f.HEAPF32=
Ga=new Float32Array(a);f.HEAPF64=Ha=new Float64Array(a)}function Y(a){if(f.onAbort)f.onAbort(a);a+="";L(a);Ia=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS\x3d1 for more info.");na(a);throw a;}function Ja(a){try{if(a==C&&Q)return new Uint8Array(Q);if(oa)return oa(a);throw"both async and sync fetching of the wasm failed";}catch(b){Y(b)}}function kb(){return Q||!Ka&&!Z||"function"!==typeof fetch?Promise.resolve().then(function(){return Ja(C)}):fetch(C,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+
C+"'";return a.arrayBuffer()}).catch(function(){return Ja(C)})}function pa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.func;"number"===typeof c?void 0===b.arg?R.get(c)():R.get(c)(b.arg):c(void 0===b.arg?null:b.arg)}}}function lb(a){this.excPtr=a;this.ptr=a-16;this.set_type=function(b){r[this.ptr+4>>2]=b};this.get_type=function(){return r[this.ptr+4>>2]};this.set_destructor=function(b){r[this.ptr+8>>2]=b};this.get_destructor=function(){return r[this.ptr+8>>2]};this.set_refcount=
function(b){r[this.ptr>>2]=b};this.set_caught=function(b){B[this.ptr+12>>0]=b?1:0};this.get_caught=function(){return 0!=B[this.ptr+12>>0]};this.set_rethrown=function(b){B[this.ptr+13>>0]=b?1:0};this.get_rethrown=function(){return 0!=B[this.ptr+13>>0]};this.init=function(b,c){this.set_type(b);this.set_destructor(c);this.set_refcount(0);this.set_caught(!1);this.set_rethrown(!1)};this.add_ref=function(){r[this.ptr>>2]+=1};this.release_ref=function(){var b=r[this.ptr>>2];r[this.ptr>>2]=b-1;return 1===
b}}function La(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function aa(a){return this.fromWireType(E[a>>2])}function mb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function nb(a,b){a=mb(a);return function(){return b.apply(this,arguments)}}function qa(a,b){var c=nb(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);
c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}function Ma(a,b,c){function d(l){l=c(l);if(l.length!==a.length)throw new ra("Mismatched type converter count");for(var m=0;m<a.length;++m)F(a[m],l[m])}a.forEach(function(l){ba[l]=b});var g=Array(b.length),h=[],k=0;b.forEach(function(l,m){I.hasOwnProperty(l)?g[m]=I[l]:(h.push(l),M.hasOwnProperty(l)||(M[l]=[]),M[l].push(function(){g[m]=I[l];++k;k===h.length&&d(g)}))});
0===h.length&&d(g)}function sa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}function x(a){for(var b="";v[a];)b+=Na[v[a++]];return b}function z(a){throw new Oa(a);}function F(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||z('type "'+d+'" must have a positive integer typeid pointer');if(I.hasOwnProperty(a)){if(c.ignoreDuplicateRegistrations)return;
z("Cannot register type '"+d+"' twice")}I[a]=b;delete ba[a];M.hasOwnProperty(a)&&(b=M[a],delete M[a],b.forEach(function(g){g()}))}function Pa(a){4<a&&0===--A[a].refcount&&(A[a]=void 0,ta.push(a))}function ua(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=ta.length?ta.pop():A.length;A[b]={refcount:1,value:a};return b}}function va(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function ob(a,
b){switch(b){case 2:return function(c){return this.fromWireType(Ga[c>>2])};case 3:return function(c){return this.fromWireType(Ha[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function pb(a,b,c,d,g){var h=b.length;2>h&&z("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].destructorFunction){l=!0;break}var m="void"!==b[0].name,n=h-2,q=Array(n),u=[],w=[];return function(){arguments.length!==
n&&z("function "+a+" called with "+arguments.length+" arguments, expected "+n+" args!");w.length=0;u.length=k?2:1;u[0]=g;if(k){var e=b[1].toWireType(w,this);u[1]=e}for(var p=0;p<n;++p)q[p]=b[p+2].toWireType(w,arguments[p]),u.push(q[p]);p=d.apply(null,u);if(l)La(w);else for(var t=k?1:2;t<b.length;t++){var y=1===t?e:q[t-2];null!==b[t].destructorFunction&&b[t].destructorFunction(y)}e=m?b[0].fromWireType(p):void 0;return e}}function qb(a,b,c){if(void 0===a[b].overloadTable){var d=a[b];a[b]=function(){a[b].overloadTable.hasOwnProperty(arguments.length)||
z("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].overloadTable+")!");return a[b].overloadTable[arguments.length].apply(this,arguments)};a[b].overloadTable=[];a[b].overloadTable[d.argCount]=d}}function rb(a,b,c){f.hasOwnProperty(a)?((void 0===c||void 0!==f[a].overloadTable&&void 0!==f[a].overloadTable[c])&&z("Cannot register public name '"+a+"' twice"),qb(f,a,a),f.hasOwnProperty(c)&&z("Cannot register multiple overloads of a function with the same number of arguments ("+
c+")!"),f[a].overloadTable[c]=b):(f[a]=b,void 0!==c&&(f[a].numArguments=c))}function sb(a,b){for(var c=[],d=0;d<a;d++)c.push(r[(b>>2)+d]);return c}function tb(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=f["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=R.get(b).apply(null,c);return d}}function S(a,b){a=x(a);var c=a.includes("j")?tb(a,b):R.get(b);"function"!==typeof c&&z("unknown function pointer with signature "+
a+": "+b);return c}function Qa(a){a=Ra(a);var b=x(a);G(a);return b}function ub(a,b){function c(h){g[h]||I[h]||(ba[h]?ba[h].forEach(c):(d.push(h),g[h]=!0))}var d=[],g={};b.forEach(c);throw new Sa(a+": "+d.map(Qa).join([", "]));}function vb(a,b,c){switch(b){case 0:return c?function(d){return B[d]}:function(d){return v[d]};case 1:return c?function(d){return K[d>>1]}:function(d){return X[d>>1]};case 2:return c?function(d){return r[d>>2]}:function(d){return E[d>>2]};default:throw new TypeError("Unknown integer type: "+
a);}}function T(){if(!T.strings){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:Ta||"./this.program"},b;for(b in wa)void 0===wa[b]?delete a[b]:a[b]=wa[b];var c=[];for(b in a)c.push(b+"\x3d"+a[b]);T.strings=c}return T.strings}function ca(a){return 0===a%4&&(0!==a%100||0===a%400)}function xa(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}function da(a,b){for(a=
new Date(a.getTime());0<b;){var c=ca(a.getFullYear()),d=a.getMonth();c=(c?ea:fa)[d];if(b>c-a.getDate())b-=c-a.getDate()+1,a.setDate(1),11>d?a.setMonth(d+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}function wb(a,b,c,d){function g(e,p,t){for(e="number"===typeof e?e.toString():e||"";e.length<p;)e=t[0]+e;return e}function h(e,p){return g(e,p,"0")}function k(e,p){function t(ha){return 0>ha?-1:0<ha?1:0}var y;0===(y=t(e.getFullYear()-p.getFullYear()))&&
0===(y=t(e.getMonth()-p.getMonth()))&&(y=t(e.getDate()-p.getDate()));return y}function l(e){switch(e.getDay()){case 0:return new Date(e.getFullYear()-1,11,29);case 1:return e;case 2:return new Date(e.getFullYear(),0,3);case 3:return new Date(e.getFullYear(),0,2);case 4:return new Date(e.getFullYear(),0,1);case 5:return new Date(e.getFullYear()-1,11,31);case 6:return new Date(e.getFullYear()-1,11,30)}}function m(e){e=da(new Date(e.tm_year+1900,0,1),e.tm_yday);var p=new Date(e.getFullYear(),0,4),t=
new Date(e.getFullYear()+1,0,4);p=l(p);t=l(t);return 0>=k(p,e)?0>=k(t,e)?e.getFullYear()+1:e.getFullYear():e.getFullYear()-1}var n=r[d+40>>2];d={tm_sec:r[d>>2],tm_min:r[d+4>>2],tm_hour:r[d+8>>2],tm_mday:r[d+12>>2],tm_mon:r[d+16>>2],tm_year:r[d+20>>2],tm_wday:r[d+24>>2],tm_yday:r[d+28>>2],tm_isdst:r[d+32>>2],tm_gmtoff:r[d+36>>2],tm_zone:n?n?P(v,n,void 0):"":""};c=c?P(v,c,void 0):"";n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S",
"%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in n)c=c.replace(new RegExp(q,"g"),n[q]);var u="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),w="January February March April May June July August September October November December".split(" ");n={"%a":function(e){return u[e.tm_wday].substring(0,
3)},"%A":function(e){return u[e.tm_wday]},"%b":function(e){return w[e.tm_mon].substring(0,3)},"%B":function(e){return w[e.tm_mon]},"%C":function(e){return h((e.tm_year+1900)/100|0,2)},"%d":function(e){return h(e.tm_mday,2)},"%e":function(e){return g(e.tm_mday,2," ")},"%g":function(e){return m(e).toString().substring(2)},"%G":function(e){return m(e)},"%H":function(e){return h(e.tm_hour,2)},"%I":function(e){e=e.tm_hour;0==e?e=12:12<e&&(e-=12);return h(e,2)},"%j":function(e){return h(e.tm_mday+xa(ca(e.tm_year+
1900)?ea:fa,e.tm_mon-1),3)},"%m":function(e){return h(e.tm_mon+1,2)},"%M":function(e){return h(e.tm_min,2)},"%n":function(){return"\n"},"%p":function(e){return 0<=e.tm_hour&&12>e.tm_hour?"AM":"PM"},"%S":function(e){return h(e.tm_sec,2)},"%t":function(){return"\t"},"%u":function(e){return e.tm_wday||7},"%U":function(e){var p=new Date(e.tm_year+1900,0,1),t=0===p.getDay()?p:da(p,7-p.getDay());e=new Date(e.tm_year+1900,e.tm_mon,e.tm_mday);return 0>k(t,e)?(p=xa(ca(e.getFullYear())?ea:fa,e.getMonth()-1)-
31,t=31-t.getDate()+p+e.getDate(),h(Math.ceil(t/7),2)):0===k(t,p)?"01":"00"},"%V":function(e){var p=new Date(e.tm_year+1901,0,4),t=l(new Date(e.tm_year+1900,0,4));p=l(p);var y=da(new Date(e.tm_year+1900,0,1),e.tm_yday);if(0>k(y,t))return"53";if(0>=k(p,y))return"01";e=t.getFullYear()<e.tm_year+1900?e.tm_yday+32-t.getDate():e.tm_yday+1-t.getDate();return h(Math.ceil(e/7),2)},"%w":function(e){return e.tm_wday},"%W":function(e){var p=new Date(e.tm_year,0,1),t=1===p.getDay()?p:da(p,0===p.getDay()?1:7-
p.getDay()+1);e=new Date(e.tm_year+1900,e.tm_mon,e.tm_mday);return 0>k(t,e)?(p=xa(ca(e.getFullYear())?ea:fa,e.getMonth()-1)-31,t=31-t.getDate()+p+e.getDate(),h(Math.ceil(t/7),2)):0===k(t,p)?"01":"00"},"%y":function(e){return(e.tm_year+1900).toString().substring(2)},"%Y":function(e){return e.tm_year+1900},"%z":function(e){e=e.tm_gmtoff;var p=0<=e;e=Math.abs(e)/60;return(p?"+":"-")+String("0000"+(e/60*100+e%60)).slice(-4)},"%Z":function(e){return e.tm_zone},"%%":function(){return"%"}};for(q in n)c.includes(q)&&
(c=c.replace(new RegExp(q,"g"),n[q](d)));q=xb(c,!1);if(q.length>b)return 0;B.set(q,a);return q.length-1}function xb(a,b,c){c=0<c?c:Da(a)+1;c=Array(c);a=Ca(a,c,0,c.length);b&&(c.length=a);return c}function ya(a){function b(){if(!ia&&(ia=!0,f.calledRun=!0,!Ia)){pa(Ua);Va(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)Wa.unshift(f.postRun.shift());pa(Wa)}}if(!(0<J)){if(f.preRun)for("function"==typeof f.preRun&&
(f.preRun=[f.preRun]);f.preRun.length;)Xa.unshift(f.preRun.shift());pa(Xa);0<J||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}O=O||{};var f="undefined"!==typeof O?O:{},Va,na;f.ready=new Promise(function(a,b){Va=a;na=b});var U={},H;for(H in f)f.hasOwnProperty(H)&&(U[H]=f[H]);var Ta="./this.program",Ka="object"===typeof window,Z="function"===typeof importScripts;"object"===typeof process&&"object"===typeof process.versions&&"string"===
typeof process.versions.node;var D="",oa;if(Ka||Z)Z?D=self.location.href:"undefined"!==typeof document&&document.currentScript&&(D=document.currentScript.src),Aa&&(D=Aa),D=0!==D.indexOf("blob:")?D.substr(0,D.lastIndexOf("/")+1):"",Z&&(oa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var yb=f.print||console.log.bind(console),L=f.printErr||console.warn.bind(console);for(H in U)U.hasOwnProperty(H)&&(f[H]=U[H]);U=
null;f.thisProgram&&(Ta=f.thisProgram);var Q;f.wasmBinary&&(Q=f.wasmBinary);f.noExitRuntime||!0;"object"!==typeof WebAssembly&&Y("no native wasm support detected");var ja,Ia=!1,Ba="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0,Ea="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0,ma,B,v,K,X,r,E,Ga,Ha;f.INITIAL_MEMORY||16777216;var R,Xa=[],Ua=[],Wa=[],J=0,V=null;f.preloadedImages={};f.preloadedAudios={};var C="i3s.wasm";C.startsWith("data:application/octet-stream;base64,")||
(C=cb(C));var ka={},M={},I={},ba={},ra=void 0,Na=void 0,Oa=void 0,ta=[],A=[{},{value:void 0},{value:null},{value:!0},{value:!1}],Sa=void 0,zb={},wa={},W={mappings:{},buffers:[null,[],[]],printChar:function(a,b){var c=W.buffers[a];0===b||10===b?((1===a?yb:L)(P(c,0)),c.length=0):c.push(b)},varargs:void 0,get:function(){W.varargs+=4;return r[W.varargs-4>>2]},getStr:function(a){return a?P(v,a,void 0):""},get64:function(a,b){return a}},ea=[31,29,31,30,31,30,31,31,30,31,30,31],fa=[31,28,31,30,31,30,31,
31,30,31,30,31];ra=f.InternalError=qa(Error,"InternalError");(function(){for(var a=Array(256),b=0;256>b;++b)a[b]=String.fromCharCode(b);Na=a})();Oa=f.BindingError=qa(Error,"BindingError");f.count_emval_handles=function(){for(var a=0,b=5;b<A.length;++b)void 0!==A[b]&&++a;return a};f.get_first_emval=function(){for(var a=5;a<A.length;++a)if(void 0!==A[a])return A[a];return null};Sa=f.UnboundTypeError=qa(Error,"UnboundTypeError");var $a={__cxa_allocate_exception:function(a){return la(a+16)+16},__cxa_atexit:function(a,
b){},__cxa_throw:function(a,b,c){(new lb(a)).init(b,c);throw a;},_embind_finalize_value_object:function(a){var b=ka[a];delete ka[a];var c=b.rawConstructor,d=b.rawDestructor,g=b.fields,h=g.map(function(k){return k.getterReturnType}).concat(g.map(function(k){return k.setterArgumentType}));Ma([a],h,function(k){var l={};g.forEach(function(m,n){var q=k[n],u=m.getter,w=m.getterContext,e=k[n+g.length],p=m.setter,t=m.setterContext;l[m.fieldName]={read:function(y){return q.fromWireType(u(w,y))},write:function(y,
ha){var Ya=[];p(t,y,e.toWireType(Ya,ha));La(Ya)}}});return[{name:b.name,fromWireType:function(m){var n={},q;for(q in l)n[q]=l[q].read(m);d(m);return n},toWireType:function(m,n){for(var q in l)if(!(q in n))throw new TypeError('Missing field:  "'+q+'"');var u=c();for(q in l)l[q].write(u,n[q]);null!==m&&m.push(d,u);return u},argPackAdvance:8,readValueFromPointer:aa,destructorFunction:d}]})},_embind_register_bigint:function(a,b,c,d,g){},_embind_register_bool:function(a,b,c,d,g){var h=sa(c);b=x(b);F(a,
{name:b,fromWireType:function(k){return!!k},toWireType:function(k,l){return l?d:g},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var l=B;else if(2===c)l=K;else if(4===c)l=r;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[k>>h])},destructorFunction:null})},_embind_register_emval:function(a,b){b=x(b);F(a,{name:b,fromWireType:function(c){var d=A[c].value;Pa(c);return d},toWireType:function(c,d){return ua(d)},argPackAdvance:8,readValueFromPointer:aa,destructorFunction:null})},
_embind_register_float:function(a,b,c){c=sa(c);b=x(b);F(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,g){if("number"!==typeof g&&"boolean"!==typeof g)throw new TypeError('Cannot convert "'+va(g)+'" to '+this.name);return g},argPackAdvance:8,readValueFromPointer:ob(b,c),destructorFunction:null})},_embind_register_function:function(a,b,c,d,g,h){var k=sb(b,c);a=x(a);g=S(d,g);rb(a,function(){ub("Cannot call "+a+" due to unbound types",k)},b-1);Ma([],k,function(l){var m=[l[0],null].concat(l.slice(1));
l=a;m=pb(a,m,null,g,h);var n=b-1;if(!f.hasOwnProperty(l))throw new ra("Replacing nonexistant public symbol");void 0!==f[l].overloadTable&&void 0!==n?f[l].overloadTable[n]=m:(f[l]=m,f[l].argCount=n);return[]})},_embind_register_integer:function(a,b,c,d,g){b=x(b);-1===g&&(g=4294967295);var h=sa(c),k=function(n){return n};if(0===d){var l=32-8*c;k=function(n){return n<<l>>>l}}var m=b.includes("unsigned");F(a,{name:b,fromWireType:k,toWireType:function(n,q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+
va(q)+'" to '+this.name);if(q<d||q>g)throw new TypeError('Passing a number "'+va(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+g+"]!");return m?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:vb(b,h,0!==d),destructorFunction:null})},_embind_register_memory_view:function(a,b,c){function d(h){h>>=2;var k=E;return new g(ma,k[h+1],k[h])}var g=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];
c=x(c);F(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{ignoreDuplicateRegistrations:!0})},_embind_register_std_string:function(a,b){b=x(b);var c="std::string"===b;F(a,{name:b,fromWireType:function(d){var g=E[d>>2];if(c)for(var h=d+4,k=0;k<=g;++k){var l=d+4+k;if(k==g||0==v[l]){var m=l-h;h=h?P(v,h,m):"";if(void 0===n)var n=h;else n+=String.fromCharCode(0),n+=h;h=l+1}}else{n=Array(g);for(k=0;k<g;++k)n[k]=String.fromCharCode(v[d+4+k]);n=n.join("")}G(d);return n},toWireType:function(d,
g){g instanceof ArrayBuffer&&(g=new Uint8Array(g));var h="string"===typeof g;h||g instanceof Uint8Array||g instanceof Uint8ClampedArray||g instanceof Int8Array||z("Cannot pass non-string to std::string");var k=(c&&h?function(){return Da(g)}:function(){return g.length})(),l=la(4+k+1);E[l>>2]=k;if(c&&h)Ca(g,v,l+4,k+1);else if(h)for(h=0;h<k;++h){var m=g.charCodeAt(h);255<m&&(G(l),z("String has UTF-16 code units that do not fit in 8 bits"));v[l+4+h]=m}else for(h=0;h<k;++h)v[l+4+h]=g[h];null!==d&&d.push(G,
l);return l},argPackAdvance:8,readValueFromPointer:aa,destructorFunction:function(d){G(d)}})},_embind_register_std_wstring:function(a,b,c){c=x(c);if(2===b){var d=db;var g=eb;var h=fb;var k=function(){return X};var l=1}else 4===b&&(d=gb,g=hb,h=ib,k=function(){return E},l=2);F(a,{name:c,fromWireType:function(m){for(var n=E[m>>2],q=k(),u,w=m+4,e=0;e<=n;++e){var p=m+4+e*b;if(e==n||0==q[p>>l])w=d(w,p-w),void 0===u?u=w:(u+=String.fromCharCode(0),u+=w),w=p+b}G(m);return u},toWireType:function(m,n){"string"!==
typeof n&&z("Cannot pass non-string to C++ string type "+c);var q=h(n),u=la(4+q+b);E[u>>2]=q>>l;g(n,u+4,q+b);null!==m&&m.push(G,u);return u},argPackAdvance:8,readValueFromPointer:aa,destructorFunction:function(m){G(m)}})},_embind_register_value_object:function(a,b,c,d,g,h){ka[a]={name:x(b),rawConstructor:S(c,d),rawDestructor:S(g,h),fields:[]}},_embind_register_value_object_field:function(a,b,c,d,g,h,k,l,m,n){ka[a].fields.push({fieldName:x(b),getterReturnType:c,getter:S(d,g),getterContext:h,setterArgumentType:k,
setter:S(l,m),setterContext:n})},_embind_register_void:function(a,b){b=x(b);F(a,{isVoid:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(c,d){}})},_emval_decref:Pa,_emval_incref:function(a){4<a&&(A[a].refcount+=1)},_emval_new_cstring:function(a){var b=zb[a];a=void 0===b?x(a):b;return ua(a)},_emval_take_value:function(a,b){var c=I[a];void 0===c&&z("_emval_take_value has unknown type "+Qa(a));a=c.readValueFromPointer(b);return ua(a)},abort:function(){Y()},emscripten_memcpy_big:function(a,
b,c){v.copyWithin(a,b,b+c)},emscripten_resize_heap:function(a){var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.min(2147483648,jb(Math.max(a,d),65536));a:{try{ja.grow(d-ma.byteLength+65535>>>16);Fa(ja.buffer);var g=1;break a}catch(h){}g=void 0}if(g)return!0}return!1},environ_get:function(a,b){var c=0;T().forEach(function(d,g){var h=b+c;g=r[a+4*g>>2]=h;for(h=0;h<d.length;++h)B[g++>>0]=d.charCodeAt(h);B[g>>0]=0;c+=d.length+1});return 0},
environ_sizes_get:function(a,b){var c=T();r[a>>2]=c.length;var d=0;c.forEach(function(g){d+=g.length+1});r[b>>2]=d;return 0},fd_close:function(a){return 0},fd_seek:function(a,b,c,d,g){},fd_write:function(a,b,c,d){for(var g=0,h=0;h<c;h++){for(var k=r[b+8*h>>2],l=r[b+(8*h+4)>>2],m=0;m<l;m++)W.printChar(a,v[k+m]);g+=l}r[d>>2]=g;return 0},raise:function(a){r[Za()>>2]=52;return-1},setTempRet0:function(a){},strftime_l:function(a,b,c,d){return wb(a,b,c,d)}};(function(){function a(g,h){f.asm=g.exports;ja=
f.asm.memory;Fa(ja.buffer);R=f.asm.__indirect_function_table;Ua.unshift(f.asm.__wasm_call_ctors);J--;f.monitorRunDependencies&&f.monitorRunDependencies(J);0==J&&V&&(g=V,V=null,g())}function b(g){a(g.instance)}function c(g){return kb().then(function(h){return WebAssembly.instantiate(h,d)}).then(g,function(h){L("failed to asynchronously prepare wasm: "+h);Y(h)})}var d={env:$a,wasi_snapshot_preview1:$a};J++;f.monitorRunDependencies&&f.monitorRunDependencies(J);if(f.instantiateWasm)try{return f.instantiateWasm(d,
a)}catch(g){return L("Module.instantiateWasm callback failed with error: "+g),!1}(function(){return Q||"function"!==typeof WebAssembly.instantiateStreaming||C.startsWith("data:application/octet-stream;base64,")||"function"!==typeof fetch?c(b):fetch(C,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,d).then(b,function(h){L("wasm streaming compile failed: "+h);L("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(na);return{}})();f.___wasm_call_ctors=
function(){return(f.___wasm_call_ctors=f.asm.__wasm_call_ctors).apply(null,arguments)};var la=f._malloc=function(){return(la=f._malloc=f.asm.malloc).apply(null,arguments)},G=f._free=function(){return(G=f._free=f.asm.free).apply(null,arguments)},Ra=f.___getTypeName=function(){return(Ra=f.___getTypeName=f.asm.__getTypeName).apply(null,arguments)};f.___embind_register_native_and_builtin_types=function(){return(f.___embind_register_native_and_builtin_types=f.asm.__embind_register_native_and_builtin_types).apply(null,
arguments)};var Za=f.___errno_location=function(){return(Za=f.___errno_location=f.asm.__errno_location).apply(null,arguments)};f.stackSave=function(){return(f.stackSave=f.asm.stackSave).apply(null,arguments)};f.stackRestore=function(){return(f.stackRestore=f.asm.stackRestore).apply(null,arguments)};f.stackAlloc=function(){return(f.stackAlloc=f.asm.stackAlloc).apply(null,arguments)};f.dynCall_vij=function(){return(f.dynCall_vij=f.asm.dynCall_vij).apply(null,arguments)};f.dynCall_jiji=function(){return(f.dynCall_jiji=
f.asm.dynCall_jiji).apply(null,arguments)};f.dynCall_viijii=function(){return(f.dynCall_viijii=f.asm.dynCall_viijii).apply(null,arguments)};f.dynCall_iiiiij=function(){return(f.dynCall_iiiiij=f.asm.dynCall_iiiiij).apply(null,arguments)};f.dynCall_iiiiijj=function(){return(f.dynCall_iiiiijj=f.asm.dynCall_iiiiijj).apply(null,arguments)};f.dynCall_iiiiiijj=function(){return(f.dynCall_iiiiiijj=f.asm.dynCall_iiiiiijj).apply(null,arguments)};var ia;V=function b(){ia||ya();ia||(V=b)};f.run=ya;if(f.preInit)for("function"==
typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();ya();return O.ready}}();bb.exports=za})(N);var Ab=N.exports;N=Object.freeze(Object.assign(Object.create(null),N.exports,{default:Ab}));ab.i3s=N});