// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../intl ../../../../../core/Accessor ../../../../../core/has ../../../../../core/Handles ../../../../../core/mathUtils ../../../../../core/maybe ../../../../../core/Quantity ../../../../../core/quantityFormatUtils ../../../../../core/unitUtils ../../../../../core/accessorSupport/decorators/property ../../../../../core/accessorSupport/ensureType ../../../../../core/Logger ../../../../../core/accessorSupport/decorators/subclass ../../../../../core/accessorSupport/trackingUtils ../../../../../chunks/mat4 ../../../../../chunks/mat4f64 ../../../../../chunks/vec3 ../../../../../chunks/vec3f64 ../../../../../chunks/vec4f64 ../../../interactive/measurementTools/support/measurementUtils ../../../interactive/measurementTools/support/viewUtils ../../../interactive/visualElements/LabelVisualElement ../../../interactive/visualElements/LineVisualElement ../../../interactive/visualElements/MeasurementAreaVisualElement ../../../interactive/visualElements/support/Segment ../../../webgl-engine/materials/lineStippleUtils ../../../../../intl/locale ../../../../../intl/messages".split(" "),
function(l,C,m,Z,M,aa,N,u,f,E,F,w,n,ba,ca,O,D,G,P,H,v,Q,I,R,A,x,S,y,T,U,V){l.AreaMeasurementView=function(J){function B(a){a=J.call(this,a)||this;a._handles=new N;a._params={...W};a._path=null;a._intersectedPath=null;a._perimeter=null;a._intersectedPerimeter=null;a._projectionLines=null;a._measurementArea=null;a._areaLabel=null;a._pathLengthLabel=null;a._cursorSegmentLengthLabel=null;a._perimeterLengthLabel=null;a._pathSegments=[];a._perimeterSegments=[];a._cursorSegment=null;a._origin=v.create();
a._originTransform=P.create();a._cursorPositionRenderSpace=v.create();a.messages=null;a.viewData=X;a.areaLabel=null;a.perimeterLengthLabel=null;a.mode=0;a.loadingMessages=!0;a.geodesicMeasurementDistanceThreshold=1E5;return a}C._inheritsLoose(B,J);var k=B.prototype;k.initialize=function(){var a=this;const b=this.view,c=this._params;this._path=new x.LineVisualElement({view:b,attached:!0,width:c.pathLineWidth,color:c.pathLineColor,polygonOffset:!0,renderOccluded:4});this._intersectedPath=new x.LineVisualElement({view:b,
attached:!0,width:c.pathLineWidth,color:c.intersectingLineColor,polygonOffset:!0,renderOccluded:4});this._perimeter=new x.LineVisualElement({view:b,attached:!0,width:c.perimeterLineWidth,color:c.perimeterLineColor,polygonOffset:!0,renderOccluded:4});this._intersectedPerimeter=new x.LineVisualElement({view:b,attached:!0,width:c.perimeterLineWidth,color:c.intersectingLineColor,polygonOffset:!0,renderOccluded:4});this._projectionLines=new x.LineVisualElement({view:b,attached:!0,width:c.projectionLineWidth,
color:c.projectionLineColor,stipplePattern:T.createStipplePatternSimple(c.projectionLineStippleSize),stippleIntegerRepeats:!1,polygonOffset:!0,renderOccluded:4});this._measurementArea=new S.MeasurementAreaVisualElement({view:b,attached:!0,color1:c.areaColor1,color2:c.areaColor2});this._areaLabel=new A.LabelVisualElement({view:this.view,attached:!0,fontSize:16});this._pathLengthLabel=new A.LabelVisualElement({view:b,attached:!0,fontSize:12});this._cursorSegmentLengthLabel=new A.LabelVisualElement({view:b,
attached:!0,fontSize:12});this._perimeterLengthLabel=new A.LabelVisualElement({view:b,attached:!0,fontSize:12});const d=this.layerView,e=d.layerViewData;this._handles.add([D.reactionInit(()=>[this.mode,this.visible,d.unit,e.measurementData,e.cursorPoint],()=>this._update()),D.reactionInit(()=>{var h;return null==(h=b.state)?void 0:h.camera},()=>this._updateLabels()),U.onLocaleChange(C._asyncToGenerator(function*(){return a._updateMessageBundle()})),D.reactionInit(()=>this.layerView.fullOpacity,()=>
this._updateVisualElementsOpacity())]);this._updateMessageBundle()};k.destroy=function(){this._measurementArea=f.destroyMaybe(this._measurementArea);this._path=f.destroyMaybe(this._path);this._intersectedPath=f.destroyMaybe(this._intersectedPath);this._perimeter=f.destroyMaybe(this._perimeter);this._intersectedPerimeter=f.destroyMaybe(this._intersectedPerimeter);this._areaLabel=f.destroyMaybe(this._areaLabel);this._pathLengthLabel=f.destroyMaybe(this._pathLengthLabel);this._cursorSegmentLengthLabel=
f.destroyMaybe(this._cursorSegmentLengthLabel);this._perimeterLengthLabel=f.destroyMaybe(this._perimeterLengthLabel);this._handles=f.destroyMaybe(this._handles);this.set("view",null)};k._update=function(){if(!this.destroyed){var a=this.layerView.layerViewData.measurementData;f.isNone(a)||(this._updateViewData(a,this.layerView.layerViewData.path,this.layerView.layerViewData.cursorPoint),this._updateOrigin(),this._updatePathSegments(),this._updatePerimeterSegments(),this._updateArea(),this._updateProjectionLines(),
this._updateLabels())}};k._updateViewData=function(a,b,c){const d=b.isValidPolygon;var e=b.lastPoint;const h=f.isSome(e)&&f.isSome(c)?new E(I.segmentLengthGeodesic(e,c),"meters"):null;e=f.isSome(e)&&f.isSome(c)?new E(a.unitNormalizer.normalizeDistance(I.segmentLengthEuclidean(e,c,a.unitNormalizer.spatialReference)),"meters"):null;let g=this.mode;0===this.mode&&(g=1,(a.geodesicPathLength?a.geodesicPathLength.value:0)+(!d&&f.isSome(h)?h.value:0)>this.geodesicMeasurementDistanceThreshold&&(g=2));null==
a.geodesicPathLength&&(g=1);const p=2===g;var q=p?a.geodesicArea:a.area;let r=1;q&&(q=this._toPreferredAreaUnit(q,this.layerView.unit),r=u.nextHighestPowerOfTen(Math.sqrt(q.value)/Math.sqrt(300)),r*=Math.sqrt(w.convertUnit(1,q.unit,"square-meters")),r/=a.unitNormalizer.normalizeDistance(1));this._set("viewData",{validMeasurement:d,path:b,pathVersion:b.version,cursorPoint:c,measurementData:a,mode:g,positionsGeographic:a.positionsGeographic,positionsRenderCoords:a.positionsRenderCoords,positionsProjected:a.positionsProjectedWorldCoords,
positionsFittedRenderCoords:a.positionsFittedRenderCoords,intersectingSegments:p?a.geodesicIntersectingSegments:a.intersectingSegments,triangleIndices:p?a.geodesicTriangleIndices:a.triangleIndices,fittingMode:a.fittingMode,areaCentroid:p?a.geodesicAreaCentroidRenderCoords:a.areaCentroidRenderCoords,pathLengthLabelSegmentIndex:d?0:b.numVertices-2,perimeterLengthLabelSegmentIndex:0,checkerSize:r,geodesicCursorSegmentLength:h,cursorSegmentLength:e})};k._updateOrigin=function(){R.midpoint(this.viewData.positionsRenderCoords,
this._origin);G.identity(this._originTransform);G.translate(this._originTransform,this._originTransform,this._origin);this._measurementArea.transform=this._originTransform;this._projectionLines.transform=this._originTransform};k._createSegments=function(a){const b=this.viewData,c=b.path,d=this.view.renderCoordsHelper.spatialReference,e=b.mode,h=[],g=[],p=[],q=b.validMeasurement?c.numVertices:c.numVertices-1;for(let r=0;r<q;++r){const K=b[a][r],L=b[a][(r+1)%c.numVertices];let z=null;switch(e){case 1:z=
new y.EuclideanSegment(K,L);break;case 2:z=new y.GeodesicSegment(K,L,d)}b.intersectingSegments.has(r)?p.push(z):g.push(z);h.push(z)}return{all:h,nonIntersecting:g,intersecting:p}};k._updatePathSegments=function(){const a=this.visible;var b=this.viewData;const c=this._createSegments("positionsRenderCoords");var d=b.path,e=!d.isValidPolygon;const h=b.cursorPoint,g=this.view.renderCoordsHelper,p=g.spatialReference,q=b.mode;this._cursorSegment=null;if(0<d.numVertices&&e&&f.isSome(h)&&g.toRenderCoords(h,
this._cursorPositionRenderSpace)){b=b.positionsRenderCoords[d.numVertices-1];d=this._cursorPositionRenderSpace;e=null;switch(q){case 1:e=new y.EuclideanSegment(b,d);break;case 2:e=new y.GeodesicSegment(b,d,p)}c.nonIntersecting.push(e);this._cursorSegment=e}this._path.setGeometryFromSegments(c.nonIntersecting,this._origin);this._path.visible=a;this._intersectedPath.setGeometryFromSegments(c.intersecting,this._origin);this._intersectedPath.visible=a;this._pathSegments=c.all};k._updatePerimeterSegments=
function(){const a=this.visible&&1===this.viewData.mode,b=this._createSegments("positionsFittedRenderCoords");this._perimeter.setGeometryFromSegments(b.nonIntersecting,this._origin);this._perimeter.visible=a;this._intersectedPerimeter.setGeometryFromSegments(b.intersecting,this._origin);this._intersectedPerimeter.visible=a;this._perimeterSegments=b.all};k._updateArea=function(){const a=this.viewData;switch(a.mode){case 1:this._updateAreaEuclidean(a);break;case 2:this._updateAreaGeodesic()}};k._updateAreaEuclidean=
function(a){const b=this.visible;a.validMeasurement&&0===a.intersectingSegments.size&&a.triangleIndices?(this._measurementArea.geometry={uv:a.positionsProjected,position:a.positionsFittedRenderCoords,triangleIndices:a.triangleIndices},this._measurementArea.size=[a.checkerSize,a.checkerSize],this._measurementArea.visible=b):this._measurementArea.visible=!1};k._updateAreaGeodesic=function(){this._measurementArea.visible=!1};k._updateProjectionLines=function(){const a=this.viewData,b=this.visible,c=
a.path;var d=a.mode;if(0<c.numVertices&&a.validMeasurement&&1===d){d=[];for(let e=0;e<c.numVertices;++e){const h=v.create();H.subtract(h,a.positionsRenderCoords[e],this._origin);const g=v.create();H.subtract(g,a.positionsFittedRenderCoords[e],this._origin);d.push([h,g])}this._projectionLines.geometry=d;this._projectionLines.visible=b}else this._projectionLines.geometry=null,this._projectionLines.visible=!1};k._updateLabels=function(){if(!this.destroyed){var a=this.viewData,b=a.path;if(b){var c=a.measurementData,
d=a.mode,e=!b.isValidPolygon,h=this.visible,g=this._formatAreaLabel(this.messages,2===d?c.geodesicArea:c.area,this.layerView.unit);f.isSome(g)?(this._areaLabel.geometry={type:"point",point:a.areaCentroid},this._areaLabel.text=g,this._areaLabel.visible=a.validMeasurement&&0===a.intersectingSegments.size&&h):this._areaLabel.visible=!1;this._set("areaLabel",f.unwrap(g));g=this._formatLengthLabel(this.messages,2===d?c.geodesicPathLength:c.pathLength,this.layerView.unit);if(f.isSome(g)&&0<=a.pathLengthLabelSegmentIndex&&
a.pathLengthLabelSegmentIndex<this._pathSegments.length){const p=this._pathSegments[a.pathLengthLabelSegmentIndex],q=f.isSome(this._cursorSegment)?this._cursorSegment:Y;this._pathLengthLabel.distance=this._params.labelDistance;this._pathLengthLabel.geometry={type:"corner",left:p,right:q};this._pathLengthLabel.text=g;this._pathLengthLabel.visible=e&&0<b.numVertices&&h}else this._pathLengthLabel.visible=!1;b=2===d?a.geodesicCursorSegmentLength:a.cursorSegmentLength;f.isSome(b)?(d=this._formatLengthLabel(this.messages,
b,this.layerView.unit),this._cursorSegmentLengthLabel.distance=this._params.labelDistance,this._cursorSegmentLengthLabel.geometry=f.isSome(this._cursorSegment)?{type:"segment",segment:this._cursorSegment,sampleLocation:"end"}:null,this._cursorSegmentLengthLabel.anchor="bottom",this._cursorSegmentLengthLabel.text=f.unwrap(d),this._cursorSegmentLengthLabel.visible=e&&0!==b.value&&h):this._cursorSegmentLengthLabel.visible=!1;this._cursorSegmentLengthLabel.overlaps(this._pathLengthLabel)&&(this._cursorSegmentLengthLabel.visible=
!1);this._pathLengthLabel.overlaps(this._areaLabel)&&(this._pathLengthLabel.visible=!1);c=(e=2===a.mode)?c.geodesicPathLength:c.perimeterLength;c=f.unwrap(null!=c?this._formatLengthLabel(this.messages,c,this.layerView.unit):null);this._set("perimeterLengthLabel",f.unwrap(c));if(a.validMeasurement&&0===a.intersectingSegments.size){this._perimeterLengthLabel.distance=this._params.labelDistance;this._perimeterLengthLabel.anchor="top";this._perimeterLengthLabel.text=c;b=this._perimeterLengthLabel.visible=
!0;for(c=0;c<a.path.numVertices;++c)if(b=(a.perimeterLengthLabelSegmentIndex+c)%a.path.numVertices,d=e?this._pathSegments[b]:this._perimeterSegments[b],b=!0,this._perimeterLengthLabel.geometry={type:"segment",segment:d,sampleLocation:"center"},this._perimeterLengthLabel.overlaps(this._areaLabel))b=!1;else break;this._perimeterLengthLabel.visible=b&&h}else this._perimeterLengthLabel.visible=!1}}};k._toPreferredAreaUnit=function(a,b){return a.toUnit(this._preferredAreaUnit(a,b))};k._preferredAreaUnit=
function(a,b){switch(b){case "metric":return w.preferredMetricAreaUnit(a.value,a.unit);case "imperial":return w.preferredImperialAreaUnit(a.value,a.unit);default:return b}};k._preferredLengthUnit=function(a,b){b=this._deriveLengthUnitFromAreaUnit(b);switch(b){case "metric":return w.preferredMetricLengthUnit(a.value,a.unit);case "imperial":return w.preferredImperialLengthUnit(a.value,a.unit);default:return b}};k._deriveLengthUnitFromAreaUnit=function(a){switch(a){case "metric":return"metric";case "imperial":return"imperial";
case "square-inches":return"inches";case "square-feet":return"feet";case "square-yards":return"yards";case "square-miles":return"miles";case "square-us-feet":return"us-feet";case "square-millimeters":return"millimeters";case "square-centimeters":return"centimeters";case "square-decimeters":return"decimeters";case "square-meters":return"meters";case "square-kilometers":return"kilometers";case "acres":return"imperial";case "ares":case "hectares":return"metric"}throw Error("unhandled area unit");};k._formatAreaLabel=
function(a,b,c){return a&&b&&F.formatDecimal(a,b,this._preferredAreaUnit(b,c))};k._formatLengthLabel=function(a,b,c){return a&&b&&F.formatDecimal(a,b,this._preferredLengthUnit(b,c))};k._updateMessageBundle=function(){this.loadingMessages=!0;V.fetchMessageBundle("esri/core/t9n/Units").then(a=>{this.messages=a;this.view&&this._update()}).finally(()=>{this.loadingMessages=!1})};k._updateVisualElementsOpacity=function(){const a=this.layerView.fullOpacity,{pathLineColor:b,intersectingLineColor:c,perimeterLineColor:d,
projectionLineColor:e,areaColor1:h,areaColor2:g}=this._params;this._path.color=u.applyOpacity(t,b,a);u.applyOpacity(t,c,a);this._intersectedPath.color=t;this._intersectedPerimeter.color=t;this._perimeter.color=u.applyOpacity(t,d,a);this._projectionLines.color=u.applyOpacity(t,e,a);this._measurementArea.color1=u.applyOpacity(t,h,a);this._measurementArea.color2=u.applyOpacity(t,g,a)};C._createClass(B,[{key:"visible",get:function(){return this.layerView.visible&&!this.layerView.suspended}},{key:"testData",
get:function(){return{labels:{area:this._areaLabel,pathLength:this._pathLengthLabel,cursorSegmentLength:this._cursorSegmentLengthLabel,perimeterLength:this._perimeterLengthLabel}}}}]);return B}(M);m.__decorate([n.property()],l.AreaMeasurementView.prototype,"view",void 0);m.__decorate([n.property()],l.AreaMeasurementView.prototype,"messages",void 0);m.__decorate([n.property()],l.AreaMeasurementView.prototype,"analysis",void 0);m.__decorate([n.property()],l.AreaMeasurementView.prototype,"viewData",
void 0);m.__decorate([n.property()],l.AreaMeasurementView.prototype,"layerView",void 0);m.__decorate([n.property({readOnly:!0})],l.AreaMeasurementView.prototype,"areaLabel",void 0);m.__decorate([n.property({readOnly:!0})],l.AreaMeasurementView.prototype,"perimeterLengthLabel",void 0);m.__decorate([n.property()],l.AreaMeasurementView.prototype,"mode",void 0);m.__decorate([n.property()],l.AreaMeasurementView.prototype,"loadingMessages",void 0);m.__decorate([n.property({readOnly:!0})],l.AreaMeasurementView.prototype,
"visible",null);m.__decorate([n.property()],l.AreaMeasurementView.prototype,"geodesicMeasurementDistanceThreshold",void 0);l.AreaMeasurementView=m.__decorate([O.subclass("esri.views.3d.layers.analysis.AreaMeasurement.AreaMeasurementView")],l.AreaMeasurementView);const W={laserLineGlowColor:[1,.5,0],laserLineGlowWidth:8,laserLineGlowFalloff:8,laserLineInnerColor:[1,1,1],laserLineInnerWidth:1,laserLineGlobalAlpha:.75,laserLineEnabled:!0,handleColor:[1,.5,0],handleOpacity:.5,handleRadius:5,handleRadiusHovered:10,
handleRadiusMouse:10,handleRadiusTouch:25,pathLineColor:[1,.5,0,1],pathLineWidth:3,intersectingLineColor:[1,.2,0,1],perimeterLineColor:[1,.5,0,1],perimeterLineWidth:2,projectionLineColor:[1,.5,0,1],projectionLineWidth:2,projectionLineStippleSize:5,areaColor1:[1,.5,0,.5],areaColor2:[1,1,1,.5],fillColor:[1,.5,0,.5],lineSubdivisions:64,labelDistance:25},X={validMeasurement:!1,path:null,pathVersion:-1,cursorPoint:null,measurementData:null,mode:null,positionsGeographic:null,positionsRenderCoords:null,
positionsProjected:null,positionsFittedRenderCoords:null,intersectingSegments:null,triangleIndices:null,fittingMode:null,areaCentroid:null,pathLengthLabelSegmentIndex:null,perimeterLengthLabelSegmentIndex:null,checkerSize:null,geodesicCursorSegmentLength:null,cursorSegmentLength:null},Y=new y.EuclideanSegment(v.create(),v.create()),t=Q.create();Object.defineProperty(l,"__esModule",{value:!0})});