// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/Handles ../../core/Logger ../../core/maybe ../../core/reactiveUtils ../../core/unitUtils ../../core/accessorSupport/decorators/property ../../core/has ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ../../properties/defaultUnit ../../views/3d/interactive/measurementTools/areaMeasurement3D/AreaMeasurement3DTool ../support/InteractiveToolViewModel".split(" "),function(l,f,r,c,g,t,m,
h,z,A,u,v,w,x){const y=c.getLogger("esri.widgets.AreaMeasurement3D.AreaMeasurement3DViewModel");c=function(p){function k(a){a=p.call(this,a)||this;a.logger=y;a.supportedViewType="3d";a.unsupportedErrorMessage="AreaMeasurement3DViewModel is only supported in 3D views.";a._handles=new r;a._userUnitOptions=null;a._userUnit=null;a.ready=!1;return a}l._inheritsLoose(k,p);var d=k.prototype;d.initialize=function(){g.isSome(this.tool)&&(this.tool.unit=this.unit);this._handles.add([t.react(()=>({view:this.view,
ready:g.isSome(this.view)&&this.view.ready}),({view:a})=>{this._disconnectFromView();this._connectToView(a)},{sync:!0})]);this._connectToView(this.view)};d.destroy=function(){this._handles=g.destroyMaybe(this._handles)};d.start=function(){return this.createTool()};d.clear=function(){this.removeTool()};d.createToolParams=function(){return{toolConstructor:w,constructorArguments:()=>({unit:this.unit})}};d._findSelectableUnit=function(a,b){const e=this.unitOptions;return-1!==e.indexOf(a)?a:b?this._findSelectableUnit(b):
e[0]};d._filteredOrAllUnits=function(a){if(!a)return m.measurementAreaUnits.slice();a=a.filter(b=>-1!==m.measurementAreaUnits.indexOf(b));return 0===a.length?m.measurementAreaUnits.slice():a};d._connectToView=function(){var a=l._asyncToGenerator(function*(b){g.isSome(b)&&b.ready&&"3d"===b.type&&(this.ready=!0)});return function(b){return a.apply(this,arguments)}}();d._disconnectFromView=function(){this.ready=!1};l._createClass(k,[{key:"state",get:function(){return this.disabled?"disabled":g.isNone(this.tool)?
"ready":this.tool.state}},{key:"measurement",get:function(){if(g.isNone(this.tool)||this.disabled||this.tool.destroyed||"pending"===this.tool.toolState)return null;var a=this.tool.measurementView;if("pending"===a.state||"destroyed"===a.state)return null;a=a.analysisView;var b=a.viewData,e=b.measurementData;const n=b.validMeasurement;b=1===b.mode;const q=(e=0===(b?e.intersectingSegments:e.geodesicIntersectingSegments).size)?n?"available":"unavailable":"invalid";return{mode:b?"euclidean":"geodesic",
area:{text:e&&n?a.areaLabel:null,state:q},perimeterLength:{text:e&&n?a.perimeterLengthLabel:null,state:q}}}},{key:"unitOptions",get:function(){return this._filteredOrAllUnits(this._userUnitOptions)},set:function(a){this._userUnitOptions=a;this._set("unitOptions",this._filteredOrAllUnits(this._userUnitOptions))}},{key:"unit",get:function(){return this._userUnit?this._userUnit=this._findSelectableUnit(this._userUnit,this.defaultUnit):this._findSelectableUnit(this.defaultUnit)},set:function(a){this._userUnit=
a?this._findSelectableUnit(a,this._userUnit):null;g.isSome(this.tool)&&(this.tool.unit=this._userUnit);this.notifyChange("unit")}}]);return k}(x.InteractiveToolViewModel);f.__decorate([h.property()],c.prototype,"ready",void 0);f.__decorate([h.property({readOnly:!0})],c.prototype,"state",null);f.__decorate([h.property({readOnly:!0})],c.prototype,"measurement",null);f.__decorate([h.property(v.defaultUnitPropertyMetadata)],c.prototype,"defaultUnit",void 0);f.__decorate([h.property()],c.prototype,"unitOptions",
null);f.__decorate([h.property()],c.prototype,"unit",null);return c=f.__decorate([u.subclass("esri.widgets.AreaMeasurement3D.AreaMeasurement3DViewModel")],c)});