// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
require({cache:{"esri/renderers/support/heatmapUtils":function(){define(["exports","../../core/global","../../core/mathUtils"],function(k,r,l){function t(a,b,c,d,f){a=new Uint32Array(a*a);b="buffer"in b?b:new Float64Array(b);c="buffer"in c?new Uint32Array(c.buffer):new Uint32Array((new Uint8Array(c)).buffer);f=c.length/(f-d);for(let g=0;g<b.length;g++)a[g]=c[l.clamp(Math.floor((b[g]-d)*f),0,c.length-1)];return a.buffer}function v(a){const b=Math.round(3*a),c=2*a*a,d=new Float64Array(2*b+1);for(let f=
0;f<=d.length;f++)d[f]=Math.exp(-((f-b)**2)/c)/Math.sqrt(2*Math.PI)*(a/2);return d}function E(a,b){return"function"===typeof a?a:a?"string"===typeof b?c=>-1*+c[a]:c=>+c[a]+b:()=>1}function B(a,b){return null!=a?"string"===typeof b?c=>-1*+c.readAttribute(a):c=>+c.readAttribute(a)+b:c=>1}const C=(()=>{if(!("document"in r))return()=>null;const a=document.createElement("canvas"),b=a.getContext("2d");a.height=512;a.width=1;return c=>{b.clearRect(0,0,1,a.height);const d=b.createLinearGradient(0,0,0,a.height);
for(const {ratio:f,color:g}of c.colorStops)d.addColorStop(Math.max(f,.001),`rgba(${g[0]}, ${g[1]}, ${g[2]}, ${g[3]})`);b.fillStyle=d;b.fillRect(0,0,1,a.height);return b.getImageData(0,0,1,a.height).data}})();k.calculateHeatmapIntensityInfo=function(a,b,c,d){const {blurRadius:f,fieldOffset:g,field:e}=b;b=new Float64Array(c*d);const h=v(f),m=Math.round(3*f);let p=Number.NEGATIVE_INFINITY;const n=E(e,g);for(const {geometry:u,attributes:q}of a){a=u.x-m;const w=u.y-m,H=Math.max(0,a);var x=Math.max(0,w);
const F=Math.min(d,u.y+m),G=Math.min(c,u.x+m),I=+n(q);for(let y=x;y<F;y++){const z=h[y-w];for(let A=H;A<G;A++)x=b[y*c+A]+=z*h[A-a]*I,x>p&&(p=x)}}return{matrix:b.buffer,max:p}};k.calculateHeatmapIntensityInfoReaders=function(a,b,c,d){const {blurRadius:f,fieldOffset:g,field:e}=b;b=new Float64Array(c*d);const h=v(f),m=Math.round(3*f);let p=Number.NEGATIVE_INFINITY;const n=B(e,g),x=new Set;for(const H of a)for(a=H.getCursor();a.next();){var u=a.getObjectId();if(x.has(u))continue;x.add(u);var q=a.readLegacyPointGeometry();
if(-128>q.x||q.x>=c+128||-128>q.y||q.y>d+128)continue;u=+n(a);const F=Math.round(q.x)-m,G=Math.round(q.y)-m,I=Math.max(0,F);var w=Math.max(0,G);const y=Math.min(d,Math.round(q.y)+m);q=Math.min(c,Math.round(q.x)+m);for(let z=w;z<y;z++){const A=h[z-G];for(let D=I;D<q;D++)w=b[z*c+D]+=A*h[D-F]*u,w>p&&(p=w)}}return{matrix:b.buffer,max:p}};k.createHeatmapImageData=t;k.createKernel=v;k.createValueFunction=E;k.createValueFunctionCursor=B;k.drawHeatmap=function(a,b,c,d,f,g){a.canvas.width=a.canvas.height=
b;a.clearRect(0,0,b,b);const e=a.getImageData(0,0,b,b);c&&d&&e.data.set(new Uint8ClampedArray(t(b,c,d,f,g)));a.putImageData(e,0,0)};k.generateGradient=C;Object.defineProperty(k,"__esModule",{value:!0})})},"esri/views/2d/layers/features/tileRenderers/BaseTileRenderer":function(){define("../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/HandleOwner ../../../../../core/accessorSupport/decorators/property ../../../../../core/has ../../../../../core/accessorSupport/ensureType ../../../../../core/Logger ../../../../../core/accessorSupport/decorators/subclass".split(" "),
function(k,r,l,t,v,E,B,C){l=function(a){function b(d){d=a.call(this,d)||this;d.tiles=new Map;return d}k._inheritsLoose(b,a);var c=b.prototype;c.destroy=function(){this.tiles.clear();this.layer=this.layerView=this.tileInfoView=this.tiles=null};c.acquireTile=function(d){const f=this.createTile(d);f.once("isReady",()=>this.notifyChange("updating"));this.tiles.set(d.id,f);return f};c.forceAttributeTextureUpload=function(){};c.forEachTile=function(d){this.tiles.forEach(d)};c.releaseTile=function(d){this.tiles.delete(d.key.id);
this.disposeTile(d)};c.isUpdating=function(){let d=!0;this.tiles.forEach(f=>{d=d&&f.isReady});return!d};c.setHighlight=function(){};c.invalidateLabels=function(){};c.requestUpdate=function(){this.layerView.requestUpdate()};k._createClass(b,[{key:"updating",get:function(){return this.isUpdating()}}]);return b}(l.HandleOwner);r.__decorate([t.property()],l.prototype,"layer",void 0);r.__decorate([t.property()],l.prototype,"layerView",void 0);r.__decorate([t.property()],l.prototype,"tileInfoView",void 0);
r.__decorate([t.property()],l.prototype,"updating",null);return l=r.__decorate([C.subclass("esri.views.2d.layers.features.tileRenderers.BaseTileRenderer")],l)})},"esri/views/2d/layers/features/tileRenderers/support/HeatmapSource":function(){define(["exports","../../../../../../renderers/support/heatmapUtils"],function(k,r){let l=function(){function t(){this.gradient=null;this.width=this.height=512}t.prototype.render=function(v){r.drawHeatmap(v,512,this.intensities,this.gradient,this.minPixelIntensity,
this.maxPixelIntensity)};return t}();k.HeatmapSource=l;Object.defineProperty(k,"__esModule",{value:!0})})},"*noref":1}});
define("../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/accessorSupport/decorators/property ../../../../../core/has ../../../../../core/accessorSupport/ensureType ../../../../../core/Logger ../../../../../core/accessorSupport/decorators/subclass ../../../../../renderers/support/heatmapUtils ../../../engine/BitmapTileContainer ./BaseTileRenderer ./support/HeatmapSource".split(" "),function(k,r,l,t,v,E,B,C,a,b,c){l=function(d){function f(e){var h=
d.call(this,e)||this;h._intensityInfo={minPixelIntensity:0,maxPixelIntensity:0};h.featuresView={attributeView:{initialize:()=>{},requestUpdate:()=>{}},requestRender:()=>{}};h._container=new a.BitmapTileContainer(e.tileInfoView);return h}k._inheritsLoose(f,d);var g=f.prototype;g.createTile=function(e){const h=this._container.createTile(e);this.tileInfoView.getTileCoords(h.bitmap,e);h.bitmap.resolution=this.tileInfoView.getTileResolution(e);return h};g.onConfigUpdate=function(){const e=this.layer.renderer;
if("heatmap"===e.type){const {minPixelIntensity:h,maxPixelIntensity:m}=e;this._intensityInfo.minPixelIntensity=h;this._intensityInfo.maxPixelIntensity=m;this._gradient=C.generateGradient(e.toJSON());this.tiles.forEach(p=>{const n=p.bitmap.source;n&&(n.minPixelIntensity=h,n.maxPixelIntensity=m,n.gradient=this._gradient,p.bitmap.invalidateTexture())})}};g.hitTest=function(){return Promise.resolve([])};g.install=function(e){e.addChild(this._container)};g.uninstall=function(e){this._container.removeAllChildren();
e.removeChild(this._container)};g.disposeTile=function(e){this._container.removeChild(e);e.destroy()};g.supportsRenderer=function(e){return e&&"heatmap"===e.type};g.onTileData=function(e){const h=this.tiles.get(e.tileKey);if(h){e=e.intensityInfo;var {minPixelIntensity:m,maxPixelIntensity:p}=this._intensityInfo,n=h.bitmap.source||new c.HeatmapSource;n.intensities=e&&e.matrix||null;n.minPixelIntensity=m;n.maxPixelIntensity=p;n.gradient=this._gradient;h.bitmap.source=n;this._container.addChild(h);this.requestUpdate()}};
g.onTileError=function(e){console.error(e)};g.lockGPUUploads=function(){};g.unlockGPUUploads=function(){};return f}(b);return l=r.__decorate([B.subclass("esri.views.2d.layers.features.tileRenderers.HeatmapTileRenderer")],l)});