// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
require({cache:{"esri/views/2d/engine/webgl/FeatureTile":function(){define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/CircularArray ../../../../core/has ../../../../core/maybe ../../../../chunks/mat2d ../../../../chunks/mat2df32 ../../../../chunks/vec2 ../../../../chunks/vec2f32 ./enums ./Utils ./WGLTile ./collisions/MetricReader ./cpuMapped/Geometry".split(" "),function(w,v,p,u,q,t,h,a,b,f,g,c,n,y){let x=0;u=function(m){function l(d,k,r,z){d=m.call(this,d,k,r)||this;d.instanceId=
x++;d.patchCount=0;d._renderState={current:{geometry:new Map,metrics:null},next:null,swap:!1,swapFrames:0,locked:!1};d._patches=new p(100);d._bufferPatches=new p(100);d._lastCommitTime=0;d._lastMessageWasClear=!1;d.transforms.labelMat2d=h.create();d._store=z;return d}v._inheritsLoose(l,m);var e=l.prototype;e.destroy=function(){m.prototype.destroy.call(this);this._renderState.current.geometry.forEach(d=>d.destroy())};e.getGeometry=function(d){return this._renderState.current.geometry.get(d)};e.setTransform=
function(d,k){m.prototype.setTransform.call(this,d,k);const r=this.transforms.labelMat2d;k=d.getScreenTransform(r,k);const z=b.create();a.transformMat2d(z,[this.x,this.y],k);t.identity(r);t.translate(r,r,z);t.multiply(r,d.viewMat2d,r)};e.patch=function(d,k){this.patchCount++;if(!d.clear||!this._lastMessageWasClear){(this._lastMessageWasClear=d.clear)&&50<=this._patches.size&&this._dropPatches();var r=d.addOrUpdate&&this.key.id!==d.addOrUpdate.tileKeyOrigin;k&&r?this._bufferPatches.enqueue(d):(d.sort=
d.sort&&!k,this._patches.enqueue(d));this.requestRender()}};e.commit=function(d){if(this._lastCommitTime!==d.time){this._lastCommitTime=d.time;for(d=0;4>d;d++)this._updateMesh(),this.isReady&&this._updateBufferMesh();this._renderState.swap&&(this._swapRenderStates(),this.requestRender())}};e.lock=function(){this._renderState.locked=!0};e.unlock=function(){this._renderState.locked=!1;this._flushUpdates();this._swap()};e._swapRenderStates=function(){this._renderState.next&&(this._renderState.locked?
(this._renderState.swap=!0,this.requestRender()):(this._renderState.swap=!0,0===this._renderState.swapFrames?(this._renderState.swapFrames=8,this.requestRender()):1!==this._renderState.swapFrames--?this.requestRender():this._swap()))};e._swap=function(){this._renderState.swap&&(this._renderState.swap=!1,q.isSome(this._renderState.next)&&(this._renderState.current.geometry.forEach(d=>d.destroy()),this._renderState.current=this._renderState.next,this._renderState.next=null))};e._flushUpdates=function(){let d=
this._patches.maxSize;for(;this._patches.size&&d--;)this._updateMesh(),this._swap()};e._updateBufferMesh=function(){var d=this._bufferPatches.peek();if(!q.isSome(d)||!d.clear||null===this._renderState.next)for(;this._bufferPatches.size;)d=this._bufferPatches.dequeue(),q.isSome(d)&&this._patchBuffer(d)};e._updateMesh=function(){var d=this._patches.peek();q.isSome(d)&&d.clear&&null!==this._renderState.next||(d=this._patches.dequeue(),q.isSome(d)&&(!0===d.clear?this.isReady&&(this._renderState.next=
{geometry:new Map,metrics:null}):(this.requestRender(),this._patch(d),d.end&&(this.ready(),this._swapRenderStates()))))};e._patch=function(d){g.forEachGeometryType(k=>{this._remove(k,d.remove);this._insert(k,d,!1)})};e._patchBuffer=function(d){g.forEachGeometryType(k=>{this._insert(k,d,!0)})};e._insert=function(d,k,r){try{var z;const A=q.unwrapOr(this._renderState.next,this._renderState.current),B=null==(z=k.addOrUpdate)?void 0:z.data[d],C=A.geometry;q.isNone(B)||(C.has(d)||C.set(d,new y.Geometry(d,
this.stage)),C.get(d).insert(B,k.sort,r),d===f.WGLGeometryType.LABEL&&this._insertLabelMetrics(k.type,B.metrics,k.clear))}catch(A){}};e._insertLabelMetrics=function(d,k,r){r=q.unwrapOr(this._renderState.next,this._renderState.current);if(!q.isNone(k))if(k=n.MetricReader.from(k),q.isNone(r.metrics))r.metrics=k;else{if("update"===d)for(d=k.getCursor();d.next();)r.metrics.delete(d.id);r.metrics.link(k)}};e._remove=function(d,k){d=q.unwrapOr(this._renderState.next,this._renderState.current).geometry.get(d);
k&&k.length&&d&&(d.remove(k),this._removeLabelMetrics(k))};e._removeLabelMetrics=function(d){const {metrics:k}=q.unwrapOr(this._renderState.next,this._renderState.current);if(!q.isNone(k)&&d.length)for(const r of d)for(;k.delete(r););};e._dropPatches=function(){const d=[];let k=!1;for(;this._patches.size;){const r=this._patches.dequeue();if(q.isNone(r))break;if(r.clear){if(k)break;k=!0}d.push(r)}this._patches.clear();d.forEach(r=>this._patches.enqueue(r))};v._createClass(l,[{key:"labelMetrics",get:function(){return this._renderState.current.metrics}},
{key:"hasData",get:function(){return!!this._renderState.current.geometry.size}}]);return l}(c.WGLTile);w.FeatureTile=u;Object.defineProperty(w,"__esModule",{value:!0})})},"esri/views/2d/engine/webgl/collisions/MetricReader":function(){define(["exports","../../../../../chunks/_rollupPluginBabelHelpers","../../../../../core/maybe"],function(w,v,p){let u=function(){function t(a){this._cursor=this._head=a}t.from=function(a){a=q.from(new Float32Array(a));return new t(a)};var h=t.prototype;h.computedMinZoom=
function(){return this._cursor.computedMinZoom()};h.setComputedMinZoom=function(a){return this._cursor.setComputedMinZoom(a)};h.boundsComputedAnchorX=function(a){return this._cursor.boundsComputedAnchorX(a)};h.boundsComputedAnchorY=function(a){return this._cursor.boundsComputedAnchorY(a)};h.setBoundsComputedAnchorX=function(a,b){return this._cursor.setBoundsComputedAnchorX(a,b)};h.setBoundsComputedAnchorY=function(a,b){return this._cursor.setBoundsComputedAnchorY(a,b)};h.boundsX=function(a){return this._cursor.boundsX(a)};
h.boundsY=function(a){return this._cursor.boundsY(a)};h.boundsWidth=function(a){return this._cursor.boundsWidth(a)};h.boundsHeight=function(a){return this._cursor.boundsHeight(a)};h.link=function(a){if(p.isSome(a._head))return this._cursor.link(a._head)};h.getCursor=function(){return this.copy()};h.copy=function(){var a;const b=new t(null==(a=this._head)?void 0:a.copy());if(!b._head)return b;a=b._head;let f=b._head._link;for(;f;)a._link=f.copy(),a=f,f=a._link;return b};h.peekId=function(){var a;return null!=
(a=this._cursor.peekId())?a:this._cursor._link.peekId()};h.nextId=function(){const a=this.id;for(;a===this.id;)if(!this.next())return!1;return!0};h.save=function(){this._savedCursor=this._cursor;this._savedOffset=this._cursor._offset};h.restore=function(){this._cursor=this._savedCursor;this._cursor._offset=this._savedOffset};h.next=function(){if(!this._cursor)return!1;if(!this._cursor.next()){if(!this._cursor._link)return!1;this._cursor=this._cursor._link;this._cursor._offset=0}return!0};h.lookup=
function(a){for(this._cursor=this._head;this._cursor&&!this._cursor.lookup(a);){if(!this._cursor._link)return!1;this._cursor=this._cursor._link}return!!this._cursor};h.delete=function(a){let b=this._head,f=null;for(;b;){if(b.delete(a))return b.isEmpty()&&p.isSome(f)&&(f._link=b._link),!0;f=b;b=b._link}return!1};v._createClass(t,[{key:"id",get:function(){return this._cursor.id}},{key:"baseZoom",get:function(){return this._cursor.baseZoom}},{key:"anchorX",get:function(){return this._cursor.anchorX}},
{key:"anchorY",get:function(){return this._cursor.anchorY}},{key:"directionX",get:function(){return this._cursor.directionX}},{key:"directionY",get:function(){return this._cursor.directionY}},{key:"size",get:function(){return this._cursor.size}},{key:"materialKey",get:function(){return this._cursor.materialKey}},{key:"boundsCount",get:function(){return this._cursor.boundsCount}}]);return t}(),q=function(){function t(a){this._offset=-1;this._link=null;this._deletedCount=this._count=0;this._offsets=
{instance:null};this._buffer=a}t.from=function(a){return new t(new Float32Array(a))};var h=t.prototype;h.isEmpty=function(){return this._deletedCount===this.count};h.computedMinZoom=function(){return this._buffer[this._offset+8]};h.setComputedMinZoom=function(a){this._buffer[this._offset+8]=a};h.boundsComputedAnchorX=function(a){return this._buffer[this._offset+10+6*a+0]};h.boundsComputedAnchorY=function(a){return this._buffer[this._offset+10+6*a+1]};h.setBoundsComputedAnchorX=function(a,b){this._buffer[this._offset+
10+6*a+0]=b};h.setBoundsComputedAnchorY=function(a,b){this._buffer[this._offset+10+6*a+1]=b};h.boundsX=function(a){return this._buffer[this._offset+10+6*a+2]};h.boundsY=function(a){return this._buffer[this._offset+10+6*a+3]};h.boundsWidth=function(a){return this._buffer[this._offset+10+6*a+4]};h.boundsHeight=function(a){return this._buffer[this._offset+10+6*a+5]};h.link=function(a){let b=this;for(;b._link;)b=b._link;b._link=a};h.getCursor=function(){return this.copy()};h.copy=function(){const a=new t(this._buffer);
a._link=this._link;a._offset=this._offset;a._deletedCount=this._deletedCount;a._offsets=this._offsets;a._count=this._count;return a};h.peekId=function(){const a=this._offset+10+6*this.boundsCount+0;return a>=this._buffer.length?0:this._buffer[a]};h.next=function(){let a=0;for(;this._offset<this._buffer.length&&100>a++&&(this._offset=-1===this._offset?0:this._offset+(10+6*this.boundsCount),4294967296===this.id););return 4294967296!==this.id&&this._offset<this._buffer.length};h.delete=function(a){const b=
this._offset,f=this.lookup(a);if(f)for(this.id=4294967295,++this._deletedCount;this.next()&&this.id===a;)this.id=4294967295,++this._deletedCount;this._offset=b;return f};h.lookup=function(a){const b=this._offset;if(p.isNone(this._offsets.instance)){this._offsets.instance=new Map;const f=this.copy();f._offset=-1;let g=0;for(;f.next();)f.id!==g&&(this._offsets.instance.set(f.id,f._offset),g=f.id)}if(!this._offsets.instance.has(a))return!1;this._offset=this._offsets.instance.get(a);return 4294967296===
this.id?(this._offset=b,!1):!0};h._computeCount=function(){const a=this._offset;let b=0;for(this._offset=-1;this.next();)b++;this._offset=a;return b};v._createClass(t,[{key:"count",get:function(){this._count||(this._count=this._computeCount());return this._count}},{key:"id",get:function(){return this._buffer[this._offset+0]},set:function(a){this._buffer[this._offset+0]=a}},{key:"baseZoom",get:function(){return this._buffer[this._offset+1]}},{key:"anchorX",get:function(){return this._buffer[this._offset+
2]}},{key:"anchorY",get:function(){return this._buffer[this._offset+3]}},{key:"directionX",get:function(){return this._buffer[this._offset+4]}},{key:"directionY",get:function(){return this._buffer[this._offset+5]}},{key:"size",get:function(){return this._buffer[this._offset+6]}},{key:"materialKey",get:function(){return this._buffer[this._offset+7]}},{key:"boundsCount",get:function(){return this._buffer[this._offset+9]}}]);return t}();w.MetricReader=u;w.MetricReaderNode=q;Object.defineProperty(w,"__esModule",
{value:!0})})},"esri/views/2d/engine/webgl/cpuMapped/Geometry":function(){define("exports ../../../../../core/maybe ../../../../webgl/BufferObject ../../../../webgl/FramebufferObject ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../core/has ../../../../webgl/checkWebGLError ../../../../webgl/enums ../../../../../chunks/builtins ../../../../webgl/renderState ../../../../webgl/Texture ../../../../webgl/VertexArrayObject ../FeatureDisplayList ./Buffer ./DisplayRecordReader".split(" "),
function(w,v,p,u,q,t,h,a,b,f,g,c,n,y,x){p=function(){function m(e,d){this._indicesInvalid=!1;this.geometryType=e}var l=m.prototype;l.destroy=function(){this._vao&&(this._vao.dispose(),this._vao=null)};l.insert=function(e,d,k){if(e.records.byteLength)if(k=e.stride,this._vertexBuffer&&this._indexBuffer){var r=e.vertices.byteLength/k;this._indexBuffer.ensure(4*e.indices.byteLength);this._vertexBuffer.ensure(r);const {vertices:z,indices:A}=e;e=x.DisplayRecordReader.from(e.records);const B=this._vertexBuffer.insert(z,
0,z.byteLength/k,0),C=this._indexBuffer.insert(A,0,A.byteLength/4,B);e.forEach(D=>{D.indexFrom+=C;D.vertexFrom+=B});v.unwrapOrThrow(this._records,"Expected records to be defined").link(e);if(d)this._indicesInvalid=!0;else if(this._displayList)for(d=e.getCursor();d.next();)this._displayList.addRecord(d)}else{r=4*e.indices.byteLength;const z=e.vertices.byteLength/k,A=k/Uint32Array.BYTES_PER_ELEMENT;this._records=x.DisplayRecordReader.from(e.records);this._indexBuffer=new y.Buffer("index",r,1);this._vertexBuffer=
new y.Buffer("vertex",z,A);this._indexBuffer.insert(e.indices,0,e.indices.byteLength/4,0);this._vertexBuffer.insert(e.vertices,0,e.vertices.byteLength/k,0);d&&(this._indicesInvalid=!0)}};l.remove=function(e){if(!v.isNone(this._records))for(const d of e){e=this._records.getCursor();if(!e.lookup(d))continue;const k=e.indexFrom,r=e.vertexFrom;let z=e.indexCount,A=e.vertexCount;for(;e.next()&&e.id===d;)z+=e.indexCount,A+=e.vertexCount;this._indexBuffer.free(k,z);this._vertexBuffer.free(r,A,!0);this._records.delete(d)}};
l.draw=function(e,d,k,r,z){if(this._vertexBuffer&&this._indexBuffer&&!v.isNone(this._records)){if(v.isNone(this._vertexBuffer.gpu)||v.isNone(this._indexBuffer.gpu))this._vao&&(this._vao.dispose(),this._vao=null),this._vertexBuffer.gpu=null,this._indexBuffer.gpu=null;this._vertexBuffer.upload(e);this._indexBuffer.upload(e);if(!this._vao){const A=this._vertexBuffer.gpu,B=this._indexBuffer.gpu;if(!B||!A)return;this._vao=new c(e,k,d,{geometry:A},B)}d=r*Uint32Array.BYTES_PER_ELEMENT;e.bindVAO(this._vao);
e.drawElements(4,z,5125,d)}};l.forEachCommand=function(e){if(!v.isNone(this._records)){this._sortIndices(this._records);if(!this._displayList){const d=this._cursorIndexOrder;this._displayList=n.FeatureDisplayList.from(this,this.geometryType,this._records.getCursor(),d)}this._displayList.forEach(e)}};l._sortIndices=function(e){if(this._indicesInvalid){this._indicesInvalid=!1;for(var d=0,k=e.getCursor(),r=this._indexBuffer.getBuffer(),z=[],A=[],B=[];k.next();)A.push(k.index),B.push(k.sortKey),z.push(k.id);
A.sort((C,D)=>{const E=B[D],F=B[C];return F===E?z[D]-z[C]:E-F});e=e.getCursor();for(const C of A){if(!e.seekIndex(C))throw Error("Expected to find index");const {indexFrom:D,indexCount:E}=e;e.indexFrom=d;for(k=0;k<E;k++)this._indexBuffer.set(d++,r[D+k])}this._cursorIndexOrder=A;this._displayList=null}};return m}();w.Geometry=p;Object.defineProperty(w,"__esModule",{value:!0})})},"esri/views/2d/engine/webgl/FeatureDisplayList":function(){define(["exports","../../../../chunks/_rollupPluginBabelHelpers",
"../../../../core/maybe","./cpuMapped/FreeList"],function(w,v,p,u){let q=function(){function h(b,f,g,c,n){this.target=b;this.geometryType=f;this.materialKey=g;this.indexFrom=c;this.indexCount=n}var a=h.prototype;a.extend=function(b){this.indexCount+=b};a.draw=function(b,f,g){this.target.draw(b,f,g,this.indexFrom,this.indexCount)};v._createClass(h,[{key:"indexEnd",get:function(){return this.indexFrom+this.indexCount}}]);return h}(),t=function(){function h(b,f){this.geometryType=0;this._target=b;this.geometryType=
f}h.from=function(b,f,g,c){b=new h(b,f);if(p.isSome(c))for(const n of c)g.seekIndex(n),b.addRecord(g);else for(;g.next();)b.addRecord(g);return b};var a=h.prototype;a.addRecord=function(b){var f=this._target,g=this.geometryType,c=b.materialKey;const n=b.indexFrom;b=b.indexCount;if(p.isNone(this._head))c=new q(f,g,c,n,b),this._head=new u.List(c);else{f=null;for(g=this._head;g;){if(n<g.data.indexFrom)return this._insert(c,n,b,f,g);f=g;g=g.next}this._insert(c,n,b,f,null)}};a.forEach=function(b){p.isSome(this._head)&&
this._head.forEach(b)};a.infos=function*(){if(p.isSome(this._head))for(const b of this._head.values())yield b};a._insert=function(b,f,g,c,n){if(p.isNone(c)&&p.isNone(n)){const y=new q(this._target,this.geometryType,b,f,g);this._head=new u.List(y)}if(p.isNone(c)&&p.isSome(n))return this._insertAtHead(b,f,g,n);if(p.isSome(c)&&p.isNone(n))return this._insertAtEnd(b,f,g,c);if(p.isSome(c)&&p.isSome(n))return this._insertAtMiddle(b,f,g,c,n)};a._insertAtHead=function(b,f,g,c){b===c.data.materialKey&&f+g===
c.data.indexFrom?(c.data.indexFrom=f,c.data.indexCount+=g):(b=new q(this._target,this.geometryType,b,f,g),this._head=new u.List(b),this._head.next=c)};a._insertAtEnd=function(b,f,g,c){c.data.materialKey===b&&c.data.indexEnd===f?c.data.indexCount+=g:(b=new q(this._target,this.geometryType,b,f,g),b=new u.List(b),c.next=b)};a._insertAtMiddle=function(b,f,g,c,n){c.data.materialKey===b&&c.data.indexEnd===f?(c.data.indexCount+=g,c.data.materialKey===n.data.materialKey&&c.data.indexEnd===n.data.indexFrom&&
(c.data.indexCount+=n.data.indexCount,c.next=n.next)):b===n.data.materialKey&&f+g===n.data.indexFrom?(n.data.indexFrom=f,n.data.indexCount+=g):(b=new q(this._target,this.geometryType,b,f,g),b=new u.List(b),c.next=b,b.next=n)};return h}();w.FeatureDisplayList=t;w.FeatureDisplayListInfo=q;Object.defineProperty(w,"__esModule",{value:!0})})},"esri/views/2d/engine/webgl/cpuMapped/FreeList":function(){define(["exports","../../../../../chunks/_rollupPluginBabelHelpers","../../../../../core/maybe"],function(w,
v,p){let u=function(){function t(a){if(Array.isArray(a)){this.data=a[0];var b=this;for(let f=1;f<a.length;f++)b.next=new t([a[f]]),b=b.next}else this.data=a}var h=t.prototype;h.values=function*(){let a=this;for(;a;)yield a.data,a=a.next};h.forEach=function(a){let b=this;for(;b;)a(b.data),b=b.next};h.find=function(a){var b;return a(this.data)?this:null==(b=this.next)?void 0:b.find(a)};h.max=function(a,b=this){b=a(this.data)>a(b.data)?this:b;return this.next?this.next.max(a,b):b};h.remove=function(a,
b=null){return this===a?b?(b.next=this.next,b):this.next:this.next.remove(a,this)};v._createClass(t,[{key:"last",get:function(){return this.next?this.next.last:this}}]);return t}(),q=function(){function t(a){this._head=null;p.isNone(a)||(this._head=new u(a))}var h=t.prototype;h.maxAvailableSpace=function(){if(p.isNone(this._head))return 0;const a=this._head.max(b=>b.end-b.start);return a.data.end-a.data.start};h.firstFit=function(a){if(p.isNone(this._head))return null;var b=null;let f=this._head;
for(;f;){const g=f.data.end-f.data.start;if(g===a)return b?b.next=f.next:this._head=f.next,f.data.start;if(g>a)return b=f.data.start,f.data.start+=a,b;b=f;f=f.next}return null};h.free=function(a,b){const f=a+b;if(p.isNone(this._head))this._head=new u({start:a,end:f});else if(f<=this._head.data.start)if(f===this._head.data.start)this._head.data.start-=b;else{var g=new u({start:a,end:f});g.next=this._head;this._head=g}else{g=this._head;for(var c=g.next;c;){if(c.data.start>=f){if(g.data.end===a){g.data.end+=
b;return}if(c.data.start===f){c.data.start-=b;return}a=new u({start:a,end:f});a.next=g.next;g.next=a;return}g=c;c=c.next}a===g.data.end?g.data.end+=b:(a=new u({start:a,end:f}),g.next=a)}};v._createClass(t,[{key:"head",get:function(){return this._head}}]);return t}();w.FreeList=q;w.List=u;Object.defineProperty(w,"__esModule",{value:!0})})},"esri/views/2d/engine/webgl/cpuMapped/Buffer":function(){define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../core/maybe ../../../../webgl/BufferObject ../../../../webgl/FramebufferObject ../../../../../core/has ../../../../webgl/checkWebGLError ../../../../webgl/enums ../../../../../chunks/builtins ../../../../webgl/renderState ../../../../webgl/Texture ../../../../webgl/VertexArrayObject ./FreeList".split(" "),
function(w,v,p,u,q,t,h,a,b,f,g,c,n){q=function(){function y(m,l,e){l=new Uint32Array(l*e);this.strideInt=e;this.bufferType=m;this.dirty={start:Infinity,end:0};this.gpu=null;this._cpu=l;this.clear()}var x=y.prototype;x.destroy=function(){p.andThen(this.gpu,m=>m.dispose())};x.clear=function(){this.dirty.start=Infinity;this.dirty.end=0;this.freeList=new n.FreeList({start:0,end:this._cpu.length/this.strideInt});this.fillPointer=0};x.ensure=function(m){if(!(this.maxAvailableSpace()>=m)&&(m*=this.strideInt,
m>this._cpu.length-this.fillPointer)){p.isSome(this.gpu)&&(this.gpu=null);m=Math.round(1.5*(this._cpu.length+m));const l=new Uint32Array(m),e=this._cpu.length/this.strideInt;this.freeList.free(e,m/this.strideInt-e);l.set(this._cpu);this._cpu=l}};x.set=function(m,l){this._cpu[m]!==l&&(this._cpu[m]=l,this.dirty.start=Math.min(m,this.dirty.start),this.dirty.end=Math.max(m,this.dirty.end))};x.getBuffer=function(){this._cpu2&&this._cpu2.length===this._cpu.length||(this._cpu2=this._cpu.slice());this._cpu2.set(this._cpu);
return this._cpu2};x.maxAvailableSpace=function(){return this.freeList.maxAvailableSpace()};x.insert=function(m,l,e,d){const k=e*this.strideInt;m=new Uint32Array(m,l*this.strideInt*Uint32Array.BYTES_PER_ELEMENT,k);e=p.unwrapOrThrow(this.freeList.firstFit(e),"First fit region must be defined")*this.strideInt;l=e/this.strideInt-l;if(0!==d)for(let r=0;r<m.length;r++)m[r]+=d;this._cpu.set(m,e);this.dirty.start=Math.min(this.dirty.start,e);this.dirty.end=Math.max(this.dirty.end,e+k);this.fillPointer=Math.max(this.fillPointer,
e+k);return l};x.free=function(m,l,e){const d=m*this.strideInt,k=(m+l)*this.strideInt;if(!0===e)for(e=m;e!==m+l;e++)this._cpu[e*this.strideInt]=2147450879;this.dirty.start=Math.min(this.dirty.start,d);this.dirty.end=Math.max(this.dirty.end,k);this.freeList.free(m,l)};x.upload=function(m){this.dirty.end&&(p.isNone(this.gpu)?this.gpu=this._createBuffer(m):this.gpu.setSubData(this._cpu,this.dirty.start,this.dirty.start,this.dirty.end),this.dirty.start=Infinity,this.dirty.end=0)};x._createBuffer=function(m){return"index"===
this.bufferType?u.createIndex(m,35048,this._cpu):u.createVertex(m,35048,this._cpu)};v._createClass(y,[{key:"elementSize",get:function(){return this._cpu.length/this.strideInt}},{key:"bufferSize",get:function(){return this._cpu.length/this.strideInt}}]);return y}();w.Buffer=q;Object.defineProperty(w,"__esModule",{value:!0})})},"esri/views/2d/layers/features/tileRenderers/BaseTileRenderer":function(){define("../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/HandleOwner ../../../../../core/accessorSupport/decorators/property ../../../../../core/has ../../../../../core/accessorSupport/ensureType ../../../../../core/Logger ../../../../../core/accessorSupport/decorators/subclass".split(" "),
function(w,v,p,u,q,t,h,a){p=function(b){function f(c){c=b.call(this,c)||this;c.tiles=new Map;return c}w._inheritsLoose(f,b);var g=f.prototype;g.destroy=function(){this.tiles.clear();this.layer=this.layerView=this.tileInfoView=this.tiles=null};g.acquireTile=function(c){const n=this.createTile(c);n.once("isReady",()=>this.notifyChange("updating"));this.tiles.set(c.id,n);return n};g.forceAttributeTextureUpload=function(){};g.forEachTile=function(c){this.tiles.forEach(c)};g.releaseTile=function(c){this.tiles.delete(c.key.id);
this.disposeTile(c)};g.isUpdating=function(){let c=!0;this.tiles.forEach(n=>{c=c&&n.isReady});return!c};g.setHighlight=function(){};g.invalidateLabels=function(){};g.requestUpdate=function(){this.layerView.requestUpdate()};w._createClass(f,[{key:"updating",get:function(){return this.isUpdating()}}]);return f}(p.HandleOwner);v.__decorate([u.property()],p.prototype,"layer",void 0);v.__decorate([u.property()],p.prototype,"layerView",void 0);v.__decorate([u.property()],p.prototype,"tileInfoView",void 0);
v.__decorate([u.property()],p.prototype,"updating",null);return p=v.__decorate([a.subclass("esri.views.2d.layers.features.tileRenderers.BaseTileRenderer")],p)})},"esri/views/2d/layers/features/tileRenderers/support/WGLFeatureView":function(){define("exports ../../../../../../chunks/_rollupPluginBabelHelpers ../../../../../../core/has ../../../../../../core/promiseUtils ../../../../engine/brushes ../../../../engine/FeatureContainer ../../../../engine/webgl/enums".split(" "),function(w,v,p,u,q,t,h){const a=
p("featurelayer-order-by-server-enabled");p=function(b){function f(c,n,y,x){c=b.call(this,c)||this;c._pointToCallbacks=new Map;c._layer=y;c._layerView=n;c._onUpdate=x;return c}v._inheritsLoose(f,b);var g=f.prototype;g.renderChildren=function(c){this.attributeView.update();this.hasAnimation&&c.painter.effects.integrate.draw(c,c.attributeView);b.prototype.renderChildren.call(this,c)};g.isUpdating=function(){return this.attributeView.isUpdating()};g.hitTest=function(c,n){c=[c,n];n=u.createResolver();
this._pointToCallbacks.set(c,n);this.requestRender();return n.promise};g.onTileData=function(c,n){const y=a&&"orderBy"in this._layer&&this._layer.orderBy,x=(null==y?void 0:y.length)&&!y[0].valueExpression&&y[0].field;c.patch(n,y&&this._layerView.orderByFields===x);this.contains(c)||this.addChild(c);this.requestRender()};g.onTileError=function(c){this.contains(c)||this.addChild(c)};g.doRender=function(c){const {minScale:n,maxScale:y}=this._layer,x=c.state.scale;x<=(n||Infinity)&&x>=y&&b.prototype.doRender.call(this,
c)};g.onAttributeStoreUpdate=function(){this.hasLabels&&this._layerView.view.labelManager.requestUpdate();this._onUpdate()};g.prepareRenderPasses=function(c){const n=c.registerRenderPass({name:"label",brushes:[q.brushes.label],target:()=>this.hasLabels?this.children:null,drawPhase:h.WGLDrawPhase.LABEL|h.WGLDrawPhase.LABEL_ALPHA}),y=c.registerRenderPass({name:"geometry",brushes:[q.brushes.fill,q.brushes.line,q.brushes.marker,q.brushes.text],target:()=>this.children,enableDefaultDraw:()=>!this._layerView.hasEffects,
effects:[{apply:c.effects.outsideEffect,enable:()=>this._layerView.hasEffects,args:()=>this._layerView.effectLists.excluded},{apply:c.effects.insideEffect,enable:()=>this._layerView.hasEffects,args:()=>this._layerView.effectLists.included},{apply:c.effects.hittest,enable:()=>!!this._pointToCallbacks.size,args:()=>this._pointToCallbacks}]}),x=c.registerRenderPass({name:"highlight",brushes:[q.brushes.fill,q.brushes.line,q.brushes.marker,q.brushes.text],target:()=>this.children,drawPhase:h.WGLDrawPhase.HIGHLIGHT,
enableDefaultDraw:()=>!1,effects:[{apply:c.effects.highlight,enable:()=>!!this._layerView.hasHighlight()}]});return[...b.prototype.prepareRenderPasses.call(this,c),y,x,n]};v._createClass(f,[{key:"hasAnimation",get:function(){return this.hasLabels}},{key:"hasLabels",get:function(){if("sublayers"in this._layer)return this._layer.sublayers.some(n=>n.labelingInfo&&n.labelingInfo.length&&n.labelsVisible);var c=this._layer.featureReduction;c=c&&"cluster"===c.type&&c.labelsVisible&&c.labelingInfo&&c.labelingInfo.length;
return this._layer.labelingInfo&&this._layer.labelingInfo.length&&this._layer.labelsVisible||!!c}}]);return f}(t.FeatureContainer);w.WGLFeatureView=p;Object.defineProperty(w,"__esModule",{value:!0})})},"*noref":1}});
define("../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/has ../../../../../core/accessorSupport/decorators/property ../../../../../core/accessorSupport/ensureType ../../../../../core/Logger ../../../../../core/accessorSupport/decorators/subclass ../../../../../geometry/support/aaBoundingRect ../../../engine/webgl/FeatureTile ../support/rendererUtils ./BaseTileRenderer ./support/visualVariablesUtils ./support/WGLFeatureView".split(" "),function(w,
v,p,u,q,t,h,a,b,f,g,c,n){u=function(y){function x(){return y.apply(this,arguments)||this}w._inheritsLoose(x,y);var m=x.prototype;m.install=function(l){const e=new n.WGLFeatureView(this.tileInfoView,this.layerView,this.layer,()=>this.notifyChange("updating"));this.featuresView=e;l.addChild(e)};m.uninstall=function(l){l.removeChild(this.featuresView);this.featuresView.destroy()};m.isUpdating=function(){const l=y.prototype.isUpdating.call(this),e=!this.featuresView||this.featuresView.isUpdating(),d=
l||e;p("esri-2d-log-updating")&&console.log(`Updating SymbolTileRenderer ${d}\n  -> updatingTiles ${l}\n  -> updatingFeaturesView ${e}`);return d};m.hitTest=function(l,e){return this.featuresView.hitTest(l,e)};m.supportsRenderer=function(l){return null!=l&&-1!==["simple","class-breaks","unique-value","dot-density","dictionary"].indexOf(l.type)};m.onConfigUpdate=function(l){var e=null;"visualVariables"in l&&(e=(f.simplifyVVRenderer(l).visualVariables||[]).map(d=>{const k=d.clone();"normalizationField"in
d&&(k.normalizationField=null);d.valueExpression&&"$view.scale"!==d.valueExpression&&(k.valueExpression=null,k.field="nop");return k}),e=c.convertVisualVariables(e));this.featuresView.setRendererInfo(l,e,this.layerView.effects)};m.onTileData=function(l){const e=this.tiles.get(l.tileKey);if(e&&l.data)this.featuresView.onTileData(e,l.data);this.layerView.view.labelManager.requestUpdate()};m.onTileError=function(l){if(l=this.tiles.get(l.tileKey))this.featuresView.onTileError(l)};m.forceAttributeTextureUpload=
function(){this.featuresView.attributeView.forceTextureUpload()};m.lockGPUUploads=function(){this.featuresView.attributeView.lockTextureUpload();this.tiles.forEach(l=>l.lock())};m.unlockGPUUploads=function(){this.featuresView.attributeView.unlockTextureUpload();this.tiles.forEach(l=>l.unlock())};m.getMaterialItems=function(){var l=w._asyncToGenerator(function*(e){return this.featuresView.getMaterialItems(e)});return function(e){return l.apply(this,arguments)}}();m.invalidateLabels=function(){this.featuresView.hasLabels&&
this.layerView.view.labelManager.requestUpdate()};m.createTile=function(l){const e=this.tileInfoView.getTileBounds(a.create(),l);return new b.FeatureTile(l,e[0],e[3],this.featuresView.attributeView)};m.disposeTile=function(l){this.featuresView.removeChild(l);l.destroy();this.layerView.view.labelManager.requestUpdate()};return x}(g);return u=v.__decorate([h.subclass("esri.views.2d.layers.features.tileRenderers.SymbolTileRenderer")],u)});