// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../request ../../../../../core/Error ../../../../../core/has ../../../../../core/Logger ../../../../../core/maybe ../../../../../core/promiseUtils ../controllers/support/sourceAdapters ./DataTileSource ../../../../support/QueueProcessor".split(" "),function(r,h,w,x,t,q,k,m,y,z,u){const A=q.getLogger("esri.views.2d.layers.features.sources.BaseFeatureSource");q=function(l){function n(c){var a=l.call(this,c)||this;a.type="feature";
a.mode="on-demand";a._adapter=y.createSourceAdapter(c.serviceInfo);a._queue=new u.QueueProcessor({concurrency:8,process:function(){var d=h._asyncToGenerator(function*(b){m.throwIfAborted(b);if(k.isSome(b.tile)){var e=b.tile.key.id,{signal:g}=b;e=t("esri-tiles-debug")?{tile:e.replace(/\//g,"."),depth:b.depth}:void 0;g=yield a._adapter.executeQuery(b.query,{signal:g,query:{...e,...a._schema.customParameters}});g.level=b.tile.key.level;return g}return a._adapter.executeQuery(b.query,{...b,query:a._schema.customParameters})});
return function(b){return d.apply(this,arguments)}}()});a._patchQueue=new u.QueueProcessor({concurrency:8,process:function(){var d=h._asyncToGenerator(function*(b){m.throwIfAborted(b);if(k.isSome(b.tile)){var e=b.tile.key.id,{signal:g}=b;e=t("esri-tiles-debug")?{tile:e.replace(/\//g,"."),depth:b.depth}:void 0;g=yield a._adapter.executeQuery(b.query,{signal:g,query:{...e,...a._schema.customParameters}});g.level=b.tile.key.level;return g}return a._adapter.executeQuery(b.query,{...b,query:a._schema.customParameters})});
return function(b){return d.apply(this,arguments)}}()});return a}h._inheritsLoose(n,l);var f=n.prototype;f.destroy=function(){l.prototype.destroy.call(this);this._adapter.destroy();this._queue.destroy();this._patchQueue.destroy()};f.enableEvent=function(c,a){};f.subscribe=function(c){l.prototype.subscribe.call(this,c);const a=this._subscriptions.get(c.id);this._fetchDataTile(c).catch(d=>{m.isAbortError(d)||A.error(new x("mapview-query-error","Encountered error when fetching tile",{tile:c,error:d}))}).then(()=>
a.end())};f.unsubscribe=function(c){l.prototype.unsubscribe.call(this,c)};f.readers=function(c){return this._subscriptions.get(c).readers()};f.query=function(){var c=h._asyncToGenerator(function*(a){return this._adapter.executeQuery(a,{query:this._schema.customParameters})});return function(a){return c.apply(this,arguments)}}();f.queryLastEditDate=function(){var c=h._asyncToGenerator(function*(){const a=this._serviceInfo.source;return(yield w(a.path,{query:{...a.query,f:"json"},responseType:"json"})).data.editingInfo.lastEditDate});
return function(){return c.apply(this,arguments)}}();f.createTileQuery=function(c,a={}){var d;const b=this.createQuery(a);b.quantizationParameters=null!=(d=a.quantizationParameters)?d:c.getQuantizationParameters();b.resultType="tile";b.geometry=c.extent;b.quantizationParameters&&"esriGeometryPolyline"===this._serviceInfo.geometryType&&(b.maxAllowableOffset=c.resolution);return b};f._executePatchQuery=function(){var c=h._asyncToGenerator(function*(a,d,b,e){d=d.clone();d.outFields=[this._serviceInfo.objectIdField,
...b];d.returnCentroid=!1;d.returnGeometry=!1;b=k.isSome(d.start)?d.start/8E3:0;return this._patchQueue.push({tile:a,query:d,signal:e.signal,depth:b})});return function(a,d,b,e){return c.apply(this,arguments)}}();f._resend=function(){var c=h._asyncToGenerator(function*(a,d){const {query:b,message:e}=a,g=k.isSome(b.outFields)?b.outFields:[];a=this._queryInfo.outFields;const v=a.filter(p=>-1===g.indexOf(p));if(k.isNone(e.addOrUpdate))this._onMessage({...e,type:"append"});else if(v.length)try{const p=
this._subscriptions.get(e.id).tile,B=yield this._executePatchQuery(p,b,v,d);m.throwIfAborted(d);b.outFields=a;e.addOrUpdate.joinAttributes(B);this._onMessage({...e,end:e.end,type:"append"})}catch(p){}else this._onMessage({...e,type:"append"})});return function(a,d){return c.apply(this,arguments)}}();f._resendSubscription=function(){var c=h._asyncToGenerator(function*(a){if(a.empty)return this._onMessage({id:a.tile.id,addOrUpdate:null,end:!1,type:"append"});const d=a.signal;for(const b of a.requests.done)yield this._resend(b,
{signal:d});if(k.isSome(a.edits))return this._onMessage(a.edits)});return function(a){return c.apply(this,arguments)}}();f.resend=function(){var c=h._asyncToGenerator(function*(){const a=Array.from(this._subscriptions.values());yield Promise.all(a.map(d=>this._resendSubscription(d)))});return function(){return c.apply(this,arguments)}}();h._createClass(n,[{key:"updating",get:function(){return!!this._queue.length||Array.from(this._subscriptions.values()).some(c=>!c.done)}},{key:"maxRecordCountFactor",
get:function(){const {query:c}=this._serviceInfo.capabilities;return c.supportsMaxRecordCountFactor?4:null}},{key:"maxPageSize",get:function(){var c,{query:a}=this._serviceInfo.capabilities;a=null!=(c=a.maxRecordCount)?c:8E3;c=k.unwrapOr(this.maxRecordCountFactor,1);return a*c}},{key:"pageSize",get:function(){return Math.min(8E3,this.maxPageSize)}}]);return n}(z.DataTileSource);r.BaseFeatureSource=q;Object.defineProperty(r,"__esModule",{value:!0})});