// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/handleUtils ../core/accessorSupport/decorators/property ../core/has ../core/accessorSupport/ensureType ../core/Logger ../core/accessorSupport/decorators/subclass ../widgets/Widget ../widgets/support/widget ../widgets/support/decorators/messageBundle ../widgets/support/jsxFactory".split(" "),function(W,x,X,B,J,pa,qa,Y,q,Z,aa,t){function L(a,c){var d=Object.keys(a);if(Object.getOwnPropertySymbols){var e=Object.getOwnPropertySymbols(a);
c&&(e=e.filter(function(f){return Object.getOwnPropertyDescriptor(a,f).enumerable}));d.push.apply(d,e)}return d}function ba(a){for(var c=1;c<arguments.length;c++){var d=null!=arguments[c]?arguments[c]:{};c%2?L(Object(d),!0).forEach(function(e){var f=d[e];e in a?Object.defineProperty(a,e,{value:f,enumerable:!0,configurable:!0,writable:!0}):a[e]=f}):Object.getOwnPropertyDescriptors?Object.defineProperties(a,Object.getOwnPropertyDescriptors(d)):L(Object(d)).forEach(function(e){Object.defineProperty(a,
e,Object.getOwnPropertyDescriptor(d,e))})}return a}J='input select textarea a[href] button [tabindex] audio[controls] video[controls] [contenteditable]:not([contenteditable\x3d"false"]) details\x3esummary:first-of-type details'.split(" ");var M=J.join(","),G="undefined"===typeof Element?function(){}:Element.prototype.matches||Element.prototype.msMatchesSelector||Element.prototype.webkitMatchesSelector,ca=function(a,c,d){var e=Array.prototype.slice.apply(a.querySelectorAll(M));c&&G.call(a,M)&&e.unshift(a);
return e=e.filter(d)},N=function(a){var c=parseInt(a.getAttribute("tabindex"),10);return isNaN(c)?"true"===a.contentEditable||("AUDIO"===a.nodeName||"VIDEO"===a.nodeName||"DETAILS"===a.nodeName)&&null===a.getAttribute("tabindex")?0:a.tabIndex:c},da=function(a,c){return a.tabIndex===c.tabIndex?a.documentOrder-c.documentOrder:a.tabIndex-c.tabIndex},ea=function(a){return"DETAILS"===a.tagName&&Array.prototype.slice.apply(a.children).some(function(c){return"SUMMARY"===c.tagName})},fa=function(a,c){for(var d=
0;d<a.length;d++)if(a[d].checked&&a[d].form===c)return a[d]},ha=function(a){if(!a.name)return!0;var c=a.form||a.ownerDocument,d=function(f){return c.querySelectorAll('input[type\x3d"radio"][name\x3d"'+f+'"]')};if("undefined"!==typeof window&&"undefined"!==typeof window.CSS&&"function"===typeof window.CSS.escape)var e=d(window.CSS.escape(a.name));else try{e=d(a.name)}catch(f){return console.error("Looks like you have a radio button with a name attribute containing invalid CSS selector characters and need the CSS.escape polyfill: %s",
f.message),!1}d=fa(e,a.form);return!d||d===a},ia=function(a,c){if("hidden"===getComputedStyle(a).visibility)return!0;var d=G.call(a,"details\x3esummary:first-of-type")?a.parentElement:a;if(G.call(d,"details:not([open]) *"))return!0;if(!c||"full"===c)for(;a;){if("none"===getComputedStyle(a).display)return!0;a=a.parentElement}else if("non-zero-area"===c)return a=a.getBoundingClientRect(),c=a.height,0===a.width&&0===c;return!1},O=function(a,c){var d;(d=c.disabled)||(d="INPUT"===c.tagName&&"hidden"===
c.type);if(!(a=d||ia(c,a.displayCheck)||ea(c)))a:{if("INPUT"===c.tagName||"SELECT"===c.tagName||"TEXTAREA"===c.tagName||"BUTTON"===c.tagName)for(a=c.parentElement;a;){if("FIELDSET"===a.tagName&&a.disabled){for(d=0;d<a.children.length;d++){var e=a.children.item(d);if("LEGEND"===e.tagName){if(e.contains(c)){a=!1;break a}break}}a=!0;break a}a=a.parentElement}a=!1}return a?!1:!0},ja=function(a,c){(a=!O(a,c))||(a="INPUT"===c.tagName&&"radio"===c.type&&!ha(c));return a||0>N(c)?!1:!0},ka=function(a,c){c=
c||{};var d=[],e=[];ca(a,c.includeContainer,ja.bind(null,c)).forEach(function(f,h){var r=N(f);0===r?d.push(f):e.push({documentOrder:h,tabIndex:r,node:f})});return e.sort(da).map(function(f){return f.node}).concat(d)},la=J.concat("iframe").join(","),ma=function(a,c){c=c||{};if(!a)throw Error("No node provided");return!1===G.call(a,la)?!1:O(c,a)},P=function(){var a=[];return{activateTrap:function(c){if(0<a.length){var d=a[a.length-1];d!==c&&d.pause()}d=a.indexOf(c);-1!==d&&a.splice(d,1);a.push(c)},
deactivateTrap:function(c){c=a.indexOf(c);-1!==c&&a.splice(c,1);0<a.length&&a[a.length-1].unpause()}}}(),K=function(a,c){var d=-1;a.every(function(e,f){return c(e)?(d=f,!1):!0});return d},C=function(a){for(var c=arguments.length,d=Array(1<c?c-1:0),e=1;e<c;e++)d[e-1]=arguments[e];return"function"===typeof a?a.apply(void 0,d):a},oa=function(a,c){var d=document,e=ba({returnFocusOnDeactivate:!0,escapeDeactivates:!0,delayInitialFocus:!0},c),f=[],h=[],r=null,y=null,m=!1,u=!1,D=void 0,n=function(k,b,g){return k&&
void 0!==k[b]?k[b]:e[g||b]},z=function(k){return f.some(function(b){return b.contains(k)})},A=function(k){var b=e[k];if(!b)return null;var g=b;if("string"===typeof b&&(g=d.querySelector(b),!g))throw Error("`".concat(k,"` refers to no known node"));if("function"===typeof b&&(g=b(),!g))throw Error("`".concat(k,"` did not return a node"));return g},H=function(){if(!1===n({},"initialFocus"))return!1;var k=null!==A("initialFocus")?A("initialFocus"):z(d.activeElement)?d.activeElement:(k=h[0])&&k.firstTabbableNode||
A("fallbackFocus");if(!k)throw Error("Your focus-trap needs to have at least one focusable element");return k},E=function(){h=f.map(function(k){var b=ka(k);if(0<b.length)return{container:k,firstTabbableNode:b[0],lastTabbableNode:b[b.length-1]}}).filter(function(k){return!!k});if(0>=h.length&&!A("fallbackFocus"))throw Error("Your focus-trap must have at least one container with at least one tabbable node in it at all times");},F=function g(b){!1!==b&&b!==d.activeElement&&(b&&b.focus?(b.focus({preventScroll:!!e.preventScroll}),
y=b,b.tagName&&"input"===b.tagName.toLowerCase()&&"function"===typeof b.select&&b.select()):g(H()))},Q=function(b){var g=A("setReturnFocus");return g?g:b},I=function(b){z(b.target)||(C(e.clickOutsideDeactivates,b)?v.deactivate({returnFocus:e.returnFocusOnDeactivate&&!ma(b.target)}):C(e.allowOutsideClick,b)||b.preventDefault())},R=function(b){var g=z(b.target);g||b.target instanceof Document?g&&(y=b.target):(b.stopImmediatePropagation(),F(y||H()))},na=function(b){E();var g=null;if(0<h.length){var p=
K(h,function(w){return w.container.contains(b.target)});if(0>p)g=b.shiftKey?h[h.length-1].lastTabbableNode:h[0].firstTabbableNode;else if(b.shiftKey){var l=K(h,function(w){return b.target===w.firstTabbableNode});0>l&&h[p].container===b.target&&(l=p);0<=l&&(g=h[0===l?h.length-1:l-1].lastTabbableNode)}else l=K(h,function(w){return b.target===w.lastTabbableNode}),0>l&&h[p].container===b.target&&(l=p),0<=l&&(g=h[l===h.length-1?0:l+1].firstTabbableNode)}else g=A("fallbackFocus");g&&(b.preventDefault(),
F(g))},S=function(b){"Escape"!==b.key&&"Esc"!==b.key&&27!==b.keyCode||!1===C(e.escapeDeactivates)?"Tab"!==b.key&&9!==b.keyCode||na(b):(b.preventDefault(),v.deactivate())},T=function(b){C(e.clickOutsideDeactivates,b)||z(b.target)||C(e.allowOutsideClick,b)||(b.preventDefault(),b.stopImmediatePropagation())},U=function(){if(m)return P.activateTrap(v),D=e.delayInitialFocus?setTimeout(function(){F(H())},0):F(H()),d.addEventListener("focusin",R,!0),d.addEventListener("mousedown",I,{capture:!0,passive:!1}),
d.addEventListener("touchstart",I,{capture:!0,passive:!1}),d.addEventListener("click",T,{capture:!0,passive:!1}),d.addEventListener("keydown",S,{capture:!0,passive:!1}),v},V=function(){if(m)return d.removeEventListener("focusin",R,!0),d.removeEventListener("mousedown",I,!0),d.removeEventListener("touchstart",I,!0),d.removeEventListener("click",T,!0),d.removeEventListener("keydown",S,!0),v};var v={activate:function(b){if(m)return this;var g=n(b,"onActivate"),p=n(b,"onPostActivate"),l=n(b,"checkCanFocusTrap");
l||E();m=!0;u=!1;r=d.activeElement;g&&g();b=function(){l&&E();U();p&&p()};if(l)return l(f.concat()).then(b,b),this;b();return this},deactivate:function(b){if(!m)return this;clearTimeout(D);D=void 0;V();u=m=!1;P.deactivateTrap(v);var g=n(b,"onDeactivate"),p=n(b,"onPostDeactivate"),l=n(b,"checkCanReturnFocus");g&&g();var w=n(b,"returnFocus","returnFocusOnDeactivate");b=function(){setTimeout(function(){w&&F(Q(r));p&&p()},0)};if(w&&l)return l(Q(r)).then(b,b),this;b();return this},pause:function(){if(u||
!m)return this;u=!0;V();return this},unpause:function(){if(!u||!m)return this;u=!1;E();U();return this},updateContainerElements:function(b){f=[].concat(b).filter(Boolean).map(function(g){return"string"===typeof g?d.querySelector(g):g});m&&E();return this}};v.updateContainerElements(a);return v};q=function(a){function c(e,f){var h=a.call(this,e,f)||this;h.container=document.createElement("div");h.content=null;h.open=!1;h._close=()=>{h.open=!1};document.body.appendChild(h.container);h.own(h.watch("open",
()=>h._toggleFocusTrap()));return h}W._inheritsLoose(c,a);var d=c.prototype;d.destroy=function(){this._destroyFocusTrap()};d.render=function(){var e=this.id;const {open:f,content:h,title:r,messages:y}=this;var m=f&&!!h;const u={["esri-identity-modal--open"]:m,["esri-identity-modal--closed"]:!m},D=t.tsx("button",{class:"esri-identity-modal__close-button","aria-label":y.close,title:y.close,bind:this,onclick:this._close},t.tsx("span",{"aria-hidden":"true",class:"esri-icon-close"})),n=`${e}_title`;e=
`${e}_content`;const z=r?t.tsx("h1",{id:n,class:"esri-identity-modal__title"},r):null;m=m?t.tsx("div",{bind:this,class:"esri-identity-modal__dialog",role:"dialog","aria-labelledby":n,"aria-describedby":e,afterCreate:this._createFocusTrap},D,z,this._renderContent(e)):null;return t.tsx("div",{tabIndex:-1,class:this.classes("esri-identity-modal",u)},m)};d._destroyFocusTrap=function(){var e;null==(e=this._focusTrap)?void 0:e.deactivate({onDeactivate:null});this._focusTrap=null};d._toggleFocusTrap=function(){const {_focusTrap:e,
open:f}=this;e&&(f?e.activate():e.deactivate())};d._createFocusTrap=function(e){this._destroyFocusTrap();const f=requestAnimationFrame(()=>{this._focusTrap=oa(e,{initialFocus:"input",onDeactivate:this._close});this._toggleFocusTrap()});this.own(X.makeHandle(()=>cancelAnimationFrame(f)))};d._renderContent=function(e){const f=this.content;return"string"===typeof f?t.tsx("div",{class:"esri-identity-modal__content",id:e,innerHTML:f}):Z.isWidget(f)?t.tsx("div",{class:"esri-identity-modal__content",id:e},
f.render()):f instanceof HTMLElement?t.tsx("div",{class:"esri-identity-modal__content",id:e,bind:f,afterCreate:this._attachToNode}):null};d._attachToNode=function(e){e.appendChild(this)};return c}(q);x.__decorate([B.property({readOnly:!0})],q.prototype,"container",void 0);x.__decorate([B.property()],q.prototype,"content",void 0);x.__decorate([B.property()],q.prototype,"open",void 0);x.__decorate([B.property(),aa.messageBundle("esri/t9n/common")],q.prototype,"messages",void 0);x.__decorate([B.property({aliasOf:"messages.auth.signIn"})],
q.prototype,"title",void 0);return q=x.__decorate([Y.subclass("esri.identity.IdentityModal")],q)});