// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Handles ../../../core/promiseUtils ../../../core/accessorSupport/decorators/property ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/Logger ../../../core/accessorSupport/decorators/subclass ./BitmapTileLayerView2D ./LayerView2D ../tiling/TileInfoView ../tiling/TileQueue ../tiling/TileStrategy ../../layers/LayerView ../../layers/RefreshableLayerView".split(" "),function(h,l,q,n,p,f,B,
C,r,t,u,v,w,x,y,z){const A=[102113,102100,3857,3785,900913];f=function(g){function k(){var a=g.apply(this,arguments)||this;a._handles=new q;a._tileStrategy=null;a._fetchQueue=null;a._tileRequests=new Map;a.layer=null;return a}h._inheritsLoose(k,g);var c=k.prototype;c.hitTest=function(){return null};c.update=function(a){this._fetchQueue.pause();this._fetchQueue.state=a.state;this._tileStrategy.update(a);this._fetchQueue.resume();this.notifyChange("updating")};c.attach=function(){if(this.tileMatrixSet){var {tileInfo:a}=
this.tileMatrixSet;this._tileInfoView=new v(a);this._fetchQueue=new w({tileInfoView:this._tileInfoView,process:b=>this.fetchTile(b)});this._tileStrategy=new x({cachePolicy:"keep",acquireTile:b=>this.acquireTile(b),releaseTile:b=>this.releaseTile(b),tileInfoView:this._tileInfoView});this._handles.add(this.watch(["layer.activeLayer.styleId","tileMatrixSet"],()=>this._refresh()));g.prototype.attach.call(this)}};c.detach=function(){g.prototype.detach.call(this);this._handles.removeAll();this._tileStrategy.destroy();
this._fetchQueue.clear();this._fetchQueue=this._tileStrategy=this._tileInfoView=null};c.moveStart=function(){this.requestUpdate()};c.viewChange=function(){this.requestUpdate()};c.moveEnd=function(){this.requestUpdate()};c.doRefresh=function(){var a=h._asyncToGenerator(function*(){this.updateRequested||this.suspended||this._refresh()});return function(){return a.apply(this,arguments)}}();c.isUpdating=function(){return 0<this._fetchQueue.length};c.acquireTile=function(a){const b=this._bitmapView.createTile(a),
d=b.bitmap;[d.x,d.y]=this._tileInfoView.getTileCoords([0,0],b.key);d.resolution=this._tileInfoView.getTileResolution(b.key);[d.width,d.height]=this._tileInfoView.tileInfo.size;this._tileInfoView.getTileCoords(d,b.key);const e={id:a.id,fulfilled:!1,promise:this._fetchQueue.push(b.key).then(m=>{b.bitmap.source=m;b.once("attach",()=>this.requestUpdate());this._bitmapView.addChild(b)}).catch(m=>{n.isAbortError(m)||(b.bitmap.source=null,b.once("attach",()=>this.requestUpdate()),this._bitmapView.addChild(b))})};
e.promise.finally(()=>e.fulfilled=!0);this._tileRequests.set(b,e);this.requestUpdate();return b};c.releaseTile=function(a){const b=this._tileRequests.get(a);b.fulfilled||this._fetchQueue.abort(b.id);this._tileRequests.delete(a);this._bitmapView.removeChild(a);a.once("detach",()=>a.destroy());this.requestUpdate()};c.fetchTile=function(){var a=h._asyncToGenerator(function*(b){return this.layer.fetchTile(b.level,b.row,b.col)});return function(b){return a.apply(this,arguments)}}();c.canResume=function(){const a=
g.prototype.canResume.call(this);return a?null!==this.tileMatrixSet:a};c._refresh=function(){this._fetchQueue.reset();this._tileStrategy.tiles.forEach(a=>{if(a.bitmap.source){var b={id:a.key.id,fulfilled:!1,promise:this._fetchQueue.push(a.key).then(d=>{a.bitmap.source=d}).catch(d=>{n.isAbortError(d)||(a.bitmap.source=null)}).finally(()=>{a.requestRender();this.notifyChange("updating");b.fulfilled=!0})};this._tileRequests.set(a,b)}});this.notifyChange("updating")};c._getTileMatrixSetBySpatialReference=
function(a){const b=this.view.spatialReference;if(!a.tileMatrixSets)return null;let d=a.tileMatrixSets.find(e=>e.tileInfo.spatialReference.wkid===b.wkid);!d&&b.isWebMercator&&(d=a.tileMatrixSets.find(e=>-1<A.indexOf(e.tileInfo.spatialReference.wkid)));return d};h._createClass(k,[{key:"tileMatrixSet",get:function(){if(this.layer.activeLayer.tileMatrixSetId)return this.layer.activeLayer.tileMatrixSet;const a=this._getTileMatrixSetBySpatialReference(this.layer.activeLayer);if(!a)return null;this.layer.activeLayer.tileMatrixSetId=
a.id;return a}}]);return k}(z.RefreshableLayerView(t.BitmapTileLayerView2D(u.LayerView2DMixin(y))));l.__decorate([p.property()],f.prototype,"suspended",void 0);l.__decorate([p.property({readOnly:!0})],f.prototype,"tileMatrixSet",null);return f=l.__decorate([r.subclass("esri.views.2d.layers.WMTSLayerView2D")],f)});