// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../geometry ../../core/has ../../core/Logger ../../core/maybe ../../core/unitUtils ../../geometry/support/aaBoundingRect ../../geometry/support/contains ../../geometry/support/webMercatorUtils ../../geometry/Point".split(" "),function(l,p,q,u,z,m,A,r,B,C,D){function v(c,e){const d=w(c,e.spatialReference);if(!d)return null;switch(c.type){case "point":c.z=m.unwrapOr(e.elevationAt(d),0);break;case "polyline":h.spatialReference=d.spatialReference;
var a=c.hasM&&!c.hasZ;for(var f=0;f<c.paths.length;f++){var b=c.paths[f],g=d.paths[f];for(let k=0;k<b.length;k++){const n=b[k],x=g[k];h.x=x[0];h.y=x[1];a&&(n[3]=n[2]);n[2]=m.unwrapOr(e.elevationAt(h),0)}}c.hasZ=!0;break;case "multipoint":h.spatialReference=d.spatialReference;a=c.hasM&&!c.hasZ;for(f=0;f<c.points.length;f++)b=c.points[f],g=d.points[f],h.x=g[0],h.y=g[1],a&&(b[3]=b[2]),b[2]=m.unwrapOr(e.elevationAt(h),0);c.hasZ=!0}return c}function w(c,e){if(m.isNone(c))return null;const d=c.spatialReference;
if(d.equals(e))return c;(c=C.project(c,e))||t.error(`Cannot project geometry spatial reference (wkid:${d.wkid}) to elevation sampler spatial reference (wkid:${e.wkid})`);return c}const t=z.getLogger("esri.layers.support.ElevationSampler");q=function(){function c(){}var e=c.prototype;e.queryElevation=function(d){return v(d.clone(),this)};e.on=function(){return E};e.projectIfRequired=function(d,a){return w(d,a)};return c}();let y=function(c){function e(a,f,b){var g=c.call(this)||this;g.tile=a;g.noDataValue=
b;g.extent=r.toExtent(a.tile.extent,f.spatialReference);b=A.getMetersPerUnitForSR(f.spatialReference);a=f.lodAt(a.tile.level).resolution*b;g.demResolution={min:a,max:a};return g}p._inheritsLoose(e,c);var d=e.prototype;d.contains=function(a){a=this.projectIfRequired(a,this.spatialReference);return B.extentContainsPoint(this.extent,a)};d.elevationAt=function(a){const f=this.projectIfRequired(a,this.spatialReference);if(m.isNone(f))return null;if(!this.contains(a)){const b=this.extent;t.warn("#elevationAt()",
`Point used to sample elevation (${a.x}, ${a.y}) is outside of the sampler extent (${`${b.xmin}, ${b.ymin}, ${b.xmax}, ${b.ymax}`})`)}return this.tile.sample(f.x,f.y)};p._createClass(e,[{key:"spatialReference",get:function(){return this.extent.spatialReference}}]);return e}(q);u=function(c){function e(d,a,f){var b=c.call(this)||this;let g;"number"===typeof a?(b.noDataValue=a,g=null):(g=a,b.noDataValue=f);b.samplers=g?d.map(k=>new y(k,g,b.noDataValue)):d;if(d=b.samplers[0]){b.extent=d.extent.clone();
const {min:k,max:n}=d.demResolution;b.demResolution={min:k,max:n};for(d=1;d<b.samplers.length;d++)a=b.samplers[d],b.extent.union(a.extent),b.demResolution.min=Math.min(b.demResolution.min,a.demResolution.min),b.demResolution.max=Math.max(b.demResolution.max,a.demResolution.max)}else b.extent=r.toExtent(r.create(),g.spatialReference),b.demResolution={min:0,max:0};return b}p._inheritsLoose(e,c);e.prototype.elevationAt=function(d){const a=this.projectIfRequired(d,this.spatialReference);if(!a)return null;
for(const f of this.samplers)if(f.contains(a))return f.elevationAt(a);t.warn("#elevationAt()",`Point used to sample elevation (${d.x}, ${d.y}) is outside of the sampler`);return null};p._createClass(e,[{key:"spatialReference",get:function(){return this.extent.spatialReference}}]);return e}(q);const h=new D,E={remove(){}};l.ElevationSamplerBase=q;l.MultiTileElevationSampler=u;l.TileElevationSampler=y;l.updateGeometryElevation=v;Object.defineProperty(l,"__esModule",{value:!0})});