// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("require exports ../../chunks/_rollupPluginBabelHelpers ../../core/Error ../../core/maybe ../../core/object ./domainUtils ../../support/arcadeOnDemand".split(" "),function(da,d,g,ea,h,w,q,fa){function R(a,b,c){if(a)for(const e of a)(a=(a=w.getDeepValue(e,b))&&"function"!==typeof a&&c.get(a))&&w.setDeepValue(e,a.name,b)}function m(a,b){if(!a||!b)return[];x.clear();n(x,a,b);return Array.from(x).sort()}function n(a,b,c){var e;if(c)if(null!=b&&null!=(e=b.fields)&&e.length)if(c.includes("*"))for(const {name:f}of b.fields)a.add(f);
else for(const f of c)p(a,b,f);else if(c.includes("*"))a.clear(),a.add("*");else for(const f of c)a.add(f)}function p(a,b,c){"string"===typeof c&&(b?(b=b.get(c))&&a.add(b.name):a.add(c))}function l(a,b,c){return y.apply(this,arguments)}function y(){y=g._asyncToGenerator(function*(a,b,c){var e;if(c){var {arcadeUtils:f}=yield fa.loadArcade();c=f.extractFieldNames(c,null==b?void 0:null==(e=b.fields)?void 0:e.map(k=>k.name));for(const k of c)p(a,b,k)}});return y.apply(this,arguments)}function S(a,b,c){return z.apply(this,
arguments)}function z(){z=g._asyncToGenerator(function*(a,b,c){if(c&&"1\x3d1"!==c){c=(yield new Promise(function(e,f){da(["../../core/sql/WhereClause"],e,f)})).WhereClause.create(c,b);if(!c.isStandardized)throw new ea("fieldUtils:collectFilterFields","Where clause is not standardized");n(a,b,c.fieldNames)}});return z.apply(this,arguments)}function A(a,b){for(const c of a)if(c&&c.valueType&&c.valueType===b)return c.name;return null}function B(){B=g._asyncToGenerator(function*(a){if(!a)return[];const b=
new Set;yield T(b,a);return Array.from(b).sort()});return B.apply(this,arguments)}function T(a,b){return C.apply(this,arguments)}function C(){C=g._asyncToGenerator(function*(a,b){if(b){var c=w.getDeepValue("elevationInfo.featureExpressionInfo",b);if(c)return c.collectRequiredFields(a,b.fieldsIndex)}});return C.apply(this,arguments)}function ha(a,b,c){return D.apply(this,arguments)}function D(){D=g._asyncToGenerator(function*(a,b,c){c.outStatistic.onStatisticValueExpression?l(a,b,c.outStatistic.onStatisticValueExpression):
a.add(c.outStatistic.onStatisticField)});return D.apply(this,arguments)}function E(){E=g._asyncToGenerator(function*(a,b,c){var e;if(b&&c&&"cluster"===c.type){var f=[];null!=(e=c.popupTemplate)&&e.expressionInfos&&f.push(...c.popupTemplate.expressionInfos.map(k=>l(a,b.fieldsIndex,k.expression)));c.fields&&f.push(...c.fields.map(k=>ha(a,b.fieldsIndex,k)));yield Promise.all(f)}});return E.apply(this,arguments)}function F(){F=g._asyncToGenerator(function*(a,b,c){b&&(b.timeInfo&&h.isSome(c)&&c.timeExtent&&
n(a,b.fieldsIndex,[b.timeInfo.startField,b.timeInfo.endField]),b.floorInfo&&n(a,b.fieldsIndex,[b.floorInfo.floorField]),h.isSome(c)&&h.isSome(c.where)&&(yield S(a,b.fieldsIndex,c.where)))});return F.apply(this,arguments)}function G(){G=g._asyncToGenerator(function*(a,b,c){b&&c&&(yield Promise.all(c.map(e=>ia(a,b,e))))});return G.apply(this,arguments)}function ia(a,b,c){return H.apply(this,arguments)}function H(){H=g._asyncToGenerator(function*(a,b,c){b&&c&&(c.valueExpression?yield l(a,b.fieldsIndex,
c.valueExpression):c.field&&p(a,b.fieldsIndex,c.field))});return H.apply(this,arguments)}function I(){I=g._asyncToGenerator(function*(a){if(!a)return[];const b="timeInfo"in a&&a.timeInfo;return b?m(a.fieldsIndex,[a.trackIdField,b.startField,b.endField]):[]});return I.apply(this,arguments)}function J(){J=g._asyncToGenerator(function*(a){if(!a)return[];const b=new Set;yield U(b,a);return Array.from(b).sort()});return J.apply(this,arguments)}function U(a,b){return K.apply(this,arguments)}function K(){K=
g._asyncToGenerator(function*(a,b){const {labelingInfo:c,fieldsIndex:e}=b;c&&c.length&&(yield Promise.all(c.map(f=>ja(a,e,f))))});return K.apply(this,arguments)}function ja(a,b,c){return L.apply(this,arguments)}function L(){L=g._asyncToGenerator(function*(a,b,c){if(c){var e=c.getLabelExpression();c=c.where;"arcade"===e.type?yield l(a,b,e.expression):(e=e.expression.match(/{[^}]*}/g))&&e.forEach(f=>{p(a,b,f.slice(1,-1))});yield S(a,b,c)}});return L.apply(this,arguments)}function M(a){return"number"===
typeof a&&!isNaN(a)&&isFinite(a)}function ka(a){return null===a||M(a)}function la(a){return null===a||r(a)}function V(a){return null!=a&&"string"===typeof a}function ma(a){return null===a||V(a)}function na(){return!0}function N(a,b){let c;switch(a.type){case "date":case "integer":case "long":case "small-integer":case "esriFieldTypeDate":case "esriFieldTypeInteger":case "esriFieldTypeLong":case "esriFieldTypeSmallInteger":c=a.nullable?la:r;break;case "double":case "single":case "esriFieldTypeSingle":case "esriFieldTypeDouble":c=
a.nullable?ka:M;break;case "string":case "esriFieldTypeString":c=a.nullable?ma:V;break;default:c=na}return 1===arguments.length?c:c(b)}function O(a){return null!=a&&oa.has(a.type)}function W(a,b){return a.nullable&&null===b?null:O(a)&&!X(a.type,Number(b))?d.NumericRangeValidationError.OUT_OF_RANGE:N(a,b)?a.domain?q.validateDomainValue(a.domain,b):null:d.TypeValidationError.INVALID_TYPE}function X(a,b){return(a="string"===typeof a?P(a):a)?a.isInteger?r(b)&&b>=a.min&&b<=a.max:b>=a.min&&b<=a.max:!1}
function P(a){switch(a){case "esriFieldTypeSmallInteger":case "small-integer":return t;case "esriFieldTypeInteger":case "integer":return u;case "esriFieldTypeSingle":case "single":return v;case "esriFieldTypeDouble":case "double":return Y}}function Z(a,b,c){if(!b||!b.attributes||!a){if(h.isSome(c))for(var e of a)c.add(e);return!0}b=b.attributes;e=!1;for(const f of a)if(!(f in b))if(e=!0,h.isSome(c))c.add(f);else break;return e}function Q(){Q=g._asyncToGenerator(function*(a,b){const c=new Set;for(const e of b)yield l(c,
a.fieldsIndex,e);return Array.from(c).sort()});return Q.apply(this,arguments)}const aa="field field2 field3 normalizationField rotationInfo.field proportionalSymbolInfo.field proportionalSymbolInfo.normalizationField colorInfo.field colorInfo.normalizationField".split(" "),ba=["field","normalizationField"],x=new Set,r=(()=>"isInteger"in Number?Number.isInteger:a=>"number"===typeof a&&isFinite(a)&&Math.floor(a)===a)(),ca=["integer","small-integer","single","double"],oa=new Set([...ca,"esriFieldTypeInteger",
"esriFieldTypeSmallInteger","esriFieldTypeSingle","esriFieldTypeDouble"]);d.NumericRangeValidationError=void 0;(d.NumericRangeValidationError||(d.NumericRangeValidationError={})).OUT_OF_RANGE="numeric-range-validation-error::out-of-range";d.TypeValidationError=void 0;(d.TypeValidationError||(d.TypeValidationError={})).INVALID_TYPE="type-validation-error::invalid-type";const t={min:-32768,max:32767,isInteger:!0},u={min:-2147483648,max:2147483647,isInteger:!0},v={min:-3.4E38,max:1.2E38,isInteger:!1},
Y={min:-Number.MAX_VALUE,max:Number.MAX_VALUE,isInteger:!1};d.collectArcadeFieldNames=l;d.collectElevationFields=T;d.collectFeatureReductionFields=function(a,b,c){return E.apply(this,arguments)};d.collectField=p;d.collectFields=n;d.collectFilterFields=function(a,b,c){return F.apply(this,arguments)};d.collectLabelingFields=U;d.collectOrderByInfos=function(a,b,c){return G.apply(this,arguments)};d.doubleRange=Y;d.featureHasFields=function(a,b){return!Z(a,b,null)};d.fixFields=m;d.fixRendererFields=function(a,
b){if(null!=a&&null!=b)for(const c of Array.isArray(a)?a:[a])if(R(aa,c,b),"visualVariables"in c&&c.visualVariables)for(const e of c.visualVariables)R(ba,e,b)};d.fixTimeInfoFields=function(a,b){if(null!=a&&null!=b&&b.fields.length)if("startField"in a){var c=b.get(a.startField);b=b.get(a.endField);a.startField=c&&c.name||null;a.endField=b&&b.name||null}else c=b.get(a.startTimeField),b=b.get(a.endTimeField),a.startTimeField=c&&c.name||null,a.endTimeField=b&&b.name||null};d.getDisplayFieldName=function({displayField:a,
fields:b}){if(a)return a;if(!b||!b.length)return null;if(!(a=A(b,"name-or-title")||A(b,"unique-identifier")||A(b,"type-or-category")))a:{for(const c of b)if(c&&c.name&&(b=c.name.toLowerCase(),-1<b.indexOf("name")||-1<b.indexOf("title"))){a=c.name;break a}a=null}return a};d.getElevationFields=function(a){return B.apply(this,arguments)};d.getExpressionFields=function(a,b){return Q.apply(this,arguments)};d.getFeatureEditFields=function(a){if(!a)return[];const b="editFieldsInfo"in a&&a.editFieldsInfo;
return b?m(a.fieldsIndex,[b&&b.creatorField,b&&b.creationDateField,b&&b.editorField,b&&b.editDateField]):[]};d.getFeatureGeometryFields=function(a){if(!a)return[];const b=a.geometryFieldsInfo;return b?m(a.fieldsIndex,[b.shapeAreaField,b.shapeLengthField]):[]};d.getFieldDefaultValue=function(a){const b=a.defaultValue;if(void 0!==b&&N(a,b))return b;if(a.nullable)return null};d.getFieldRange=function(a){const b=q.getDomainRange(a.domain);if(b)return b;if(O(a))return P(a.type)};d.getLabelingFields=function(a){return J.apply(this,
arguments)};d.getNumericTypeForValue=function(a){if(!M(a))return null;if(r(a)){if(a>=t.min&&a<=t.max)return"esriFieldTypeSmallInteger";if(a>=u.min&&a<=u.max)return"esriFieldTypeInteger"}return a>=v.min&&a<=v.max?"esriFieldTypeSingle":"esriFieldTypeDouble"};d.getTimeFields=function(a){return I.apply(this,arguments)};d.integerRange=u;d.isDateField=function(a){return null!=a&&("date"===a.type||"esriFieldTypeDate"===a.type)};d.isNumberInRange=X;d.isNumericField=O;d.isStringField=function(a){return null!=
a&&("string"===a.type||"esriFieldTypeString"===a.type)};d.isValidFieldValue=function(a,b){return null===W(a,b)};d.isValueMatchingFieldType=N;d.numericTypes=ca;d.packFields=function(a,b,c=1){if(!b||!a)return[];if(b.includes("*"))return["*"];b=m(a,b);return b.length/a.fields.length>=c?["*"]:b};d.populateMissingFields=Z;d.rendererFields=aa;d.sanitizeNullFieldValue=function(a){return null==a||"number"===typeof a&&isNaN(a)?null:a};d.singleRange=v;d.smallIntegerRange=t;d.unpackFieldNames=function(a,b){return h.isNone(b)||
h.isNone(a)?[]:b.includes("*")?a.fields.map(c=>c.name):b};d.validateFieldValue=W;d.validationErrorToString=function(a,b,c){switch(a){case q.DomainValidationError.INVALID_CODED_VALUE:return`Value ${c} is not in the coded domain - field: ${b.name}, domain: ${JSON.stringify(b.domain)}`;case q.DomainValidationError.VALUE_OUT_OF_RANGE:return`Value ${c} is out of the range of valid values - field: ${b.name}, domain: ${JSON.stringify(b.domain)}`;case d.TypeValidationError.INVALID_TYPE:return`Value ${c} is not a valid value for the field type - field: ${b.name}, type: ${b.type}, nullable: ${b.nullable}`;
case d.NumericRangeValidationError.OUT_OF_RANGE:{const {min:e,max:f}=P(b.type);return`Value ${c} is out of range for the number type - field: ${b.name}, type: ${b.type}, value range is ${e} to ${f}`}}};d.visualVariableFields=ba;Object.defineProperty(d,"__esModule",{value:!0})});