// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define(["../../chunks/_rollupPluginBabelHelpers","../../core/Error","../../core/maybe","../../core/workers/workers","./PixelBlock"],function(f,g,l,n,k){return function(){function m(){this._workerThread=null;this._destroyed=!1}var d=m.prototype;d.initialize=function(){var c=f._asyncToGenerator(function*(){const a=yield n.open("RasterWorker");this._destroyed?a.close():this._workerThread=a});return function(){return c.apply(this,arguments)}}();d.destroy=function(){this._destroyed=!0;this._workerThread&&
(this._workerThread.close(),this._workerThread=null)};d.convertVectorFieldData=function(){var c=f._asyncToGenerator(function*(a,b){if(!this._workerThread)throw new g("raster-jobhandler:no-connection","no available worker connection");return(a=yield this._workerThread.invoke("convertVectorFieldData",{pixelBlock:a.pixelBlock.toJSON(),type:a.dataType},b))?new k(a):null});return function(a,b){return c.apply(this,arguments)}}();d.decode=function(){var c=f._asyncToGenerator(function*(a,b){if(!this._workerThread)throw new g("raster-jobhandler:no-connection",
"no available worker connection");return(a=yield this._workerThread.invoke("decode",a,b))?new k(a):null});return function(a,b){return c.apply(this,arguments)}}();d.symbolize=function(){var c=f._asyncToGenerator(function*(a,b){if(!this._workerThread)throw new g("raster-jobhandler:no-connection","no available worker connection");a={extent:a.extent&&a.extent.toJSON(),pixelBlock:l.isSome(a.pixelBlock)&&a.pixelBlock.toJSON(),simpleStretchParams:a.simpleStretchParams,bandIds:a.bandIds};return(b=yield this._workerThread.invoke("symbolize",
a,b))?new k(b):null});return function(a,b){return c.apply(this,arguments)}}();d.updateSymbolizer=function(){var c=f._asyncToGenerator(function*(a,b){var e;if(!this._workerThread)throw new g("raster-jobhandler:no-connection","no available worker connection");const h=null==a?void 0:null==(e=a.rendererJSON)?void 0:e.histograms;yield Promise.all(this._workerThread.broadcast("updateSymbolizer",{symbolizerJSON:a.toJSON(),histograms:h},b))});return function(a,b){return c.apply(this,arguments)}}();d.stretch=
function(){var c=f._asyncToGenerator(function*(a,b){if(!this._workerThread)throw new g("raster-jobhandler:no-connection","no available worker connection");if(null==a||!a.pixelBlock)return null;a={srcPixelBlock:a.pixelBlock.toJSON(),stretchParams:a.stretchParams};return(b=yield this._workerThread.invoke("stretch",a,b))?new k(b):null});return function(a,b){return c.apply(this,arguments)}}();d.split=function(){var c=f._asyncToGenerator(function*(a,b){if(!this._workerThread)throw new g("raster-jobhandler:no-connection",
"no available worker connection");if(null==a||!a.pixelBlock)return null;a={srcPixelBlock:a.pixelBlock.toJSON(),tileSize:a.tileSize,maximumPyramidLevel:a.maximumPyramidLevel};const e=yield this._workerThread.invoke("split",a,b);e&&e.forEach((h,p)=>{e.set(p,h?k.fromJSON(h):null)});return Promise.resolve(e)});return function(a,b){return c.apply(this,arguments)}}();d.estimateStatisticsHistograms=function(){var c=f._asyncToGenerator(function*(a,b){if(!this._workerThread)throw new g("raster-jobhandler:no-connection",
"no available worker connection");if(null==a||!a.pixelBlock)return null;a={srcPixelBlock:a.pixelBlock.toJSON()};b=yield this._workerThread.invoke("estimateStatisticsHistograms",a,b);return Promise.resolve(b)});return function(a,b){return c.apply(this,arguments)}}();d.mosaicAndTransform=function(){var c=f._asyncToGenerator(function*(a,b){var e;if(!this._workerThread)throw new g("raster-jobhandler:no-connection","no available worker connection");if(null==a||null==(e=a.srcPixelBlocks)||!e.length)return null;
a={...a,srcPixelBlocks:a.srcPixelBlocks.map(h=>l.isSome(h)?h.toJSON():null)};return(b=yield this._workerThread.invoke("mosaicAndTransform",a,b))?new k(b):null});return function(a,b){return c.apply(this,arguments)}}();return m}()});