// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../ArcadePortal ../Dictionary ../Feature ../featureSetCollection ../featureSetUtils ../../chunks/languageUtils ../featureset/actions/Adapted ../featureset/actions/AttributeFilter ../featureset/actions/OrderBy ../featureset/actions/Top ../featureset/sources/Empty ../featureset/sources/FeatureLayerMemory ../featureset/support/OrderbyClause ../featureset/support/shared ../featureset/support/sqlUtils ./fieldStats ../../core/promiseUtils ../../core/sql/WhereClause ../../layers/FeatureLayer ../../layers/support/Field".split(" "),
function(T,M,C,H,U,B,d,v,V,aa,ba,ca,da,ea,N,W,O,A,z,P,I){function fa(c,e,n,b){if(1===b.length){if(d.isArray(b[0]))return O.calculateStat(c,b[0],-1);if(d.isImmutableArray(b[0]))return O.calculateStat(c,b[0].toArray(),-1)}return O.calculateStat(c,b,-1)}function Q(c,e,n){const b=c.getVariables();if(0<b.length){const p=[];for(let a=0;a<b.length;a++)p.push(e.evaluateIdentifier(n,{name:b[a]}));return A.all(p).then(a=>{const g={};for(let q=0;q<b.length;q++)g[b[q]]=a[q];c.parameters=g;return c})}return A.resolve(c)}
function r(c,e,n=null){for(const b in c)if(b.toLowerCase()===e.toLowerCase())return c[b];return n}function X(c){if(null===c)return null;const e={type:r(c,"type",""),name:r(c,"name","")};if("range"===e.type)e.range=r(c,"range",[]);else{e.codedValues=[];for(const n of r(c,"codedValues",[]))e.codedValues.push({name:r(n,"name",""),code:r(n,"code",null)})}return e}function R(c){if(null===c)return null;const e={},n=r(c,"wkt",null);null!==n&&(e.wkt=n);c=r(c,"wkid",null);null!==c&&(e.wkid=c);return e}function Y(c){if(null===
c)return null;const e={hasZ:r(c,"hasz",!1),hasM:r(c,"hasm",!1)};var n=r(c,"spatialreference",null);n&&(e.spatialReference=R(n));n=r(c,"x",null);if(null!==n)return e.x=n,e.y=r(c,"y",null),e;n=r(c,"rings",null);if(null!==n)return e.rings=n,e;n=r(c,"paths",null);if(null!==n)return e.paths=n,e;n=r(c,"points",null);if(null!==n)return e.points=n,e;for(const b of"xmin xmax ymin ymax zmin zmax mmin mmax".split(" "))n=r(c,b,null),null!==n&&(e[b]=n);return e}T.registerFunctions=function(c){"async"===c.mode&&
(c.functions.getuser=function(e,n){return c.standardFunctionAsync(e,n,(b,p,a)=>{d.pcCheck(a,1,2);let g=d.defaultUndefined(a[1],""),q=!0===g;g=!0===g||!1===g?"":d.toString(g);if(a[0]instanceof M)return b=null,e.services&&e.services.portal&&(b=e.services.portal),b=B.getPortal(a[0],b),B.lookupUser(b,g,q).then(l=>{if(l){l=JSON.parse(JSON.stringify(l));for(const f of["lastLogin","created","modified"])void 0!==l[f]&&null!==l[f]&&(l[f]=new Date(l[f]));return C.convertObjectToArcadeDictionary(l)}return null});
let m=null;d.isFeatureSet(a[0])&&(m=a[0]);if(m)return q=!1,g?null:m.load().then(()=>m.getOwningSystemUrl()).then(l=>{if(!l)return g?null:m.getIdentityUser().then(k=>k?C.convertObjectToArcadeDictionary({username:k}):null);let f=null;e.services&&e.services.portal&&(f=e.services.portal);f=B.getPortal(new M(l),f);return B.lookupUser(f,g,q).then(k=>{if(k){k=JSON.parse(JSON.stringify(k));for(const h of["lastLogin","created","modified"])void 0!==k[h]&&null!==k[h]&&(k[h]=new Date(k[h]));return C.convertObjectToArcadeDictionary(k)}return null})});
throw Error("Invalid Parameter");})},c.signatures.push({name:"getuser",min:"1",max:"2"}),c.functions.featuresetbyid=function(e,n){return c.standardFunctionAsync(e,n,(b,p,a)=>{d.pcCheck(a,2,4);if(a[0]instanceof U){b=d.toString(a[1]);p=d.defaultUndefined(a[2],null);const g=d.toBoolean(d.defaultUndefined(a[3],!0));null===p&&(p=["*"]);if(!1===d.isArray(p))throw Error("Invalid Parameter");return a[0].featureSetById(b,g,p)}throw Error("Invalid Parameter");})},c.signatures.push({name:"featuresetbyid",min:"2",
max:"4"}),c.functions.getfeatureset=function(e,n){return c.standardFunctionAsync(e,n,(b,p,a)=>{d.pcCheck(a,1,2);if(a[0]instanceof H)return b=d.defaultUndefined(a[1],"datasource"),null===b&&(b="datasource"),b=d.toString(b).toLowerCase(),B.convertToFeatureSet(a[0]._layer,b,e.lrucache,e.interceptor,e.spatialReference);throw Error("Invalid Parameter");})},c.signatures.push({name:"getfeatureset",min:"1",max:"2"}),c.functions.featuresetbyportalitem=function(e,n){return c.standardFunctionAsync(e,n,(b,p,
a)=>{d.pcCheck(a,2,5);if(null===a[0])throw Error("Portal is required");if(a[0]instanceof M){b=d.toString(a[1]);p=d.toString(a[2]);var g=d.defaultUndefined(a[3],null);const q=d.toBoolean(d.defaultUndefined(a[4],!0));null===g&&(g=["*"]);if(!1===d.isArray(g))throw Error("Invalid Parameter");let m=null;e.services&&e.services.portal&&(m=e.services.portal);m=B.getPortal(a[0],m);return B.constructFeatureSetFromPortalItem(b,p,e.spatialReference,g,q,m,e.lrucache,e.interceptor)}if(!1===d.isString(a[0]))throw Error("Portal is required");
b=d.toString(a[0]);p=d.toString(a[1]);g=d.defaultUndefined(a[2],null);a=d.toBoolean(d.defaultUndefined(a[3],!0));null===g&&(g=["*"]);if(!1===d.isArray(g))throw Error("Invalid Parameter");if(e.services&&e.services.portal)return B.constructFeatureSetFromPortalItem(b,p,e.spatialReference,g,a,e.services.portal,e.lrucache,e.interceptor);throw Error("Portal is required");})},c.signatures.push({name:"featuresetbyportalitem",min:"2",max:"5"}),c.functions.featuresetbyname=function(e,n){return c.standardFunctionAsync(e,
n,(b,p,a)=>{d.pcCheck(a,2,4);if(a[0]instanceof U){b=d.toString(a[1]);p=d.defaultUndefined(a[2],null);const g=d.toBoolean(d.defaultUndefined(a[3],!0));null===p&&(p=["*"]);if(!1===d.isArray(p))throw Error("Invalid Parameter");return a[0].featureSetByName(b,g,p)}throw Error("Invalid Parameter");})},c.signatures.push({name:"featuresetbyname",min:"2",max:"4"}),c.functions.featureset=function(e,n){return c.standardFunction(e,n,(b,p,a)=>{d.pcCheck(a,1,1);p=a[0];b={layerDefinition:{geometryType:"",objectIdField:"",
globalIdField:"",typeIdField:"",fields:[]},featureSet:{geometryType:"",features:[]}};if(d.isString(p))p=JSON.parse(p),void 0!==p.layerDefinition?(b.layerDefinition=p.layerDefinition,b.featureSet=p.featureSet,p.layerDefinition.spatialReference&&(b.layerDefinition.spatialReference=p.layerDefinition.spatialReference)):(b.featureSet.features=p.features,b.featureSet.geometryType=p.geometryType,b.layerDefinition.geometryType=b.featureSet.geometryType,b.layerDefinition.objectIdField=p.objectIdFieldName,
b.layerDefinition.typeIdField=p.typeIdFieldName,b.layerDefinition.globalIdField=p.globalIdFieldName,b.layerDefinition.fields=p.fields,p.spatialReference&&(b.layerDefinition.spatialReference=p.spatialReference));else if(a[0]instanceof C)if(p=JSON.parse(a[0].castToText()),a=r(p,"layerdefinition"),null!==a){b.layerDefinition.geometryType=r(a,"geometrytype","");b.featureSet.geometryType=b.layerDefinition.geometryType;b.layerDefinition.globalIdField=r(a,"globalidfield","");b.layerDefinition.objectIdField=
r(a,"objectidfield","");b.layerDefinition.typeIdField=r(a,"typeidfield","");var g=r(a,"spatialreference",null);g&&(b.layerDefinition.spatialReference=R(g));for(const h of r(a,"fields",[]))g={name:r(h,"name",""),alias:r(h,"alias",""),type:r(h,"type",""),nullable:r(h,"nullable",!0),editable:r(h,"editable",!0),length:r(h,"length",null),domain:X(r(h,"domain"))},b.layerDefinition.fields.push(g);var q=r(p,"featureset",null);if(q){g={};for(var m of b.layerDefinition.fields)g[m.name.toLowerCase()]=m.name;
for(var l of r(q,"features",[])){q={};m=r(l,"attributes",{});for(var f in m)q[g[f.toLowerCase()]]=m[f];b.featureSet.features.push({attributes:q,geometry:Y(r(l,"geometry",null))})}}}else{b.layerDefinition.geometryType=r(p,"geometrytype","");b.featureSet.geometryType=b.layerDefinition.geometryType;b.layerDefinition.objectIdField=r(p,"objectidfieldname","");b.layerDefinition.typeIdField=r(p,"typeidfieldname","");if(l=r(p,"spatialreference",null))b.layerDefinition.spatialReference=R(l);for(const h of r(p,
"fields",[]))l={name:r(h,"name",""),alias:r(h,"alias",""),type:r(h,"type",""),nullable:r(h,"nullable",!0),editable:r(h,"editable",!0),length:r(h,"length",null),domain:X(r(h,"domain"))},b.layerDefinition.fields.push(l);l={};for(const h of b.layerDefinition.fields)l[h.name.toLowerCase()]=h.name;for(g of r(p,"features",[])){f={};m=r(g,"attributes",{});for(q in m)f[l[q.toLowerCase()]]=m[q];b.featureSet.features.push({attributes:f,geometry:Y(r(g,"geometry",null))})}}else throw Error("Invalid Parameter");
if(b.layerDefinition&&b.featureSet){b:{l=" esriGeometryPoint esriGeometryPolyline esriGeometryPolygon esriGeometryMultipoint esriGeometryEnvelope".split(" ");for(k of l)if(k===b.layerDefinition.geometryType){var k=!0;break b}k=!1}k=!1===k||null===b.layerDefinition.objectIdField||""===b.layerDefinition.objectIdField||!1===d.isArray(b.layerDefinition.fields)||!1===d.isArray(b.featureSet.features)?!1:!0}else k=!1;if(!1===k)throw Error("Invalid Parameter");return da.create(b,e.spatialReference)})},c.signatures.push({name:"featureset",
min:"1",max:"1"}),c.functions.filter=function(e,n){return c.standardFunctionAsync(e,n,(b,p,a)=>{d.pcCheck(a,2,2);return d.isFeatureSet(a[0])?a[0].load().then(g=>{const q=z.WhereClause.create(a[1],g.getFieldsIndex()),m=q.getVariables();if(0<m.length){g=[];for(let l=0;l<m.length;l++)g.push(c.evaluateIdentifier(e,{name:m[l]}));return A.all(g).then(l=>{const f={};for(let k=0;k<m.length;k++)f[m[k]]=l[k];q.parameters=f;return new V({parentfeatureset:a[0],whereclause:q})})}return A.resolve(new V({parentfeatureset:a[0],
whereclause:q}))}):c.failDefferred("Filter cannot accept this parameter type")})},c.signatures.push({name:"filter",min:"2",max:"2"}),c.functions.orderby=function(e,n){return c.standardFunctionAsync(e,n,(b,p,a)=>{d.pcCheck(a,2,2);return d.isFeatureSet(a[0])?(b=new ea(a[1]),A.resolve(new aa({parentfeatureset:a[0],orderbyclause:b}))):c.failDefferred("Order cannot accept this parameter type")})},c.signatures.push({name:"orderby",min:"2",max:"2"}),c.functions.top=function(e,n){return c.standardFunctionAsync(e,
n,(b,p,a)=>{d.pcCheck(a,2,2);return d.isFeatureSet(a[0])?A.resolve(new ba({parentfeatureset:a[0],topnum:a[1]})):d.isArray(a[0])?d.toNumber(a[1])>=a[0].length?a[0].slice(0):a[0].slice(0,d.toNumber(a[1])):d.isImmutableArray(a[0])?d.toNumber(a[1])>=a[0].length()?a[0].slice(0):a[0].slice(0,d.toNumber(a[1])):c.failDefferred("Top cannot accept this parameter type")})},c.signatures.push({name:"top",min:"2",max:"2"}),c.functions.first=function(e,n){return c.standardFunctionAsync(e,n,(b,p,a)=>{d.pcCheck(a,
1,1);return d.isFeatureSet(a[0])?a[0].first(b.abortSignal).then(g=>{if(null!==g){const q=H.createFromGraphicLikeObject(g.geometry,g.attributes,a[0]);q._underlyingGraphic=g;g=q}return g}):d.isArray(a[0])?0===a[0].length?A.resolve(null):A.resolve(a[0][0]):d.isImmutableArray(a[0])?0===a[0].length()?A.resolve(null):A.resolve(a[0].get(0)):null})},c.signatures.push({name:"first",min:"1",max:"1"}),c.functions.attachments=function(e,n){return c.standardFunctionAsync(e,n,(b,p,a)=>{d.pcCheck(a,1,2);var g=-1,
q=-1,m=null,l=!1;if(1<a.length)if(a[1]instanceof C)a[1].hasField("minsize")&&(g=d.toNumber(a[1].field("minsize"))),a[1].hasField("metadata")&&(l=d.toBoolean(a[1].field("metadata"))),a[1].hasField("maxsize")&&(q=d.toNumber(a[1].field("maxsize"))),a[1].hasField("types")&&(b=d.toStringArray(a[1].field("types"),!1),0<b.length&&(m=b));else if(null!==a[1])throw Error("Invalid Parameter");if(a[0]instanceof H){let f=a[0]._layer;f instanceof P&&(f=B.constructFeatureSet(f,e.spatialReference,["*"],!0,e.lrucache,
e.interceptor));return null===f||!1===d.isFeatureSet(f)?[]:f.load().then(()=>f.queryAttachments(a[0].field(f.objectIdField),g,q,m,l))}if(null===a[0])return[];throw Error("Invalid Parameter");})},c.signatures.push({name:"attachments",min:"1",max:"2"}),c.functions.featuresetbyrelationshipname=function(e,n){return c.standardFunctionAsync(e,n,(b,p,a)=>{d.pcCheck(a,2,4);const g=a[0],q=d.toString(a[1]);let m=d.defaultUndefined(a[2],null);const l=d.toBoolean(d.defaultUndefined(a[3],!0));null===m&&(m=["*"]);
if(!1===d.isArray(m))throw Error("Invalid Parameter");if(null===a[0])return null;if(!(a[0]instanceof H))throw Error("Invalid Parameter");b=g._layer;b instanceof P&&(b=B.constructFeatureSet(b,e.spatialReference,["*"],!0,e.lrucache,e.interceptor));return null===b||!1===d.isFeatureSet(b)?null:b.load().then(f=>{const k=f.relationshipMetaData().filter(x=>x.name===q);if(0===k.length)return null;if(void 0!==k[0].relationshipTableId&&null!==k[0].relationshipTableId&&-1<k[0].relationshipTableId)return B.constructFeatureSetFromRelationship(f,
k[0],g.field(f.objectIdField),f.spatialReference,m,l,e.lrucache,e.interceptor);let h=f.serviceUrl();if(!h)return null;h="/"===h.charAt(h.length-1)?h+k[0].relatedTableId.toString():h+"/"+k[0].relatedTableId.toString();return B.constructFeatureSetFromUrl(h,f.spatialReference,m,l,e.lrucache,e.interceptor).then(x=>x.load().then(()=>x.relationshipMetaData()).then(t=>{t=t.filter(y=>y.id===k[0].id);if(!1===g.hasField(k[0].keyField)||null===g.field(k[0].keyField))return f.getFeatureByObjectId(g.field(f.objectIdField),
[k[0].keyField]).then(y=>{if(y){const G=z.WhereClause.create(t[0].keyField+"\x3d @id",x.getFieldsIndex());G.parameters={id:y.attributes[k[0].keyField]};return x.filter(G)}return new ca({parentfeatureset:x})});const w=z.WhereClause.create(t[0].keyField+"\x3d @id",x.getFieldsIndex());w.parameters={id:g.field(k[0].keyField)};return x.filter(w)}))})})},c.signatures.push({name:"featuresetbyrelationshipname",min:"2",max:"4"}),c.functions.featuresetbyassociation=function(e,n){return c.standardFunctionAsync(e,
n,(b,p,a)=>{d.pcCheck(a,2,3);const g=a[0],q=d.toString(d.defaultUndefined(a[1],"")).toLowerCase(),m=d.isString(a[2])?d.toString(a[2]):null;if(null===a[0])return null;if(!(a[0]instanceof H))throw Error("Invalid Parameter");let l=g._layer;l instanceof P&&(l=B.constructFeatureSet(l,e.spatialReference,["*"],!0,e.lrucache,e.interceptor));return null===l||!1===d.isFeatureSet(l)?null:l.load().then(()=>{const f=l.serviceUrl();return B.constructAssociationMetaDataFeatureSetFromUrl(f,e.spatialReference)}).then(f=>
{var k=null,h=null;let x=!1;if(null!==m&&""!==m&&void 0!==m){for(var t of f.terminals)t.terminalName===m&&(h=t.terminalId);null===h&&(x=!0)}var w=f.associations.getFieldsIndex();t=w.get("TOGLOBALID").name;const y=w.get("FROMGLOBALID").name,G=w.get("TOTERMINALID").name,S=w.get("FROMTERMINALID").name,J=w.get("FROMNETWORKSOURCEID").name,K=w.get("TONETWORKSOURCEID").name;var E=w.get("ASSOCIATIONTYPE").name;const ha=w.get("ISCONTENTVISIBLE").name,ia=w.get("OBJECTID").name;for(var L of l.fields)if("global-id"===
L.type){k=g.field(L.name);break}let F=null;L=new v.SqlExpressionAdapted(new I({name:"percentalong",alias:"percentalong",type:"double"}),z.WhereClause.create("0",f.associations.getFieldsIndex()));let Z=new v.SqlExpressionAdapted(new I({name:"side",alias:"side",type:"string"}),z.WhereClause.create("''",f.associations.getFieldsIndex()));var u={};for(var D in f.lkp)u[D]=f.lkp[D].sourceId;D=new v.StringToCodeAdapted(new I({name:"classname",alias:"classname",type:"string"}),null,u);u="";switch(q){case "midspan":u=
`((${t}='${k}') OR ( ${y}='${k}')) AND (${E} IN (5))`;D.codefield=z.WhereClause.create(`CASE WHEN (${t}='${k}') THEN ${J} ELSE ${K} END`,f.associations.getFieldsIndex());h=N.cloneField(v.AdaptedFeatureSet.findField(f.associations.fields,y));h.name="globalid";h.alias="globalid";F=new v.SqlExpressionAdapted(h,z.WhereClause.create(`CASE WHEN (${y}='${k}') THEN ${t} ELSE ${y} END`,f.associations.getFieldsIndex()));L=4<=f.unVersion?new v.OriginalField(v.AdaptedFeatureSet.findField(f.associations.fields,
w.get("PERCENTALONG").name)):new v.SqlExpressionAdapted(new I({name:"percentalong",alias:"percentalong",type:"double"}),z.WhereClause.create("0",f.associations.getFieldsIndex()));break;case "junctionedge":u=`((${t}='${k}') OR ( ${y}='${k}')) AND (${E} IN (4,6))`;D.codefield=z.WhereClause.create(`CASE WHEN (${t}='${k}') THEN ${J} ELSE ${K} END`,f.associations.getFieldsIndex());h=N.cloneField(v.AdaptedFeatureSet.findField(f.associations.fields,y));h.name="globalid";h.alias="globalid";F=new v.SqlExpressionAdapted(h,
z.WhereClause.create(`CASE WHEN (${y}='${k}') THEN ${t} ELSE ${y} END`,f.associations.getFieldsIndex()));Z=new v.SqlExpressionAdapted(new I({name:"side",alias:"side",type:"string"}),z.WhereClause.create(`CASE WHEN (${E}=4) THEN 'from' ELSE 'to' END`,f.associations.getFieldsIndex()));break;case "connected":w=`${t}='@T'`;E=`${y}='@T'`;null!==h&&(w+=` AND ${G}=@A`,E+=` AND ${S}=@A`);u="(("+w+") OR ("+E+"))";u=d.multiReplace(u,"@T",k);w=d.multiReplace(w,"@T",k);null!==h&&(w=d.multiReplace(w,"@A",h.toString()),
u=d.multiReplace(u,"@A",h.toString()));D.codefield=z.WhereClause.create("CASE WHEN "+w+` THEN ${J} ELSE ${K} END`,f.associations.getFieldsIndex());k=N.cloneField(v.AdaptedFeatureSet.findField(f.associations.fields,y));k.name="globalid";k.alias="globalid";F=new v.SqlExpressionAdapted(k,z.WhereClause.create("CASE WHEN "+w+` THEN ${y} ELSE ${t} END`,f.associations.getFieldsIndex()));break;case "container":u=`${t}='${k}' AND ${E} = 2`,null!==h&&(u+=` AND ${G} = `+h.toString()),D.codefield=J,u="( "+u+
" )",F=new v.FieldRename(v.AdaptedFeatureSet.findField(f.associations.fields,y),"globalid","globalid");case "content":u=`(${y}='${k}' AND ${E} = 2)`;null!==h&&(u+=` AND ${S} = `+h.toString());D.codefield=K;u="( "+u+" )";F=new v.FieldRename(v.AdaptedFeatureSet.findField(f.associations.fields,t),"globalid","globalid");break;case "structure":u=`(${t}='${k}' AND ${E} = 3)`;null!==h&&(u+=` AND ${G} = `+h.toString());D.codefield=J;u="( "+u+" )";F=new v.FieldRename(v.AdaptedFeatureSet.findField(f.associations.fields,
y),"globalid","globalId");break;case "attached":u=`(${y}='${k}' AND ${E} = 3)`;null!==h&&(u+=` AND ${S} = `+h.toString());D.codefield=K;u="( "+u+" )";F=new v.FieldRename(v.AdaptedFeatureSet.findField(f.associations.fields,t),"globalid","globalId");break;default:throw Error("Invalid Parameter");}x&&(u="1 \x3c\x3e 1");return new v.AdaptedFeatureSet({parentfeatureset:f.associations,adaptedFields:[new v.OriginalField(v.AdaptedFeatureSet.findField(f.associations.fields,ia)),new v.OriginalField(v.AdaptedFeatureSet.findField(f.associations.fields,
ha)),F,Z,D,L],extraFilter:u?z.WhereClause.create(u,f.associations.getFieldsIndex()):null})})})},c.signatures.push({name:"featuresetbyassociation",min:"2",max:"6"}),c.functions.groupby=function(e,n){return c.standardFunctionAsync(e,n,(b,p,a)=>{d.pcCheck(a,3,3);return d.isFeatureSet(a[0])?a[0].load().then(g=>{const q=[],m=[];var l=!1,f=[];if(d.isString(a[1]))f.push(a[1]);else if(a[1]instanceof C)f.push(a[1]);else if(d.isArray(a[1]))f=a[1];else if(d.isImmutableArray(a[1]))f=a[1].toArray();else return c.failDefferred("Illegal Value: GroupBy");
for(var k of f)if(d.isString(k)){f=z.WhereClause.create(d.toString(k),g.getFieldsIndex());var h=!0===W.isSingleField(f)?d.toString(k):"%%%%FIELDNAME";q.push({name:h,expression:f});"%%%%FIELDNAME"===h&&(l=!0)}else if(k instanceof C){f=k.hasField("name")?k.field("name"):"%%%%FIELDNAME";h=k.hasField("expression")?k.field("expression"):"";"%%%%FIELDNAME"===f&&(l=!0);if(!f)return c.failDefferred("Illegal Value: GroupBy");q.push({name:f,expression:z.WhereClause.create(h?h:f,g.getFieldsIndex())})}else return c.failDefferred("Illegal Value: GroupBy");
f=[];if(d.isString(a[2]))f.push(a[2]);else if(d.isArray(a[2]))f=a[2];else if(d.isImmutableArray(a[2]))f=a[2].toArray();else if(a[2]instanceof C)f.push(a[2]);else return c.failDefferred("Illegal Value: GroupBy");for(const t of f)if(t instanceof C){k=t.hasField("name")?t.field("name"):"";f=t.hasField("statistic")?t.field("statistic"):"";h=t.hasField("expression")?t.field("expression"):"";if(!k||!f||!h)return c.failDefferred("Illegal Value: GroupBy");m.push({name:k,statistic:f.toLowerCase(),expression:z.WhereClause.create(h,
g.getFieldsIndex())})}else return c.failDefferred("Illegal Value: GroupBy");if(l){l={};for(const t of g.fields)l[t.name.toLowerCase()]=1;for(const t of q)"%%%%FIELDNAME"!==t.name&&(l[t.name.toLowerCase()]=1);for(const t of m)"%%%%FIELDNAME"!==t.name&&(l[t.name.toLowerCase()]=1);g=0;for(var x of q)if("%%%%FIELDNAME"===x.name){for(;1===l["field_"+g.toString()];)g++;l["field_"+g.toString()]=1;x.name="FIELD_"+g.toString()}}x=[];for(const t of q)x.push(Q(t.expression,c,e));for(const t of m)x.push(Q(t.expression,
c,e));return 0<x.length?A.all(x).then(()=>A.resolve(a[0].groupby(q,m))):A.resolve(a[0].groupby(q,m))}):c.failDefferred("Illegal Value: GroupBy")})},c.signatures.push({name:"groupby",min:"3",max:"3"}),c.functions.distinct=function(e,n){return c.standardFunctionAsync(e,n,(b,p,a)=>d.isFeatureSet(a[0])?(d.pcCheck(a,2,2),a[0].load().then(g=>{const q=[];var m=[];if(d.isString(a[1]))m.push(a[1]);else if(a[1]instanceof C)m.push(a[1]);else if(d.isArray(a[1]))m=a[1];else if(d.isImmutableArray(a[1]))m=a[1].toArray();
else return c.failDefferred("Illegal Value: GroupBy");var l=!1;for(const h of m)if(d.isString(h)){m=z.WhereClause.create(d.toString(h),g.getFieldsIndex());var f=!0===W.isSingleField(m)?d.toString(h):"%%%%FIELDNAME";q.push({name:f,expression:m});"%%%%FIELDNAME"===f&&(l=!0)}else if(h instanceof C){m=h.hasField("name")?h.field("name"):"%%%%FIELDNAME";f=h.hasField("expression")?h.field("expression"):"";"%%%%FIELDNAME"===m&&(l=!0);if(!m)return c.failDefferred("Illegal Value: GroupBy");q.push({name:m,expression:z.WhereClause.create(f?
f:m,g.getFieldsIndex())})}else return c.failDefferred("Illegal Value: GroupBy");if(l){l={};for(const h of g.fields)l[h.name.toLowerCase()]=1;for(const h of q)"%%%%FIELDNAME"!==h.name&&(l[h.name.toLowerCase()]=1);g=0;for(var k of q)if("%%%%FIELDNAME"===k.name){for(;1===l["field_"+g.toString()];)g++;l["field_"+g.toString()]=1;k.name="FIELD_"+g.toString()}}k=[];for(const h of q)k.push(Q(h.expression,c,e));return 0<k.length?A.all(k).then(()=>A.resolve(a[0].groupby(q,[]))):A.resolve(a[0].groupby(q,[]))})):
fa("distinct",b,p,a))})};Object.defineProperty(T,"__esModule",{value:!0})});