// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Promise ../../../../core/promiseUtils ../../../../core/workers/workers ../../../../core/accessorSupport/decorators/property ../../../../core/has ../../../../core/accessorSupport/ensureType ../../../../core/Logger ../../../../core/accessorSupport/decorators/subclass".split(" "),function(c,k,g,f,r,m,u,v,w,t){g=function(p){function l(b){b=p.call(this,b)||this;b._startupResolver=f.createResolver();b.isReady=
!1;return b}c._inheritsLoose(l,p);var d=l.prototype;d.initialize=function(){this._controller=f.createAbortController();this.addResolvingPromise(this._startWorker(this._controller.signal))};d.destroy=function(){this._controller.abort();this._connection&&this._connection.close()};d.startup=function(){var b=c._asyncToGenerator(function*(a,e,h,q){yield this.when();var n=this._controller.signal;n=Array.isArray(h.source)?{transferList:h.source,signal:n}:void 0;a=a.tileInfo.toJSON();yield this._connection.invoke("startup",
{service:h,config:e,tileInfo:a,tiles:q},n);this._startupResolver.resolve();this._set("isReady",!0)});return function(a,e,h,q){return b.apply(this,arguments)}}();d.updateTiles=function(){var b=c._asyncToGenerator(function*(a){yield this._startupResolver.promise;return f.ignoreAbortErrors(this._connection.invoke("updateTiles",a))});return function(a){return b.apply(this,arguments)}}();d.update=function(){var b=c._asyncToGenerator(function*(a){a={config:a};yield this._startupResolver.promise;return this._connection.invoke("update",
a)});return function(a){return b.apply(this,arguments)}}();d.applyUpdate=function(){var b=c._asyncToGenerator(function*(a){yield this._startupResolver.promise;return this._connection.invoke("applyUpdate",a)});return function(a){return b.apply(this,arguments)}}();d.setHighlight=function(){var b=c._asyncToGenerator(function*(a){yield this._startupResolver.promise;return f.ignoreAbortErrors(this._connection.invoke("controller.setHighlight",a))});return function(a){return b.apply(this,arguments)}}();
d.refresh=function(){var b=c._asyncToGenerator(function*(){yield this._startupResolver.promise;return f.ignoreAbortErrors(this._connection.invoke("controller.refresh"))});return function(){return b.apply(this,arguments)}}();d.querySummaryStatistics=function(){var b=c._asyncToGenerator(function*(a,e,h){yield this._startupResolver.promise;return this._connection.invoke("controller.querySummaryStatistics",{query:a.toJSON(),params:e},h)});return function(a,e,h){return b.apply(this,arguments)}}();d.queryFeatures=
function(){var b=c._asyncToGenerator(function*(a,e){yield this._startupResolver.promise;return this._connection.invoke("controller.queryFeatures",a.toJSON(),e)});return function(a,e){return b.apply(this,arguments)}}();d.queryObjectIds=function(){var b=c._asyncToGenerator(function*(a,e){yield this._startupResolver.promise;return this._connection.invoke("controller.queryObjectIds",a.toJSON(),e)});return function(a,e){return b.apply(this,arguments)}}();d.queryFeatureCount=function(){var b=c._asyncToGenerator(function*(a,
e){yield this._startupResolver.promise;return this._connection.invoke("controller.queryFeatureCount",a.toJSON(),e)});return function(a,e){return b.apply(this,arguments)}}();d.queryExtent=function(){var b=c._asyncToGenerator(function*(a,e){return this._connection.invoke("controller.queryExtent",a.toJSON(),e)});return function(a,e){return b.apply(this,arguments)}}();d.queryLatestObservations=function(){var b=c._asyncToGenerator(function*(a,e){yield this._startupResolver.promise;return this._connection.invoke("controller.queryLatestObservations",
a.toJSON(),e)});return function(a,e){return b.apply(this,arguments)}}();d.queryStatistics=function(){var b=c._asyncToGenerator(function*(a){yield this._startupResolver.promise;return this._connection.invoke("controller.queryStatistics",a)});return function(a){return b.apply(this,arguments)}}();d.getObjectId=function(){var b=c._asyncToGenerator(function*(a){yield this._startupResolver.promise;return this._connection.invoke("controller.getObjectId",a)});return function(a){return b.apply(this,arguments)}}();
d.getDisplayId=function(){var b=c._asyncToGenerator(function*(a){yield this._startupResolver.promise;return this._connection.invoke("controller.getDisplayId",a)});return function(a){return b.apply(this,arguments)}}();d.getFeature=function(){var b=c._asyncToGenerator(function*(a){yield this._startupResolver.promise;return this._connection.invoke("controller.getFeature",a)});return function(a){return b.apply(this,arguments)}}();d.getAggregate=function(){var b=c._asyncToGenerator(function*(a){yield this._startupResolver.promise;
return this._connection.invoke("controller.getAggregate",a)});return function(a){return b.apply(this,arguments)}}();d.getAggregates=function(){var b=c._asyncToGenerator(function*(){yield this._startupResolver.promise;return this._connection.invoke("controller.getAggregates")});return function(){return b.apply(this,arguments)}}();d.getAggregateValueRanges=function(){var b=c._asyncToGenerator(function*(){yield this._startupResolver.promise;return this._connection.invoke("controller.getAggregateValueRanges")});
return function(){return b.apply(this,arguments)}}();d.mapValidDisplayIds=function(){var b=c._asyncToGenerator(function*(a){yield this._startupResolver.promise;return this._connection.invoke("controller.mapValidDisplayIds",a)});return function(a){return b.apply(this,arguments)}}();d.onEdits=function(){var b=c._asyncToGenerator(function*(a){yield this._startupResolver.promise;return f.ignoreAbortErrors(this._connection.invoke("controller.onEdits",a))});return function(a){return b.apply(this,arguments)}}();
d.enableEvent=function(){var b=c._asyncToGenerator(function*(a,e){yield this._startupResolver.promise;return f.ignoreAbortErrors(this._connection.invoke("controller.enableEvent",{name:a,value:e}))});return function(a,e){return b.apply(this,arguments)}}();d._startWorker=function(){var b=c._asyncToGenerator(function*(a){try{this._connection=yield r.open("Pipeline",{client:this.client,strategy:"dedicated",signal:a})}catch(e){f.throwIfNotAbortError(e)}});return function(a){return b.apply(this,arguments)}}();
c._createClass(l,[{key:"tileRenderer",set:function(b){this.client.tileRenderer=b}},{key:"closed",get:function(){return this._connection.closed}}]);return l}(g.EsriPromise);k.__decorate([m.property()],g.prototype,"isReady",void 0);k.__decorate([m.property()],g.prototype,"client",void 0);k.__decorate([m.property()],g.prototype,"tileRenderer",null);return g=k.__decorate([t.subclass("esri.views.2d.layers.support.FeatureLayerProxy")],g)});