// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/Accessor ../core/Collection ../core/HandleOwner ../core/Logger ../core/maybe ../core/watchUtils ../core/accessorSupport/decorators/property ../core/has ../core/accessorSupport/ensureType ../core/accessorSupport/decorators/subclass ./input/InputManager ./input/ViewEvents ./interactive/interactiveToolUtils ./interactive/ToolViewManagerManipulatorState".split(" "),function(p,h,t,q,d,u,e,v,k,A,B,w,x,y,m,z){const n=u.getLogger("esri.views.ToolViewManager");
d=function(r){function l(a){var b=r.call(this,a)||this;b._manipulatorState=new z;b.tools=new q;b.cursor=null;b._forEachTool=c=>{for(const g of b.tools.items)if(c(g))break};return b}p._inheritsLoose(l,r);var f=l.prototype;f.initialize=function(){this.handles.add([this.view.on(y.eventTypes,a=>{this._handleInputEvent(a)},x.ViewEventPriorities.TOOL),...m.getToolAttachDetachHandles(this.tools),this.tools.on("before-add",a=>{const b=a.item;if(null==b||this.tools.includes(b))n.warn("Tool is either already in the list of tools or tool is `null`. Not adding tool."),
a.preventDefault()}),this.tools.on("before-remove",({item:a})=>{this._manipulatorState.clearPointers(a,this._forEachTool)}),this.tools.on("change",()=>{this._refreshToolWatchers()})])};f.destroy=function(){this._forEachTool(a=>a.destroy())};f.attach=function(){this._forEachTool(a=>a.attach());"3d"===this.view.type?this.handles.add([this.view.state.watch("camera",()=>{this._forEachManipulator(a=>{if(null!=a.onViewChange)a.onViewChange()})}),this.view.elevationProvider.on("elevation-change",a=>{this._forEachManipulator(b=>
{if(null!=b.onElevationChange)b.onElevationChange(a)})})],"manipulators"):this.handles.add(this.view.watch("extent",()=>{this._forEachManipulator(a=>{if(null!=a.onViewChange)a.onViewChange()})}))};f.detach=function(){e.isSome(this.activeTool)&&(this.activeTool=null);this._forEachTool(a=>{a.detach();a.destroy()});this.tools.removeAll();this.handles.remove("manipulators")};f._forEachManipulator=function(a){this._forEachTool(b=>{b.manipulators&&b.manipulators.forEach(({manipulator:c})=>a(c,b))})};f._handleInputEvent=
function(a){let b=!1;const c={...a,stopPropagation:()=>{b=!0;a.stopPropagation()}};e.isSome(this.activeTool)?this.activeTool.handleInputEvent&&this.activeTool.handleInputEvent(c):this._forEachTool(g=>{!b&&g.attached&&g.visible&&g.handleInputEvent(c)});!b&&"key-down"===a.type&&"Escape"===a.key&&this.activeTool&&(a.stopPropagation(),this.activeTool=null);this._manipulatorState.handleInputEvent(c,{forEachTool:this._forEachTool,activeTool:this.activeTool,setActiveTool:g=>{this.activeTool=g},view:this.view});
!b&&e.isSome(this.activeTool)&&this.activeTool.handleInputEventAfter(c);this._manipulatorState.handleHoverEvent(c,this._forEachTool);this._updateCursor()};f._refreshToolWatchers=function(){this.handles.remove("tools");this._forEachTool(a=>{if(a instanceof t){const b=v.watch(a,["cursor","visible","editable"],()=>{m.areToolManipulatorsEditable(a)||this._manipulatorState.clearPointers(a,this._forEachTool);this._updateCursor()});this.handles.add(b,"tools")}a.manipulators&&this.handles.add(a.manipulators.on("change",
b=>{b.removed.forEach(({id:c})=>{this._manipulatorState.clearPointers(a,this._forEachTool,!0,c)});this._manipulatorState.updateHoveredStateFromKnownPointers(this._forEachTool);this._updateCursor()}),"tools")});this._manipulatorState.updateHoveredStateFromKnownPointers(this._forEachTool);this._updateCursor()};f._updateCursor=function(){let a=this._manipulatorState.cursor;this._forEachTool(b=>e.isSome(b.cursor)&&b.visible?(a=b.cursor,!0):!1);this._get("cursor")!==a&&this._set("cursor",a)};f._removeIncompleteTools=
function(a){this.tools.filter(b=>(e.isNone(a)||b!==a)&&!b.completed).forEach(b=>{this.tools.remove(b);b.destroy()})};p._createClass(l,[{key:"activeTool",set:function(a){if(e.isSome(a)&&!this.view.ready)n.error("Cannot set active tool while view is not ready.");else if(a===this.activeTool)n.warn("Tool is already active - ignoring activation request.");else{e.isSome(this.activeTool)&&this.activeTool.deactivate();e.isSome(a)&&a.activate();this._set("activeTool",a);this._removeIncompleteTools(a);a=e.isNone(this.activeTool);
for(const b of this.tools){b.setEditableFlag(1,a||b===this.activeTool);const c=m.areToolManipulatorsEditable(b);!a&&c||this._manipulatorState.clearPointers(b,this._forEachTool,!c)}this._updateCursor()}}},{key:"updating",get:function(){return this.updatingHandles.updating||this.tools.some(a=>a.updating)}}]);return l}(d.HandleOwner);h.__decorate([k.property({constructOnly:!0,nonNullable:!0})],d.prototype,"view",void 0);h.__decorate([k.property({value:null})],d.prototype,"activeTool",null);h.__decorate([k.property({readOnly:!0,
type:q})],d.prototype,"tools",void 0);h.__decorate([k.property({readOnly:!0})],d.prototype,"cursor",void 0);h.__decorate([k.property({readOnly:!0})],d.prototype,"updating",null);return d=h.__decorate([w.subclass("esri.views.ToolViewManager")],d)});