// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define(["exports","../../../core/maybe","../PixelBlock"],function(x,L,D){function z(a){return L.isSome(a)&&"esri.layers.support.PixelBlock"===a.declaredClass&&a.pixels&&0<a.pixels.length}function U(a,c){a=Math.min(Math.max(a,-100),100);c=Math.min(Math.max(c,-100),100);let b,e;const h=new Uint8Array(256);for(b=0;256>b;b++)0<a&&100>a?e=(200*b-25500+510*c)/(2*(100-a))+128:0>=a&&-100<a?e=(200*b-25500+510*c)*(100+a)/2E4+128:100===a?(e=200*b-25500+256*(100-a)+510*c,e=0<e?255:0):-100===a&&(e=128),h[b]=255<
e?255:0>e?0:e;return h}function V(a,c,b,e,h,k,m,l){return{xmin:h<=b*a?0:h<b*a+a?h-b*a:a,ymin:k<=e*c?0:k<e*c+c?k-e*c:c,xmax:h+m<=b*a?0:h+m<b*a+a?h+m-b*a:a,ymax:k+l<=e*c?0:k+l<e*c+c?k+l-e*c:c}}function P(a,c,b,e,h,k){const {width:m,height:l}=b.block,{x:d,y:g}=b.offset,{width:f,height:p}=b.mosaic;b=V(m,l,e,h,d,g,f,p);let q=0;var n=0;if(k){var u=k.hasGCSSShiftTransform?360:k.halfWorldWidth,t=m*k.resolutionX,r=k.startX+e*t;t=r+t;r<u&&t>u?n=k.rightPadding:r>=u&&(q=k.leftMargin-k.rightPadding,n=0)}b.xmax-=
n;if("number"===typeof c)for(k=b.ymin;k<b.ymax;k++)for(n=(h*l+k-g)*f+(e*m-d)+q,u=b.xmin;u<b.xmax;u++)a[n+u]=c;else for(k=b.ymin;k<b.ymax;k++)for(n=(h*l+k-g)*f+(e*m-d)+q,u=k*m,r=b.xmin;r<b.xmax;r++)a[n+r]=c[u+r]}function W(a,c,b,e,h){var k=a.filter(t=>z(t))[0];if(L.isNone(k))return null;const m=e?e.width:c.width,l=e?e.height:c.height;var d=k.width,g=k.height;const f=c.width/d,p=c.height/g;c={offset:b||{x:0,y:0},mosaic:e||c,block:{width:d,height:g}};b=k.pixelType;e=D.getPixelArrayConstructor(b);d=k.pixels.length;
k=[];for(var q=0;q<d;q++){g=new e(m*l);for(let t=0;t<p;t++)for(let r=0;r<f;r++){var n=a[t*f+r];z(n)&&(n=n.pixels[q],P(g,n,c,r,t,h))}k.push(g)}let u;if(a.some(t=>L.isNone(t)||t.mask&&0<t.mask.length))for(u=new Uint8Array(m*l),e=0;e<p;e++)for(d=0;d<f;d++)g=a[e*f+d],(q=L.isSome(g)?g.mask:null)?P(u,q,c,d,e,h):g?P(u,1,c,d,e,h):P(u,0,c,d,e,h);a=new D({width:m,height:l,pixels:k,pixelType:b,mask:u});a.updateStatistics();return a}function X(a){if(!z(a))return null;const c=a.clone(),{width:b,height:e,pixels:h,
mask:k}=a;var m=h[0];a=c.pixels[0];for(let g=2;g<e-1;g++){const f=new Map;for(var l=g-2;l<g+2;l++)for(var d=0;4>d;d++){const p=l*b+d;M(f,m[p],k?k[p]:1)}a[g*b]=Y(f);a[g*b+1]=a[g*b+2]=a[g*b];for(l=3;l<b-1;l++)d=(g-2)*b+l+1,M(f,m[d],k?k[d]:1),d=(g-1)*b+l+1,M(f,m[d],k?k[d]:1),d=g*b+l+1,M(f,m[d],k?k[d]:1),d=(g+1)*b+l+1,M(f,m[d],k?k[d]:1),d=(g-2)*b+l-3,Q(f,m[d],k?k[d]:1),d=(g-1)*b+l-3,Q(f,m[d],k?k[d]:1),d=g*b+l-3,Q(f,m[d],k?k[d]:1),d=(g+1)*b+l-3,Q(f,m[d],k?k[d]:1),a[g*b+l]=Y(f);a[g*b+l+1]=a[g*b+l]}for(m=
0;m<b;m++)a[m]=a[b+m]=a[2*b+m],a[(e-1)*b+m]=a[(e-2)*b+m];c.updateStatistics();return c}function Y(a){if(0===a.size)return 0;let c=0,b=-1,e=0;const h=a.keys();let k=h.next();for(;!k.done;)e=a.get(k.value),e>c&&(b=k.value,c=e),k=h.next();return b}function Q(a,c,b){0!==b&&(b=a.get(c),1===b?a.delete(c):a.set(c,b-1))}function M(a,c,b){0!==b&&a.set(c,a.has(c)?a.get(c)+1:1)}function Z(a,c,b){let {x:e,y:h}=c;const {width:k,height:m}=b;if(0===e&&0===h&&m===a.height&&k===a.width)return a;const {width:l,height:d}=
a;c=Math.max(0,h);const g=Math.max(0,e),f=Math.min(e+k,l),p=Math.min(h+m,d);if(0>f||0>p||!z(a))return null;e=Math.max(0,-e);h=Math.max(0,-h);const {pixels:q,mask:n}=a;var u=k*m,t=q.length;const r=[];for(var v=0;v<t;v++){var y=q[v],w=D.createEmptyBand(a.pixelType,u);for(let A=c;A<p;A++){const H=A*l;let I=(A+h-c)*k+e;for(let E=g;E<f;E++)w[I++]=y[H+E]}r.push(w)}u=new Uint8Array(u);for(t=c;t<p;t++)for(v=t*l,y=(t+h-c)*k+e,w=g;w<f;w++)u[y++]=n?n[v+w]:1;a=new D({width:b.width,height:b.height,pixelType:a.pixelType,
pixels:r,mask:u});a.updateStatistics();return a}function aa(a,c=!0){if(!z(a))return null;const {pixels:b,width:e,height:h,mask:k,pixelType:m}=a;a=[];const l=Math.round(e/2),d=Math.round(h/2),g=h-1,f=e-1;for(var p=0;p<b.length;p++){var q=b[p],n=D.createEmptyBand(m,l*d),u=0;for(var t=0;t<h;t+=2)for(var r=0;r<e;r+=2){var v=q[t*e+r];if(c){var y=r===f?v:q[t*e+r+1];const w=t===g?v:q[t*e+r+e],A=r===f?w:t===g?y:q[t*e+r+e+1];n[u++]=(v+y+w+A)/4}else n[u++]=v}a.push(n)}p=null;if(k)for(p=new Uint8Array(l*d),
q=0,n=0;n<h;n+=2)for(u=0;u<e;u+=2)t=k[n*e+u],c?(r=u===f?t:k[n*e+u+1],v=n===g?t:k[n*e+u+e],y=u===f?v:n===g?r:k[n*e+u+e+1],p[q++]=t*r*v*y?1:0):p[q++]=t;return new D({width:l,height:d,pixelType:m,pixels:a,mask:p})}x.approximateTransform=function(a,c,b,e,h="nearest"){if(!z(a))return null;"majority"===h&&(a=X(a));const {pixels:k,mask:m,pixelType:l}=a,d=a.width;var g=a.height;a=D.getPixelArrayConstructor(l);var f=k.length;const {width:p,height:q}=c;c=e.cols;var n=e.rows;const u=Math.ceil(p/c-.1/c),t=Math.ceil(q/
n-.1/n);e=!1;for(var r=0;r<b.length;r+=3)-1===b[r]&&-1===b[r+1]&&-1===b[r+2]&&(e=!0);let v,y,w,A,H,I;const E=u*c;r=E*t*n;const N=new Float32Array(r),O=new Float32Array(r);r=0;let J,K;const R="majority"===h?0:.5;for(let F=0;F<t;F++)for(let G=0;G<u;G++){v=12*(F*u+G);h=b[v];y=b[v+1];w=b[v+2];A=b[v+3];H=b[v+4];I=b[v+5];for(var B=0;B<n;B++){r=(F*n+B)*E+G*c;K=(B+.5)/n;for(var C=0;C<B;C++)J=(C+.5)/c,N[r+C]=Math.round((h*J+y*K+w)*d-R),O[r+C]=Math.round((A*J+H*K+I)*g-R)}v+=6;h=b[v];y=b[v+1];w=b[v+2];A=b[v+
3];H=b[v+4];I=b[v+5];for(B=0;B<n;B++)for(r=(F*n+B)*E+G*c,K=(B+.5)/n,C=B;C<c;C++)J=(C+.5)/c,N[r+C]=Math.round((h*J+y*K+w)*d-R),O[r+C]=Math.round((A*J+H*K+I)*g-R)}b=(F,G)=>{for(let S=0;S<q;S++){v=S*E;for(let T=0;T<p;T++)F[S*p+T]=0>N[v]||0>O[v]?0:G[N[v]+O[v]*d],v++}};g=[];for(n=0;n<f;n++)c=new a(p*q),b(c,k[n]),g.push(c);a=new D({width:p,height:q,pixelType:l,pixels:g});if(m)a.mask=new Uint8Array(p*q),b(a.mask,m);else if(e)for(a.mask=new Uint8Array(p*q),f=0;f<p*q;f++)a.mask[f]=0>N[f]||0>O[f]?0:1;a.updateStatistics();
return a};x.clip=Z;x.colorize=function(a,c){if(!z(a)||!c&&(c.indexedColormap||c.indexed2DColormap))return a;const b=a.clone();var e=b.pixels;let h=b.mask;const k=b.width*b.height;if(1!==e.length)return a;const {indexedColormap:m,indexed2DColormap:l,offset:d,alphaSpecified:g}=c;c=m.length-1;a=0;e=e[0];const f=new Uint8Array(e.length),p=new Uint8Array(e.length),q=new Uint8Array(e.length);let n=0;if(m)if(h)for(a=0;a<k;a++)h[a]&&(n=4*(e[a]-d),n<d||n>c?h[a]=0:(f[a]=m[n],p[a]=m[n+1],q[a]=m[n+2],h[a]=m[n+
3]));else{h=new Uint8Array(k);for(a=0;a<k;a++)n=4*(e[a]-d),n<d||n>c?h[a]=0:(f[a]=m[n],p[a]=m[n+1],q[a]=m[n+2],h[a]=m[n+3]);b.mask=h}else if(h)for(a=0;a<k;a++)h[a]&&(c=l[e[a]],f[a]=c[0],p[a]=c[1],q[a]=c[2],h[a]=c[3]);else{h=new Uint8Array(k);for(a=0;a<k;a++)c=l[e[a]],f[a]=c[0],p[a]=c[1],q[a]=c[2],h[a]=c[3];b.mask=h}b.pixels=[f,p,q];b.statistics=null;b.pixelType="u8";b.maskIsAlpha=g;return b};x.createColormapLUT=function(a){if(a){var c=a.colormap;if(c&&0!==c.length){c=c.sort((g,f)=>g[0]-f[0]);var b=
0;0>c[0][0]&&(b=c[0][0]);var e=Math.max(256,c[c.length-1][0]-b+1),h=new Uint8Array(4*e),k=[],m=0,l=0,d=5===c[0].length;if(65536<e)return c.forEach(g=>{k[g[0]-b]=d?g.slice(1):g.slice(1).concat([255])}),{indexed2DColormap:k,offset:b,alphaSpecified:d};if(a.fillUnspecified)for(a=c[l],m=a[0]-b;m<e;m++)h[4*m]=a[1],h[4*m+1]=a[2],h[4*m+2]=a[3],h[4*m+3]=d?a[4]:255,m===a[0]-b&&(a=l===c.length-1?a:c[++l]);else for(m=0;m<c.length;m++)a=c[m],l=4*(a[0]-b),h[l]=a[1],h[l+1]=a[2],h[l+2]=a[3],h[l+3]=d?a[4]:255;return{indexedColormap:h,
offset:b,alphaSpecified:d}}}};x.createContrastBrightnessLUT=U;x.createHistogramEqualizationLUT=function(a,c=256){c=Math.min(c,256);const {size:b,counts:e}=a;a=new Uint8Array(b);var h=e.reduce((g,f)=>g+f/c,0);let k=0;var m=0;let l=0,d=h;for(let g=0;g<b;g++)if(l+=e[g],!(g<b-1&&l+e[g+1]<d)){for(;k<c-1&&d<l;)k++,d+=h;for(;m<=g;m++)a[m]=k;m=g+1}for(h=m;h<b;h++)a[h]=c-1;return a};x.createStretchLUT=function(a){const {minCutOff:c,maxCutOff:b,gamma:e,pixelType:h}=a,k=a.outMin||0,m=a.outMax||255;if(-1===["u8",
"u16","s8","s16"].indexOf(h))return null;const l=c.length;let d;let g=0;"s8"===h?g=-127:"s16"===h&&(g=-32767);let f=256;-1<["u16","s16"].indexOf(h)&&(f=65536);const p=[],q=m-k;for(d=0;d<l;d++)p[d]=b[d]-c[d];var n=e&&e.length>=l;const u=[];if(n)for(d=0;d<l;d++)u[d]=1<e[d]?2<e[d]?6.5+(e[d]-2)**2.5:6.5+100*(2-e[d])**4:1;let t;const r=[];let v,y,w;if(n)for(d=0;d<l;d++){w=[];for(n=0;n<f;n++)v=n+g,t=(v-c[d])/p[d],y=1,1<e[d]&&(y-=(1/q)**(t*u[d])),w[n]=v<b[d]&&v>c[d]?Math.floor(y*q*t**(1/e[d]))+k:v>=b[d]?
m:k;r[d]=w}else for(d=0;d<l;d++){w=[];for(n=0;n<f;n++)v=n+g,w[n]=v<=c[d]?k:v>=b[d]?m:Math.floor((v-c[d])/p[d]*q)+k;r[d]=w}if(null!=a.contrastOffset)for(a=U(a.contrastOffset,a.brightnessOffset),d=0;d<l;d++)for(w=r[d],n=0;n<f;n++)w[n]=a[w[n]];return{lut:r,offset:g}};x.estimateStatisticsFromHistograms=function(a){const c=[];for(let k=0;k<a.length;k++){const {min:m,max:l,size:d,counts:g}=a[k];let f=0;var b=0;for(var e=0;e<d;e++)f+=g[e],b+=e*g[e];b/=f;e=0;for(var h=0;h<d;h++)e+=g[h]*(h-b)**2;h=(l-m)/d;
c.push({min:m,max:l,avg:(b+.5)*h+m,stddev:Math.sqrt(e/(f-1))*h})}return c};x.estimateStatisticsHistograms=function(a){if(!z(a))return null;a.statistics||a.updateStatistics();const {pixels:c,mask:b,pixelType:e,statistics:h}=a;a=a.width*a.height;const k=c.length;let m,l;let d;var g;const f=[],p=[];for(d=0;d<k;d++){var q=new Uint32Array(256);var n=c[d];if("u8"===e)if(m=-.5,l=255.5,b)for(g=0;g<a;g++)b[g]&&q[n[g]]++;else for(g=0;g<a;g++)q[n[g]]++;else{m=h[d].minValue;l=h[d].maxValue;var u=(l-m)/256;var t=
new Uint32Array(257);if(b)for(g=0;g<a;g++)b[g]&&t[Math.floor((n[g]-m)/u)]++;else for(g=0;g<a;g++)t[Math.floor((n[g]-m)/u)]++;for(g=0;255>g;g++)q[g]=t[g];q[255]=t[255]+t[256]}f.push({min:m,max:l,size:256,counts:q});for(g=n=t=u=0;256>g;g++)u+=q[g],t+=g*q[g];t/=u;for(g=0;256>g;g++)n+=q[g]*(g-t)**2;q=Math.sqrt(n/(u-1));u=(l-m)/256;g=(t+.5)*u+m;q*=u;p.push({min:m,max:l,avg:g,stddev:q})}return{statistics:p,histograms:f}};x.extractBands=function(a,c){if(null==c||!c.length||!z(a))return a;const b=a.pixels.length;
return c&&c.some(e=>e>=b)||1===b&&1===c.length&&0===c[0]||b===c.length&&!c.some((e,h)=>e!==h)?a:new D({pixelType:a.pixelType,width:a.width,height:a.height,mask:a.mask,validPixelCount:a.validPixelCount,maskIsAlpha:a.maskIsAlpha,pixels:c.map(e=>a.pixels[e]),statistics:a.statistics&&c.map(e=>a.statistics[e])})};x.getClipBounds=V;x.isValidPixelBlock=z;x.lookupPixels=function(a,c){if(!z(a))return null;const {pixels:b,mask:e}=a,h=a.width*a.height,k=b.length;let m=c.lut;({offset:c}=c);let l,d;m&&1===m[0].length&&
(m=b.map(()=>m));const g=[];let f,p,q;if(c)if(null==e)for(l=0;l<k;l++){f=b[l];p=m[l];q=new Uint8Array(h);for(d=0;d<h;d++)q[d]=p[f[d]-c];g.push(q)}else for(l=0;l<k;l++){f=b[l];p=m[l];q=new Uint8Array(h);for(d=0;d<h;d++)e[d]&&(q[d]=p[f[d]-c]);g.push(q)}else if(null==e)for(l=0;l<k;l++){f=b[l];p=m[l];q=new Uint8Array(h);for(d=0;d<h;d++)q[d]=p[f[d]];g.push(q)}else for(l=0;l<k;l++){f=b[l];p=m[l];q=new Uint8Array(h);for(d=0;d<h;d++)e[d]&&(q[d]=p[f[d]]);g.push(q)}a=new D({width:a.width,height:a.height,pixels:g,
mask:e,pixelType:"u8"});a.updateStatistics();return a};x.mosaic=W;x.mosaicPixelData=function(a,c){if(!a||0===a.length)return null;var b=a.filter(p=>p.pixelBlock)[0];if(!b||L.isNone(b.pixelBlock))return null;var e=(b.extent.xmax-b.extent.xmin)/b.pixelBlock.width;const h=(b.extent.ymax-b.extent.ymin)/b.pixelBlock.height,k=.01*Math.min(e,h),m=a.sort((p,q)=>Math.abs(p.extent.ymax-q.extent.ymax)>k?q.extent.ymax-p.extent.ymax:Math.abs(p.extent.xmin-q.extent.xmin)>k?p.extent.xmin-q.extent.xmin:0);var l=
Math.min.apply(null,m.map(p=>p.extent.xmin));const d=Math.min.apply(null,m.map(p=>p.extent.ymin)),g=Math.max.apply(null,m.map(p=>p.extent.xmax)),f=Math.max.apply(null,m.map(p=>p.extent.ymax));a={x:Math.round((c.xmin-l)/e),y:Math.round((f-c.ymax)/h)};l={width:Math.round((g-l)/e),height:Math.round((f-d)/h)};e={width:Math.round((c.xmax-c.xmin)/e),height:Math.round((c.ymax-c.ymin)/h)};if(Math.round(l.width/b.pixelBlock.width)*Math.round(l.height/b.pixelBlock.height)!==m.length||0>a.x||0>a.y||l.width<
e.width||l.height<e.height)return null;b=m.map(p=>p.pixelBlock);b=W(b,l,a,e);return{extent:c,pixelBlock:b}};x.remapColor=function(a,c){if(!z(a))return null;a=a.clone();var {pixels:b}=a;const e=a.width*a.height,h=c.length,k=Math.floor(h/2),m=c[Math.floor(k)];b=b[0];let l,d,g,f,p,q,n=!1;const u=new Uint8Array(e),t=new Uint8Array(e),r=new Uint8Array(e);let v=a.mask;const y=4===c[0].mappedColor.length;v||(v=new Uint8Array(e),v.fill(y?255:1),a.mask=v);for(p=0;p<e;p++)if(v[p]){l=b[p];n=!1;q=k;d=m;g=0;for(f=
h-1;1<f-g;){if(l===d.value){n=!0;break}l>d.value?g=q:f=q;q=Math.floor((g+f)/2);d=c[Math.floor(q)]}n||(l===c[g].value?(d=c[g],n=!0):l===c[f].value?(d=c[f],n=!0):l<c[g].value?(n=!1,d=null):l>c[g].value&&(l<c[f].value?(d=c[g],n=!0):f===h-1?(n=!1,d=null):(d=c[f],n=!0)));n?(u[p]=d.mappedColor[0],t[p]=d.mappedColor[1],r[p]=d.mappedColor[2],v[p]=d.mappedColor[3]):u[p]=t[p]=r[p]=v[p]=0}a.pixels=[u,t,r];a.mask=v;a.pixelType="u8";a.maskIsAlpha=y;return a};x.resampleByMajority=X;x.setValidBoundary=function(a,
c,b){if(!z(a))return null;const {width:e,height:h}=a,k=c.x;c=c.y;const m=b.width+k;b=b.height+c;if(0>k||0>c||m>e||b>h||0===k&&0===c&&m===e&&b===h)return a;a.mask||(a.mask=new Uint8Array(e*h));const l=a.mask;for(let d=0;d<h;d++){const g=d*e;for(let f=0;f<e;f++)l[g+f]=d<c||d>=b||f<k||f>=m?0:1}a.updateStatistics();return a};x.split=function(a,c,b){if(!z(a))return null;const {width:e,height:h}=c;let {width:k,height:m}=a;const l=new Map,d={x:0,y:0};b=null==b?1:1+b;for(let g=0;g<b;g++){const f=Math.ceil(k/
e),p=Math.ceil(m/h);for(let q=0;q<p;q++){d.y=q*h;for(let n=0;n<f;n++){d.x=n*e;const u=Z(a,d,c);l.set(`${g}/${q}/${n}`,u)}}g<b-1&&(a=aa(a));k=Math.round(k/2);m=Math.round(m/2)}return l};x.stretch=function(a,c){if(!z(a))return null;a=a.clone();const {pixels:b,mask:e}=a,{minCutOff:h,maxCutOff:k,gamma:m}=c,l=c.outMin||0;c=c.outMax||255;const d=a.width*a.height,g=b.length;let f;let p,q,n;const u=c-l,t=[];for(f=0;f<g;f++)t[f]=k[f]-h[f];var r=m&&m.length>=g;const v=[];if(r)for(f=0;f<g;f++)v[f]=1<m[f]?2<
m[f]?6.5+(m[f]-2)**2.5:6.5+100*(2-m[f])**4:1;if(r)if(null!=e)for(r=0;r<d;r++){if(e[r])for(f=0;f<g;f++)p=b[f][r],n=(p-h[f])/t[f],q=1,1<m[f]&&(q-=(1/u)**(n*v[f])),b[f][r]=p<k[f]&&p>h[f]?Math.floor(q*u*n**(1/m[f]))+l:p>=k[f]?c:l}else for(r=0;r<d;r++)for(f=0;f<g;f++)p=b[f][r],n=(p-h[f])/t[f],q=1,1<m[f]&&(q-=(1/u)**(n*v[f])),b[f][r]=p<k[f]&&p>h[f]?Math.floor(q*u*n**(1/m[f]))+l:p>=k[f]?c:l;else if(null!=e)for(r=0;r<d;r++){if(e[r])for(f=0;f<g;f++)p=b[f][r],b[f][r]=p<k[f]&&p>h[f]?Math.floor((p-h[f])/t[f]*
u)+l:p>=k[f]?c:l}else for(r=0;r<d;r++)for(f=0;f<g;f++)p=b[f][r],b[f][r]=p<k[f]&&p>h[f]?Math.floor((p-h[f])/t[f]*u)+l:p>=k[f]?c:l;a.pixelType="u8";a.updateStatistics();return a};Object.defineProperty(x,"__esModule",{value:!0})});