// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Evented ../../../core/HandleOwner ../../../core/watchUtils ../../../core/accessorSupport/decorators/property ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/Logger ../../../core/accessorSupport/decorators/subclass ./support/ButtonMenu ../../support/widgetUtils".split(" "),function(p,e,d,u,v,f,z,A,B,w,x,y){d=function(r){function q(b){var a=r.call(this,b)||this;a._menuContainer=null;a.activeRowIndex=
null;a.autoWidth=!1;a.cellValueFormatFunction=({value:c})=>y.renderingSanitizer.sanitize(c);a.flexGrow=1;a.footerRenderFunction=null;a.frozen=!1;a.grid=null;a.header=null;a.headerRenderFunction=c=>{const {root:h}=c,{header:g,headerMenuEnabled:m,path:k,sortable:n}=p._assertThisInitialized(a);a.removeCellContent(h);n?(a.headerSorterRenderFunction(c),m&&a.headerMenuRenderFunction(c)):(m&&a.headerMenuRenderFunction(c),c=g||k,h.innerHTML!==c&&(h.innerHTML=c))};a.headerMenuRenderFunction=({root:c})=>{var h,
g;(null==(h=a.menu)?0:null==(g=h.items)?0:g.length)&&c.appendChild(a._menuContainer)};a.headerSorterRenderFunction=({root:c})=>{var h;const {header:g,path:m,sortElement:k}=p._assertThisInitialized(a),n=g||m;k?(k.innerHTML!==n&&k.setAttribute("innerHTML",n),c.appendChild(k),c=null==(h=a.grid)?void 0:h.getSlotElementByName(c.slot),(h=null==c?void 0:c.parentElement)&&!h.onkeydown&&(h.onkeydown=({key:t})=>{"Enter"!==t&&"Spacebar"!==t||k.click()})):c.innerHTML=n};a.hidden=!1;a.headerMenuEnabled=!0;a.menu=
null;a.menuConfig=null;a.messages=null;a.messagesCommon=null;a.renderFunction=({root:c,column:h,rowData:g})=>{const m=a.getCellValue(h,g);h=a.cellValueFormatFunction({column:h,rowData:g,value:m});c.innerHTML!==h&&(c.innerHTML=h)};a.resizable=!0;a.sortable=!0;a.sortElement=null;a.textAlign="start";a.width=200;return a}p._inheritsLoose(q,r);var l=q.prototype;l.initialize=function(){const {messages:b,path:a}=this;this._set("sortElement",this.createSortElement());this.sortElement.setAttribute("path",
a);this._menuContainer=document.createElement("div");this._menuContainer.classList.add("esri-column__menu-container");this.menu=new x({label:null==b?void 0:b.options,iconClass:"esri-icon-handle-horizontal",...this.menuConfig});this.menu.container=this._menuContainer;this.menu.set("items",this.getMenuItems());this.handles.add([v.watch(this,"hidden",()=>{var c;return null==(c=this.menu)?void 0:c.set("open",!1)})])};l.destroy=function(){var b;null==(b=this.menu)?void 0:b.destroy()};l.getMenuItems=function(){const {menuConfig:b,
sortable:a}=this,c=null==b?void 0:b.items,h=this.getSortMenuItems(),g=[];a&&g.push(...h);(null==c?0:c.length)&&g.push(...c);return g.length?g:null};l.getSortMenuItems=function(){const {messages:b}=this;return[{selected:"asc"===this.direction,iconClass:"esri-icon-arrow-up",label:null==b?void 0:b.sortAsc,autoCloseMenu:!0,clickFunction:()=>this.set("direction","asc"!==this.direction?"asc":null)},{selected:"desc"===this.direction,iconClass:"esri-icon-arrow-down",label:null==b?void 0:b.sortDesc,autoCloseMenu:!0,
clickFunction:()=>this.set("direction","desc"!==this.direction?"desc":null)}]};l.getCellValue=function(b,a){var c;return null!=(c=null==a?void 0:a.item[null==b?void 0:b.path])?c:""};l.createSortElement=function(){const {direction:b,header:a,path:c}=this,h=a||c,g=document.createElement("vaadin-grid-sorter");g.classList.add("esri-column__sorter");g.setAttribute("path",c);g.setAttribute("title",h);g.innerHTML=h;b&&g.setAttribute("direction",b);g.addEventListener("direction-changed",()=>{this.direction!==
g.direction&&this._set("direction",g.direction)});return g};l.removeCellContent=function(b){if(b)for(;b.firstChild;)try{b.removeChild(b.firstChild)}catch(a){}};p._createClass(q,[{key:"direction",get:function(){return this._get("direction")||null},set:function(b){this.sortable&&(this.sortElement&&(b?this.sortElement.direction!==b&&this.sortElement.setAttribute("direction",b):this.sortElement.removeAttribute("direction")),this._set("direction",b))}},{key:"path",set:function(b){this.sortElement&&this.sortElement.path!==
b&&this.sortElement.setAttribute("path",b);this._set("path",b)}}]);return q}(u.HandleOwnerMixin(d.EventedAccessor));e.__decorate([f.property()],d.prototype,"activeRowIndex",void 0);e.__decorate([f.property()],d.prototype,"autoWidth",void 0);e.__decorate([f.property()],d.prototype,"cellValueFormatFunction",void 0);e.__decorate([f.property()],d.prototype,"direction",null);e.__decorate([f.property()],d.prototype,"flexGrow",void 0);e.__decorate([f.property()],d.prototype,"footerRenderFunction",void 0);
e.__decorate([f.property()],d.prototype,"frozen",void 0);e.__decorate([f.property()],d.prototype,"grid",void 0);e.__decorate([f.property()],d.prototype,"header",void 0);e.__decorate([f.property()],d.prototype,"headerRenderFunction",void 0);e.__decorate([f.property()],d.prototype,"headerMenuRenderFunction",void 0);e.__decorate([f.property()],d.prototype,"headerSorterRenderFunction",void 0);e.__decorate([f.property()],d.prototype,"hidden",void 0);e.__decorate([f.property()],d.prototype,"headerMenuEnabled",
void 0);e.__decorate([f.property()],d.prototype,"menu",void 0);e.__decorate([f.property()],d.prototype,"menuConfig",void 0);e.__decorate([f.property()],d.prototype,"messages",void 0);e.__decorate([f.property()],d.prototype,"messagesCommon",void 0);e.__decorate([f.property()],d.prototype,"path",null);e.__decorate([f.property()],d.prototype,"renderFunction",void 0);e.__decorate([f.property()],d.prototype,"resizable",void 0);e.__decorate([f.property()],d.prototype,"sortable",void 0);e.__decorate([f.property({readOnly:!0})],
d.prototype,"sortElement",void 0);e.__decorate([f.property()],d.prototype,"textAlign",void 0);e.__decorate([f.property()],d.prototype,"width",void 0);return d=e.__decorate([w.subclass("esri.widgets.FeatureTable.Grid.Column")],d)});