// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../../../../../chunks/_rollupPluginBabelHelpers ../../../../../../core/has ../../../../../../core/maybe ../../../../../../core/workers/Connection ../../../../../../geometry/support/quantizationUtils ../../../../../../layers/graphics/featureConversionUtils ../../../../../../layers/ogc/ogcFeatureUtils ../../../../../../rest/query/operations/query ../../support/FeatureSetReaderJSON ../../support/FeatureSetReaderPBF".split(" "),function(p,g,w,m,x,u,q,v,r,k,y){function z(c){return t.apply(this,
arguments)}function t(){t=g._asyncToGenerator(function*(c){const d=new x;yield d.open(c,{});return d});return t.apply(this,arguments)}let l=function(){function c(d){this.service=d}c.prototype.destroy=function(){};return c}(),A=function(c){function d(a){var b=c.call(this,a)||this;b._portsOpen=z(a.source).then(f=>b.client=f);return b}g._inheritsLoose(d,c);var e=d.prototype;e.destroy=function(){this.client.close();this.client=null};e.executeQuery=function(){var a=g._asyncToGenerator(function*(b,f){yield this._portsOpen;
b=yield this.client.invoke("queryFeatures",b.toJSON(),f);return k.FeatureSetReaderJSON.fromFeatureSet(b,this.service.objectIdField)});return function(b,f){return a.apply(this,arguments)}}();return d}(l),B=function(c){function d(){return c.apply(this,arguments)||this}g._inheritsLoose(d,c);d.prototype.executeQuery=function(){var e=g._asyncToGenerator(function*(a,b){({data:b}=yield r.executeQueryPBFBuffer(this.service.source,a,b));return y.FeatureSetReaderPBF.fromBuffer(b,this.service.geometryType,!a.quantizationParameters)});
return function(a,b){return e.apply(this,arguments)}}();return d}(l),F=function(c){function d(){return c.apply(this,arguments)||this}g._inheritsLoose(d,c);d.prototype.executeQuery=function(){var e=g._asyncToGenerator(function*(a,b){const {source:f,capabilities:n,spatialReference:C,objectIdField:D,geometryType:E}=this.service;if(m.isSome(a.quantizationParameters)&&!n.query.supportsQuantization){const h=a.clone();a=u.toQuantizationTransform(m.unwrap(h.quantizationParameters));h.quantizationParameters=
null;({data:b}=yield r.executeQuery(f,h,C,b));b=q.convertFromFeatureSet(b,D);q.quantizeOptimizedFeatureSet(a,b);return k.FeatureSetReaderJSON.fromOptimizedFeatureSet(b)}({data:a}=yield r.executeQuery(f,a,this.service.spatialReference,b));"esriGeometryPoint"===E&&(a.features=a.features.filter(h=>m.isSome(h.geometry)?(h=h.geometry,Number.isFinite(h.x)&&Number.isFinite(h.y)):!0));return k.FeatureSetReaderJSON.fromFeatureSet(a,this.service.objectIdField)});return function(a,b){return e.apply(this,arguments)}}();
return d}(l),G=function(c){function d(){return c.apply(this,arguments)||this}g._inheritsLoose(d,c);d.prototype.executeQuery=function(){var e=g._asyncToGenerator(function*(a,b){var {capabilities:f}=this.service;if(a.quantizationParameters&&!f.query.supportsQuantization){const n=a.clone();f=u.toQuantizationTransform(m.unwrap(n.quantizationParameters));n.quantizationParameters=null;a=yield v.queryOptimizedFeatureSet(this.service.source,a,b);q.quantizeOptimizedFeatureSet(f,a);return k.FeatureSetReaderJSON.fromOptimizedFeatureSet(a)}a=
yield v.queryOptimizedFeatureSet(this.service.source,a,b);return k.FeatureSetReaderJSON.fromOptimizedFeatureSet(a)});return function(a,b){return e.apply(this,arguments)}}();return d}(l);p.SourceAdapter=l;p.createSourceAdapter=function(c){const {capabilities:d}=c;var e=c.source;return e&&e.capabilities&&e.collection&&e.layerDefinition?new G(c):Array.isArray(c.source)?new A(c):d.query.supportsFormatPBF&&w("featurelayer-pbf")?new B(c):new F(c)};Object.defineProperty(p,"__esModule",{value:!0})});