// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("require exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/maybe ../../../../chunks/vec2f64 ../../../../chunks/vec3 ../../../../chunks/vec4f64 ../../../../support/requestImageUtils ./glUtil3D ./SSAOTechnique ./Util ../../../webgl/FramebufferObject ../../../webgl/Texture ../../../webgl/Util".split(" "),function(y,v,z,c,A,B,C,D,E,q,F,r,G,t){let H=function(){function u(a,d,f){this._techniqueRep=a;this._rctx=d;this._requestRender=f;this._enabled=!1;this._ssaoTechniqueConfig=
new q.SSAOTechniqueConfiguration;this.quadVAO=null;this._blurSizePx=2;this._attenuation=.5}var k=u.prototype;k.dispose=function(){this.quadVAO=c.disposeMaybe(this.quadVAO)};k.computeSSAO=function(a,d,f){if(!(!this.enabled||c.isNone(this._noiseTexture)||c.isNone(this._ssaoFBO)||c.isNone(this._blur0FBO)||c.isNone(this._blur1FBO))){var e=this._rctx,n=a.fullViewport,g=n[2],h=n[3],l=g/this._blurSizePx,m=h/this._blurSizePx;this._ssaoFBO.resize(g,h);this._blur0FBO.resize(l,m);this._blur1FBO.resize(l,m);
l=1*g;m=1*h;e.bindFramebuffer(this._ssaoFBO);e.setViewport(0,0,g,h);var b=this._ssaoTechnique.program;e.useProgram(b);e.setPipelineState(this._ssaoTechnique.pipeline);b.setUniform2f("rnmScale",g/this._noiseTexture.descriptor.width,h/this._noiseTexture.descriptor.height);F.inverseProjectionInfo(a.projectionMatrix,a.fullWidth,a.fullHeight,w,x);b.setUniform4fv("projInfo",w);b.setUniform2fv("zScale",x);b.setUniform2f("nearFar",a.near,a.far);g=1/a.computeRenderPixelSizeAtDist(1);b.setUniform1f("projScale",
1*g);b.setUniform2f("screenDimensions",l,m);h=B.distance(a.eye,a.center);var p=20*a.computeRenderPixelSizeAtDist(h);p=Math.max(.1,p);b.setUniform1f("radius",p);b.setUniform1f("intensity",4*this._attenuation/p**6);b.bindTexture(this._noiseTexture,"rnm");b.bindTexture(f,"normalMap");b.bindTexture(d,"depthMap");c.isNone(this.quadVAO)&&(this.quadVAO=E.createQuadVAO(this._rctx));e.bindVAO(this.quadVAO);e.drawArrays(5,0,t.vertexCount(this.quadVAO,"geometry"));b=this._blurTechnique.program;e.useProgram(b);
b.bindTexture(this._ssaoFBO.colorTexture,"tex");b.bindTexture(f,"normalMap");b.bindTexture(d,"depthMap");e.setViewport(0,0,l/this._blurSizePx,m/this._blurSizePx);e.bindFramebuffer(this._blur0FBO);b.setUniform2f("screenDimensions",l,m);b.setUniform2f("blurSize",0,1*this._blurSizePx/m);b.setUniform2f("nearFar",a.near,a.far);5E4<h&&(g=Math.max(0,g-(h-5E4)));b.setUniform1f("projScale",g);e.drawArrays(5,0,t.vertexCount(this.quadVAO,"geometry"));b.setUniform2f("blurSize",1*this._blurSizePx/l,0);e.bindFramebuffer(this._blur1FBO);
b.bindTexture(this._blur0FBO.colorTexture,"tex");e.drawArrays(5,0,t.vertexCount(this.quadVAO,"geometry"));e.setViewport(n[0],n[1],n[2],n[3])}};k.bind=function(a,d){this.enabled&&c.isSome(this._blur1FBO)&&c.isSome(this._ssaoFBO)?(a.bindTexture(this._blur1FBO.colorTexture,"ssaoTex"),a.setUniform4f("viewportPixelSz",d.fullViewport[0],d.fullViewport[1],1/this._ssaoFBO.width,1/this._ssaoFBO.height)):a.setUniform4f("viewportPixelSz",-1,-1,-1,-1)};k._selectPrograms=function(){this._ssaoTechniqueConfig.output=
0;this._ssaoTechnique=this._techniqueRep.releaseAndAcquire(q.SSAOTechnique,this._ssaoTechniqueConfig,this._ssaoTechnique);this._ssaoTechniqueConfig.output=1;this._blurTechnique=this._techniqueRep.releaseAndAcquire(q.SSAOTechnique,this._ssaoTechniqueConfig,this._blurTechnique)};k._enable=function(){this.enabled||(this._enabled=!0,this._loadResources(()=>{this._enabled&&this._initialize()}))};k._loadResources=function(a){this._data?a():(new Promise(function(d,f){y(["./SSAOHelperData"],d,f)})).then(d=>
{this._data=d;a()})};k._initialize=function(){const a={target:3553,pixelFormat:6408,dataType:5121,samplingMode:9729,wrapMode:33071,width:0,height:0},d={colorTarget:0,depthStencilTarget:0};D.requestImage(this._data.noiseTexture).then(f=>{this._enabled&&(this._ssaoFBO=new r(this._rctx,d,a),this._blur0FBO=new r(this._rctx,d,a),this._blur1FBO=new r(this._rctx,d,a),this._noiseTexture=new G(this._rctx,{target:3553,pixelFormat:6408,dataType:5121,hasMipmap:!0,width:f.width,height:f.height},f),this._requestRender())});
this._selectPrograms()};k._disable=function(){this._enabled=!1;this._noiseTexture=c.disposeMaybe(this._noiseTexture);this._blur1FBO=c.disposeMaybe(this._blur1FBO);this._blur0FBO=c.disposeMaybe(this._blur0FBO);this._ssaoFBO=c.disposeMaybe(this._ssaoFBO)};z._createClass(u,[{key:"enabled",get:function(){return this._enabled},set:function(a){a?this._enable():this._disable()}},{key:"ready",get:function(){return this.enabled&&c.isSome(this._noiseTexture)&&c.isSome(this._ssaoFBO)&&c.isSome(this._blur0FBO)&&
c.isSome(this._blur1FBO)}},{key:"gpuMemoryUsage",get:function(){return(c.isSome(this._blur0FBO)?this._blur0FBO.gpuMemoryUsage:0)+(c.isSome(this._blur1FBO)?this._blur1FBO.gpuMemoryUsage:0)+(c.isSome(this._ssaoFBO)?this._ssaoFBO.gpuMemoryUsage:0)}},{key:"test",get:function(){return{ssao:this._ssaoFBO,blur:this._blur1FBO}}}]);return u}();const x=A.create(),w=C.create();v.SSAOHelper=H;Object.defineProperty(v,"__esModule",{value:!0})});