// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/maybe ../../../../chunks/vec3f64 ../../../webgl/BufferObject ../../../webgl/FramebufferObject ../../../webgl/Program ../../../webgl/enums ../../../webgl/checkWebGLError ../../../webgl/renderState ../../../webgl/Texture ../../../webgl/VertexArrayObject ./doublePrecisionUtils ./Util ../../../webgl/testFloatBufferBlend ../../../webgl/testSVGPremultipliedAlpha".split(" "),function(g,t,h,k,u,v,w,G,H,I,J,x,l,y,z,A){function m(a,
b){var c=new v(a,{colorTarget:0,depthStencilTarget:0},{target:3553,wrapMode:33071,pixelFormat:6408,dataType:5121,samplingMode:9728,width:1,height:1});const n=u.createVertex(a,35044,new Uint16Array([0,0,1,0,0,1,1,1])),p=new x(a,new Map([["position",0]]),{geometry:[{name:"position",count:2,type:5123,offset:0,stride:4,normalized:!1}]},{geometry:n}),q=k.fromValues(5633261.287538229,2626832.878767164,1434988.0495278358),r=k.fromValues(5633271.46742708,2626873.6381334523,1434963.231608387);b=new w.Program(a,
`\n\n  precision highp float;\n\n  attribute vec2 position;\n\n  uniform vec3 u_highA;\n  uniform vec3 u_lowA;\n  uniform vec3 u_highB;\n  uniform vec3 u_lowB;\n\n  varying vec4 v_color;\n\n  ${b?"#define DOUBLE_PRECISION_REQUIRES_OBFUSCATION":""}\n\n  #ifdef DOUBLE_PRECISION_REQUIRES_OBFUSCATION\n\n  vec3 dpPlusFrc(vec3 a, vec3 b) {\n    return mix(a, a + b, vec3(notEqual(b, vec3(0))));\n  }\n\n  vec3 dpMinusFrc(vec3 a, vec3 b) {\n    return mix(vec3(0), a - b, vec3(notEqual(a, b)));\n  }\n\n  vec3 dpAdd(vec3 hiA, vec3 loA, vec3 hiB, vec3 loB) {\n    vec3 t1 = dpPlusFrc(hiA, hiB);\n    vec3 e = dpMinusFrc(t1, hiA);\n    vec3 t2 = dpMinusFrc(hiB, e) + dpMinusFrc(hiA, dpMinusFrc(t1, e)) + loA + loB;\n    return t1 + t2;\n  }\n\n  #else\n\n  vec3 dpAdd(vec3 hiA, vec3 loA, vec3 hiB, vec3 loB) {\n    vec3 t1 = hiA + hiB;\n    vec3 e = t1 - hiA;\n    vec3 t2 = ((hiB - e) + (hiA - (t1 - e))) + loA + loB;\n    return t1 + t2;\n  }\n\n  #endif\n\n  const float MAX_RGBA_FLOAT =\n    255.0 / 256.0 +\n    255.0 / 256.0 / 256.0 +\n    255.0 / 256.0 / 256.0 / 256.0 +\n    255.0 / 256.0 / 256.0 / 256.0 / 256.0;\n\n  const vec4 FIXED_POINT_FACTORS = vec4(1.0, 256.0, 256.0 * 256.0, 256.0 * 256.0 * 256.0);\n\n  vec4 float2rgba(const float value) {\n    // Make sure value is in the domain we can represent\n    float valueInValidDomain = clamp(value, 0.0, MAX_RGBA_FLOAT);\n\n    // Decompose value in 32bit fixed point parts represented as\n    // uint8 rgba components. Decomposition uses the fractional part after multiplying\n    // by a power of 256 (this removes the bits that are represented in the previous\n    // component) and then converts the fractional part to 8bits.\n    vec4 fixedPointU8 = floor(fract(valueInValidDomain * FIXED_POINT_FACTORS) * 256.0);\n\n    // Convert uint8 values (from 0 to 255) to floating point representation for\n    // the shader\n    const float toU8AsFloat = 1.0 / 255.0;\n\n    return fixedPointU8 * toU8AsFloat;\n  }\n\n  void main() {\n    vec3 val = dpAdd(u_highA, u_lowA, -u_highB, -u_lowB);\n\n    v_color = float2rgba(val.z / 25.0);\n\n    gl_Position = vec4(position * 2.0 - 1.0, 0.0, 1.0);\n  }\n  `,
"\n  precision highp float;\n\n  varying vec4 v_color;\n\n  void main() {\n    gl_FragColor \x3d v_color;\n  }\n  ",new Map([["position",0]]));var d=new Float32Array(6);l.encodeDoubleArray(q,d,3);var e=new Float32Array(6);l.encodeDoubleArray(r,e,3);a.useProgram(b);b.setUniform3f("u_highA",d[0],d[2],d[4]);b.setUniform3f("u_lowA",d[1],d[3],d[5]);b.setUniform3f("u_highB",e[0],e[2],e[4]);b.setUniform3f("u_lowB",e[1],e[3],e[5]);d=b;e=a.getBoundFramebufferObject();const {x:B,y:C,width:D,height:E}=a.getViewport();
a.bindFramebuffer(c);a.setViewport(0,0,1,1);a.bindVAO(p);a.drawArrays(5,0,4);b=new Uint8Array(4);c.readPixels(0,0,1,1,6408,5121,b);d.dispose();p.dispose(!1);n.dispose();c.dispose();a.setViewport(B,C,D,E);a.bindFramebuffer(e);a=(q[2]-r[2])/25;c=y.unpackFloatRGBA(b);return Math.abs(a-c)}let F=function(){function a(b){this.context=b;this.floatBufferBlendWorking=this.svgAlwaysPremultipliesAlpha=!1;this._doublePrecisionRequiresObfuscation=null;this.floatBufferBlendWorking=z.testFloatBufferBlend(b);A.testSVGPremultipliedAlpha(b).then(c=>
this.svgAlwaysPremultipliesAlpha=!c)}t._createClass(a,[{key:"doublePrecisionRequiresObfuscation",get:function(){if(h.isNone(this._doublePrecisionRequiresObfuscation)){const b=m(this.context,!1),c=m(this.context,!0);this._doublePrecisionRequiresObfuscation=0!==b&&(0===c||5<b/c)}return this._doublePrecisionRequiresObfuscation}}]);return a}(),f=null;g.clearTestWebGLDriver=function(a){h.isSome(f)&&f.context===a&&(f=null)};g.testWebGLDriver=function(a){if(h.isNone(f)||f.context!==a)f=new F(a);return f};
Object.defineProperty(g,"__esModule",{value:!0})});