// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
require({cache:{"esri/geometry/support/meshUtils/deduplicate":function(){define(["exports","../../../core/mathUtils"],function(l,n){function t(r,h,c){var d,g=r.byteLength/(4*h),m=new Uint32Array(r,0,g*h);r=new Uint32Array(g);var u=null!=(d=null==c?void 0:c.minReduction)?d:0;const D=(d=(null==c?void 0:c.originalIndices)||null)?d.length:0;var p=(null==c?void 0:c.componentOffsets)||null;c=0;if(p)for(var E=0;E<p.length-1;E++){var G=p[E+1]-p[E];G>c&&(c=G)}else c=g;var q=Math.floor(1.1*c)+1;if(null==B||
B.length<2*q)B=new Uint32Array(n.nextHighestPowerOfTwo(2*q));for(c=0;c<2*q;c++)B[c]=0;c=0;G=(E=!!p&&!!d)?D:g;var x=E?new Uint32Array(D):null,v=0!==u?Math.ceil(7.84*1.96/(u*u)*u*(1-u)):G,z=1,A=p?p[1]:G;for(var C=0;C<G;C++){if(C===v){var F=1-c/C;if(F+1.96*Math.sqrt(F*(1-F)/C)<u)return null;v*=2}if(C===A){for(A=0;A<2*q;A++)B[A]=0;if(d)for(A=p[z-1];A<p[z];A++)x[A]=r[d[A]];A=p[++z]}F=E?d[C]:C;const N=F*h;var H=0;for(var I=0;I<h;I++)H=m[N+I]+H|0,H=H+(H<<11)+(H>>>2)|0;H>>>=0;I=H%q;let K=c;for(;0!==B[2*I+
1];){if(B[2*I]===H){const L=B[2*I+1]-1;var J=L*h;a:{for(let M=0;M<h;M++)if(m[N+M]!==m[J+M]){J=!1;break a}J=!0}if(J){K=r[L];break}}I++;I>=q&&(I-=q)}K===c&&(B[2*I]=H,B[2*I+1]=F+1,c++);r[F]=K}if(0!==u&&1-c/g<u)return null;if(E){for(g=p[z-1];g<x.length;g++)x[g]=r[d[g]];r=x}g=new Uint32Array(h*c);c=0;for(z=0;z<G;z++)if(r[z]===c){u=m;p=(E?d[z]:z)*h;q=g;x=c*h;v=h;for(C=0;C<v;C++)q[x+C]=u[p+C];c++}if(d&&!E){h=new Uint32Array(D);for(m=0;m<h.length;m++)h[m]=r[d[m]];r=h}return{buffer:g.buffer,indices:r,uniqueCount:c}}
let B=null;l.deduplicate=t;l["default"]=t;Object.defineProperty(l,"__esModule",{value:!0})})},"esri/views/3d/support/meshProcessing":function(){define(["exports"],function(l){l.computeNeighbors=function(n,t,B){t/=3;const r=new Uint32Array(B+1),h=new Uint32Array(B+1);var c=(q,x)=>{q<x?r[q+1]++:h[x+1]++};for(var d=0;d<t;d++){var g=n[3*d],m=n[3*d+1],u=n[3*d+2];c(g,m);c(m,u);c(u,g)}d=c=0;for(g=0;g<B;g++)m=r[g+1],u=h[g+1],r[g+1]=c,h[g+1]=d,c+=m,d+=u;const D=new Uint32Array(6*t),p=r[B];c=(q,x,v)=>{q<x?
(q=r[q+1]++,D[2*q]=x,D[2*q+1]=v):(x=h[x+1]++,D[2*p+2*x]=q,D[2*p+2*x+1]=v)};for(d=0;d<t;d++)g=n[3*d],m=n[3*d+1],u=n[3*d+2],c(g,m,d),c(m,u,d),c(u,g,d);c=(q,x)=>{const v=2*q;q=x-q;for(x=1;x<q;x++){const z=D[v+2*x],A=D[v+2*x+1];let C=x-1;for(C;0<=C&&D[v+2*C]>z;C--)D[v+2*C+2]=D[v+2*C],D[v+2*C+3]=D[v+2*C+1];D[v+2*C+2]=z;D[v+2*C+3]=A}};for(d=0;d<B;d++)c(r[d],r[d+1]),c(p+h[d],p+h[d+1]);const E=new Int32Array(3*t),G=(q,x)=>q===n[3*x]?0:q===n[3*x+1]?1:q===n[3*x+2]?2:-1;t=(q,x)=>{q=G(q,x);E[3*x+q]=-1};c=(q,
x,v,z)=>{q=G(q,x);E[3*x+q]=z;v=G(v,z);E[3*z+v]=x};for(d=0;d<B;d++){g=r[d];m=r[d+1];u=h[d];const q=h[d+1];for(;g<m&&u<q;){const x=D[2*g],v=D[2*p+2*u];x===v?(c(d,D[2*g+1],v,D[2*p+2*u+1]),g++,u++):x<v?(t(d,D[2*g+1]),g++):(t(v,D[2*p+2*u+1]),u++)}for(;g<m;)t(d,D[2*g+1]),g++;for(;u<q;)t(D[2*p+2*u],D[2*p+2*u+1]),u++}return E};Object.defineProperty(l,"__esModule",{value:!0})})},"esri/views/3d/support/buffer/workerHelper":function(){define(["exports","../../../../geometry/support/buffer/BufferView","./InterleavedLayout"],
function(l,n,t){function B(c){const d=[];c.fields.forEach((g,m)=>{var u=g.constructor;d.push([m,{...g,constructor:`${u.ElementType}_${u.ElementCount}`}])});return{stride:c.stride,fields:d,fieldNames:c.fieldNames}}function r(c){const d=t.newLayout();d.stride=c.stride;d.fieldNames=c.fieldNames;c.fields.forEach(g=>d.fields.set(g[0],{...g[1],constructor:h.get(g[1].constructor)}));return d}n=[n.BufferViewFloat,n.BufferViewVec2f,n.BufferViewVec3f,n.BufferViewVec4f,n.BufferViewMat3f,n.BufferViewMat4f,n.BufferViewFloat64,
n.BufferViewVec2f64,n.BufferViewVec3f64,n.BufferViewVec4f64,n.BufferViewMat3f64,n.BufferViewMat4f64,n.BufferViewUint8,n.BufferViewVec2u8,n.BufferViewVec3u8,n.BufferViewVec4u8,n.BufferViewUint16,n.BufferViewVec2u16,n.BufferViewVec3u16,n.BufferViewVec4u16,n.BufferViewUint32,n.BufferViewVec2u32,n.BufferViewVec3u32,n.BufferViewVec4u32,n.BufferViewInt8,n.BufferViewVec2i8,n.BufferViewVec3i8,n.BufferViewVec4i8,n.BufferViewInt16,n.BufferViewVec2i16,n.BufferViewVec3i16,n.BufferViewVec4i16,n.BufferViewInt32,
n.BufferViewVec2i32,n.BufferViewVec3i32,n.BufferViewVec4i32];const h=new Map;n.forEach(c=>h.set(`${c.ElementType}_${c.ElementCount}`,c));l.packInterleavedBuffer=function(c,d){d.push(c.buffer);return{buffer:c.buffer,layout:B(c.layout)}};l.packLayout=B;l.unpackInterleavedBuffer=function(c){return r(c.layout).createView(c.buffer)};l.unpackLayout=r;Object.defineProperty(l,"__esModule",{value:!0})})},"esri/geometry/support/buffer/BufferView":function(){define("exports ../../../chunks/_rollupPluginBabelHelpers ./internals/Mat3 ./internals/Mat4 ./internals/Scalar ./internals/Vec2 ./internals/Vec3 ./internals/Vec4".split(" "),
function(l,n,t,B,r,h,c,d){let g=function(e){function b(a,f=0,w,y){a=e.call(this,Float32Array,a,f,w,y)||this;a.elementType="f32";return a}n._inheritsLoose(b,e);b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(r.BufferViewScalarImpl);g.ElementType="f32";let m=function(e){function b(a,f=0,w,y){a=e.call(this,Float32Array,a,f,w,y)||this;a.elementType="f32";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,
f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(h.BufferViewVec2Impl);m.ElementType="f32";let u=function(e){function b(a,f=0,w,y){a=e.call(this,Float32Array,a,f,w,y)||this;a.elementType="f32";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(c.BufferViewVec3Impl);u.ElementType="f32";let D=
function(e){function b(a,f=0,w,y){a=e.call(this,Float32Array,a,f,w,y)||this;a.elementType="f32";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(d.BufferViewVec4Impl);D.ElementType="f32";let p=function(e){function b(a,f=0,w,y){a=e.call(this,Float32Array,a,f,w,y)||this;a.elementType="f32";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,
f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(t.BufferViewMat3Impl);p.ElementType="f32";t=function(e){function b(a,f=0,w,y){a=e.call(this,Float64Array,a,f,w,y)||this;a.elementType="f64";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(t.BufferViewMat3Impl);
t.ElementType="f64";let E=function(e){function b(a,f=0,w,y){a=e.call(this,Float32Array,a,f,w,y)||this;a.elementType="f32";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(B.BufferViewMat4Impl);E.ElementType="f32";B=function(e){function b(a,f=0,w,y){a=e.call(this,Float64Array,a,f,w,y)||this;a.elementType="f64";return a}n._inheritsLoose(b,e);b.prototype.slice=
function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(B.BufferViewMat4Impl);B.ElementType="f64";let G=function(e){function b(a,f=0,w,y){a=e.call(this,Float64Array,a,f,w,y)||this;a.elementType="f64";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(r.BufferViewScalarImpl);
G.ElementType="f64";let q=function(e){function b(a,f=0,w,y){a=e.call(this,Float64Array,a,f,w,y)||this;a.elementType="f64";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(h.BufferViewVec2Impl);q.ElementType="f64";let x=function(e){function b(a,f=0,w,y){a=e.call(this,Float64Array,a,f,w,y)||this;a.elementType="f64";return a}n._inheritsLoose(b,e);b.prototype.slice=
function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(c.BufferViewVec3Impl);x.ElementType="f64";let v=function(e){function b(a,f=0,w,y){a=e.call(this,Float64Array,a,f,w,y)||this;a.elementType="f64";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(d.BufferViewVec4Impl);
v.ElementType="f64";let z=function(e){function b(a,f=0,w,y){a=e.call(this,Uint8Array,a,f,w,y)||this;a.elementType="u8";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(r.BufferViewScalarImpl);z.ElementType="u8";let A=function(e){function b(a,f=0,w,y){a=e.call(this,Uint8Array,a,f,w,y)||this;a.elementType="u8";return a}n._inheritsLoose(b,e);b.prototype.slice=
function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(h.BufferViewVec2Impl);A.ElementType="u8";let C=function(e){function b(a,f=0,w,y){a=e.call(this,Uint8Array,a,f,w,y)||this;a.elementType="u8";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(c.BufferViewVec3Impl);
C.ElementType="u8";let F=function(e){function b(a,f=0,w,y){a=e.call(this,Uint8Array,a,f,w,y)||this;a.elementType="u8";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(d.BufferViewVec4Impl);F.ElementType="u8";let H=function(e){function b(a,f=0,w,y){a=e.call(this,Uint16Array,a,f,w,y)||this;a.elementType="u16";return a}n._inheritsLoose(b,e);b.prototype.slice=
function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(r.BufferViewScalarImpl);H.ElementType="u16";let I=function(e){function b(a,f=0,w,y){a=e.call(this,Uint16Array,a,f,w,y)||this;a.elementType="u16";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(h.BufferViewVec2Impl);
I.ElementType="u16";let J=function(e){function b(a,f=0,w,y){a=e.call(this,Uint16Array,a,f,w,y)||this;a.elementType="u16";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(c.BufferViewVec3Impl);J.ElementType="u16";let N=function(e){function b(a,f=0,w,y){a=e.call(this,Uint16Array,a,f,w,y)||this;a.elementType="u16";return a}n._inheritsLoose(b,e);b.prototype.slice=
function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(d.BufferViewVec4Impl);N.ElementType="u16";let K=function(e){function b(a,f=0,w,y){a=e.call(this,Uint32Array,a,f,w,y)||this;a.elementType="u32";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(r.BufferViewScalarImpl);
K.ElementType="u32";let L=function(e){function b(a,f=0,w,y){a=e.call(this,Uint32Array,a,f,w,y)||this;a.elementType="u32";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(h.BufferViewVec2Impl);L.ElementType="u32";let M=function(e){function b(a,f=0,w,y){a=e.call(this,Uint32Array,a,f,w,y)||this;a.elementType="u32";return a}n._inheritsLoose(b,e);b.prototype.slice=
function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(c.BufferViewVec3Impl);M.ElementType="u32";let P=function(e){function b(a,f=0,w,y){a=e.call(this,Uint32Array,a,f,w,y)||this;a.elementType="u32";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(d.BufferViewVec4Impl);
P.ElementType="u32";let Q=function(e){function b(a,f=0,w,y){a=e.call(this,Int8Array,a,f,w,y)||this;a.elementType="i8";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(r.BufferViewScalarImpl);Q.ElementType="i8";let R=function(e){function b(a,f=0,w,y){a=e.call(this,Int8Array,a,f,w,y)||this;a.elementType="i8";return a}n._inheritsLoose(b,e);b.prototype.slice=
function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(h.BufferViewVec2Impl);R.ElementType="i8";let S=function(e){function b(a,f=0,w,y){a=e.call(this,Int8Array,a,f,w,y)||this;a.elementType="i8";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(c.BufferViewVec3Impl);
S.ElementType="i8";let T=function(e){function b(a,f=0,w,y){a=e.call(this,Int8Array,a,f,w,y)||this;a.elementType="i8";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(d.BufferViewVec4Impl);T.ElementType="i8";let O=function(e){function b(a,f=0,w,y){a=e.call(this,Int16Array,a,f,w,y)||this;a.elementType="i16";return a}n._inheritsLoose(b,e);b.prototype.slice=
function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(r.BufferViewScalarImpl);O.ElementType="i16";let U=function(e){function b(a,f=0,w,y){a=e.call(this,Int16Array,a,f,w,y)||this;a.elementType="i16";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(h.BufferViewVec2Impl);
U.ElementType="i16";let V=function(e){function b(a,f=0,w,y){a=e.call(this,Int16Array,a,f,w,y)||this;a.elementType="i16";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(c.BufferViewVec3Impl);V.ElementType="i16";let k=function(e){function b(a,f=0,w,y){a=e.call(this,Int16Array,a,f,w,y)||this;a.elementType="i16";return a}n._inheritsLoose(b,e);b.prototype.slice=
function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(d.BufferViewVec4Impl);k.ElementType="i16";r=function(e){function b(a,f=0,w,y){a=e.call(this,Int32Array,a,f,w,y)||this;a.elementType="i32";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(r.BufferViewScalarImpl);
r.ElementType="i32";h=function(e){function b(a,f=0,w,y){a=e.call(this,Int32Array,a,f,w,y)||this;a.elementType="i32";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(h.BufferViewVec2Impl);h.ElementType="i32";c=function(e){function b(a,f=0,w,y){a=e.call(this,Int32Array,a,f,w,y)||this;a.elementType="i32";return a}n._inheritsLoose(b,e);b.prototype.slice=
function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(c.BufferViewVec3Impl);c.ElementType="i32";d=function(e){function b(a,f=0,w,y){a=e.call(this,Int32Array,a,f,w,y)||this;a.elementType="i32";return a}n._inheritsLoose(b,e);b.prototype.slice=function(a,f){return this.sliceBuffer(b,a,f)};b.fromTypedArray=function(a,f){return new b(a.buffer,a.byteOffset,f,a.byteOffset+a.byteLength)};return b}(d.BufferViewVec4Impl);
d.ElementType="i32";l.BufferViewFloat=g;l.BufferViewFloat64=G;l.BufferViewInt16=O;l.BufferViewInt32=r;l.BufferViewInt8=Q;l.BufferViewMat3f=p;l.BufferViewMat3f64=t;l.BufferViewMat4f=E;l.BufferViewMat4f64=B;l.BufferViewUint16=H;l.BufferViewUint32=K;l.BufferViewUint8=z;l.BufferViewVec2f=m;l.BufferViewVec2f64=q;l.BufferViewVec2i16=U;l.BufferViewVec2i32=h;l.BufferViewVec2i8=R;l.BufferViewVec2u16=I;l.BufferViewVec2u32=L;l.BufferViewVec2u8=A;l.BufferViewVec3f=u;l.BufferViewVec3f64=x;l.BufferViewVec3i16=
V;l.BufferViewVec3i32=c;l.BufferViewVec3i8=S;l.BufferViewVec3u16=J;l.BufferViewVec3u32=M;l.BufferViewVec3u8=C;l.BufferViewVec4f=D;l.BufferViewVec4f64=v;l.BufferViewVec4i16=k;l.BufferViewVec4i32=d;l.BufferViewVec4i8=T;l.BufferViewVec4u16=N;l.BufferViewVec4u32=P;l.BufferViewVec4u8=F;Object.defineProperty(l,"__esModule",{value:!0})})},"esri/geometry/support/buffer/internals/Mat3":function(){define(["exports","../../../../chunks/_rollupPluginBabelHelpers"],function(l,n){let t=function(){function B(h,
c,d=0,g,m){this.TypedArrayConstructor=h;this.elementCount=9;h=this.TypedArrayConstructor;void 0===g&&(g=9*h.BYTES_PER_ELEMENT);const u=0===c.byteLength?0:d;this.typedBuffer=null==m?new h(c,u):new h(c,u,(m-d)/h.BYTES_PER_ELEMENT);this.typedBufferStride=g/h.BYTES_PER_ELEMENT;this.count=Math.ceil(this.typedBuffer.length/this.typedBufferStride);this.stride=this.typedBufferStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT}var r=B.prototype;r.sliceBuffer=function(h,c,d=this.count-c){c=this.typedBuffer.byteOffset+
c*this.stride;return new h(this.buffer,c,this.stride,c+d*this.stride)};r.getMat=function(h,c){h*=this.typedBufferStride;for(let d=0;9>d;d++)c[d]=this.typedBuffer[h++];return c};r.setMat=function(h,c){h*=this.typedBufferStride;for(let d=0;9>d;d++)this.typedBuffer[h++]=c[d]};r.get=function(h,c){return this.typedBuffer[h*this.typedBufferStride+c]};r.set=function(h,c,d){this.typedBuffer[h*this.typedBufferStride+c]=d};r.copyFrom=function(h,c,d){const g=this.typedBuffer,m=c.typedBuffer;h*=this.typedBufferStride;
c=d*c.typedBufferStride;for(d=0;9>d;++d)g[h++]=m[c++]};n._createClass(B,[{key:"buffer",get:function(){return this.typedBuffer.buffer}}]);return B}();t.ElementCount=9;l.BufferViewMat3Impl=t;Object.defineProperty(l,"__esModule",{value:!0})})},"esri/geometry/support/buffer/internals/Mat4":function(){define(["exports","../../../../chunks/_rollupPluginBabelHelpers"],function(l,n){let t=function(){function B(h,c,d=0,g,m){this.TypedArrayConstructor=h;this.elementCount=16;h=this.TypedArrayConstructor;void 0===
g&&(g=16*h.BYTES_PER_ELEMENT);const u=0===c.byteLength?0:d;this.typedBuffer=null==m?new h(c,u):new h(c,u,(m-d)/h.BYTES_PER_ELEMENT);this.typedBufferStride=g/h.BYTES_PER_ELEMENT;this.count=Math.ceil(this.typedBuffer.length/this.typedBufferStride);this.stride=this.typedBufferStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT}var r=B.prototype;r.sliceBuffer=function(h,c,d=this.count-c){c=this.typedBuffer.byteOffset+c*this.stride;return new h(this.buffer,c,this.stride,c+d*this.stride)};r.getMat=function(h,
c){h*=this.typedBufferStride;for(let d=0;16>d;d++)c[d]=this.typedBuffer[h++];return c};r.setMat=function(h,c){h*=this.typedBufferStride;for(let d=0;16>d;d++)this.typedBuffer[h++]=c[d]};r.get=function(h,c){return this.typedBuffer[h*this.typedBufferStride+c]};r.set=function(h,c,d){this.typedBuffer[h*this.typedBufferStride+c]=d};r.copyFrom=function(h,c,d){const g=this.typedBuffer,m=c.typedBuffer;h*=this.typedBufferStride;c=d*c.typedBufferStride;for(d=0;16>d;++d)g[h++]=m[c++]};n._createClass(B,[{key:"buffer",
get:function(){return this.typedBuffer.buffer}}]);return B}();t.ElementCount=16;l.BufferViewMat4Impl=t;Object.defineProperty(l,"__esModule",{value:!0})})},"esri/geometry/support/buffer/internals/Scalar":function(){define(["exports","../../../../chunks/_rollupPluginBabelHelpers"],function(l,n){let t=function(){function B(h,c,d=0,g,m){this.TypedArrayConstructor=h;this.elementCount=1;h=this.TypedArrayConstructor;void 0===g&&(g=h.BYTES_PER_ELEMENT);const u=0===c.byteLength?0:d;this.typedBuffer=null==
m?new h(c,u):new h(c,u,(m-d)/h.BYTES_PER_ELEMENT);this.typedBufferStride=g/h.BYTES_PER_ELEMENT;this.count=Math.ceil(this.typedBuffer.length/this.typedBufferStride);this.stride=this.typedBufferStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT}var r=B.prototype;r.sliceBuffer=function(h,c,d=this.count-c){c=this.typedBuffer.byteOffset+c*this.stride;return new h(this.buffer,c,this.stride,c+d*this.stride)};r.get=function(h){return this.typedBuffer[h*this.typedBufferStride]};r.set=function(h,c){this.typedBuffer[h*
this.typedBufferStride]=c};n._createClass(B,[{key:"buffer",get:function(){return this.typedBuffer.buffer}}]);return B}();t.ElementCount=1;l.BufferViewScalarImpl=t;Object.defineProperty(l,"__esModule",{value:!0})})},"esri/geometry/support/buffer/internals/Vec2":function(){define(["exports","../../../../chunks/_rollupPluginBabelHelpers","../../../../chunks/vec2"],function(l,n,t){let B=function(){function r(c,d,g=0,m,u){this.TypedArrayConstructor=c;this.elementCount=2;c=this.TypedArrayConstructor;void 0===
m&&(m=2*c.BYTES_PER_ELEMENT);const D=0===d.byteLength?0:g;this.typedBuffer=null==u?new c(d,D):new c(d,D,(u-g)/c.BYTES_PER_ELEMENT);this.typedBufferStride=m/c.BYTES_PER_ELEMENT;this.count=Math.ceil(this.typedBuffer.length/this.typedBufferStride);this.stride=this.typedBufferStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT}var h=r.prototype;h.sliceBuffer=function(c,d,g=this.count-d){d=this.typedBuffer.byteOffset+d*this.stride;return new c(this.buffer,d,this.stride,d+g*this.stride)};h.getVec=function(c,
d){c*=this.typedBufferStride;return t.set(d,this.typedBuffer[c],this.typedBuffer[c+1])};h.setVec=function(c,d){c*=this.typedBufferStride;this.typedBuffer[c++]=d[0];this.typedBuffer[c]=d[1]};h.get=function(c,d){return this.typedBuffer[c*this.typedBufferStride+d]};h.set=function(c,d,g){this.typedBuffer[c*this.typedBufferStride+d]=g};h.setValues=function(c,d,g){c*=this.typedBufferStride;this.typedBuffer[c++]=d;this.typedBuffer[c]=g};h.copyFrom=function(c,d,g){const m=this.typedBuffer,u=d.typedBuffer;
c*=this.typedBufferStride;d=g*d.typedBufferStride;m[c++]=u[d++];m[c]=u[d]};n._createClass(r,[{key:"buffer",get:function(){return this.typedBuffer.buffer}}]);return r}();B.ElementCount=2;l.BufferViewVec2Impl=B;Object.defineProperty(l,"__esModule",{value:!0})})},"esri/chunks/vec2":function(){define(["exports","./common"],function(l,n){function t(k,e){k[0]=e[0];k[1]=e[1];return k}function B(k,e,b){k[0]=e;k[1]=b;return k}function r(k,e,b){k[0]=e[0]+b[0];k[1]=e[1]+b[1];return k}function h(k,e,b){k[0]=
e[0]-b[0];k[1]=e[1]-b[1];return k}function c(k,e,b){k[0]=e[0]*b[0];k[1]=e[1]*b[1];return k}function d(k,e,b){k[0]=e[0]/b[0];k[1]=e[1]/b[1];return k}function g(k,e){k[0]=Math.ceil(e[0]);k[1]=Math.ceil(e[1]);return k}function m(k,e){k[0]=Math.floor(e[0]);k[1]=Math.floor(e[1]);return k}function u(k,e,b){k[0]=Math.min(e[0],b[0]);k[1]=Math.min(e[1],b[1]);return k}function D(k,e,b){k[0]=Math.max(e[0],b[0]);k[1]=Math.max(e[1],b[1]);return k}function p(k,e){k[0]=Math.round(e[0]);k[1]=Math.round(e[1]);return k}
function E(k,e,b){k[0]=e[0]*b;k[1]=e[1]*b;return k}function G(k,e,b,a){k[0]=e[0]+b[0]*a;k[1]=e[1]+b[1]*a;return k}function q(k,e){const b=e[0]-k[0];k=e[1]-k[1];return Math.sqrt(b*b+k*k)}function x(k,e){const b=e[0]-k[0];k=e[1]-k[1];return b*b+k*k}function v(k){const e=k[0];k=k[1];return Math.sqrt(e*e+k*k)}function z(k){const e=k[0];k=k[1];return e*e+k*k}function A(k,e){k[0]=-e[0];k[1]=-e[1];return k}function C(k,e){k[0]=1/e[0];k[1]=1/e[1];return k}function F(k,e){var b=e[0];const a=e[1];b=b*b+a*a;
0<b&&(b=1/Math.sqrt(b),k[0]=e[0]*b,k[1]=e[1]*b);return k}function H(k,e){return k[0]*e[0]+k[1]*e[1]}function I(k,e,b){e=e[0]*b[1]-e[1]*b[0];k[0]=k[1]=0;k[2]=e;return k}function J(k,e,b,a){const f=e[0];e=e[1];k[0]=f+a*(b[0]-f);k[1]=e+a*(b[1]-e);return k}function N(k,e){e=e||1;const b=2*n.RANDOM()*Math.PI;k[0]=Math.cos(b)*e;k[1]=Math.sin(b)*e;return k}function K(k,e,b){const a=e[0];e=e[1];k[0]=b[0]*a+b[2]*e;k[1]=b[1]*a+b[3]*e;return k}function L(k,e,b){const a=e[0];e=e[1];k[0]=b[0]*a+b[2]*e+b[4];k[1]=
b[1]*a+b[3]*e+b[5];return k}function M(k,e,b){const a=e[0];e=e[1];k[0]=b[0]*a+b[3]*e+b[6];k[1]=b[1]*a+b[4]*e+b[7];return k}function P(k,e,b){const a=e[0];e=e[1];k[0]=b[0]*a+b[4]*e+b[12];k[1]=b[1]*a+b[5]*e+b[13];return k}function Q(k,e,b,a){const f=e[0]-b[0];e=e[1]-b[1];const w=Math.sin(a);a=Math.cos(a);k[0]=f*a-e*w+b[0];k[1]=f*w+e*a+b[1];return k}function R(k,e){var b=k[0];k=k[1];const a=e[0];e=e[1];let f=b*b+k*k;0<f&&(f=1/Math.sqrt(f));let w=a*a+e*e;0<w&&(w=1/Math.sqrt(w));b=(b*a+k*e)*f*w;return 1<
b?0:-1>b?Math.PI:Math.acos(b)}function S(k){return"vec2("+k[0]+", "+k[1]+")"}function T(k,e){return k[0]===e[0]&&k[1]===e[1]}function O(k,e){const b=k[0];k=k[1];const a=e[0];e=e[1];return Math.abs(b-a)<=n.EPSILON*Math.max(1,Math.abs(b),Math.abs(a))&&Math.abs(k-e)<=n.EPSILON*Math.max(1,Math.abs(k),Math.abs(e))}function U(k,e,b,a,f){let w=e[0]-b[0];b=e[1]-b[1];f=(a[0]*w+a[1]*b)*(f-1);w=a[0]*f;b=a[1]*f;k[0]=e[0]+w;k[1]=e[1]+b;return k}var V=Object.freeze({__proto__:null,copy:t,set:B,add:r,subtract:h,
multiply:c,divide:d,ceil:g,floor:m,min:u,max:D,round:p,scale:E,scaleAndAdd:G,distance:q,squaredDistance:x,length:v,squaredLength:z,negate:A,inverse:C,normalize:F,dot:H,cross:I,lerp:J,random:N,transformMat2:K,transformMat2d:L,transformMat3:M,transformMat4:P,rotate:Q,angle:R,str:S,exactEquals:T,equals:O,projectAndScale:U,len:v,sub:h,mul:c,div:d,dist:q,sqrDist:x,sqrLen:z});l.add=r;l.angle=R;l.ceil=g;l.copy=t;l.cross=I;l.dist=q;l.distance=q;l.div=d;l.divide=d;l.dot=H;l.equals=O;l.exactEquals=T;l.floor=
m;l.inverse=C;l.len=v;l.length=v;l.lerp=J;l.max=D;l.min=u;l.mul=c;l.multiply=c;l.negate=A;l.normalize=F;l.projectAndScale=U;l.random=N;l.rotate=Q;l.round=p;l.scale=E;l.scaleAndAdd=G;l.set=B;l.sqrDist=x;l.sqrLen=z;l.squaredDistance=x;l.squaredLength=z;l.str=S;l.sub=h;l.subtract=h;l.transformMat2=K;l.transformMat2d=L;l.transformMat3=M;l.transformMat4=P;l.vec2=V})},"esri/geometry/support/buffer/internals/Vec3":function(){define(["exports","../../../../chunks/_rollupPluginBabelHelpers","../../../../chunks/vec3"],
function(l,n,t){let B=function(){function r(c,d,g=0,m,u){this.TypedArrayConstructor=c;this.elementCount=3;c=this.TypedArrayConstructor;void 0===m&&(m=3*c.BYTES_PER_ELEMENT);const D=0===d.byteLength?0:g;this.typedBuffer=null==u?new c(d,D):new c(d,D,(u-g)/c.BYTES_PER_ELEMENT);this.typedBufferStride=m/c.BYTES_PER_ELEMENT;this.count=Math.ceil(this.typedBuffer.length/this.typedBufferStride);this.stride=this.typedBufferStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT}var h=r.prototype;h.sliceBuffer=
function(c,d,g=this.count-d){d=this.typedBuffer.byteOffset+d*this.stride;return new c(this.buffer,d,this.stride,d+g*this.stride)};h.getVec=function(c,d){c*=this.typedBufferStride;return t.set(d,this.typedBuffer[c],this.typedBuffer[c+1],this.typedBuffer[c+2])};h.setVec=function(c,d){c*=this.typedBufferStride;this.typedBuffer[c++]=d[0];this.typedBuffer[c++]=d[1];this.typedBuffer[c]=d[2]};h.get=function(c,d){return this.typedBuffer[c*this.typedBufferStride+d]};h.set=function(c,d,g){this.typedBuffer[c*
this.typedBufferStride+d]=g};h.setValues=function(c,d,g,m){c*=this.typedBufferStride;this.typedBuffer[c++]=d;this.typedBuffer[c++]=g;this.typedBuffer[c]=m};h.copyFrom=function(c,d,g){const m=this.typedBuffer,u=d.typedBuffer;c*=this.typedBufferStride;d=g*d.typedBufferStride;m[c++]=u[d++];m[c++]=u[d++];m[c]=u[d]};n._createClass(r,[{key:"buffer",get:function(){return this.typedBuffer.buffer}}]);return r}();B.ElementCount=3;l.BufferViewVec3Impl=B;Object.defineProperty(l,"__esModule",{value:!0})})},"esri/geometry/support/buffer/internals/Vec4":function(){define(["exports",
"../../../../chunks/_rollupPluginBabelHelpers","../../../../chunks/vec4"],function(l,n,t){let B=function(){function r(c,d,g=0,m,u){this.TypedArrayConstructor=c;this.elementCount=4;c=this.TypedArrayConstructor;void 0===m&&(m=4*c.BYTES_PER_ELEMENT);const D=0===d.byteLength?0:g;this.typedBuffer=null==u?new c(d,D):new c(d,D,(u-g)/c.BYTES_PER_ELEMENT);this.typedBufferStride=m/c.BYTES_PER_ELEMENT;this.count=Math.ceil(this.typedBuffer.length/this.typedBufferStride);this.stride=this.typedBufferStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT}
var h=r.prototype;h.sliceBuffer=function(c,d,g=this.count-d){d=this.typedBuffer.byteOffset+d*this.stride;return new c(this.buffer,d,this.stride,d+g*this.stride)};h.getVec=function(c,d){c*=this.typedBufferStride;return t.set(d,this.typedBuffer[c++],this.typedBuffer[c++],this.typedBuffer[c++],this.typedBuffer[c])};h.setVec=function(c,d){c*=this.typedBufferStride;this.typedBuffer[c++]=d[0];this.typedBuffer[c++]=d[1];this.typedBuffer[c++]=d[2];this.typedBuffer[c]=d[3]};h.get=function(c,d){return this.typedBuffer[c*
this.typedBufferStride+d]};h.set=function(c,d,g){this.typedBuffer[c*this.typedBufferStride+d]=g};h.setValues=function(c,d,g,m,u){c*=this.typedBufferStride;this.typedBuffer[c++]=d;this.typedBuffer[c++]=g;this.typedBuffer[c++]=m;this.typedBuffer[c]=u};h.copyFrom=function(c,d,g){const m=this.typedBuffer,u=d.typedBuffer;c*=this.typedBufferStride;d=g*d.typedBufferStride;m[c++]=u[d++];m[c++]=u[d++];m[c++]=u[d++];m[c]=u[d]};n._createClass(r,[{key:"buffer",get:function(){return this.typedBuffer.buffer}}]);
return r}();B.ElementCount=4;l.BufferViewVec4Impl=B;Object.defineProperty(l,"__esModule",{value:!0})})},"esri/views/3d/support/buffer/InterleavedLayout":function(){define(["exports","../../../../chunks/_rollupPluginBabelHelpers","../../../../geometry/support/buffer/BufferView","../../../../geometry/support/buffer/types"],function(l,n,t,B){let r=function(){function c(g,m){this.layout=g;this.buffer="number"===typeof m?new ArrayBuffer(m*g.stride):m;for(const u of g.fieldNames)m=g.fields.get(u),this[u]=
new m.constructor(this.buffer,m.offset,this.stride)}var d=c.prototype;d.getField=function(g,m){return(g=this[g])&&g.elementCount===m.ElementCount&&g.elementType===m.ElementType?g:null};d.slice=function(g,m){return new c(this.layout,this.buffer.slice(g*this.stride,m*this.stride))};d.copyFrom=function(g,m,u,D){const p=this.stride;0===p%4?(g=new Uint32Array(g.buffer,m*p,D*p/4),(new Uint32Array(this.buffer,u*p,D*p/4)).set(g)):(g=new Uint8Array(g.buffer,m*p,D*p),(new Uint8Array(this.buffer,u*p,D*p)).set(g))};
n._createClass(c,[{key:"stride",get:function(){return this.layout.stride}},{key:"count",get:function(){return this.buffer.byteLength/this.stride}},{key:"byteLength",get:function(){return this.buffer.byteLength}}]);return c}(),h=function(){function c(){this.stride=0;this.fields=new Map;this.fieldNames=[]}var d=c.prototype;d.vec2f=function(g,m){this.appendField(g,t.BufferViewVec2f,m);return this};d.vec2f64=function(g,m){this.appendField(g,t.BufferViewVec2f64,m);return this};d.vec3f=function(g,m){this.appendField(g,
t.BufferViewVec3f,m);return this};d.vec3f64=function(g,m){this.appendField(g,t.BufferViewVec3f64,m);return this};d.vec4f=function(g,m){this.appendField(g,t.BufferViewVec4f,m);return this};d.vec4f64=function(g,m){this.appendField(g,t.BufferViewVec4f64,m);return this};d.mat3f=function(g,m){this.appendField(g,t.BufferViewMat3f,m);return this};d.mat3f64=function(g,m){this.appendField(g,t.BufferViewMat3f64,m);return this};d.mat4f=function(g,m){this.appendField(g,t.BufferViewMat4f,m);return this};d.mat4f64=
function(g,m){this.appendField(g,t.BufferViewMat4f64,m);return this};d.vec4u8=function(g,m){this.appendField(g,t.BufferViewVec4u8,m);return this};d.f32=function(g,m){this.appendField(g,t.BufferViewFloat,m);return this};d.f64=function(g,m){this.appendField(g,t.BufferViewFloat64,m);return this};d.u8=function(g,m){this.appendField(g,t.BufferViewUint8,m);return this};d.u16=function(g,m){this.appendField(g,t.BufferViewUint16,m);return this};d.i8=function(g,m){this.appendField(g,t.BufferViewInt8,m);return this};
d.vec2i8=function(g,m){this.appendField(g,t.BufferViewVec2i8,m);return this};d.vec2i16=function(g,m){this.appendField(g,t.BufferViewVec2i16,m);return this};d.vec2u8=function(g,m){this.appendField(g,t.BufferViewVec2u8,m);return this};d.vec4u16=function(g,m){this.appendField(g,t.BufferViewVec4u16,m);return this};d.u32=function(g,m){this.appendField(g,t.BufferViewUint32,m);return this};d.appendField=function(g,m,u){const D=m.ElementCount*B.elementTypeSize(m.ElementType);this.fields.set(g,{size:D,constructor:m,
offset:this.stride,optional:u});this.stride+=D;this.fieldNames.push(g)};d.alignTo=function(g){this.stride=Math.floor((this.stride+g-1)/g)*g;return this};d.hasField=function(g){return 0<=this.fieldNames.indexOf(g)};d.createBuffer=function(g){return new r(this,g)};d.createView=function(g){return new r(this,g)};d.clone=function(){const g=new c;g.stride=this.stride;g.fields=new Map;this.fields.forEach((m,u)=>g.fields.set(u,m));g.fieldNames=this.fieldNames.slice();g.BufferType=this.BufferType;return g};
return c}();l.InterleavedBuffer=r;l.InterleavedLayout=h;l.newLayout=function(){return new h};Object.defineProperty(l,"__esModule",{value:!0})})},"esri/geometry/support/buffer/types":function(){define(["exports","../../../core/has"],function(l,n){l.elementTypeSize=function(t){switch(t){case "u8":return 1;case "u16":return 2;case "u32":return 4;case "i8":return 1;case "i16":return 2;case "i32":return 4;case "f32":return 4;case "f64":return 8}};l.isInteger=function(t){switch(t){case "u8":case "u16":case "u32":case "i8":case "i16":case "i32":return!0;
case "f32":case "f64":return!1}};l.isSigned=function(t){switch(t){case "u8":case "u16":case "u32":return!1;case "i8":case "i16":case "i32":case "f32":case "f64":return!0}};l.maximumValue=function(t){switch(t){case "u8":return 255;case "u16":return 65535;case "u32":return 4294967295;case "i8":return 127;case "i16":return 32767;case "i32":return 2147483647;case "f32":return 3.402823E38;case "f64":return 1.79769E308}};Object.defineProperty(l,"__esModule",{value:!0})})},"esri/views/3d/webgl-engine/lib/edgeRendering/bufferLayouts":function(){define(["exports",
"../../../support/buffer/glUtil","../../../support/buffer/InterleavedLayout"],function(l,n,t){const B=t.newLayout().vec3f("position").u16("componentIndex").u16("u16padding"),r=t.newLayout().vec2u8("sideness");n=n.glLayout(r);t=t.newLayout().vec3f("position0").vec3f("position1").u16("componentIndex").u8("variantOffset",{glNormalized:!0}).u8("variantStroke").u8("variantExtension",{glNormalized:!0}).u8("u8padding",{glPadding:!0}).u16("u16padding",{glPadding:!0});const h=t.clone().vec3f("normal"),c=t.clone().vec3f("normalA").vec3f("normalB"),
d=new Map([["position0",0],["position1",1],["componentIndex",2],["variantOffset",3],["variantStroke",4],["variantExtension",5],["normal",6],["normalA",6],["normalB",7],["sideness",8]]);l.CommonInstancesLayout=t;l.EdgeInputBufferLayout=B;l.EdgeShaderAttributeLocations=d;l.RegularEdgeInstancesLayout=h;l.SilhouetteEdgeInstancesLayout=c;l.VertexLayout=r;l.glVertexLayout=n;Object.defineProperty(l,"__esModule",{value:!0})})},"esri/views/3d/support/buffer/glUtil":function(){define(["exports"],function(l){const n=
{u8:5121,u16:5123,u32:5125,i8:5120,i16:5122,i32:5124,f32:5126};l.glLayout=function(t,B=0){const r=t.stride;return t.fieldNames.filter(h=>{h=t.fields.get(h).optional;return!(h&&h.glPadding)}).map(h=>{const c=t.fields.get(h),d=c.constructor.ElementCount;var g=n[c.constructor.ElementType];if(!g)throw Error("BufferType not supported in WebGL");return{name:h,stride:r,count:d,type:g,offset:c.offset,normalized:!(!c.optional||!c.optional.glNormalized),divisor:B}})};Object.defineProperty(l,"__esModule",{value:!0})})},
"esri/views/3d/webgl-engine/lib/edgeRendering/edgeBufferWriters":function(){define("exports ../../../../../core/RandomLCG ../../../../../chunks/vec3 ../../../../../chunks/vec3f64 ../../../support/buffer/glUtil ./bufferLayouts".split(" "),function(l,n,t,B,r,h){function c(v){const z=u;z[0]=v.position0[0];z[1]=v.position0[1];z[2]=v.position0[2];z[3]=v.position1[0];z[4]=v.position1[1];z[5]=v.position1[2];p[0]=5381;for(v=0;v<D.length;v++)p[0]=31*p[0]+D[v];return p[0]}function d(v){const z=u;z[0]=g(v.position0[0]);
z[1]=g(v.position0[1]);z[2]=g(v.position0[2]);z[3]=g(v.position1[0]);z[4]=g(v.position1[1]);z[5]=g(v.position1[2]);p[0]=5381;for(v=0;v<D.length;v++)p[0]=31*p[0]+D[v];return p[0]}function g(v){return Math.round(1E4*v)/1E4}let m=function(){function v(){}var z=v.prototype;z.updateSettings=function(A){this.settings=A;this.edgeHashFunction=A.reducedPrecision?d:c};z.write=function(A,C,F){var H=this.edgeHashFunction(F);x.seed=H;H=x.getIntRange(0,255);const I=x.getIntRange(0,this.settings.variants-1);var J=
x.getFloat();J=-(1-Math.min(J/.7,1))+Math.max(0,J-.7)/(1-.7);J=255*(Math.abs(J)**1.2*(0>J?-1:1)*.5+.5);A.position0.setVec(C,F.position0);A.position1.setVec(C,F.position1);A.componentIndex.set(C,F.componentIndex);A.variantOffset.set(C,H);A.variantStroke.set(C,I);A.variantExtension.set(C,J)};z.trim=function(A,C){return A.slice(0,C)};return v}();const u=new Float32Array(6),D=new Uint32Array(u.buffer),p=new Uint32Array(1);let E=function(){function v(){this.commonWriter=new m}var z=v.prototype;z.updateSettings=
function(A){this.commonWriter.updateSettings(A)};z.allocate=function(A){return h.RegularEdgeInstancesLayout.createBuffer(A)};z.write=function(A,C,F){this.commonWriter.write(A,C,F);t.add(q,F.faceNormal0,F.faceNormal1);t.normalize(q,q);A.normal.setVec(C,q)};z.trim=function(A,C){return this.commonWriter.trim(A,C)};return v}();E.Layout=h.RegularEdgeInstancesLayout;E.glLayout=r.glLayout(h.RegularEdgeInstancesLayout,1);let G=function(){function v(){this.commonWriter=new m}var z=v.prototype;z.updateSettings=
function(A){this.commonWriter.updateSettings(A)};z.allocate=function(A){return h.SilhouetteEdgeInstancesLayout.createBuffer(A)};z.write=function(A,C,F){this.commonWriter.write(A,C,F);A.normalA.setVec(C,F.faceNormal0);A.normalB.setVec(C,F.faceNormal1)};z.trim=function(A,C){return this.commonWriter.trim(A,C)};return v}();G.Layout=h.SilhouetteEdgeInstancesLayout;G.glLayout=r.glLayout(h.SilhouetteEdgeInstancesLayout,1);const q=B.create(),x=new n;l.CommonBufferWriter=m;l.RegularEdgeBufferWriter=E;l.SilhouetteEdgeBufferWriter=
G;Object.defineProperty(l,"__esModule",{value:!0})})},"esri/views/3d/webgl-engine/lib/edgeRendering/edgePreprocessing":function(){define("exports ../../../../../core/arrayUtils ../../../../../core/mathUtils ../../../../../core/typedArrayUtil ../../../../../chunks/vec3 ../../../../../chunks/vec3f64".split(" "),function(l,n,t,B,r,h){function c(p,E){const G=t.acosClamped(p.cosAngle),q=m.fwd,x=m.ortho;r.direction(q,p.position1,p.position0);p=0<r.dot(r.cross(x,p.faceNormal0,p.faceNormal1),q)?-1:1;return G*
p>E}function d(p){const E=p.faces.length/3,G=p.faces;p=p.neighbors;var q=0;for(var x=0;x<E;x++){var v=p[3*x+1],z=p[3*x+2],A=G[3*x],C=G[3*x+1],F=G[3*x+2];q+=-1===p[3*x]||A<C?1:0;q+=-1===v||C<F?1:0;q+=-1===z||F<A?1:0}q=new Int32Array(4*q);x=0;for(v=0;v<E;v++){z=p[3*v];A=p[3*v+1];C=p[3*v+2];F=G[3*v];const H=G[3*v+1],I=G[3*v+2];if(-1===z||F<H)q[x++]=F,q[x++]=H,q[x++]=v,q[x++]=z;if(-1===A||H<I)q[x++]=H,q[x++]=I,q[x++]=v,q[x++]=A;if(-1===C||I<F)q[x++]=I,q[x++]=F,q[x++]=v,q[x++]=C}return q}function g(p){const E=
p.faces.length/3,G=p.vertices.position;p=p.faces;const q=u.v0,x=u.v1,v=u.v2,z=new Float32Array(3*E);for(let A=0;A<E;A++){const C=p[3*A+1],F=p[3*A+2];G.getVec(p[3*A],q);G.getVec(C,x);G.getVec(F,v);r.subtract(x,x,q);r.subtract(v,v,q);r.cross(q,x,v);r.normalize(q,q);z[3*A]=q[0];z[3*A+1]=q[1];z[3*A+2]=q[2]}return z}const m={edge:{position0:h.create(),position1:h.create(),faceNormal0:h.create(),faceNormal1:h.create(),componentIndex:0,cosAngle:0},ortho:h.create(),fwd:h.create()},u={v0:h.create(),v1:h.create(),
v2:h.create()},D={anglePlanar:4,angleSignificantEdge:35};l.extractEdges=function(p,E,G,q=D){const x=p.vertices.position;var v=p.vertices.componentIndex,z=t.deg2rad(q.anglePlanar);q=t.deg2rad(q.angleSignificantEdge);const A=Math.cos(q),C=Math.cos(z),F=m.edge,H=F.position0,I=F.position1,J=F.faceNormal0,N=F.faceNormal1,K=g(p),L=d(p),M=L.length/4;p=E.allocate(M);q=0;const P=G.allocate(M);let Q=0,R=0,S=0;const T=n.range(0,M),O=new Float32Array(M);B.forEach(O,(e,b,a)=>{x.getVec(L[4*b],H);x.getVec(L[4*b+
1],I);a[b]=r.distance(H,I)});T.sort((e,b)=>O[b]-O[e]);const U=[],V=[];for(let e=0;e<M;e++){var k=T[e];const b=O[k],a=L[4*k],f=L[4*k+1],w=L[4*k+2];k=L[4*k+3];const y=-1===k;x.getVec(a,H);x.getVec(f,I);if(y)r.set(J,K[3*w],K[3*w+1],K[3*w+2]),r.copy(N,J),F.componentIndex=v.get(a),F.cosAngle=r.dot(J,N);else{r.set(J,K[3*w],K[3*w+1],K[3*w+2]);r.set(N,K[3*k],K[3*k+1],K[3*k+2]);F.componentIndex=v.get(a);F.cosAngle=r.dot(J,N);if(F.cosAngle>C)continue;-.9999>F.cosAngle&&r.copy(N,J)}R+=b;S++;y||F.cosAngle<A?
(E.write(p,q++,F),U.push(b)):c(F,z)&&(G.write(P,Q++,F),V.push(b))}v=new Float32Array(U.reverse());z=new Float32Array(V.reverse());return{regular:{instancesData:E.trim(p,q),lodInfo:{lengths:v}},silhouette:{instancesData:G.trim(P,Q),lodInfo:{lengths:z}},averageEdgeLength:R/S}};Object.defineProperty(l,"__esModule",{value:!0})})},"*noref":1}});
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../geometry/support/meshUtils/deduplicate ../../../support/meshProcessing ../../../support/buffer/workerHelper ./bufferLayouts ./edgeBufferWriters ./edgePreprocessing".split(" "),function(l,n,t,B,r,h,c,d){function g(){g=n._asyncToGenerator(function*(p){var E={data:h.EdgeInputBufferLayout.createView(p.dataBuffer),indices:"Uint32Array"===p.indicesType?new Uint32Array(p.indicesBuffer):"Uint16Array"===p.indicesType?new Uint16Array(p.indicesBuffer):
void 0,indicesLength:p.indicesLength,writerSettings:p.writerSettings,skipDeduplicate:p.skipDeduplicate};p=m(E);E=[E.data.buffer];E.push(p.regular.lodInfo.lengths.buffer);E.push(p.silhouette.lodInfo.lengths.buffer);return{result:{regular:{instancesData:r.packInterleavedBuffer(p.regular.instancesData,E),lodInfo:{lengths:p.regular.lodInfo.lengths.buffer}},silhouette:{instancesData:r.packInterleavedBuffer(p.silhouette.instancesData,E),lodInfo:{lengths:p.silhouette.lodInfo.lengths.buffer}},averageEdgeLength:p.averageEdgeLength},
transferList:E}});return g.apply(this,arguments)}function m(p){var E=p.data,G=p.indices;var q=p.indicesLength;if(p.skipDeduplicate){const x=B.computeNeighbors(G,q,E.count);q={faces:G,facesLength:q,neighbors:x,vertices:E}}else E=t.deduplicate(E.buffer,E.stride/4,{originalIndices:G,originalIndicesLength:q}),q=B.computeNeighbors(E.indices,q,E.uniqueCount),q={faces:E.indices,facesLength:E.indices.length,neighbors:q,vertices:h.EdgeInputBufferLayout.createView(E.buffer)};u.updateSettings(p.writerSettings);
D.updateSettings(p.writerSettings);return d.extractEdges(q,u,D)}const u=new c.RegularEdgeBufferWriter,D=new c.SilhouetteEdgeBufferWriter;l.work=m;l.wrappedWork=function(p){return g.apply(this,arguments)};Object.defineProperty(l,"__esModule",{value:!0})});