// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/Accessor ../../../../../core/arrayUtils ../../../../../core/Logger ../../../../../core/mathUtils ../../../../../core/maybe ../../../../../core/promiseUtils ../../../../../core/accessorSupport/decorators/property ../../../../../core/has ../../../../../core/accessorSupport/ensureType ../../../../../core/accessorSupport/decorators/subclass ../../../../../chunks/mat3 ../../../../../chunks/mat3f64 ../../../../../chunks/mat4 ../../../../../chunks/mat4f64 ../../../../../chunks/vec3 ../../../../../chunks/vec3f64 ../../../../../chunks/sphere ../../../../../chunks/vec33 ../../core/shaderLibrary/attributes/VertexPosition.glsl ../../core/util/TwoVectorPosition ../GridLocalOriginFactory ../localOriginHelper ../LocalOriginManager ../Object3D ./bufferLayouts ./edgeBufferWriters ./EdgeRenderer ./EdgeWorkerHandle ./strokes ./util ../TextureBackedBuffer/BufferManager ../../../../support/WatchUpdatingTracking ../../../../webgl/BufferObject ../../../../webgl/VertexArrayObject".split(" "),
function(w,u,z,R,S,T,K,t,U,A,la,ma,V,H,L,W,M,E,I,N,X,Y,Z,aa,ba,ca,da,B,O,C,ea,fa,v,ha,ia,J,P){function ja(D){let y=null,n=null;for(let a=0;a<D.geometries.length;a++){var b;const c=D.geometryRecords[a];if(c.material.supportsEdges){if(!y)y=c.transformation;else if(!S.equals(y,c.transformation))return!1;if(!n&&t.isSome(c.origin))n=c;else if(t.isSome(null==(b=n)?void 0:b.origin)&&t.isSome(c.origin)&&n.origin.id!==c.origin.id)return!1}}return!0}const ka=T.getLogger("esri.views.3d.webgl-engine.lib.edgeRendering.EdgeView");
w.EdgeView=function(D){function y(b){var a=D.call(this,b)||this;a.updatingHandles=new ia.WatchUpdatingTracking;a.perObjectData=new Map;a.perObjectDataEvictionCache=new Set;a.renderers=new Map;a.numberOfRenderedEdges=0;a.gpuMemoryUsage=0;a.workerAbort=U.createAbortController();a.tmpModelPosition=I.create();a.localOrigins=new ca.LocalOriginManager(new aa.GridLocalOriginFactory(b.renderSR));return a}u._inheritsLoose(y,D);var n=y.prototype;n.initialize=function(){this.worker=new ea(this.schedule);this.componentColorManager=
new ha.BufferManager(this.rctx,2);const b=B.VertexLayout.createBuffer(4);for(let a=0;4>a;a++)b.sideness.set(a,0,0===a||3===a?0:1),b.sideness.set(a,1,0===a||1===a?0:1);this.verticesBufferObject=J.createVertex(this.rctx,35044,b.buffer)};n.destroy=function(){this.destroyed||(this.perObjectData.forEach(b=>this._discardObjectEntry(b)),this.perObjectData.clear(),this.strokesTexture=t.disposeMaybe(this.strokesTexture),this.componentColorManager=t.destroyMaybe(this.componentColorManager),this.workerAbort.abort(),
this.worker.destroy(),this.verticesBufferObject=t.disposeMaybe(this.verticesBufferObject),this.renderers.clear(),this.updatingHandles.destroy())};n.shouldRender=function(){return 0<this.renderers.size};n.addComponentObject=function(){var b=u._asyncToGenerator(function*(a,c,d,e,k,g,f,m){if(!this.hasObject(a)){var h;d=new Q(new Promise(l=>h=l),d.center,d.radius);this.perObjectData.set(a,d);yield this.updatingHandles.addPromise(this.addComponentGeometry(c,d,e,k,g,f,m));this.setNeedsRender();h()}});return function(a,
c,d,e,k,g,f,m){return b.apply(this,arguments)}}();n.addOrUpdateObject3D=function(){var b=u._asyncToGenerator(function*(a,c,d,e){if(this.destroyed)ka.warn("Attempt to add an object to a destroyed instance");else{var k=this.perObjectData.get(a);0<(null==k?void 0:k.renderables.length)&&this.perObjectDataEvictionCache.add(k);var g,f=a.boundingVolumeWorldSpace.bounds;f=new Q(new Promise(h=>g=h),N.getCenter(f),N.getRadius(f));this.perObjectData.set(a,f);var m=[];if(d.mergeGeometries&&1<a.geometries.length&&
ja(a))m.push(this.addObjectMergedGeometries(a,f,c,d,e));else for(let h=0;h<a.geometries.length;h++){const l=a.geometryRecords[h];l.material.supportsEdges&&m.push(this.addGeometry(a,f,a.geometries[h],l,c[0],d,e))}yield this.updatingHandles.addPromise(Promise.all(m));this.perObjectDataEvictionCache.delete(f);this._discardObjectEntry(k);this.setNeedsRender();g()}});return function(a,c,d,e){return b.apply(this,arguments)}}();n._discardObjectEntry=function(b){b&&(b.renderables.length&&(b.renderables.forEach(a=>
this.removeRenderable(a)),this.setNeedsRender()),b.loaded=null)};n.hasObject=function(b){return this.perObjectData.has(b)};n.updateAllComponentOpacities=function(){var b=u._asyncToGenerator(function*(a,c){const d=c instanceof Array?e=>c[e]:()=>c;(yield this.updatingHandles.addPromise(this.getObjectEntry(a))).renderables.forEach(e=>{const k=e.components.meta.length;for(let g=0;g<k;g++){const f=d(g),m=e.components.meta[g],h=m.index;m.material.opacity=f;e.components.buffer.textureBuffer.setDataElement(h,
1,3,255*f)}this.updateTransparency(e)});this.setNeedsRender()});return function(a,c){return b.apply(this,arguments)}}();n.updateAllComponentMaterials=function(){var b=u._asyncToGenerator(function*(a,c,d,e){const k=a instanceof da.Object3D,g=!!d.slicePlaneEnabled,f=v.determineRendererType(c),m=C.EdgeRenderer.getKey(f,g,k);(yield this.updatingHandles.addPromise(this.getObjectEntry(a))).renderables.forEach(h=>{if(m!==h.rendererKey){var l=this.renderers.get(h.rendererKey);const p=this.acquireRenderer(f,
g,k);l.removeRenderable(h);l.refCount.decrement();h.rendererKey=m;p.addRenderable(h)}for(l=0;l<c.length;l++)h.components.meta[l].material=c[l];e&&this.updateComponentBuffer(h.components);this.updateTransparency(h)});this.setNeedsRender()});return function(a,c,d,e){return b.apply(this,arguments)}}();n.updateObjectVisibility=function(){var b=u._asyncToGenerator(function*(a,c){(yield this.updatingHandles.addPromise(this.getObjectEntry(a))).renderables.forEach(d=>d.visible=c);this.setNeedsRender()});
return function(a,c){return b.apply(this,arguments)}}();n.removeObject=function(b){const a=this.perObjectData.get(b);a&&(this.perObjectData.delete(b),this._discardObjectEntry(a))};n.getObjectEntry=function(){var b=u._asyncToGenerator(function*(a){a=this.perObjectData.get(a);if(!a)throw"no object";yield a.loaded;return a});return function(a){return b.apply(this,arguments)}}();n.removeAll=function(){this.perObjectData.forEach((b,a)=>this.removeObject(a))};n.render=function(b,a){if(!t.isNone(this.componentColorManager)){this.localOrigins.updateViewMatrices(b.camera.viewMatrix);
var c=b.camera.viewInverseTransposeMatrix,d=I.create(),e=new Z.TwoVectorPosition,k=new Y.VertexPosition.ViewProjectionTransform,g=L.create();E.set(d,c[3],c[7],c[11]);e.set(d);E.copy(k.worldFromView_TH,e.high);E.copy(k.worldFromView_TL,e.low);H.fromMat4(k.viewFromCameraRelative_RS,b.camera.viewMatrix);W.copy(k.projFromView,b.camera.projectionMatrix);c=L.create();H.transpose(c,k.viewFromCameraRelative_RS);H.invert(g,c);var f=0,m=0;this.renderers.forEach(l=>{0===l.refCount.value?(this.renderers.delete(l.key),
l.dispose()):l.forEachRenderable(p=>{f+=p.statistics.averageEdgeLength;m++},a)});this.componentColorManager.garbageCollect();this.componentColorManager.updateTextures();if(0!==m){var h={distanceFalloffFactor:40*f/m,minimumEdgeLength:b.camera.perScreenPixelRatio,transparency:a,viewProjectionTransform:k,transformNormal_ViewFromGlobal:g};this.updateObjectCameraDistances(b);this.numberOfRenderedEdges=0;this.renderers.forEach(l=>{this.renderRegularEdges(l,b,h);this.renderSilhouetteEdges(l,b,h)})}}};n.updateTransparency=
function(b){const a=v.determineEdgeTransparency(b.components.meta),c=v.determineObjectTransparency(b.components.meta);if(a!==b.edgeTransparency||c!==b.objectTransparency)b.edgeTransparency=a,b.objectTransparency=c,this.renderers.get(b.rendererKey).setRenderablesDirty()};n.computeModelTransformWithLocalOrigin=function(b,a,c){b.getCombinedStaticTransformation(a,c);t.isSome(a.origin)?this.localOrigins.register(a.origin):(b=E.set(this.tmpModelPosition,c[12],c[13],c[14]),a.origin=this.localOrigins.acquire(b));
ba.applyToModelMatrix(a.origin.vec3,c);return a.origin};n.updateComponentBuffer=function(b){const {meta:a,buffer:c}=b;for(b=0;b<a.length;b++){var d=a[b].material;const e=a[b].index,k=K.clamp(Math.round(d.size*C.LINE_WIDTH_FRACTION_FACTOR),0,255),g=K.clamp(d.extensionLength,-C.EXTENSION_LENGTH_OFFSET,255-C.EXTENSION_LENGTH_OFFSET)+C.EXTENSION_LENGTH_OFFSET,f="solid"===d.type?0:1,m=255*d.opacity;d=d.color;c.textureBuffer.setData(e,0,255*d[0],255*d[1],255*d[2],255*d[3]);c.textureBuffer.setData(e,1,k,
g,f,m)}};n.createComponentBuffers=function(b){if(t.isNone(this.componentColorManager))return null;const a=[],c=this.componentColorManager.getBuffer(b.length);for(let d=0;d<b.length;d++){const e=b[d],k=c.acquireIndex();a.push({index:k,material:e})}b={meta:a,buffer:c};this.updateComponentBuffer(b);return b};n.extractEdges=function(b,a,c,d,e,k=e.length){return this.worker.process({data:a,indices:e,indicesLength:k,writerSettings:b,skipDeduplicate:c},this.workerAbort.signal,d)};n.createEdgeResources=function(b){const a=
{};if(t.isNone(this.verticesBufferObject))return a;if(0<b.regular.lodInfo.lengths.length){var c=new P(this.rctx,B.EdgeShaderAttributeLocations,{vertices:B.glVertexLayout,instances:O.RegularEdgeBufferWriter.glLayout},{vertices:this.verticesBufferObject,instances:J.createVertex(this.rctx,35044,b.regular.instancesData.buffer)});a.regular={vao:c,lod:b.regular.lodInfo}}0<b.silhouette.lodInfo.lengths.length&&(c=new P(this.rctx,B.EdgeShaderAttributeLocations,{vertices:B.glVertexLayout,instances:O.SilhouetteEdgeBufferWriter.glLayout},
{vertices:this.verticesBufferObject,instances:J.createVertex(this.rctx,35044,b.silhouette.instancesData.buffer)}),a.silhouette={vao:c,lod:b.silhouette.lodInfo});return a};n.addGeometry=function(){var b=u._asyncToGenerator(function*(a,c,d,e,k,g,f){const m=d.vertexAttributes.get("position"),h=d.indices.get("position"),l=M.create();a=this.computeModelTransformWithLocalOrigin(a,e,l);return this.addPositionData(c,{position:m,indices:h,modelTransform:l,origin:a},d.edgeIndicesLength,k,g,f)});return function(a,
c,d,e,k,g,f){return b.apply(this,arguments)}}();n.addPositionData=function(){var b=u._asyncToGenerator(function*(a,c,d,e,k,g=!1){if(null!=a.loaded){var f=this.createComponentBuffers([e]);if(!(t.isNone(f)||0>=d)){e=this.acquireRenderer(e.type,!!k.slicePlaneEnabled);var {modelTransform:m,origin:h}=c;k=c.indices;c=c.position;var l=c.data.length/c.size,p=B.EdgeInputBufferLayout.createBuffer(l);for(let x=0;x<l;x++)p.position.set(x,0,c.data[x*c.size]),p.position.set(x,1,c.data[x*c.size+1]),p.position.set(x,
2,c.data[x*c.size+2]);v.fillComponenBufferIndices(f.meta,[0,p.componentIndex.count],p.componentIndex);g=yield this.updatingHandles.addPromise(this.extractEdges(e.writerSettings,p,!1,g,k,d));if(null!=a.loaded){var {regular:r,silhouette:q}=this.createEdgeResources(g);d=(r?r.vao.size:0)+(q?q.vao.size:0);f={regular:r,silhouette:q,transform:{modelMatrix:m,origin:h},statistics:{gpuMemoryUsage:d,averageEdgeLength:g.averageEdgeLength},components:f,visible:!0,edgeTransparency:v.determineEdgeTransparency(f.meta),
objectTransparency:v.determineObjectTransparency(f.meta),distanceToCamera:0,rendererKey:e.key};a.renderables.push(f);e.addRenderable(f);this.gpuMemoryUsage+=d}}}});return function(a,c,d,e,k){return b.apply(this,arguments)}}();n.addComponentGeometry=function(){var b=u._asyncToGenerator(function*(a,c,d,e,k,g,f){if(null!=c.loaded){var m=this.createComponentBuffers(g);if(!t.isNone(m)&&(g=v.determineRendererType(g),f=this.acquireRenderer(g,f.slicePlaneEnabled||!1,!1),g=B.EdgeInputBufferLayout.createBuffer(d.count),
X.copy(g.position,d),v.fillComponenBufferIndices(m.meta,k,g.componentIndex,e),e=yield this.updatingHandles.addPromise(this.extractEdges(f.writerSettings,g,!0,!1,e)),null!=c.loaded)){var {regular:h,silhouette:l}=this.createEdgeResources(e);d=(h?h.vao.size:0)+(l?l.vao.size:0);a={regular:h,silhouette:l,transform:a,statistics:{gpuMemoryUsage:d,averageEdgeLength:e.averageEdgeLength},components:m,visible:!0,edgeTransparency:v.determineEdgeTransparency(m.meta),objectTransparency:v.determineObjectTransparency(m.meta),
distanceToCamera:0,rendererKey:f.key};c.renderables.push(a);f.addRenderable(a);this.gpuMemoryUsage+=d}}});return function(a,c,d,e,k,g,f){return b.apply(this,arguments)}}();n.addObjectMergedGeometries=function(){var b=u._asyncToGenerator(function*(a,c,d,e,k){var g=new Map,f=0,m=null,h=0;for(var l=0;l<a.geometries.length;l++){var p=a.geometries[l],r=a.geometryRecords[l];r.material.supportsEdges&&(!m&&r.origin&&(m=r),r=p.vertexAttributes.get("position"),h+=r.data.length/r.size,f+=p.edgeIndicesLength)}h=
65536<=h?Uint32Array:Uint16Array;f=f?new h(f):null;h=[];l=0;for(p=0;p<a.geometries.length;p++){r=a.geometries[p];if(!a.geometryRecords[p].material.supportsEdges)continue;var q=r.vertexAttributes.get("position");const x=r.indices.get("position");let G=g.get(q.data);if(null==G){G=h.length/3;for(let F=0;F<q.data.length;F+=q.size)h.push(q.data[F+0]),h.push(q.data[F+1]),h.push(q.data[F+2]);g.set(q.data,G)}if(x)for(q=0;q<r.edgeIndicesLength;q++)f[l++]=G+x[q]}m=m||a.geometryRecords[0];g=M.create();m=this.computeModelTransformWithLocalOrigin(a,
m,g);for(l=0;l<a.geometryRecords.length;l++)a.geometryRecords[l].origin=m;yield this.updatingHandles.addPromise(this.addPositionData(c,{position:{data:h,size:3},indices:f,modelTransform:g,origin:m},f.length,d[0],e,k))});return function(a,c,d,e,k){return b.apply(this,arguments)}}();n.acquireRenderer=function(b,a,c=!0){const d=C.EdgeRenderer.getKey(b,a,c);let e=this.renderers.get(d);t.isNone(this.strokesTexture)&&(this.strokesTexture=fa.generateStrokesTexture(this.rctx));e||(e=new C.EdgeRenderer(this.rctx,
this.techniqueRepository,{type:b,slicePlaneEnabled:a,strokesTexture:this.strokesTexture,legacy:c}),this.renderers.set(d,e));e.refCount.increment();return e};n.removeRenderable=function(b){b.regular&&(b.regular.vao.vertexBuffers.instances.dispose(),b.regular.vao.dispose(!1),b.regular.vao=null);b.silhouette&&(b.silhouette.vao.vertexBuffers.instances.dispose(),b.silhouette.vao.dispose(!1),b.silhouette.vao=null);const a=this.renderers.get(b.rendererKey);if(a){a.removeRenderable(b);a.refCount.decrement();
"origin"in b.transform&&this.localOrigins.release(b.transform.origin);this.gpuMemoryUsage-=b.statistics.gpuMemoryUsage;for(const c of b.components.meta)b.components.buffer.releaseIndex(c.index)}};n.updateObjectCameraDistances=function(b){const a=b.camera.eye,c=b.camera.viewForward,d=I.create();b=e=>{const {center:k,radius:g}=e;E.sub(d,k,a);const f=E.dot(d,c),m=f<-g?Infinity:f<g?0:f-g;e.renderables.forEach(h=>h.distanceToCamera=m)};this.perObjectData.forEach(b);this.perObjectDataEvictionCache.forEach(b)};
n.renderRegularEdges=function(b,a,c){b.bindRegularEdges(a,c);b.forEachRenderable(d=>{if(d.visible&&d.regular){var e=v.computeEdgeCount(d.regular.lod.lengths,d.distanceToCamera,c);"origin"in d.transform&&(a.localViewMatrixForEdges=this.localOrigins.getViewMatrix(d.transform.origin));b.renderRegularEdges(d,a,e);this.numberOfRenderedEdges+=e}},c.transparency)};n.renderSilhouetteEdges=function(b,a,c){b.bindSilhouetteEdges(a,c);b.forEachRenderable(d=>{if(d.visible&&d.silhouette){var e=v.computeEdgeCount(d.silhouette.lod.lengths,
d.distanceToCamera,c);"origin"in d.transform&&(a.localViewMatrixForEdges=this.localOrigins.getViewMatrix(d.transform.origin));b.renderSilhouetteEdges(d,a,e);this.numberOfRenderedEdges+=e}},c.transparency)};u._createClass(y,[{key:"updating",get:function(){return this.updatingHandles.updating}},{key:"usedMemory",get:function(){return this.gpuMemoryUsage}},{key:"numberOfRenderedPrimitives",get:function(){return this.numberOfRenderedEdges}}]);return y}(R);z.__decorate([A.property({constructOnly:!0})],
w.EdgeView.prototype,"rctx",void 0);z.__decorate([A.property({constructOnly:!0})],w.EdgeView.prototype,"renderSR",void 0);z.__decorate([A.property({constructOnly:!0})],w.EdgeView.prototype,"techniqueRepository",void 0);z.__decorate([A.property({constructOnly:!0})],w.EdgeView.prototype,"setNeedsRender",void 0);z.__decorate([A.property({constructOnly:!0})],w.EdgeView.prototype,"schedule",void 0);z.__decorate([A.property({readOnly:!0})],w.EdgeView.prototype,"updatingHandles",void 0);z.__decorate([A.property({readOnly:!0})],
w.EdgeView.prototype,"updating",null);w.EdgeView=z.__decorate([V.subclass("esri.views.3d.webgl-engine.lib.edgeRendering.EdgeView")],w.EdgeView);let Q=function(D,y,n){this.center=y;this.radius=n;this.renderables=[];this.loaded=D;this.loaded.then(()=>{null!=this.loaded&&(this.loaded=!0)})};Object.defineProperty(w,"__esModule",{value:!0})});