// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
require({cache:{"esri/libs/i3s/I3SModule":function(){define(["require","exports","../../assets"],function(k,r,E){function l(p){return E.getAssetUrl(`esri/libs/i3s/${p}`)}let A;r.get=function(){A||(A=(new Promise(p=>(new Promise(function(q,t){k(["../../chunks/i3s"],q,t)})).then(function(q){return q.i3s}).then(({default:q})=>{const t=q({locateFile:l,onRuntimeInitialized:()=>p(t)});delete t.then}))).catch(p=>Promise.reject(p)));return A};Object.defineProperty(r,"__esModule",{value:!0})})},"*noref":1}});
define(["exports","../../../chunks/_rollupPluginBabelHelpers","../../../core/maybe","../../../core/typedArrayUtil","../../../libs/i3s/I3SModule"],function(k,r,E,l,A){function p(){p=r._asyncToGenerator(function*(a){yield y();const c=[a.geometryBuffer];return{result:I(a,c),transferList:c}});return p.apply(this,arguments)}function q(){q=r._asyncToGenerator(function*(a){var c;yield y();const e=[a.geometryBuffer];var {geometryBuffer:g}=a,h=g.byteLength;a=d._malloc(h);h=new Uint8Array(d.HEAPU8.buffer,a,
h);h.set(new Uint8Array(g));g=d.dracoDecompressPointCloudData(a,h.byteLength);d._free(a);if(0<g.error.length)throw`i3s.wasm: ${g.error}`;a=0<(null==(c=g.featureIds)?void 0:c.length)?l.slice(g.featureIds):null;c=l.slice(g.positions);a&&e.push(a.buffer);e.push(c.buffer);return{result:{positions:c,featureIds:a},transferList:e}});return q.apply(this,arguments)}function t(){t=r._asyncToGenerator(function*(a){yield y();J(a);a={buffer:a.buffer};return{result:a,transferList:[a.buffer]}});return t.apply(this,
arguments)}function F(){F=r._asyncToGenerator(function*(a){yield y();K(a)});return F.apply(this,arguments)}function G(){G=r._asyncToGenerator(function*(a){yield y();d.setLegacySchema(a.context,a.jsonSchema)});return G.apply(this,arguments)}function K(a){const c=a.modifications,e=d._malloc(8*c.length),g=new Float64Array(d.HEAPU8.buffer,e,c.length);for(let h=0;h<c.length;++h)g[h]=c[h];d.setModifications(a.context,e,c.length,a.isGeodetic);d._free(e)}function I(a,c){if(!d)return null;const {context:e,
localOrigin:g,globalTrafo:h,mbs:B,obb:C,elevationOffset:O,geometryBuffer:H,geometryDescriptor:L,indexToVertexProjector:P,vertexToRenderProjector:Q}=a;var u=d._malloc(H.byteLength),v=d._malloc(33*Float64Array.BYTES_PER_ELEMENT),b=new Uint8Array(d.HEAPU8.buffer,u,H.byteLength);b.set(new Uint8Array(H));var f=new Float64Array(d.HEAPU8.buffer,v,33);z(f,g);var m=f.byteOffset+3*f.BYTES_PER_ELEMENT,n=new Float64Array(f.buffer,m);z(n,h);m+=16*f.BYTES_PER_ELEMENT;n=new Float64Array(f.buffer,m);z(n,B);m+=4*
f.BYTES_PER_ELEMENT;E.isSome(C)&&(n=new Float64Array(f.buffer,m),z(n,C.center),m+=3*f.BYTES_PER_ELEMENT,n=new Float64Array(f.buffer,m),z(n,C.halfSize),m+=3*f.BYTES_PER_ELEMENT,n=new Float64Array(f.buffer,m),z(n,C.quaternion));f={isDraco:!1,isLegacy:!1,color:a.layouts.some(w=>w.some(x=>"color"===x.name)),normal:a.needNormals&&a.layouts.some(w=>w.some(x=>"normalCompressed"===x.name)),uv0:a.layouts.some(w=>w.some(x=>"uv0"===x.name)),uvRegion:a.layouts.some(w=>w.some(x=>"uvRegion"===x.name)),featureIndex:L.featureIndex};
b=d.process(e,!!a.obb,u,b.byteLength,L,f,v,O,P,Q,a.normalReferenceFrame);d._free(v);d._free(u);if(0<b.error.length)throw`i3s.wasm: ${b.error}`;if(b.discarded)return null;u=0<b.componentOffsets.length?l.slice(b.componentOffsets):null;v=0<b.featureIds.length?l.slice(b.featureIds):null;f=l.slice(b.interleavedVertedData).buffer;m=1===b.indicesType?l.slice(new Uint16Array(b.indices.buffer,b.indices.byteOffset,b.indices.byteLength/2)):l.slice(new Uint32Array(b.indices.buffer,b.indices.byteOffset,b.indices.byteLength/
4));n=l.slice(b.positions);const M=1===b.positionIndicesType?l.slice(new Uint16Array(b.positionIndices.buffer,b.positionIndices.byteOffset,b.positionIndices.byteLength/2)):l.slice(new Uint32Array(b.positionIndices.buffer,b.positionIndices.byteOffset,b.positionIndices.byteLength/4));a={layout:a.layouts[0],interleavedVertexData:f,indices:m,hasColors:b.hasColors,hasModifications:b.hasModifications,positionData:{data:n,indices:M}};v&&c.push(v.buffer);u&&c.push(u.buffer);c.push(f);c.push(m.buffer);c.push(n.buffer);
c.push(M.buffer);return{componentOffsets:u,featureIds:v,transformedGeometry:a,obb:b.obb}}function J(a){const {context:c,buffer:e}=a;a=d._malloc(e.byteLength);const g=e.byteLength/Float64Array.BYTES_PER_ELEMENT,h=new Float64Array(d.HEAPU8.buffer,a,g),B=new Float64Array(e);h.set(B);d.filterOBBs(c,a,g);B.set(h);d._free(a)}function N(a){d&&d.destroy(a)}function z(a,c){for(let e=0;e<c.length;++e)a[e]=c[e]}function y(){if(d)return Promise.resolve();D||(D=A.get().then(a=>{d=a;D=null}));return D}let D,d;
const R={transform:I,destroy:N};k.destroyContext=function(a){N(a)};k.dracoDecompressPointCloudData=function(a){return q.apply(this,arguments)};k.filterObbsForModifications=function(a){return t.apply(this,arguments)};k.filterObbsForModificationsSync=J;k.initialize=y;k.interpretObbModificationResults=function(a){return 0===a?0:1===a?1:2===a?2:3};k.process=function(a){return p.apply(this,arguments)};k.setLegacySchema=function(a){return G.apply(this,arguments)};k.setModifications=function(a){return F.apply(this,
arguments)};k.setModificationsSync=K;k.test=R;Object.defineProperty(k,"__esModule",{value:!0})});