// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("require ../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../intl ../core/accessorSupport/decorators/aliasOf ../core/has ../core/accessorSupport/ensureType ../core/Logger ../core/accessorSupport/decorators/property ../core/accessorSupport/decorators/subclass ../layers/support/domainUtils ../layers/support/fieldUtils ./Widget ./FeatureForm/FeatureFormViewModel ./support/Heading ./support/widgetUtils ./support/decorators/messageBundle ./support/decorators/vmEvent ./support/jsxFactory ../chunks/datetime ../intl/locale".split(" "),
function(G,v,q,n,w,P,Q,R,A,H,I,J,K,L,C,S,M,N,k,x,D){const E={datePattern:"D",timePattern:"tt"};n=function(F){function B(a,b){var c=F.call(this,a,b)||this;c._activeDateFieldEdit=null;c._activeInputName=null;c._fieldFocusNeeded=!1;c._fieldToInitialIncompatibleDomainValue=new Map;c._switchFieldsWithInitialIncompatibleValue=new Set;c._userUpdatedInputFieldNames=new Set;c.description=null;c.feature=null;c.fieldConfig=null;c.formTemplate=null;c.groupDisplay="all";c.headingLevel=2;c.label=void 0;c.layer=
null;c.messages=null;c.strict=null;c.title=null;c.viewModel=new L;c._handleRadioInputChange=d=>{c._commitInputValue(d.target)};c._handleInputInput=d=>{c._commitInputValue(d.target,!0)};c._handleFormKeyDown=c._handleFormKeyDown.bind(v._assertThisInitialized(c));c._handleInputBlur=c._handleInputBlur.bind(v._assertThisInitialized(c));c._handleInputFocus=c._handleInputFocus.bind(v._assertThisInitialized(c));c._handleNumberInputMouseDown=c._handleNumberInputMouseDown.bind(v._assertThisInitialized(c));
c._handleInputKeyDown=c._handleInputKeyDown.bind(v._assertThisInitialized(c));c._handleOptionChange=c._handleOptionChange.bind(v._assertThisInitialized(c));c._handleGroupClick=c._handleGroupClick.bind(v._assertThisInitialized(c));c._handleSubmit=c._handleSubmit.bind(v._assertThisInitialized(c));c._afterInputCreateOrUpdate=c._afterInputCreateOrUpdate.bind(v._assertThisInitialized(c));return c}v._inheritsLoose(B,F);var h=B.prototype;h.initialize=function(){this.own(this.watch("feature",()=>{const a=
this._getFocusableInput("forward");this._activeInputName=a&&a.name;this._userUpdatedInputFieldNames.clear();this._fieldToInitialIncompatibleDomainValue.clear();this._switchFieldsWithInitialIncompatibleValue.clear();this._fieldFocusNeeded=!0}),this.on("submit",a=>{if(0<a.invalid.length){const [b]=a.invalid;a.invalid.forEach(c=>this._userUpdatedInputFieldNames.add(c));this._activeInputName=b;this._fieldFocusNeeded=!0;this.scheduleRender()}}))};h.loadDependencies=function(){return new Promise(function(a,
b){G(["../chunks/switch"],a,b)})};h.destroy=function(){this._userUpdatedInputFieldNames.clear();this._userUpdatedInputFieldNames=null};h.getValues=function(){return null};h.submit=function(){return null};h.render=function(){const {state:a}=this.viewModel;return k.tsx("div",{class:this.classes("esri-feature-form","esri-widget","esri-widget--panel")},"ready"===a?this.renderForm():null)};h.renderForm=function(){var a=this.title?k.tsx(C.Heading,{key:"title",level:this.headingLevel},this.title):null;const b=
this.description?k.tsx("p",{class:"esri-feature-form__description-text",key:"description"},this.description):null;a=a||b?k.tsx("div",{class:"esri-feature-form__form-header"},a,b):null;return k.tsx("form",{class:"esri-feature-form__form",novalidate:!0,onsubmit:this._handleSubmit,onkeydown:this._handleFormKeyDown},a,this.renderFields())};h.renderFields=function(){const {viewModel:{inputFields:a}}=this;return a.map((b,c)=>b&&b.inputFields?this.renderGroup(b,c):this.renderLabeledField(b))};h.renderGroup=
function(a,b){const {description:c,inputFields:d,label:e,state:f}=a;var g=this.viewModel.findField(this._activeInputName);g=!(!g||g.group!==a);const m=`${this.id}_group_${b}`,l=`${this.id}_group-label_${b}`,p=`${this.id}_group-description_${b}`,t=c?k.tsx("p",{class:this.classes("esri-feature-form__group-description","esri-feature-form__description-text"),id:p},c):null,r="sequential"===this.groupDisplay,u=r?g:"expanded"===f,z=u?"esri-icon-up":"esri-icon-down";return k.tsx("fieldset",{"aria-expanded":u.toString(),
"aria-labelledby":l,"aria-describedby":c?p:"",class:this.classes("esri-feature-form__group",r?"esri-feature-form__group--sequential":null,u?null:"esri-feature-form__group--collapsed",g?"esri-feature-form__group--active":null),"data-group":a,id:m,key:b,onclick:this._handleGroupClick},k.tsx("button",{role:r?"presentation":void 0,class:"esri-feature-form__group-header",type:"button",tabIndex:r?-1:0},k.tsx("div",{class:"esri-feature-form__group-title"},k.tsx(C.Heading,{class:"esri-feature-form__group-label",
id:l,level:this.headingLevel+(this.title?1:0)},e),t),r?null:k.tsx("span",{class:this.classes(z,"esri-feature-form__group-toggle-icon")})),d.map(y=>this.renderLabeledField(y)))};h._getFocusableInput=function(a,b){var c=this.viewModel._allInputFields;c="forward"===a?c:c.slice().reverse();b?b&&b.inputFields?a=c.indexOf(b.inputFields[0]):(this._isFieldInClosedCollapsibleGroup(b)?({inputFields:b}=b.group,a="forward"===a?b[b.length-1]:b[0]):a=b,a=c.indexOf(a)+1):a=0;for(;a<c.length;a++)if(b=c[a],b.visible)return b;
return null};h.renderLabeledField=function(a){const {label:b,layer:c,type:d}=a;return k.tsx("label",{key:`${c.id}-${a.name}`,class:"esri-feature-form__label"},[b,"unsupported"!==d?this.renderInputField(a):this.renderUnsupportedField(a),this.renderAuxiliaryText(a)])};h.renderInputField=function(a){var {viewModel:b}=this;const {domain:c,editable:d,name:e,type:f}=a;b=b.getValue(e);const g=!d,m=this.getCommonInputProps(a);if("coded-value"===(null==c?void 0:c.type)&&!g){if("switch"===a.editorType)if(this._switchFieldsWithInitialIncompatibleValue.has(e)||
null==b||a.config.onValue!==b&&a.config.offValue!==b)this._switchFieldsWithInitialIncompatibleValue.add(e);else return this.renderSwitchInputField(b,m);return"radio-buttons"===a.editorType?this.renderRadioButtonsInputField(b,c.codedValues.map(({code:l,name:p})=>({value:l,name:p})),m):this.renderSelectInputField(b,c.codedValues.map(({code:l,name:p})=>({value:l,name:p})),m)}return"text"===f&&"text-area"===a.editorType||"rich-text"===a.editorType?k.tsx("textarea",{...m}):"datetime-picker"===a.editorType||
"date"===f?this.renderDateInputField(b,m):k.tsx("input",{type:"text"===f?"text":"number",...m})};h._parseDateTime=function(a,b,c){if(c){var d;a=x.DateTime.fromJSDate(this._parseDate(a,c));b=x.DateTime.fromMillis(null!=(d=b.value)?d:Date.now());a="date"===c?a.set({hour:b.hour,minute:b.minute,second:b.second}):a.set({day:b.day,month:b.month,year:b.year});return a.isValid?a.toMillis():null}c=x.DateTime.fromJSDate(this._parseDate(a));return c.isValid?c.toMillis():null};h.renderDateInputField=function(a,
b){const {date:c,time:d}=this._formatDate(0);var e=`${this.id}-${b.key}`;const f=`${e}-date`;e=`${e}-time`;const g=b["data-field"],{includeTime:m}=g,{_activeDateFieldEdit:l}=this;let {date:p,time:t}=this._formatDate(a);if((null==l?void 0:l.fieldName)===g.name){var r,u,z,y;p=null!=(r=null==(u=l.date.input)?void 0:u.value)?r:p;t=null!=(z=null==(y=l.time.input)?void 0:y.value)?z:t}return k.tsx("div",{key:`${b.key}-date`,class:"esri-feature-form__date-input-container"},k.tsx("div",{class:this.classes("esri-feature-form__date-input-part",
m?null:"esri-feature-form__date-input-part--lone")},k.tsx("input",{"aria-label":g.label,"aria-describedby":f,type:"text",...b,"data-date-part":"date",class:this.classes(b.class,"esri-feature-form__input--date"),value:p}),k.tsx("div",{class:"esri-feature-form__date-format-hint",id:f},c)),m?k.tsx("div",{class:"esri-feature-form__date-input-part",key:"time-input"},k.tsx("input",{"aria-describedby":e,"aria-label":g.label,type:"text",...b,"data-date-part":"time",class:this.classes(b.class,"esri-feature-form__input--time"),
value:t}),k.tsx("div",{class:"esri-feature-form__date-format-hint",id:e},d)):null)};h.renderUnsupportedField=function(a){a=this.getCommonInputProps(a);return k.tsx("input",{afterCreate:a.afterCreate,afterUpdate:a.afterUpdate,class:this.classes("esri-input","esri-feature-form__input","esri-feature-form__input--disabled"),"data-field":a["data-field"],onfocus:a.onfocus,readOnly:!0,tabIndex:a.tabIndex,type:"text",value:a.value})};h.renderSelectInputField=function(a,b,c){const d=b.map(g=>k.tsx("option",
{value:`${g.value}`,key:g.name},g.name)),e=c["data-field"];this.registerIncompatibleValue(a,b,e,g=>{d.unshift(k.tsx("option",{value:`${g}`,key:"incompatible-option",readOnly:!0},g))});if(!e.required&&("combo-box"!==e.editorType||e.config.showNoValueOption)){var f;a=(null==(f=e.config)?void 0:f.noValueOptionLabel)||this.messages.empty;d.unshift(k.tsx("option",{value:"",key:"empty-option"},a))}return k.tsx("select",{...c,class:this.classes(c.class,"esri-select"),onchange:this._handleOptionChange},d)};
h.registerIncompatibleValue=function(a,b,c,d){const e=this._fieldToInitialIncompatibleDomainValue,f=e.has(c.name);if(f||null!=a&&""!==a&&!b.find(g=>g.value===a)||f)f||e.set(c.name,a),null==d?void 0:d(e.get(c.name))};h.renderRadioButtonsInputField=function(a,b,c){const d=c["data-field"],e=b.map(g=>this.renderRadioButton({key:g.name,label:g.name,name:d.name,value:g.value,selected:g.value===a,props:c}));this.registerIncompatibleValue(a,b,d);if(!d.required&&(!d.config||d.config.showNoValueOption)){var f;
b=(null==(f=d.config)?void 0:f.noValueOptionLabel)||this.messages.empty;e.unshift(this.renderRadioButton({key:"empty-option",label:b,name:d.name,value:"",selected:""===a||null===a,props:c}))}return k.tsx("div",{key:`${c.key}-radio`,class:"esri-feature-form__input--radio-group"},e)};h.renderSwitchInputField=function(a,b){return k.tsx("calcite-switch",{...b,class:"esri-feature-form__input--switch",switched:a===b["data-field"].config.onValue,onCalciteSwitchChange:c=>{this._parseValue(c.currentTarget)}})};
h.renderRadioButton=function({key:a,name:b,value:c,selected:d,label:e,props:f}){return k.tsx("label",{key:a,class:"esri-feature-form__input--radio-label"},k.tsx("input",{...f,class:"esri-feature-form__input--radio",name:b,type:"radio",value:c,checked:d,onchange:this._handleRadioInputChange}),e)};h.renderAuxiliaryText=function(a){if(this._userUpdatedInputFieldNames.has(a.name)&&!a.valid)return k.tsx("div",{key:"error-message"},k.tsx("span",{class:this.classes("esri-feature-form__input-icon--invalid",
"esri-icon-notice-triangle")}),k.tsx("div",{class:"esri-feature-form__field-error-message"},a.errorMessage));if(a.description)return k.tsx("div",{key:"description",class:"esri-feature-form__description-text"},a.description)};h.getCommonInputProps=function(a){const {groupDisplay:b,viewModel:c}=this,{editable:d,group:e,hint:f,maxLength:g,minLength:m,name:l,required:p,type:t,valid:r}=a,u=c.getValue(l),z=this._userUpdatedInputFieldNames.has(l),y=!d,O="all"===b&&"collapsed"===(null==e?void 0:e.state);
return{afterCreate:this._afterInputCreateOrUpdate,afterUpdate:this._afterInputCreateOrUpdate,"aria-invalid":r?"false":"true",class:this.classes("esri-input","esri-feature-form__input",y?"esri-feature-form__input--disabled":null,z&&!r?"esri-feature-form__input--invalid":null),key:l,minlength:-1<m?`${m}`:"",maxlength:-1<g?`${g}`:"",...this._getNumberFieldConstraints(a),readOnly:y,value:null==u?"":`${u}`,"data-field":a,onfocus:this._handleInputFocus,oninput:this._handleInputInput,onblur:this._handleInputBlur,
onkeydown:this._handleInputKeyDown,onmousedown:"number"===t?this._handleNumberInputMouseDown:null,placeholder:"number"===t||"text"===t?f:"",required:p,tabIndex:O?-1:0}};h._isFieldInClosedCollapsibleGroup=function(a){var b;return"all"===this.groupDisplay&&!(a&&a.inputFields)&&"collapsed"===(null==a?void 0:null==(b=a.group)?void 0:b.state)};h._handleNumberInputMouseDown=function({target:a}){a.focus();this.scheduleRender()};h._getNumberFieldConstraints=function(a){return(a=I.getDomainRange(a.domain)||
J.getFieldRange(a.field))&&a.max!==Number.MAX_VALUE&&a.min!==Number.MIN_VALUE?a:{min:null,max:null}};h._afterInputCreateOrUpdate=function(a){const b=a["data-field"],c=this.viewModel.findField(this._activeInputName),d=this._fieldToInitialIncompatibleDomainValue.get(b.name)===b.value;this._fieldFocusNeeded&&c===b&&("radio-buttons"!==b.editorType||d||a.checked)&&(this._fieldFocusNeeded=!1,a.focus())};h._handleInputFocus=function(a){a=a.target;const b=a["data-field"];this._activeInputName=b.name;"date"===
b.type&&this._syncDateFieldEdits(a)};h._handleInputBlur=function(a){const b=a.target,c=b["data-field"];if("date"===c.type){const f=a.relatedTarget;var d=f&&f["data-field"];if(d&&"date"===c.type&&"date"===d.type&&c.field===d.field){if(""!==b.value&&""===f.value){var e;d=f.getAttribute("data-date-part");f.value=this._formatDate(null!=(e=c.value)?e:Date.now())[d];this._parseDate(b.value,b.getAttribute("data-date-part"))&&this._commitInputValue(a.target,!0,!1)}return}}this._commitInputValue(b);this.scheduleRender()};
h._commitInputValue=function(a,b=!1,c=!0){const d=a["data-field"];if(this._activeDateFieldEdit){const {date:l,time:p}=this._activeDateFieldEdit,t=this._parseDateTime(a.value,d,l.active?"date":"time");a=null!==this.viewModel.getValue(d.name);const r=l.input&&(p.input||!d.includeTime),u=null===t;if(b)u||(r||!c||a)&&this._updateDateFieldValue(d,t);else{var e,f;if(""===(null==(e=l.input)?void 0:e.value)||""===(null==(f=p.input)?void 0:f.value))this._updateDateFieldValue(d,null);else if(r){var g,m;b=`${l.input.value} ${null!=
(g=null==(m=p.input)?void 0:m.value)?g:""}`;g=this._parseDateTime(b,d);null===g&&a||this._updateDateFieldValue(d,g)}this._activeDateFieldEdit=null}}else this._updateFieldValue(a)};h._handleInputKeyDown=function(a){const {key:b,altKey:c,ctrlKey:d,metaKey:e}=a;var f=a.target["data-field"];if("Enter"!==b){var {type:g}=f.field;f="single"===g||"double"===g;if(!("integer"!==g&&"small-integer"!==g&&!f||c||d||e)&&1===b.length){g=Number(b);const m=["-","+"],l=["e","."];f=f?[...m,...l]:m;isNaN(g)&&-1===f.indexOf(b)&&
a.preventDefault()}}else this._isFieldInClosedCollapsibleGroup(f)&&(f.group.state="expanded")};h._syncDateFieldEdits=function(a){var b,c;const d=a["data-field"];if("date"===d.type){var e=a.getAttribute("data-date-part"),f="date"===e?{value:a.value,input:a,active:!0}:{...null==(b=this._activeDateFieldEdit)?void 0:b.date,active:!1};a="time"===e?{value:a.value,input:a,active:!0}:{...null==(c=this._activeDateFieldEdit)?void 0:c.time,active:!1};this._activeDateFieldEdit={fieldName:d.name,date:f,time:a}}};
h._updateFieldValue=function(a){const b=a["data-field"];this.viewModel.setValue(b.name,this._parseValue(a));this._userUpdatedInputFieldNames.add(b.name)};h._updateDateFieldValue=function(a,b){this.viewModel.setValue(a.name,b);this._userUpdatedInputFieldNames.add(a.name)};h._parseValue=function(a){var b=a["data-field"],c=a.value;if("switch"===b.editorType&&!(a instanceof HTMLSelectElement))return a.switched?b.config.onValue:b.config.offValue;if("radio-buttons"===b.editorType&&"radio"===a.type&&!a.checked)return b.value;
var {type:d}=b;if("number"===d)return c?parseFloat(c):null;if("date"===d){if(!c)return null;d=Number(c);if(!isNaN(d))return d;a=a.getAttribute("data-date-part");c=this._parseDate(c,a);if(!c)return null;c=x.DateTime.fromJSDate(c);var e=b.domain;const f=x.DateTime.now();d=f;e&&"range"===e.type&&(e=x.DateTime.fromMillis(e.maxValue),f<e&&(d=e));b=this.viewModel.getValue(b.name);b=null!=b?x.DateTime.fromMillis(b):d;c="date"===a?c.set({hour:b.hour,minute:b.minute,second:b.second}):c.set({day:b.day,month:b.month,
year:b.year});return c.toMillis()}return c};h._handleOptionChange=function(a){this._commitInputValue(a.target);this.scheduleRender()};h._handleGroupClick=function(a){var b;const c=a.currentTarget["data-group"],d="expanded"===c.state,e="sequential"===this.groupDisplay;if(!d||a.target.closest(".esri-feature-form__group-header")){this._activeInputName=null==(b=this._getFocusableInput("forward",c))?void 0:b.name;if(e){a=a.target.closest(".esri-feature-form__group-header");if(d&&!a)return;this.viewModel.inputFields.forEach(f=>
{f&&f.inputFields&&f!==c&&(f.state="collapsed")})}c.state=d?"collapsed":"expanded";this._fieldFocusNeeded=e;this.scheduleRender()}};h._handleSubmit=function(a){a.preventDefault()};h._handleFormKeyDown=function(a){"Enter"===a.key&&this.viewModel.submit()};h._formatDate=function(a){if(null==a)return{date:"",time:""};a=x.DateTime.fromMillis(a,{locale:D.getLocale(),numberingSystem:"latn"});return{date:a.toLocaleString({year:"numeric",month:"2-digit",day:"2-digit"}),time:a.toFormat(E.timePattern)}};h._parseDate=
function(a,b){if(null==a||""===a)return null;const {timePattern:c,datePattern:d}=E;a=x.DateTime.fromFormat(a,b?"date"===b?d:c:`${d} ${c}`,{locale:D.getLocale(),numberingSystem:"latn"});return a.isValid?a.toJSDate():null};return B}(K);q.__decorate([w.aliasOf("viewModel.description")],n.prototype,"description",void 0);q.__decorate([w.aliasOf("viewModel.feature")],n.prototype,"feature",void 0);q.__decorate([w.aliasOf("viewModel.fieldConfig")],n.prototype,"fieldConfig",void 0);q.__decorate([w.aliasOf("viewModel.formTemplate")],
n.prototype,"formTemplate",void 0);q.__decorate([A.property()],n.prototype,"groupDisplay",void 0);q.__decorate([A.property()],n.prototype,"headingLevel",void 0);q.__decorate([A.property({aliasOf:{source:"messages.widgetLabel",overridable:!0}})],n.prototype,"label",void 0);q.__decorate([w.aliasOf("viewModel.layer")],n.prototype,"layer",void 0);q.__decorate([A.property(),M.messageBundle("esri/widgets/FeatureForm/t9n/FeatureForm")],n.prototype,"messages",void 0);q.__decorate([w.aliasOf("viewModel.strict")],
n.prototype,"strict",void 0);q.__decorate([w.aliasOf("viewModel.title")],n.prototype,"title",void 0);q.__decorate([A.property(),N.vmEvent(["value-change","submit"])],n.prototype,"viewModel",void 0);q.__decorate([w.aliasOf("viewModel.getValues")],n.prototype,"getValues",null);q.__decorate([w.aliasOf("viewModel.submit")],n.prototype,"submit",null);return n=q.__decorate([H.subclass("esri.widgets.FeatureForm")],n)});