// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../intl ../core/deprecate ../core/domUtils ../core/Evented ../core/Handles ../core/has ../core/lang ../core/Logger ../core/Promise ../core/promiseUtils ../core/uuid ../core/watchUtils ../core/accessorSupport/decorators/property ../core/accessorSupport/decorators/cast ../core/accessorSupport/decorators/subclass ../core/accessorSupport/tracking ../core/accessorSupport/tracking/SimpleTrackingTarget ../libs/maquette-advanced-projector/projector ../chunks/componentsUtils ./support/jsxWidgetSupport ./support/widgetUtils ../intl/locale ../intl/messages".split(" "),
function(q,f,d,G,H,I,J,Z,K,L,M,v,N,C,h,O,P,Q,R,S,T,y,D,U,V){function E(l,e){for(const c in e)null!=l[c]&&("object"===typeof l[c]&&"object"===typeof e[c]?E(l[c],e[c]):l[c]=e[c]);return l}const F=L.getLogger("esri.widgets.Widget");let W=0;const X=S.createAdvancedProjector({postProcessProjectionOptions(l){const e=l.eventHandlerInterceptor,c=/capture$/i;l.eventHandlerInterceptor=(b,m,a,k)=>{const n=e(b,m,a,k),t=c.test(b);b=b.replace(c,"");if(!(b.toLowerCase()in a)||t){const u=b[2].toLowerCase()+b.slice(3),
r=g=>n.call(a,g);a.addEventListener(u,r,t);const p=k.afterRemoved;k.afterRemoved=g=>{null==p?void 0:p(g);a.removeEventListener(u,r,t)}}return n}},handleInterceptedEvent(l,e,c,b){const {eventPhase:m,type:a}=b,k=m===Event.CAPTURING_PHASE;let n=`on${a}${k?"capture":""}`;e=e.properties;if(!(n in e||(n=`on${a[0].toUpperCase()}${a.slice(1)}${k?"Capture":""}`,n in e)))return;l.scheduleRender();e[n].call(e.bind||c,b)}});let z=!1;d=function(l){function e(b,m){var a=l.call(this,b,m)||this;a._attached=!1;a._internalHandles=
new J;a._projector=X;a.domNode=null;a.iconClass="esri-icon-checkbox-unchecked";a.label=a.declaredClass.split(".").pop();a.visible=!0;a.key=q._assertThisInitialized(a);a._loadLocale=v.debounce(q._asyncToGenerator(function*(){if(a._messageBundleProps&&a._messageBundleProps.length){const r=yield v.eachAlways(a._messageBundleProps.map(function(){var p=q._asyncToGenerator(function*({bundlePath:g,propertyName:A}){g=yield V.fetchMessageBundle(g);a.uiStrings&&Object.keys(a.uiStrings)&&(g=E(K.clone(g),a.uiStrings));
a[A]=g});return function(g){return p.apply(this,arguments)}}()));for(const p of r)p.error&&F.error("widget-intl:locale-error",a.declaredClass,p.error)}yield a.loadLocale()}));T.commitAssetPath();b=D.getThemeName()||"light";["light","dark"].includes(b)||G.deprecated(F,"The following themes are deprecated: light-blue, dark-blue, light-green, dark-green, light-purple, dark-purple, light-red, and dark-red.",{version:"4.19",warnOnce:!0,see:"https://developers.arcgis.com/javascript/latest/styling/"});const k=
"esri-widget-uid-"+N.generateUUID(),n=a.render.bind(q._assertThisInitialized(a));let t=!1;a._trackingTarget=new R.SimpleTrackingTarget(()=>a.scheduleRender());const u=()=>{var r;if(!t||a.destroyed)return null;if(!a.visible)return{vnodeSelector:"div",properties:{key:k,class:"",styles:{display:"none"}},domNode:void 0,children:void 0,text:void 0};const p=n();let {properties:g}=p;g||(p.properties=g={});let {key:A,styles:w}=g;A||(g.key=k);w||(g.styles=w={});w.display||(w.display="");let Y=0;null==(r=p.children)?
void 0:r.forEach(B=>{if(!y.isWidgetConstructor(B.vnodeSelector)){var {properties:x}=B;x||(B.properties=x={});x.key||(x.key=`${a.id}--${Y++}`)}});return y.processWidgets(q._assertThisInitialized(a),p)};a.render=()=>{if(z)return u();a._trackingTarget.clear();z=!0;let r;try{r=Q.runTracked(a._trackingTarget,u)}finally{z=!1}return r};a.addResolvingPromise(a._resourcesFetch=a.beforeFirstRender().then(()=>{t=!0;a._postInitialize()}));return a}q._inheritsLoose(e,l);var c=e.prototype;c.normalizeCtorArgs=function(b,
m){b={...b};m&&(b.container=m);return b};c.postInitialize=function(){};c.beforeFirstRender=function(){return Promise.all([this.loadDependencies(),this._loadLocale()]).then(()=>{}).catch(v.throwIfNotAbortError)};c.loadDependencies=function(){var b=q._asyncToGenerator(function*(){});return function(){return b.apply(this,arguments)}}();c.loadLocale=function(){var b=q._asyncToGenerator(function*(){});return function(){return b.apply(this,arguments)}}();c.destroy=function(){this.destroyed||(this._trackingTarget.destroy(),
this._trackingTarget=null,this.viewModel&&(this.viewModel.destroy(),this.viewModel=null),this._detach(this.container),this._set("container",null),this._internalHandles.destroy(),this._emitter.clear(),this.render=()=>null,this._projector=null)};c.castContainer=function(b){return H.byId(b)};c.render=function(){throw Error("not implemented");};c.scheduleRender=function(){this.destroyed||this._projector.scheduleRender()};c.classes=function(...b){return D.classes.apply(this,b)};c.own=function(b){1<arguments.length&&
(b=Array.prototype.slice.call(arguments));this._internalHandles.add(b)};c.renderNow=function(){this._projector.renderNow()};c._postInitialize=function(){var b,m=this;this.destroyed||(this.scheduleRender(),null!=(b=this._delegatedEventNames)&&b.length&&this._internalHandles.add(C.init(this,"viewModel",(a,k)=>{k&&this._internalHandles.remove("delegated-events");a&&this._internalHandles.add(this._delegatedEventNames.map(n=>a.on(n,t=>{this.emit(n,t)})),"delegated-events")})),this.postInitialize(),b=function(){var a=
q._asyncToGenerator(function*(){yield m._loadLocale().catch(v.throwIfNotAbortError);m.scheduleRender()});return function(){return a.apply(this,arguments)}}(),this._internalHandles.add([U.onLocaleChange(b),this.watch("uiStrings",b),C.whenOnce(this,"container",function(){var a=q._asyncToGenerator(function*(k){m.destroyed||m._attach(k)});return function(k){return a.apply(this,arguments)}}())]))};c._attach=function(b){b&&(this._projector.merge(b,this.render),this._attached=!0)};c._detach=function(b){b&&
this._attached&&(this._projector.detach(this.render),b.parentNode&&b.parentNode.removeChild(b),this._attached=!1)};q._createClass(e,[{key:"container",set:function(b){this._get("container")||this._set("container",b)}},{key:"id",get:function(){return this._get("id")||this.get("container.id")||Date.now().toString(16)+"-widget-"+W++},set:function(b){b&&this._set("id",b)}},{key:"renderable",get:function(){return this._resourcesFetch}},{key:"test",get:function(){return{projector:this._projector,handles:this._internalHandles}}}]);
return e}(M.EsriPromiseMixin(I.EventedAccessor));d[y.WIDGET_SYMBOL]=!0;f.__decorate([h.property({value:null})],d.prototype,"container",null);f.__decorate([O.cast("container")],d.prototype,"castContainer",null);f.__decorate([h.property({aliasOf:"container"})],d.prototype,"domNode",void 0);f.__decorate([h.property()],d.prototype,"iconClass",void 0);f.__decorate([h.property()],d.prototype,"id",null);f.__decorate([h.property()],d.prototype,"label",void 0);f.__decorate([h.property()],d.prototype,"renderable",
null);f.__decorate([h.property()],d.prototype,"uiStrings",void 0);f.__decorate([h.property()],d.prototype,"viewModel",void 0);f.__decorate([h.property()],d.prototype,"visible",void 0);f.__decorate([h.property()],d.prototype,"key",void 0);f.__decorate([h.property()],d.prototype,"children",void 0);f.__decorate([h.property()],d.prototype,"afterCreate",void 0);f.__decorate([h.property()],d.prototype,"afterUpdate",void 0);f.__decorate([h.property()],d.prototype,"afterRemoved",void 0);return d=f.__decorate([P.subclass("esri.widgets.Widget")],
d)});