// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../core/maybe ../../../chunks/mat4f64 ./DefaultErrorContext ./LoaderResult ./internal/Resource".split(" "),function(y,r,t,F,G,z,H){function w(){w=r._asyncToGenerator(function*(g,a,d={},l=!0){const c=yield H.Resource.load(g,u,a,d),e=`gltf_${I++}`,f={lods:[],materials:new Map,textures:new Map,meta:J(c)};g=!(!c.json.asset.extras||"symbolResource"!==c.json.asset.extras.ESRI_type);const n=new Map;yield K(c,function(){var h=r._asyncToGenerator(function*(b,
m,k,v){var q;const A=null!=(q=n.get(k))?q:0;n.set(k,A+1);var p=void 0!==b.mode?b.mode:4;q=4===p||5===p||6===p?p:null;if(t.isNone(q))u.warnUnsupported("Unsupported primitive mode ("+L[p]+"). Skipping primitive.");else if(c.hasPositions(b)){p=c.getPositionData(b,d);var M=c.getMaterial(b,d,l),B=c.hasNormals(b)?c.getNormalData(b,d):null,C=c.hasTangents(b)?c.getTangentData(b,d):null,D=c.hasTextureCoordinates(b)?c.getTextureCoordinates(b,d):null,E=c.hasVertexColors(b)?c.getVertexColors(b,d):null;b=c.getIndexData(b,
d);m={transform:F.clone(m),attributes:{position:yield p,normal:B?yield B:null,texCoord0:D?yield D:null,color:E?yield E:null,tangent:C?yield C:null},indices:yield b,primitiveType:q,material:N(f,yield M,e)};b=null;t.isSome(f.meta)&&t.isSome(f.meta.ESRI_lod)&&"screenSpaceRadius"===f.meta.ESRI_lod.metric&&(b=f.meta.ESRI_lod.thresholds[k]);f.lods[k]=f.lods[k]||{parts:[],name:v,lodThreshold:b};f.lods[k].parts[A]=m}else u.warn("Skipping primitive without POSITION vertex attribute.")});return function(b,
m,k,v){return h.apply(this,arguments)}}());for(const h of f.lods)h.parts=h.parts.filter(b=>!!b);return{model:f,meta:{isEsriSymbolResource:g,uri:c.uri},customMeta:{}}});return w.apply(this,arguments)}function J(g){let a=null;g.json.nodes.forEach(d=>{d=d.extras;t.isSome(d)&&(d.ESRI_proxyEllipsoid||d.ESRI_lod)&&(a=d)});return a}function K(g,a){return x.apply(this,arguments)}function x(){x=r._asyncToGenerator(function*(g,a){function d(h,b){return l.apply(this,arguments)}function l(){l=r._asyncToGenerator(function*(h,
b){const m=c.nodes[h];h=g.getNodeTransform(h);u.warnUnsupportedIf(null!=m.weights,"Morph targets are not supported.");if(null!=m.mesh){const k=c.meshes[m.mesh];for(const v of k.primitives)n.push(a(v,h,b,k.name))}for(const k of m.children||[])n.push(d(k,b))});return l.apply(this,arguments)}const c=g.json;var e=c.scenes[c.scene||0].nodes;const f=1<e.length,n=[];for(const h of e)e=c.nodes[h],n.push(d(h,0)),e.extensions&&e.extensions.MSFT_lod&&Array.isArray(e.extensions.MSFT_lod.ids)&&!f&&e.extensions.MSFT_lod.ids.forEach((b,
m)=>d(b,m+1));yield Promise.all(n)});return x.apply(this,arguments)}function N(g,a,d){const l=e=>{const f=`${d}_tex_${e&&e.id}${e&&e.name?"_"+e.name:""}`;if(e&&!g.textures.has(f)){const n=z.makeTextureSource(e.data,{wrap:{s:e.wrapS,t:e.wrapT},mipmap:O.some(h=>h===e.minFilter),noUnpackFlip:!0});g.textures.set(f,n)}return f},c=`${d}_mat_${a.id}_${a.name}`;g.materials.has(c)||(a=z.makeMaterialParameters({color:[a.color[0],a.color[1],a.color[2]],opacity:a.color[3],alphaMode:a.alphaMode,alphaCutoff:a.alphaCutoff,
doubleSided:a.doubleSided,colorMixMode:a.ESRI_externalColorMixMode,textureColor:a.colorTexture?l(a.colorTexture):void 0,textureNormal:a.normalTexture?l(a.normalTexture):void 0,textureOcclusion:a.occlusionTexture?l(a.occlusionTexture):void 0,textureEmissive:a.emissiveTexture?l(a.emissiveTexture):void 0,textureMetallicRoughness:a.metallicRoughnessTexture?l(a.metallicRoughnessTexture):void 0,emissiveFactor:[a.emissiveFactor[0],a.emissiveFactor[1],a.emissiveFactor[2]],metallicFactor:a.metallicFactor,
roughnessFactor:a.roughnessFactor}),g.materials.set(c,a));return c}let I=0;const u=new G.DefaultErrorContext,O=[9987,9985],L="POINTS LINES LINE_LOOP LINE_STRIP TRIANGLES TRIANGLE_STRIP TRIANGLE_FAN".split(" ");y.load=function(g,a){return w.apply(this,arguments)};Object.defineProperty(y,"__esModule",{value:!0})});