// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../Color ../../../../core/maybe ../../../../core/screenUtils ../../../../chunks/earcut ../../../../chunks/mat4f64 ../../../../chunks/vec4 ../../../../geometry/support/aaBoundingBox ../../../../geometry/support/buffer/BufferView ./elevationAlignmentUtils ./ElevationContext ./Graphics3DDrapedGraphicLayer ./Graphics3DObject3DGraphicLayer ./Graphics3DSymbolLayer ./graphicUtils ./lineUtils ./polygonUtils ../support/patternUtils ../support/uvUtils ../../webgl-engine/lib/Object3D ../../webgl-engine/lib/RenderGeometry ../../webgl-engine/materials/lineStippleUtils ../../webgl-engine/materials/NativeLineMaterial ../../webgl-engine/materials/PatternMaterial ../../webgl-engine/materials/RibbonLineMaterial".split(" "),
function(w,x,C,d,y,D,E,F,m,t,q,L,M,N,u,O,G,r,H,I,P,J,z,A,Q,R){const S=["polyline","polygon","extent"];u=function(B){function v(a,b,c,e){a=B.call(this,a,b,c,e)||this;a._needsUV=!1;a._hasOutline=!1;return a}x._inheritsLoose(v,B);var h=v.prototype;h.doLoad=function(){var a=x._asyncToGenerator(function*(){});return function(){return a.apply(this,arguments)}}();h.ensureMaterials=function(){this.ensureFillMaterial();this.ensureOutlineMaterial()};h.ensureFillMaterial=function(){if(!d.isSome(this._material)){var a=
d.get(this.symbolLayer,"material","color");a=this._getCombinedOpacityAndColor(a);this._material=H.createMaterial(this.symbolLayer,{color:a,transparent:1>a[3]||this.needsDrivenTransparentPass,polygonOffset:!1,vertexColors:!0,writeLinearDepth:!0,slicePlaneEnabled:this._context.slicePlaneEnabled},{isDraped:this.draped});this._needsUV=this._material instanceof Q.PatternMaterial;this._context.stage.add(this._material)}};h.ensureOutlineMaterial=function(){const a=this.symbolLayer.outline;!d.isSome(this._outlineMaterial)&&
this._isValidOutline(a)&&(this._hasOutline=!0,this._outlineMaterial=(b=>{const c=d.mapOr(a.stipplePattern,z.scaleStipplePattern(z.getStipplePatternForLinePattern(a.pattern),y.pt2px(a.size)),f=>z.createStipplePattern(f.map(y.pt2px))),e=a.stippleOffColor?C.toUnitRGBA(a.stippleOffColor):null;return 1.5<b?new R.RibbonLineMaterial({width:b,color:this._getOutlineColor(),polygonOffset:!0,slicePlaneEnabled:this._context.slicePlaneEnabled,isClosed:!0,stipplePattern:c,stippleIntegerRepeats:!0,stippleOffColor:e,
cap:a.patternCap||"butt"}):new A.NativeLineMaterial({color:this._getOutlineColor(),slicePlaneEnabled:this._context.slicePlaneEnabled,width:b,stipplePattern:c,stippleIntegerRepeats:!0,stippleOffColor:e})})(y.pt2px(a.size)),this._context.stage.add(this._outlineMaterial))};h._isValidOutline=function(a){return d.isSome(a)&&a.size&&0<a.size&&d.isSome(a.color)&&"none"!==a.pattern};h.destroy=function(){B.prototype.destroy.call(this);this._context.stage.remove(this._material);this._material=null;this._context.stage.remove(this._outlineMaterial);
this._outlineMaterial=null};h.createGraphics3DGraphic=function(a){const b=a.graphic;if(!this._validateGeometry(b.geometry,S,this.symbolLayer.type))return null;a=this._getVertexOpacityAndColor(a.renderingInfo,255);const c=this.setGraphicElevationContext(b,new L.ElevationContext);this.ensureDrapedStatus("on-the-ground"===c.mode);this.ensureMaterials();return this.draped?this._createAsOverlay(b,a):this._createAs3DShape(b,a,c)};h.layerOpacityChanged=function(){if(d.isSome(this._material)){var a=this._material.params.color,
b=d.get(this.symbolLayer,"material","color");b=this._getCombinedOpacity(b);this._material.setParameterValues({color:[a[0],a[1],a[2],b],transparent:1>b||this.needsDrivenTransparentPass})}d.isSome(this._outlineMaterial)&&(a=this._outlineMaterial.params.color,this._outlineMaterial.setParameterValues({color:[a[0],a[1],a[2],this._getOutlineOpacity()]}));return!0};h.layerElevationInfoChanged=function(a,b,c){const e=this._elevationContext.mode;c=q.elevationModeChangeUpdateType(v.elevationModeChangeTypes,
c,e);if(c!==q.SymbolUpdateType.UPDATE)return c;const f=q.needsElevationUpdates2D(e);return this.updateGraphics3DGraphicElevationInfo(a,b,()=>f)};h.slicePlaneEnabledChanged=function(){d.isSome(this._material)&&this._material.setParameterValues({slicePlaneEnabled:this._context.slicePlaneEnabled});d.isSome(this._outlineMaterial)&&this._outlineMaterial.setParameterValues({slicePlaneEnabled:this._context.slicePlaneEnabled});return!0};h.physicalBasedRenderingChanged=function(){return!0};h.pixelRatioChanged=
function(){return!0};h._createAs3DShape=function(a,b,c){const e=r.geometryAsPolygon(a.geometry);if(d.isNone(e))return null;g.renderData=r.geometryToRenderInfo(e,this._context.elevationProvider,this._context.renderCoordsHelper,c);g.color=b;b=g.renderData.position.length/3;this._needsUV&&(g.uvMapSpace=new Float32Array(4*b),g.boundingRect=new Float64Array(9*b));g.outNum=0;g.outGeometries=[];g.outTransforms=[];g.outMaterials=[];this._createAs3DShapeFill(g);this._hasOutline&&this._createAs3DShapeOutline(g);
this._logGeometryCreationWarnings(g.renderData,e.rings,"rings","FillSymbol3DLayer");if(0===g.outNum)return null;this._needsUV&&I.createMapSpaceUVCoords(t.BufferViewVec4f.fromTypedArray(g.uvMapSpace),t.BufferViewVec3f64.fromTypedArray(g.renderData.position),this._context.renderCoordsHelper,t.BufferViewMat3f64.fromTypedArray(g.boundingRect));a=new P.Object3D({geometries:g.outGeometries,materials:g.outMaterials,transformations:g.outTransforms,castShadow:!1,metadata:{layerUid:this._context.layer.uid,
graphicUid:a.uid}});a=new N.Graphics3DObject3DGraphicLayer(this,a,g.outGeometries,null,null,H.uvElevationAligner,c);a.alignedSampledElevation=g.renderData.sampledElevation;a.needsElevationUpdates=q.needsElevationUpdates2D(c.mode);return a};h._createAs3DShapeFill=function(a){var b=a.renderData.polygons;for(const {position:c,mapPosition:e,holeIndices:f,index:p,count:k}of b){if(d.isSome(this._context.clippingExtent)&&(m.empty(n),m.expandWithBuffer(n,e),!m.intersectsClippingArea(n,this._context.clippingExtent)))continue;
b=D.earcut(e,f,3);0!==b.length&&(b=new Uint32Array(b),b=r.createColorGeometry({indices:b,attributeData:{position:c,color:a.color,mapPosition:e,uvMapSpace:this._needsUV?new Float32Array(a.uvMapSpace.buffer,4*p*a.uvMapSpace.BYTES_PER_ELEMENT,4*k):null,boundingRect:this._needsUV?new Float64Array(a.boundingRect.buffer,9*p*a.boundingRect.BYTES_PER_ELEMENT,9*k):null}}),a.outGeometries.push(b),a.outMaterials.push(d.unwrap(this._material)),a.outTransforms.push(E.IDENTITY),a.outNum++)}};h._createAs3DShapeOutline=
function(a){if(this._hasOutline){var b=a.renderData.outlines,c=this._outlineMaterial instanceof A.NativeLineMaterial;for(let e=0;e<b.length;++e){const {mapPosition:f,position:p}=b[e];if(d.isSome(this._context.clippingExtent)&&(m.empty(n),m.expandWithBuffer(n,f),!m.intersectsClippingArea(n,this._context.clippingExtent)))continue;const k=G.createGeometry({removeDuplicateStartEnd:c?0:1,attributeData:{position:p,mapPosition:f}}),K=k.vertexAttributes.get("position");K.data===p&&(K.data=new Float64Array(p));
a.outGeometries.push(k);a.outMaterials.push(d.unwrap(this._outlineMaterial));a.outTransforms.push(E.IDENTITY);a.outNum++}}};h._createAsOverlay=function(a,b){const c=r.geometryAsPolygon(a.geometry);if(d.isNone(c))return null;d.unwrap(this._material).renderPriority=this._renderPriority+this._renderPriorityStep/2;d.isSome(this._outlineMaterial)&&(this._outlineMaterial.renderPriority=this._renderPriority);l.renderData=r.geometryToRenderInfoDraped(c,this._context.overlaySR);l.color=b;b=l.renderData.position.length/
3;this._needsUV&&(l.uvMapSpace=new Float32Array(4*b));l.outNum=0;l.outGeometries=[];l.outBoundingBox=m.empty();l.layerUid=this._context.layer.uid;l.graphicsUid=a.uid;this._createAsOverlayFill(l);this._hasOutline&&this._createAsOverlayOutline(l);this._logGeometryCreationWarnings(l.renderData,c.rings,"rings","FillSymbol3DLayer");if(0===l.outNum)return null;this._needsUV&&I.createMapSpaceUVCoordsDraped(t.BufferViewVec4f.fromTypedArray(l.uvMapSpace),t.BufferViewVec3f64.fromTypedArray(l.renderData.position),
this._context.overlaySR);return 0<l.outNum?new M(this,l.outGeometries,l.outBoundingBox):null};h._createAsOverlayFill=function(a){var b=a.renderData.polygons;for(const {position:c,holeIndices:e,index:f,count:p}of b){m.empty(n);m.expandWithBuffer(n,c);if(!m.intersectsClippingArea(n,this._context.clippingExtent))continue;b=D.earcut(c,e,3);if(0===b.length)continue;m.expandWithAABB(a.outBoundingBox,n);b=new Uint32Array(b);b=r.createColorGeometry({indices:b,attributeData:{position:c,color:a.color,uvMapSpace:this._needsUV?
new Float32Array(a.uvMapSpace.buffer,4*f*a.uvMapSpace.BYTES_PER_ELEMENT,4*p):null}});b=new J.RenderGeometry(b,d.unwrap(this._material),a.layerUid,a.graphicsUid);const k=n;F.set(b.boundingSphere,.5*(k[0]+k[3]),.5*(k[1]+k[4]),0,.5*Math.sqrt((k[3]-k[0])*(k[3]-k[0])+(k[4]-k[1])*(k[4]-k[1])));a.outGeometries.push(b);a.outNum++}};h._createAsOverlayOutline=function(a){if(this._hasOutline){var b=a.renderData.outlines;for(let e=0;e<b.length;++e){var {position:c}=b[e];m.empty(n);m.expandWithBuffer(n,c);if(!m.intersectsClippingArea(n,
this._context.clippingExtent))continue;m.expandWithAABB(a.outBoundingBox,n);c=G.createGeometry({removeDuplicateStartEnd:this._outlineMaterial instanceof A.NativeLineMaterial?0:1,attributeData:{position:c}});c=new J.RenderGeometry(c,d.unwrap(this._outlineMaterial),a.layerUid,a.graphicsUid);const f=n;F.set(c.boundingSphere,.5*(f[0]+f[3]),.5*(f[1]+f[4]),0,.5*Math.sqrt((f[3]-f[0])*(f[3]-f[0])+(f[4]-f[1])*(f[4]-f[1])));a.outGeometries.push(c);a.outNum++}}};h._getOutlineOpacity=function(){const a=d.get(this.symbolLayer,
"outline","color");return(this.draped?1:this._getLayerOpacity())*(d.isSome(a)?a.a:0)};h._getOutlineColor=function(){const a=d.get(this.symbolLayer,"outline","color"),b=this._getOutlineOpacity();return O.mixinColorAndOpacity(d.isSome(a)?C.toUnitRGB(a):null,b)};x._createClass(v,[{key:"test",get:function(){return{createAsOverlay:(a,b)=>this._createAsOverlay(a,b),createAs3DShape:(a,b,c)=>this._createAs3DShape(a,b,c)}}}]);return v}(u.Graphics3DSymbolLayer);u.elevationModeChangeTypes={definedChanged:q.SymbolUpdateType.RECREATE,
staysOnTheGround:q.SymbolUpdateType.NONE,onTheGroundChanged:q.SymbolUpdateType.RECREATE};const n=m.create(),g={renderData:null,color:null,uvMapSpace:null,boundingRect:null,outNum:0,outBoundingBox:null,outGeometries:null,outMaterials:null,outTransforms:null},l={renderData:null,color:null,uvMapSpace:null,outNum:0,outBoundingBox:null,outGeometries:null,outMaterials:null,outTransforms:null};w.Graphics3DPolygonFillSymbolLayer=u;w["default"]=u;Object.defineProperty(w,"__esModule",{value:!0})});