// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../request ../../../../core/asyncUtils ../../../../core/Error ../../../../core/Logger ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/Version ../../../../chunks/vec3f64 ../../../../geometry/support/aaBoundingBox ../../../../support/requestImageUtils ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/Texture ../../webgl-engine/materials/DefaultMaterial".split(" "),function(v,w,P,H,Q,R,u,I,J,K,z,S,T,U,V){function A(){A=
w._asyncToGenerator(function*(a,b){a=yield W(a,b);b=yield L(a.textureDefinitions,b);return{resource:a,textures:b}});return A.apply(this,arguments)}function W(a,b){return B.apply(this,arguments)}function B(){B=w._asyncToGenerator(function*(a,b){const f=u.isSome(b)&&b.streamDataRequester;if(f)return X(a,f,b);a=yield H.result(P(a,u.unwrap(b)));if(!0===a.ok)return a.value.data;I.throwIfAbortError(a.error);M(a.error)});return B.apply(this,arguments)}function X(a,b,f){return C.apply(this,arguments)}function C(){C=
w._asyncToGenerator(function*(a,b,f){a=yield H.result(b.request(a,"json",f));if(!0===a.ok)return a.value;I.throwIfAbortError(a.error);M(a.error.details.url)});return C.apply(this,arguments)}function M(a){throw new Q("",`Request for object resource failed: ${a}`);}function Y(a){const b=z.empty();a.forEach(f=>{f=f.boundingInfo;u.isSome(f)&&(z.expandWithVec3(b,f.getBBMin()),z.expandWithVec3(b,f.getBBMax()))});return b}function L(a,b){return D.apply(this,arguments)}function D(){D=w._asyncToGenerator(function*(a,
b){const f=[];for(const q in a){var m=a[q],l=m.images[0].data;if(!l){n.warn("Externally referenced texture data is not yet supported");continue}l=m.encoding+";base64,"+l;const r="/textureDefinitions/"+q,t="rgba"===m.channels?m.alphaChannelUsage||"transparency":"none",x={noUnpackFlip:!0,wrap:{s:10497,t:10497},preMultiplyAlpha:1!==N(t)};m=u.isSome(b)&&b.disableTextures?Promise.resolve(null):S.requestImage(l,b);f.push(m.then(E=>({refId:r,image:E,params:x,alphaChannelUsage:t})))}a=yield Promise.all(f);
b={};for(const q of a)b[q.refId]=q;return b});return D.apply(this,arguments)}function N(a){switch(a){case "mask":return 2;case "maskAndTransparency":return 3;case "none":return 1;case "transparency":return 0;default:return 0}}const n=R.getLogger("esri.views.3d.layers.graphics.objectResourceUtils"),Z=new J.Version(1,2,"wosr");v.createTextureResources=L;v.load=function(a,b){return A.apply(this,arguments)};v.processLoadResult=function(a,b){const f=[],m=[],l=[],q=[],r=a.resource;var t=J.Version.parse(r.version||
"1.0","wosr");Z.validate(t);t=r.model.name;const x=r.model.geometries,E=r.materialDefinitions;a=a.textures;let O=0;const F=new Map;for(let G=0;G<x.length;G++){var e=x[G],p=e,d=p.params,g=d.topology;var c=!0;d.vertexAttributes||(n.warn("Geometry must specify vertex attributes"),c=!1);switch(d.topology){case "PerAttributeArray":break;case "Indexed":case null:case void 0:g=d.faces;if(!g)n.warn("Indexed geometries must specify faces"),c=!1;else if(d.vertexAttributes)for(const h in d.vertexAttributes)(d=
g[h])&&d.values?(null!=d.valueType&&"UInt32"!==d.valueType&&(n.warn(`Unsupported indexed geometry indices type '${d.valueType}', only UInt32 is currently supported`),c=!1),null!=d.valuesPerElement&&1!==d.valuesPerElement&&(n.warn(`Unsupported indexed geometry values per element '${d.valuesPerElement}', only 1 is currently supported`),c=!1)):(n.warn(`Indexed geometry does not specify face indices for '${h}' attribute`),c=!1);break;default:n.warn(`Unsupported topology '${g}'`),c=!1}p.params.material||
(n.warn("Geometry requires material"),c=!1);p=p.params.vertexAttributes;for(const h in p)p[h].values||(n.warn("Geometries with externally defined attributes are not yet supported"),c=!1);if(c){c=e.params;c={id:1,material:c.material,texture:c.texture,region:c.texture};d=e.params.vertexAttributes;p=[];for(const h in d)g=d[h],p.push([h,{data:g.values,size:g.valuesPerElement,exclusive:!0}]);d=[];if("PerAttributeArray"!==e.params.topology){e=e.params.faces;for(const h in e)d.push([h,new Uint32Array(e[h].values)])}if((e=
a&&a[c.texture])&&!F.has(c.texture)){const {image:h,params:aa}=e;g=new U.Texture(h,aa);q.push(g);F.set(c.texture,g)}g=(g=F.get(c.texture))?g.id:void 0;var k=l[c.material]?l[c.material][c.texture]:null;if(!k){k=c.material.substring(c.material.lastIndexOf("/")+1);k=E[k].params;1===k.transparency&&(k.transparency=0);var y=e&&e.alphaChannelUsage;y=0<k.transparency||"transparency"===y||"maskAndTransparency"===y;const h=e?N(e.alphaChannelUsage):void 0;e={ambient:K.fromArray(k.diffuse),diffuse:K.fromArray(k.diffuse),
opacity:1-(k.transparency||0),transparent:y,textureAlphaMode:h,textureAlphaCutoff:.33,textureId:g,initTextureTransparent:!0,doubleSided:!0,cullFace:0,colorMixMode:k.externalColorMixMode||"tint",textureAlphaPremultiplied:e?!!e.params.preMultiplyAlpha:!1};u.isSome(b)&&b.materialParamsMixin&&Object.assign(e,b.materialParamsMixin);k=new V.DefaultMaterial(e);l[c.material]||(l[c.material]={});l[c.material][c.texture]=k}m.push(k);c=new T.Geometry(p,d);O+=d.position?d.position.length:0;f.push(c)}}return{name:t,
stageResources:{textures:q,materials:m,geometries:f},pivotOffset:r.model.pivotOffset,boundingBox:Y(f),numberOfVertices:O,lodThreshold:null}};Object.defineProperty(v,"__esModule",{value:!0})});