// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../../../../core/maybe ../../../../webgl/BufferObject ../../../../webgl/FramebufferObject ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../core/has ../../../../webgl/checkWebGLError ../../../../webgl/enums ../../../../../chunks/builtins ../../../../webgl/renderState ../../../../webgl/Texture ../../../../webgl/VertexArrayObject ../FeatureDisplayList ./Buffer ./DisplayRecordReader".split(" "),function(p,k,q,y,z,A,B,C,D,E,F,w,x,r,t){q=function(){function u(a,b){this._indicesInvalid=
!1;this.geometryType=a}var l=u.prototype;l.destroy=function(){this._vao&&(this._vao.dispose(),this._vao=null)};l.insert=function(a,b,c){if(a.records.byteLength)if(c=a.stride,this._vertexBuffer&&this._indexBuffer){var f=a.vertices.byteLength/c;this._indexBuffer.ensure(4*a.indices.byteLength);this._vertexBuffer.ensure(f);const {vertices:e,indices:d}=a;a=t.DisplayRecordReader.from(a.records);const g=this._vertexBuffer.insert(e,0,e.byteLength/c,0),m=this._indexBuffer.insert(d,0,d.byteLength/4,g);a.forEach(h=>
{h.indexFrom+=m;h.vertexFrom+=g});k.unwrapOrThrow(this._records,"Expected records to be defined").link(a);if(b)this._indicesInvalid=!0;else if(this._displayList)for(b=a.getCursor();b.next();)this._displayList.addRecord(b)}else{f=4*a.indices.byteLength;const e=a.vertices.byteLength/c,d=c/Uint32Array.BYTES_PER_ELEMENT;this._records=t.DisplayRecordReader.from(a.records);this._indexBuffer=new r.Buffer("index",f,1);this._vertexBuffer=new r.Buffer("vertex",e,d);this._indexBuffer.insert(a.indices,0,a.indices.byteLength/
4,0);this._vertexBuffer.insert(a.vertices,0,a.vertices.byteLength/c,0);b&&(this._indicesInvalid=!0)}};l.remove=function(a){if(!k.isNone(this._records))for(const b of a){a=this._records.getCursor();if(!a.lookup(b))continue;const c=a.indexFrom,f=a.vertexFrom;let e=a.indexCount,d=a.vertexCount;for(;a.next()&&a.id===b;)e+=a.indexCount,d+=a.vertexCount;this._indexBuffer.free(c,e);this._vertexBuffer.free(f,d,!0);this._records.delete(b)}};l.draw=function(a,b,c,f,e){if(this._vertexBuffer&&this._indexBuffer&&
!k.isNone(this._records)){if(k.isNone(this._vertexBuffer.gpu)||k.isNone(this._indexBuffer.gpu))this._vao&&(this._vao.dispose(),this._vao=null),this._vertexBuffer.gpu=null,this._indexBuffer.gpu=null;this._vertexBuffer.upload(a);this._indexBuffer.upload(a);if(!this._vao){const d=this._vertexBuffer.gpu,g=this._indexBuffer.gpu;if(!g||!d)return;this._vao=new w(a,c,b,{geometry:d},g)}b=f*Uint32Array.BYTES_PER_ELEMENT;a.bindVAO(this._vao);a.drawElements(4,e,5125,b)}};l.forEachCommand=function(a){if(!k.isNone(this._records)){this._sortIndices(this._records);
if(!this._displayList){const b=this._cursorIndexOrder;this._displayList=x.FeatureDisplayList.from(this,this.geometryType,this._records.getCursor(),b)}this._displayList.forEach(a)}};l._sortIndices=function(a){if(this._indicesInvalid){this._indicesInvalid=!1;for(var b=0,c=a.getCursor(),f=this._indexBuffer.getBuffer(),e=[],d=[],g=[];c.next();)d.push(c.index),g.push(c.sortKey),e.push(c.id);d.sort((m,h)=>{const n=g[h],v=g[m];return v===n?e[h]-e[m]:n-v});a=a.getCursor();for(const m of d){if(!a.seekIndex(m))throw Error("Expected to find index");
const {indexFrom:h,indexCount:n}=a;a.indexFrom=b;for(c=0;c<n;c++)this._indexBuffer.set(b++,f[h+c])}this._cursorIndexOrder=d;this._displayList=null}};return u}();p.Geometry=q;Object.defineProperty(p,"__esModule",{value:!0})});