// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define(["exports","./reservedWordsGLSL3","../../chunks/builtins"],function(B,I,x){function J(){function c(n){n.length&&r.push({type:K[f],data:n,position:t,line:C,column:z})}function k(){d=d.length?[]:d;if("/"===g&&"*"===a)return t=p+b-1,f=0,g=a,b+1;if("/"===g&&"/"===a)return t=p+b-1,f=1,g=a,b+1;if("#"===a)return f=2,t=p+b,b;if(/\s/.test(a))return f=9,t=p+b,b;D=/\d/.test(a);E=/[^\w_]/.test(a);t=p+b;f=D?4:E?3:9999;return b}function h(){if(("\r"===a||"\n"===a)&&"\\"!==g)return c(d.join("")),f=999,b;
d.push(a);g=a;return b+1}function e(){if("."===g&&/\d/.test(a))return f=5,b;if("/"===g&&"*"===a)return f=0,b;if("/"===g&&"/"===a)return f=1,b;if("."===a&&d.length){for(;m(d););f=5;return b}if(";"===a||")"===a||"("===a){if(d.length)for(;m(d););c(a);f=999;return b+1}var n=2===d.length&&"\x3d"!==a;if(/[\w_\d\s]/.test(a)||n){for(;m(d););f=999;return b}d.push(a);g=a;return b+1}function m(n){var v=0;do{var F=x.operators.indexOf(n.slice(0,n.length+v).join(""));var y=x.operators[F];if(-1===F){if(0<v--+n.length)continue;
y=n.slice(0,1).join("")}c(y);t+=y.length;d=d.slice(y.length);return d.length}while(1)}function q(){if("."===a||/[eE]/.test(a))return d.push(a),f=5,g=a,b+1;if("x"===a&&1===d.length&&"0"===d[0])return f=11,d.push(a),g=a,b+1;if(/[^\d]/.test(a))return c(d.join("")),f=999,b;d.push(a);g=a;return b+1}function l(){"f"===a&&(d.push(a),g=a,b+=1);if(/[eE]/.test(a)||"-"===a&&/[eE]/.test(g))return d.push(a),g=a,b+1;if(/[^\d]/.test(a))return c(d.join("")),f=999,b;d.push(a);g=a;return b+1}var b=0,p=0,f=999,a,g,
d=[],r=[],C=1,z=0,t=0,D=!1,E=!1,u="",G;return function(n){r=[];if(null!==n){n=n.replace?n.replace(/\r\n/g,"\n"):n;b=0;u+=n;for(G=u.length;a=u[b],b<G;){n=b;switch(f){case 0:"/"===a&&"*"===g?(d.push(a),c(d.join("")),f=999):(d.push(a),g=a);b+=1;break;case 1:b=h();break;case 2:b=h();break;case 3:b=e();break;case 4:b=q();break;case 11:/[^a-fA-F0-9]/.test(a)?(c(d.join("")),f=999):(d.push(a),g=a,b+=1);break;case 5:b=l();break;case 9999:if(/[^\d\w_]/.test(a)){var v=d.join("");f=-1<x.literals.indexOf(v)?8:
-1<x.builtins.indexOf(v)?7:6;c(d.join(""));f=999}else d.push(a),g=a,b+=1;break;case 9:/[^\s]/g.test(a)?(c(d.join("")),f=999):(d.push(a),g=a,b+=1);break;case 999:b=k()}if(n!==b)switch(u[n]){case "\n":z=0;++C;break;default:++z}}p+=b;u=u.slice(b);return r}d.length&&c(d.join(""));f=10;c("(eof)");return r}}function L(c){return c.map(k=>"eof"!==k.type?k.data:"").join("")}function M(c,k="100",h="300 es"){const e=/^\s*#version\s+([0-9]+(\s+[a-zA-Z]+)?)\s*/;for(const m of c)if("preprocessor"===m.type){const q=
e.exec(m.data);if(q){c=q[1].replace(/\s\s+/g," ");if(c===h)return c;if(c===k)return m.data="#version "+h,k;throw Error("unknown glsl version: "+c);}}c.splice(0,0,{type:"preprocessor",data:"#version "+h},{type:"whitespace",data:"\n"});return null}function w(c,k,h,e){e=e||h;for(const m of c)if("ident"===m.type&&m.data===h)return e in k?k[e]++:k[e]=0,w(c,k,e+"_"+k[e],e);return h}function H(c,k,h="afterVersion"){const e={data:"\n",type:"whitespace"},m=l=>l<c.length?/[^\r\n]$/.test(c[l].data):!1;let q=
function(l){let b=-1,p=0,f=-1;for(let g=0;g<l.length;g++){var a=l[g];"preprocessor"===a.type&&(a.data.match(/#(if|ifdef|ifndef)\s+.+/)?++p:a.data.match(/#endif\s*.*/)&&--p);("afterVersion"===h||"afterPrecision"===h)&&"preprocessor"===a.type&&/^#version/.test(a.data)&&(f=Math.max(f,g));if("afterPrecision"===h&&"keyword"===a.type&&"precision"===a.data){a:{for(a=g;a<l.length;a++){const d=l[a];if("operator"===d.type&&";"===d.data)break a}a=null}if(null===a)throw Error("precision statement not followed by any semicolons!");
f=Math.max(f,a)}b<f&&0===p&&(b=g)}return b+1}(c);m(q-1)&&c.splice(q++,0,e);for(const l of k)c.splice(q++,0,l);m(q-1)&&m(q)&&c.splice(q,0,e)}function N(c,k,h,e="lowp"){H(c,[{type:"keyword",data:"out"},{type:"whitespace",data:" "},{type:"keyword",data:e},{type:"whitespace",data:" "},{type:"keyword",data:h},{type:"whitespace",data:" "},{type:"ident",data:k},{type:"operator",data:";"}],"afterPrecision")}function O(c,k,h,e,m="lowp"){H(c,[{type:"keyword",data:"layout"},{type:"operator",data:"("},{type:"keyword",
data:"location"},{type:"whitespace",data:" "},{type:"operator",data:"\x3d"},{type:"whitespace",data:" "},{type:"integer",data:e.toString()},{type:"operator",data:")"},{type:"whitespace",data:" "},{type:"keyword",data:"out"},{type:"whitespace",data:" "},{type:"keyword",data:m},{type:"whitespace",data:" "},{type:"keyword",data:h},{type:"whitespace",data:" "},{type:"ident",data:k},{type:"operator",data:";"}],"afterPrecision")}var K="block-comment line-comment preprocessor operator integer float ident builtin keyword whitespace eof integer".split(" ");
const A=["GL_OES_standard_derivatives","GL_EXT_frag_depth","GL_EXT_draw_buffers","GL_EXT_shader_texture_lod"];B.transpileShader=function(c,k){var h=J(),e=[];e=e.concat(h(c));c=e=e.concat(h(null));if("300 es"===M(c,"100","300 es"))throw Error("shader is already glsl 300 es");e=h=null;const m={},q={};for(let f=0;f<c.length;++f){const a=c[f];switch(a.type){case "keyword":35633===k&&"attribute"===a.data?a.data="in":"varying"===a.data&&(a.data=35633===k?"out":"in");break;case "builtin":/^texture(2D|Cube)(Proj)?(Lod|Grad)?(EXT)?$/.test(a.data.trim())&&
(a.data=a.data.replace(/(2D|Cube|EXT)/g,""));35632===k&&"gl_FragColor"===a.data&&(h||(h=w(c,m,"fragColor"),N(c,h,"vec4")),a.data=h);if(35632===k&&"gl_FragData"===a.data){{var l=void 0;let g=void 0;var b=c;var p=f+1;let d=-1;for(;p<b.length;p++){const r=b[p];if("operator"===r.type&&("["===r.data&&(g=p),"]"===r.data)){l=p;break}"integer"===r.type&&(d=parseInt(r.data,10))}g&&l&&b.splice(g,l-g+1);b=d}l=w(c,m,"fragData");O(c,l,"vec4",b,"mediump");a.data=l}else 35632===k&&"gl_FragDepthEXT"===a.data&&(e||
(e=w(c,m,"gl_FragDepth")),a.data=e);break;case "ident":if(0<=I.indexOf(a.data)){if(b=35633===k)a:{for(b=f-1;0<=b;b--)if(l=c[b],"whitespace"!==l.type&&"block-comment"!==l.type)if("keyword"===l.type){if("attribute"===l.data||"in"===l.data){b=!0;break a}}else break;b=!1}if(b)throw Error("attribute in vertex shader uses a name that is a reserved word in glsl 300 es");a.data in q||(q[a.data]=w(c,m,a.data));a.data=q[a.data]}}}for(k=c.length-1;0<=k;--k)h=c[k],"preprocessor"===h.type&&((e=h.data.match(/#extension\s+(.*):/))&&
e[1]&&0<=A.indexOf(e[1].trim())&&(e=c[k+1],c.splice(k,e&&"whitespace"===e.type?2:1)),(e=h.data.match(/#ifdef\s+(.*)/))&&e[1]&&0<=A.indexOf(e[1].trim())&&(h.data="#if 1"),(e=h.data.match(/#ifndef\s+(.*)/))&&e[1]&&0<=A.indexOf(e[1].trim())&&(h.data="#if 0"));return L(c)};Object.defineProperty(B,"__esModule",{value:!0})});