// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../3d/webgl-engine/lib/OrderIndependentTransparency ./BufferObject ./FramebufferObject ./Program ./renderState ./VertexArrayObject".split(" "),function(O,Q,R,S,T,U,V){var P={exports:{}};(function(g){(function(r){r=r();void 0!==r&&(g.exports=r)})(function(){function r(a){if(null==y){y={};A={};for(var e in a)"number"==typeof a[e]&&(y[a[e]]=e,A[e]=a[e])}}function z(){if(null==y)throw"WebGLDebugUtils.init(ctx) not called";}function u(a){z();var e=y[a];return void 0!==e?"gl."+e:"/*UNKNOWN WebGL ENUM*/ 0x"+
a.toString(16)}function w(a,e,h,d){a=K[a];if(void 0!==a&&(a=a[e],void 0!==a&&a[h])){if("object"===typeof a[h]&&void 0!==a[h].enumBitwiseOr){e=a[h].enumBitwiseOr;h=0;a=[];for(var q=0;q<e.length;++q){var t=A[e[q]];0!==(d&t)&&(h|=t,a.push(u(t)))}return h===d?a.join(" | "):u(d)}return u(d)}return null===d?"null":void 0===d?"undefined":d.toString()}function B(a,e,h){a.__defineGetter__(h,function(){return e[h]});a.__defineSetter__(h,function(d){e[h]=d})}function H(a,e,h,d){function q(p,f){return function(){h&&
h(f,arguments);var C=p[f].apply(p,arguments),l=d.getError();0!=l&&(t[l]=!0,e(l,f,arguments));return C}}d=d||a;r(a);e=e||function(p,f,C){for(var l="",F=C.length,x=0;x<F;++x)l+=(0==x?"":", ")+w(f,F,x,C[x]);p="WebGL error "+u(p)+" in "+f+"("+l+")";window.console&&window.console.error?window.console.error(p):window.console&&window.console.log&&window.console.log(p)};var t={},D={},k;for(k in a)if("function"==typeof a[k])if("getExtension"!=k)D[k]=q(a,k);else{var I=q(a,k);D[k]=function(){var p=I.apply(a,
arguments);return H(p,e,h,d)}}else B(D,a,k);D.getError=function(){for(var p in t)if(t.hasOwnProperty(p)&&t[p])return t[p]=!1,p;return a.NO_ERROR};return D}function J(a){var e=a.getParameter(a.MAX_VERTEX_ATTRIBS),h=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,h);for(var d=0;d<e;++d)a.disableVertexAttribArray(d),a.vertexAttribPointer(d,4,a.FLOAT,!1,0,0),a.vertexAttrib1f(d,0);a.deleteBuffer(h);e=a.getParameter(a.MAX_TEXTURE_IMAGE_UNITS);for(d=0;d<e;++d)a.activeTexture(a.TEXTURE0+d),a.bindTexture(a.TEXTURE_CUBE_MAP,
null),a.bindTexture(a.TEXTURE_2D,null);a.activeTexture(a.TEXTURE0);a.useProgram(null);a.bindBuffer(a.ARRAY_BUFFER,null);a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,null);a.bindFramebuffer(a.FRAMEBUFFER,null);a.bindRenderbuffer(a.RENDERBUFFER,null);a.disable(a.BLEND);a.disable(a.CULL_FACE);a.disable(a.DEPTH_TEST);a.disable(a.DITHER);a.disable(a.SCISSOR_TEST);a.blendColor(0,0,0,0);a.blendEquation(a.FUNC_ADD);a.blendFunc(a.ONE,a.ZERO);a.clearColor(0,0,0,0);a.clearDepth(1);a.clearStencil(-1);a.colorMask(!0,!0,
!0,!0);a.cullFace(a.BACK);a.depthFunc(a.LESS);a.depthMask(!0);a.depthRange(0,1);a.frontFace(a.CCW);a.hint(a.GENERATE_MIPMAP_HINT,a.DONT_CARE);a.lineWidth(1);a.pixelStorei(a.PACK_ALIGNMENT,4);a.pixelStorei(a.UNPACK_ALIGNMENT,4);a.pixelStorei(a.UNPACK_FLIP_Y_WEBGL,!1);a.pixelStorei(a.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!1);a.UNPACK_COLORSPACE_CONVERSION_WEBGL&&a.pixelStorei(a.UNPACK_COLORSPACE_CONVERSION_WEBGL,a.BROWSER_DEFAULT_WEBGL);a.polygonOffset(0,0);a.sampleCoverage(1,!1);a.scissor(0,0,a.canvas.width,
a.canvas.height);a.stencilFunc(a.ALWAYS,0,4294967295);a.stencilMask(4294967295);a.stencilOp(a.KEEP,a.KEEP,a.KEEP);a.viewport(0,0,a.canvas.width,a.canvas.height);for(a.clear(a.COLOR_BUFFER_BIT|a.DEPTH_BUFFER_BIT|a.STENCIL_BUFFER_BIT);a.getError(););}var K={enable:{1:{0:!0}},disable:{1:{0:!0}},getParameter:{1:{0:!0}},drawArrays:{3:{0:!0}},drawElements:{4:{0:!0,2:!0}},createShader:{1:{0:!0}},getShaderParameter:{2:{1:!0}},getProgramParameter:{2:{1:!0}},getShaderPrecisionFormat:{2:{0:!0,1:!0}},getVertexAttrib:{2:{1:!0}},
vertexAttribPointer:{6:{2:!0}},bindTexture:{2:{0:!0}},activeTexture:{1:{0:!0}},getTexParameter:{2:{0:!0,1:!0}},texParameterf:{3:{0:!0,1:!0}},texParameteri:{3:{0:!0,1:!0,2:!0}},texImage2D:{9:{0:!0,2:!0,6:!0,7:!0},6:{0:!0,2:!0,3:!0,4:!0}},texSubImage2D:{9:{0:!0,6:!0,7:!0},7:{0:!0,4:!0,5:!0}},copyTexImage2D:{8:{0:!0,2:!0}},copyTexSubImage2D:{8:{0:!0}},generateMipmap:{1:{0:!0}},compressedTexImage2D:{7:{0:!0,2:!0}},compressedTexSubImage2D:{8:{0:!0,6:!0}},bindBuffer:{2:{0:!0}},bufferData:{3:{0:!0,2:!0}},
bufferSubData:{3:{0:!0}},getBufferParameter:{2:{0:!0,1:!0}},pixelStorei:{2:{0:!0,1:!0}},readPixels:{7:{4:!0,5:!0}},bindRenderbuffer:{2:{0:!0}},bindFramebuffer:{2:{0:!0}},checkFramebufferStatus:{1:{0:!0}},framebufferRenderbuffer:{4:{0:!0,1:!0,2:!0}},framebufferTexture2D:{5:{0:!0,1:!0,2:!0}},getFramebufferAttachmentParameter:{3:{0:!0,1:!0,2:!0}},getRenderbufferParameter:{2:{0:!0,1:!0}},renderbufferStorage:{4:{0:!0,1:!0}},clear:{1:{0:{enumBitwiseOr:["COLOR_BUFFER_BIT","DEPTH_BUFFER_BIT","STENCIL_BUFFER_BIT"]}}},
depthFunc:{1:{0:!0}},blendFunc:{2:{0:!0,1:!0}},blendFuncSeparate:{4:{0:!0,1:!0,2:!0,3:!0}},blendEquation:{1:{0:!0}},blendEquationSeparate:{2:{0:!0,1:!0}},stencilFunc:{3:{0:!0}},stencilFuncSeparate:{4:{0:!0,1:!0}},stencilMaskSeparate:{2:{0:!0}},stencilOp:{3:{0:!0,1:!0,2:!0}},stencilOpSeparate:{4:{0:!0,1:!0,2:!0,3:!0}},cullFace:{1:{0:!0}},frontFace:{1:{0:!0}},drawArraysInstancedANGLE:{4:{0:!0}},drawElementsInstancedANGLE:{5:{0:!0,2:!0}},blendEquationEXT:{1:{0:!0}}},y=null,A=null;return{init:r,mightBeEnum:function(a){z();
return void 0!==y[a]},glEnumToString:u,glFunctionArgToString:w,glFunctionArgsToString:function(a,e){for(var h="",d=e.length,q=0;q<d;++q)h+=(0==q?"":", ")+w(a,d,q,e[q]);return h},makeDebugContext:H,makeLostContextSimulatingCanvas:function(a){function e(c){return"function"==typeof c?c:function(b){c.handleEvent(b)}}function h(){for(var c=Object.keys(E),b=0;b<c.length;++b)delete E[c]}function d(){++G;l||x==G&&a.loseContext()}function q(c,b){var m=c[b];return function(){d();if(!l)return m.apply(c,arguments)}}
function t(c){return{statusMessage:c,preventDefault:function(){L=!0}}}function D(c){for(var b in c)"function"==typeof c[b]?f[b]=q(c,b):B(f,c,b);f.getError=function(){d();if(!l)for(var n;n=k.getError();)E[n]=!0;for(n in E)if(E[n])return delete E[n],n;return f.NO_ERROR};var m="createBuffer createFramebuffer createProgram createRenderbuffer createShader createTexture".split(" ");for(b=0;b<m.length;++b){var v=m[b];f[v]=function(n){return function(){d();if(l)return null;var M=n.apply(c,arguments);M.__webglDebugContextLostId__=
C;F.push(M);return M}}(c[v])}m="getActiveAttrib getActiveUniform getBufferParameter getContextAttributes getAttachedShaders getFramebufferAttachmentParameter getParameter getProgramParameter getProgramInfoLog getRenderbufferParameter getShaderParameter getShaderInfoLog getShaderSource getTexParameter getUniform getUniformLocation getVertexAttrib".split(" ");for(b=0;b<m.length;++b)v=m[b],f[v]=function(n){return function(){d();return l?null:n.apply(c,arguments)}}(f[v]);m="isBuffer isEnabled isFramebuffer isProgram isRenderbuffer isShader isTexture".split(" ");
for(b=0;b<m.length;++b)v=m[b],f[v]=function(n){return function(){d();return l?!1:n.apply(c,arguments)}}(f[v]);f.checkFramebufferStatus=function(n){return function(){d();return l?f.FRAMEBUFFER_UNSUPPORTED:n.apply(c,arguments)}}(f.checkFramebufferStatus);f.getAttribLocation=function(n){return function(){d();return l?-1:n.apply(c,arguments)}}(f.getAttribLocation);f.getVertexAttribOffset=function(n){return function(){d();return l?0:n.apply(c,arguments)}}(f.getVertexAttribOffset);f.isContextLost=function(){return l};
return f}var k,I=[],p=[];var f={};var C=1,l=!1,F=[],x=0,G=0,L=!1,N=0,E={};a.getContext=function(c){return function(){var b=c.apply(a,arguments);if(b instanceof WebGLRenderingContext){if(b!=k){if(k)throw"got different context";k=b;f=D(k)}return f}return b}}(a.getContext);(function(c){var b=c.addEventListener;c.addEventListener=function(m,v,n){switch(m){case "webglcontextlost":I.push(e(v));break;case "webglcontextrestored":p.push(e(v));break;default:b.apply(c,arguments)}}})(a);a.loseContext=function(){if(!l){l=
!0;x=0;for(++C;k.getError(););h();E[k.CONTEXT_LOST_WEBGL]=!0;var c=t("context lost"),b=I.slice();setTimeout(function(){for(var m=0;m<b.length;++m)b[m](c);0<=N&&setTimeout(function(){a.restoreContext()},N)},0)}};a.restoreContext=function(){l&&p.length&&setTimeout(function(){if(!L)throw"can not restore. webglcontestlost listener did not call event.preventDefault";for(var c=0;c<F.length;++c){var b=F[c];b instanceof WebGLBuffer?k.deleteBuffer(b):b instanceof WebGLFramebuffer?k.deleteFramebuffer(b):b instanceof
WebGLProgram?k.deleteProgram(b):b instanceof WebGLRenderbuffer?k.deleteRenderbuffer(b):b instanceof WebGLShader?k.deleteShader(b):b instanceof WebGLTexture&&k.deleteTexture(b)}J(k);l=!1;G=0;L=!1;c=p.slice();b=t("context restored");for(var m=0;m<c.length;++m)c[m](b)},0)};a.loseContextInNCalls=function(c){if(l)throw"You can not ask a lost contet to be lost";x=G+c};a.getNumCalls=function(){return G};a.setRestoreTimeout=function(c){N=c};return a},resetToInitialState:J}})})(P);O.testFloatBufferBlend=function(g){var r,
z,u;if(!g.gl)return!1;if("webgl"===g.webglVersion){var w,B;return(null==(w=g.capabilities.textureFloat)?void 0:w.textureFloat)&&(null==(B=g.capabilities.colorBufferFloat)?void 0:B.textureFloat)}if(!((null==(r=g.capabilities.textureFloat)?0:r.textureFloat)&&(null==(z=g.capabilities.colorBufferFloat)?0:z.textureFloat)&&(null==(u=g.capabilities.colorBufferFloat)?0:u.floatBlend)))return!1;r=new S(g,{colorTarget:0,depthStencilTarget:0},{target:3553,wrapMode:33071,pixelFormat:6408,dataType:5126,internalFormat:34836,
samplingMode:9728,width:1,height:1});z=R.createVertex(g,35044,new Uint16Array([0,0,1,0,0,1,1,1]));u=new V(g,new Map([["a_pos",0]]),{geometry:[{name:"a_pos",count:2,type:5123,offset:0,stride:4,normalized:!1}]},{geometry:z});w=new T.Program(g,"\n  precision highp float;\n  attribute vec2 a_pos;\n\n  void main() {\n    gl_Position \x3d vec4(a_pos * 2.0 - 1.0, 0.0, 1.0);\n  }\n  ","\n   precision highp float;\n\n   void main() {\n    gl_FragColor \x3d vec4(0.5, 0.5, 0.5, 0.5);\n   }\n  ",new Map([["a_pos",
0]]));g.useProgram(w);B=g.getBoundFramebufferObject();const {x:H,y:J,width:K,height:y}=g.getViewport();g.bindFramebuffer(r);g.setViewport(0,0,1,1);g.bindVAO(u);g.drawArrays(5,0,4);var A=U.makePipelineState({blending:Q.blendingAlpha});g.setPipelineState(A);g.drawArrays(5,0,4);P.exports.init(g);A=g.gl.getError();g.setViewport(H,J,K,y);g.bindFramebuffer(B);w.dispose();u.dispose(!1);z.dispose();r.dispose();return 1282===A?(console.warn("Device claims support for WebGL extension EXT_float_blend but does not support it. Using fall back."),
!1):!0};Object.defineProperty(O,"__esModule",{value:!0})});