// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../core/mathUtils ../../core/maybe ./checkWebGLError ./enums ./capabilities/isWebGL2Context".split(" "),function(v,q,r,p,t,w){let u=function(){function g(a,b,c=null){this._context=a;this.type="texture";this._glName=null;this._descriptor=void 0;this._wrapModeDirty=this._samplingModeDirty=!1;a.instanceCounter.increment(t.ResourceType.Texture,this);this._descriptor={target:3553,samplingMode:9729,wrapMode:10497,flipped:!1,hasMipmap:!1,isOpaque:!1,unpackAlignment:4,
preMultiplyAlpha:!1,...b};34067===this._descriptor.target?this.setDataCubeMap(c):this.setData(c)}var l=g.prototype;l.dispose=function(){this._context.gl&&this._glName&&(this._context.unbindTextureAllUnits(this),this._context.gl.deleteTexture(this._glName),this._glName=null,this._context.instanceCounter.decrement(t.ResourceType.Texture,this))};l.release=function(){this.dispose()};l.resize=function(a,b){const c=this._descriptor;if(c.width!==a||c.height!==b)c.width=a,c.height=b,34067===this._descriptor.target?
this.setDataCubeMap(null):this.setData(null)};l.setDataCubeMap=function(a=null){for(let b=34069;34074>=b;b++)this.setData(a,b)};l.setData=function(a,b=3553){if(this._context&&this._context.gl){var c=this._context.gl;this._glName||(this._glName=c.createTexture());void 0===a&&(a=null);null===a&&(this._descriptor.width=this._descriptor.width||4,this._descriptor.height=this._descriptor.height||4);var k=this._context.bindTexture(this,g.TEXTURE_UNIT_FOR_UPDATES),d=this._descriptor;g._validateTexture(this._context,
d);c.pixelStorei(c.UNPACK_ALIGNMENT,d.unpackAlignment);c.pixelStorei(c.UNPACK_FLIP_Y_WEBGL,d.flipped?1:0);c.pixelStorei(c.UNPACK_PREMULTIPLY_ALPHA_WEBGL,d.preMultiplyAlpha?1:0);var h=d.pixelFormat,m=d.internalFormat?d.internalFormat:this._deriveInternalFormat(h,d.dataType);if(a instanceof ImageData||a instanceof HTMLImageElement||a instanceof HTMLCanvasElement||a instanceof HTMLVideoElement){var f=a.width,e=a.height;a instanceof HTMLVideoElement&&(f=a.videoWidth,e=a.videoHeight);c.texImage2D(b,0,
m,h,d.dataType,a);p.checkWebGLError(c);d.hasMipmap&&this.generateMipmap();void 0===d.width&&(d.width=f);void 0===d.height&&(d.height=e)}else{null!=d.width&&null!=d.height||console.error("Width and height must be specified!");c.DEPTH24_STENCIL8&&m===c.DEPTH_STENCIL&&(m=c.DEPTH24_STENCIL8);f=d.width;e=d.height;var n=a;if(r.isSome(n)&&"type"in n&&"compressed"===n.type)for(h=Math.round(Math.log(Math.max(f,e))/Math.LN2)+1,d.hasMipmap=d.hasMipmap&&h===a.levels.length,h=0;;++h){c.compressedTexImage2D(b,
h,m,f,e,0,a.levels[Math.min(h,a.levels.length-1)]);if(1===f&&1===e||!d.hasMipmap)break;f=Math.max(1,f>>1);e=Math.max(1,e>>1)}else if(r.isSome(a))c.texImage2D(b,0,m,f,e,0,h,d.dataType,a),p.checkWebGLError(c),d.hasMipmap&&this.generateMipmap();else for(a=0;;++a){c.texImage2D(b,a,m,f,e,0,h,d.dataType,null);p.checkWebGLError(c);if(1===f&&1===e||!d.hasMipmap)break;f=Math.max(1,f>>1);e=Math.max(1,e>>1)}}g._applySamplingMode(c,this._descriptor);g._applyWrapMode(c,this._descriptor);g._applyAnisotropicFilteringParameters(this._context,
this._descriptor);p.checkWebGLError(c);this._context.bindTexture(k,g.TEXTURE_UNIT_FOR_UPDATES)}};l.updateData=function(a,b,c,k,d,h,m=3553){h||console.error("An attempt to use uninitialized data!");this._glName||console.error("An attempt to update uninitialized texture!");const f=this._context.gl,e=this._descriptor,n=this._context.bindTexture(this,g.TEXTURE_UNIT_FOR_UPDATES);(0>b||0>c||k>e.width||d>e.height||b+k>e.width||c+d>e.height)&&console.error("An attempt to update out of bounds of the texture!");
f.pixelStorei(f.UNPACK_ALIGNMENT,e.unpackAlignment);f.pixelStorei(f.UNPACK_FLIP_Y_WEBGL,e.flipped?1:0);f.pixelStorei(f.UNPACK_PREMULTIPLY_ALPHA_WEBGL,e.preMultiplyAlpha?1:0);h instanceof ImageData||h instanceof HTMLImageElement||h instanceof HTMLCanvasElement||h instanceof HTMLVideoElement?f.texSubImage2D(m,a,b,c,e.pixelFormat,e.dataType,h):f.texSubImage2D(m,a,b,c,k,d,e.pixelFormat,e.dataType,h);this._context.bindTexture(n,g.TEXTURE_UNIT_FOR_UPDATES)};l.generateMipmap=function(){const a=this._descriptor;
a.hasMipmap||(this._samplingModeDirty=a.hasMipmap=!0,g._validateTexture(this._context,a));9729===a.samplingMode?(this._samplingModeDirty=!0,a.samplingMode=9985):9728===a.samplingMode&&(this._samplingModeDirty=!0,a.samplingMode=9984);const b=this._context.bindTexture(this,g.TEXTURE_UNIT_FOR_UPDATES);this._context.gl.generateMipmap(a.target);this._context.bindTexture(b,g.TEXTURE_UNIT_FOR_UPDATES)};l.setSamplingMode=function(a){a!==this._descriptor.samplingMode&&(this._descriptor.samplingMode=a,this._samplingModeDirty=
!0)};l.setWrapMode=function(a){a!==this._descriptor.wrapMode&&(this._descriptor.wrapMode=a,g._validateTexture(this._context,this._descriptor),this._wrapModeDirty=!0)};l.applyChanges=function(){const a=this._context.gl,b=this._descriptor;this._samplingModeDirty&&(g._applySamplingMode(a,b),this._samplingModeDirty=!1);this._wrapModeDirty&&(g._applyWrapMode(a,b),this._wrapModeDirty=!1)};l._deriveInternalFormat=function(a,b){if("webgl"===this._context.webglVersion)return a;switch(b){case 5126:switch(a){case 6408:return 34836;
case 6407:return 34837;default:throw Error("Unable to derive format");}default:return a}};g._validateTexture=function(a,b){(0>b.width||0>b.height)&&console.error("Negative dimension parameters are not allowed!");const c=q.isPowerOfTwo(b.width)&&q.isPowerOfTwo(b.height);w(a.gl)||c||("number"===typeof b.wrapMode?33071!==b.wrapMode&&console.error("Non-power-of-two textures must have a wrap mode of CLAMP_TO_EDGE!"):(33071!==b.wrapMode.s||33071!==b.wrapMode.t)&&console.error("Non-power-of-two textures must have a wrap mode of CLAMP_TO_EDGE!"),
b.hasMipmap&&console.error("Mipmapping requires power-of-two textures!"))};g._applySamplingMode=function(a,b){let c=b.samplingMode,k=b.samplingMode;if(9985===c||9987===c)c=9729,b.hasMipmap||(k=9729);else if(9984===c||9986===c)c=9728,b.hasMipmap||(k=9728);a.texParameteri(b.target,a.TEXTURE_MAG_FILTER,c);a.texParameteri(b.target,a.TEXTURE_MIN_FILTER,k)};g._applyWrapMode=function(a,b){"number"===typeof b.wrapMode?(a.texParameteri(b.target,a.TEXTURE_WRAP_S,b.wrapMode),a.texParameteri(b.target,a.TEXTURE_WRAP_T,
b.wrapMode)):(a.texParameteri(b.target,a.TEXTURE_WRAP_S,b.wrapMode.s),a.texParameteri(b.target,a.TEXTURE_WRAP_T,b.wrapMode.t))};g._applyAnisotropicFilteringParameters=function(a,b){var c;const k=a.capabilities.textureFilterAnisotropic;k&&a.gl.texParameterf(b.target,k.TEXTURE_MAX_ANISOTROPY,null!=(c=b.maxAnisotropy)?c:1)};v._createClass(g,[{key:"glName",get:function(){return this._glName}},{key:"descriptor",get:function(){return this._descriptor}}]);return g}();u.TEXTURE_UNIT_FOR_UPDATES=0;return u});