// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../../../../geometry ../../../../../core/compilerUtils ../../../../../core/Logger ../../../../../core/mathUtils ../../../../../core/maybe ../../../../../core/screenUtils ../../../../../chunks/mat4 ../../../../../chunks/mat4f64 ../../../../../chunks/quat ../../../../../chunks/vec3 ../../../../../chunks/vec3f64 ../../../../../chunks/boundedPlane ../../../../../geometry/support/plane ../../../../../geometry/support/ray ../../../../../geometry/support/vector ../../../../../geometry/support/vectorStacks ../../Manipulator3D ../../manipulatorUtils ./sliceToolConfig ../../visualElements/LineVisualElement ../../visualElements/SlicePlaneVisualElement ../../../support/ElevationProvider ../../../support/geometryUtils/ray ../../../webgl-engine/lib/Geometry ../../../webgl-engine/lib/GeometryUtil ../../../webgl-engine/materials/ColorMaterial ../../../webgl-engine/materials/ImageMaterial ../../../webgl-engine/materials/NativeLineMaterial ../../../webgl-engine/materials/RibbonLineMaterial ../../../../../widgets/Slice/SlicePlane ../../../../../geometry/Point".split(" "),
function(q,ma,X,Y,E,z,K,t,L,R,e,x,y,F,Z,G,l,M,aa,n,ba,ca,da,ea,fa,A,H,ha,N,ia,ja,ka){function S(a,b,d,c,f,h){const g=e.dot(a,b),k=l.sv3d.get(),p=l.sv3d.get();switch(0===c?Math.abs(g)>n.VERTICAL_DOT_THRESHOLD?1:2:c){case 2:e.cross(k,Math.abs(g)<=n.SMALL_ANGLE_DOT_THRESHOLD?a:d.viewUp,b);e.copy(p,b);break;case 1:e.cross(k,d.viewUp,b);e.cross(p,b,k);break;case 3:e.cross(k,Math.abs(g)<=n.SMALL_ANGLE_DOT_THRESHOLD?b:d.viewUp,a),e.cross(p,a,k)}a=e.cross(l.sv3d.get(),k,p);0<e.dot(a,d.viewForward)&&e.scale(p,
p,-1);e.normalize(f,k);e.normalize(h,p)}function O(a,b){switch(b){case 0:return{basis:a.basis1,direction:1,position:e.add(l.sv3d.get(),a.origin,a.basis1),edge:b};case 1:return{basis:a.basis2,direction:1,position:e.add(l.sv3d.get(),a.origin,a.basis2),edge:b};case 2:return{basis:a.basis1,direction:-1,position:e.subtract(l.sv3d.get(),a.origin,a.basis1),edge:b};case 3:return{basis:a.basis2,direction:-1,position:e.subtract(l.sv3d.get(),a.origin,a.basis2),edge:b}}}function P(a,b,d){const c=d.projectToRenderScreen(e.add(l.sv3d.get(),
a,b),K.castRenderScreenPointArray3(l.sv3d.get()));a=d.projectToRenderScreen(e.subtract(l.sv3d.get(),a,b),K.castRenderScreenPointArray3(l.sv3d.get()));return e.squaredLength(e.subtract(c,c,a))}function D(a){const b=e.length(a.basis1);a=e.length(a.basis2);return n.RESIZE_HANDLE_EDGE_PADDING_FRAC*Math.min(b,a)}function I(a){return 0!==a.direction[0]&&0!==a.direction[1]}function T(a,b,d){const c=f=>{const h=(f?b:a).slice(0);var g=e.subtract(l.sv3d.get(),h[0],h[1]);e.normalize(g,g);var k=e.subtract(l.sv3d.get(),
h[h.length-1],h[h.length-2]);e.normalize(k,k);if(0<d.padding){var p=e.scale(x.create(),k,-d.padding);h[h.length-1]=e.add(p,p,h[h.length-1]);d.bothEnds&&(p=e.scale(x.create(),g,-d.padding),h[0]=e.add(p,p,h[0]))}var m=f?d.tipFocusMultiplier:1;p=d.tipLength*(d.focusTipLength?m:1);const v=d.tipRadius*m;m=t.identity(l.sm4d.get());if(0<d.padding){var r=p/4,u=e.set(l.sv3d.get(),0,r,0);r=1+d.padding/r;t.translate(m,m,u);t.scale(m,m,e.set(l.sv3d.get(),r,r,r));t.translate(m,m,e.scale(u,u,-1/r))}r=t.identity(L.create());
u=x.fromValues(0,1,0);k=t.fromQuat(L.create(),R.rotationTo(l.sq4d.get(),u,k));k[12]=h[h.length-1][0];k[13]=h[h.length-1][1];k[14]=h[h.length-1][2];t.multiply(k,k,m);{f=d.tubeRadius*(f?d.tubeFocusMultiplier:1)+d.padding;var w=d.flat;const Q=[];if(z.isSome(w))Q.push([f,w.thickness/2],[-f,w.thickness/2],[-f,-w.thickness/2],[f,-w.thickness/2]);else for(w=0;12>w;w++){const U=w/12*2*Math.PI;Q.push([Math.cos(U)*f,Math.sin(U)*f])}f=A.createPathExtrusionGeometry(Q,h,[],[],!1)}f=[{part:"tube",geometry:f,transform:r}];
let B;z.isSome(d.flat)?r=A.createExtrudedTriangle(p,v,v,d.flat.thickness):(r=A.createConeGeometry(p,v,24,!1,!1,!0),B=A.createConeGeometry(p,v,24,!1,!0,!1));f.push({part:"tip",geometry:r,transform:k});B&&f.push({part:"cap",geometry:B,transform:k});d.bothEnds&&(g=t.fromQuat(L.create(),R.rotationTo(l.sq4d.get(),u,g)),g[12]=h[0][0],g[13]=h[0][1],g[14]=h[0][2],t.multiply(g,g,m),f.push({part:"tip",geometry:r,transform:g}),B&&f.push({part:"cap",geometry:B,transform:g}));return f};return{normal:c(!1),focused:c(!0)}}
function V(a,b){const d=e.subtract(x.create(),a[a.length-1],a[a.length-2]);e.normalize(d,d);e.scale(d,d,n.ROTATE_HEADING_TIP_LENGTH);e.add(d,d,a[a.length-1]);return b?(b=e.subtract(x.create(),a[0],a[1]),e.normalize(b,b),e.scale(b,b,n.ROTATE_HEADING_TIP_LENGTH),e.add(b,b,a[0]),[b,...a,d]):[...a,d]}function W(a,b,d,c,f,h,g=y.create()){if(!h.toRenderCoords(a,g.origin))return la.error(`Failed to project slice plane position, projection from ${a.spatialReference.wkid} is not supported`),null;h.worldBasisAtPosition(g.origin,
0,g.basis1);h.worldBasisAtPosition(g.origin,1,g.basis2);F.fromVectorsAndPoint(g.basis2,g.basis1,g.origin,g.plane);y.rotate(g,-E.deg2rad(b),y.normal(g),g);y.rotate(g,E.deg2rad(d),g.basis1,g);e.scale(g.basis1,g.basis1,c/2);e.scale(g.basis2,g.basis2,f/2);y.updateUnboundedPlane(g);return g}const la=Y.getLogger("esri.views.3d.interactive.analysisTools.slice.sliceToolUtils"),J=Z.create(),C=Math.PI/2;q.DidPointerMoveRecentlyFlag=16;q.IsShiftEdgeOnScreenFlag=32;q.addArrowTips=V;q.calculateBoundedPlaneTranslateRotate=
function(a,b){return aa.calculateTranslateRotateFromBases(a.basis1,a.basis2,a.origin,b)};q.calculateDiagonalResizeHandleScale=function(a){return D(a)};q.calculatePlaneHalfSize=function(a,b){return n.INITIAL_PLANE_HALF_SIZE_VIEW_PROPORTION*Math.min(b.width,b.height)*b.computeRenderPixelSizeAt(a)};q.calculateResizeHandlePadding=D;q.calculateScreenSpaceBasisLength2=P;q.createArrowGeometry=T;q.createGridVisualElement=function(a){return new ca.SlicePlaneVisualElement({view:a,attached:!0,backgroundColor:[...n.PLANE_BACKGROUND_COLOR],
gridColor:n.GRID_COLOR,gridWidth:4,renderOccluded:4})};q.createOutlineVisualElement=function(a){return new ba.LineVisualElement({view:a,attached:!0,color:n.PLANE_OUTLINE_COLOR,width:n.PLANE_OUTLINE_WIDTH,writeDepthEnabled:!1,renderOccluded:4,geometry:[[[-1,-1,0],[1,-1,0],[1,1,0],[-1,1,0],[-1,-1,0]]]})};q.createPlane=function(a,b,d,c,f,h,g,k){g=g.worldUpAtPosition(a,l.sv3d.get());S(b,g,f,h,k.basis1,k.basis2);e.scale(k.basis1,k.basis1,d);e.scale(k.basis2,k.basis2,c);e.copy(k.origin,a);F.fromVectorsAndPoint(k.basis2,
k.basis1,k.origin,k.plane);return k};q.createResizeManipulator=function(a,b){const d=(b=I(b))?[x.fromValues(1,0,0),x.fromValues(0,0,0),x.fromValues(0,1,0)]:[x.fromValues(1,0,0),x.fromValues(-1,0,0)];var c=A.createPolylineGeometry(d);const f=[...n.HANDLE_COLOR,1],h=v=>new ia.RibbonLineMaterial({color:f,width:v,renderOccluded:4}),g=()=>new N.NativeLineMaterial({color:f,renderOccluded:4}),k=b?n.RESIZE_HANDLE_CORNER_WIDTH:n.RESIZE_HANDLE_EDGE_WIDTH,p=k*n.DISPLAY_FOCUS_MULTIPLIER,m=n.RESIZE_HANDLE_EDGE_WIDTH;
c=[{geometry:c,material:1<k?h(k):g(),stateMask:17},{geometry:c,material:1<p?h(p):g(),stateMask:18},{geometry:c,material:1<m?h(m):g(),stateMask:32}];a=new M.Manipulator3D({view:a,renderObjects:c,collisionType:{type:"line",paths:[d]},autoScaleRenderObjects:!1,worldSized:!0,radius:b?n.RESIZE_HANDLE_CORNER_INPUT_RADIUS:n.RESIZE_HANDLE_EDGE_INPUT_RADIUS,idHint:b?1:2});a.state=16;return a};q.createRotateManipulator=function(a,b){var d=new ha.ImageMaterial({transparent:!0,writeDepth:!1,textureId:b.id,renderOccluded:16});
const c=n.ROTATE_HEADING_OFFSET_DISTANCE;b=n.ROTATE_HEADING_DISC_RADIUS;const f=b*n.ROTATE_HEADING_DISC_RADIUS_FOCUS_MULTIPLIER,h=m=>{const v=new Uint32Array([0,1,2,2,3,0]);return new fa.Geometry([["position",{size:3,data:[c-m,-m,0,c+m,-m,0,c+m,m,0,c-m,m,0],exclusive:!0}],["uv0",{size:2,data:[0,0,1,0,1,1,0,1]}]],[["position",v],["uv0",v]])},g=A.createPolylineGeometry([[0,0,0],[c-b,0,0]]),k=A.createPolylineGeometry([[0,0,0],[c-f,0,0]]),p=new N.NativeLineMaterial({color:n.ROTATE_HEADING_CALLOUT_COLOR,
renderOccluded:4});d=[{geometry:h(b),material:d,stateMask:17},{geometry:g,material:p,stateMask:17},{geometry:h(f),material:d,stateMask:18},{geometry:k,material:p,stateMask:18}];return new M.Manipulator3D({view:a,renderObjects:d,autoScaleRenderObjects:!1,collisionType:{type:"disc",direction:[0,0,1],offset:[c,0,0]},collisionPriority:1,radius:b/2,state:16})};q.createRotatePlane=function(a,b,d,c){b=b.worldUpAtPosition(a.origin,l.sv3d.get());const f=l.sv3d.get();switch(d){case 1:e.copy(f,b);break;case 2:e.copy(f,
a.basis1)}return F.fromPositionAndNormal(a.origin,f,c)};q.createShiftManipulator=function(a,b=1){var d=0===b?n.SHIFT_RESTART_OFFSET_DISTANCE:0;const c=[x.fromValues(d,0,-n.SHIFT_RESTART_ARROW_LENGTH/2),x.fromValues(d,0,n.SHIFT_RESTART_ARROW_LENGTH/2)];b=V(c,!0);var f=(u,w)=>T(c,c,{tubeRadius:n.SHIFT_RESTART_TUBE_RADIUS,tipRadius:n.SHIFT_RESTART_TIP_RADIUS,tipLength:n.SHIFT_RESTART_TIP_LENGTH,tubeFocusMultiplier:n.SHIFT_RESTART_TUBE_FOCUS_MULTIPLIER,tipFocusMultiplier:n.SHIFT_RESTART_TIP_FOCUS_MULTIPLIER,
padding:u,bothEnds:!0,flat:null,focusTipLength:!0,addCap:w});const h=f(0,!1);f=f(n.SHIFT_RESTART_ARROW_OUTLINE_WIDTH,!0);const g=new H.ColorMaterial({color:n.SHIFT_RESTART_ARROW_TIP_COLOR,cullFace:2,renderOccluded:16}),k=new H.ColorMaterial({color:n.SHIFT_RESTART_ARROW_CAP_COLOR,cullFace:2,renderOccluded:16}),p=new H.ColorMaterial({color:n.SHIFT_RESTART_TUBE_COLOR,cullFace:2,renderOccluded:16}),m=new H.ColorMaterial({color:n.SHIFT_RESTART_OUTLINE_COLOR,transparent:!0,writeDepth:!1,cullFace:1,renderOccluded:2}),
v=A.createPolylineGeometry([[d,0,0],[d-n.SHIFT_RESTART_OFFSET_DISTANCE,0,0]]);d=A.createPolylineGeometry([[d,0,0],[d-n.SHIFT_RESTART_OFFSET_DISTANCE,0,0]]);const r=new N.NativeLineMaterial({color:n.SHIFT_RESTART_CALLOUT_COLOR,renderOccluded:4});return new M.Manipulator3D({view:a,renderObjects:[...h.normal.map(({part:u,geometry:w,transform:B})=>({geometry:w,material:"tip"===u?g:"cap"===u?k:p,transform:B,stateMask:17})),...f.normal.map(({geometry:u,transform:w})=>({geometry:u,material:m,transform:w,
stateMask:17})),{geometry:v,material:r,stateMask:49},...h.focused.map(({part:u,geometry:w,transform:B})=>({geometry:w,material:"tip"===u?g:"cap"===u?k:p,transform:B,stateMask:18})),...f.focused.map(({geometry:u,transform:w})=>({geometry:u,material:m,transform:w,stateMask:18})),{geometry:d,material:r,stateMask:50}],autoScaleRenderObjects:!1,collisionType:{type:"line",paths:[b]},collisionPriority:1,radius:n.SHIFT_RESTART_TIP_RADIUS,state:16})};q.createShiftPlane=function(a,b,d,c){d=e.cross(l.sv3d.get(),
b,d);e.cross(d,d,b);return F.fromPositionAndNormal(a,d,c)};q.forceHorizontalOrVertical=function(a,b,d){var c=b.worldUpAtPosition(a.origin,l.sv3d.get());b=a.basis1;c=G.angleAroundAxis(c,a.basis2,a.basis1)+C;return y.rotate(a,Math.round(c/C)*C-c,b,d)};q.isAlwaysDrapedLayer=function(a){switch(a.type){case "building-scene":case "csv":case "direct-line-measurement":case "area-measurement":case "feature":case "geo-rss":case "geojson":case "graphics":case "group":case "integrated-mesh":case "kml":case "line-of-sight":case "map-notes":case "ogc-feature":case "point-cloud":case "route":case "slice":case "scene":case "stream":case "voxel":case "subtype-group":case "unknown":case "unsupported":case "wfs":case null:return!1;
case "base-dynamic":case "base-elevation":case "base-tile":case "bing-maps":case "elevation":case "imagery":case "imagery-tile":case "map-image":case "open-street-map":case "tile":case "vector-tile":case "wcs":case "web-tile":case "wms":case "wmts":return!0;default:return X.neverReached(a.type),!1}};q.isDiagonalResizeHandle=I;q.normalToBases=S;q.planeToShape=function(a,b,d,c=new ja){if(z.isNone(a))return null;const f=z.isSome(c.position)?c.position:new ka;b.fromRenderCoords(a.origin,f,d);c.position=
f;d=b.worldUpAtPosition(a.origin,l.sv3d.get());b=b.worldBasisAtPosition(a.origin,1,l.sv3d.get());c.width=2*e.length(a.basis1);c.height=2*e.length(a.basis2);c.tilt=E.rad2deg(G.angleAroundAxis(d,a.basis2,a.basis1)+C);c.heading=E.rad2deg(G.angleAroundAxis(a.basis1,b,d)-C);return c};q.resizeNormal=16;q.resizeOutlineOnly=32;q.resizePlane=function(a,b,d,c,f,h){const g=e.copy(l.sv3d.get(),f.origin);e.add(g,g,e.scale(l.sv3d.get(),f.basis1,0>a.direction[0]?1:-1));e.add(g,g,e.scale(l.sv3d.get(),f.basis2,0>
a.direction[1]?1:-1));var k=e.length(f.basis1);const p=e.length(f.basis2);d=e.subtract(l.sv3d.get(),d,g);var m=e.subtract(l.sv3d.get(),b,g);let v=0;b=0;if(I(a)){var r=D(f);const u=D(h);v=k-.5*a.direction[0]*e.dot(f.basis1,m)/k;b=p-.5*a.direction[1]*e.dot(f.basis2,m)/p;m=u/r;v*=m;b*=m}m=.5*a.direction[0]*e.dot(f.basis1,d)/k;r=.5*a.direction[1]*e.dot(f.basis2,d)/p;d=v+m;b+=r;k=e.scale(l.sv3d.get(),f.basis1,d/k);f=e.scale(l.sv3d.get(),f.basis2,b/p);(0>=d||P(h.origin,k,c)<=n.PLANE_MIN_BASIS_SCREEN_LEN2)&&
e.copy(k,h.basis1);(0>=b||P(h.origin,f,c)<=n.PLANE_MIN_BASIS_SCREEN_LEN2)&&e.copy(f,h.basis2);c=e.copy(l.sv3d.get(),g);e.add(c,c,e.scale(l.sv3d.get(),k,0>a.direction[0]?-1:1));e.add(c,c,e.scale(l.sv3d.get(),f,0>a.direction[1]?-1:1));return y.fromValues(c,k,f,h)};q.shapeToElevationAlignedPlane=function(a,b,d=y.create()){if(z.isNone(a)||z.isNone(a.position))return null;let c=a.position;a.position.hasZ||(c=a.position.clone(),c.z=z.unwrapOr(da.getElevationAtPoint(b.elevationProvider,a.position),0));return W(c,
a.heading,a.tilt,a.width,a.height,b.renderCoordsHelper,d)};q.shapeToPlane=function(a,b,d=y.create()){return z.isNone(a)||z.isNone(a.position)?null:W(a.position,a.heading,a.tilt,a.width,a.height,b,d)};q.updateResizeHandle=function(a,b,d,c){var f=e.length(c.basis1);const h=e.length(c.basis2);var g=D(c);const k=D(c),p=e.set(l.sv3d.get(),0,0,0);e.add(p,e.scale(l.sv3d.get(),c.basis1,b.direction[0]),e.scale(l.sv3d.get(),c.basis2,b.direction[1]));e.add(p,c.origin,p);c=0;let m=1;I(b)?(1===b.direction[0]&&
-1===b.direction[1]?c=C:1===b.direction[0]&&1===b.direction[1]?c=Math.PI:-1===b.direction[0]&&1===b.direction[1]&&(c=3*Math.PI/2),m=k):(c=0!==b.direction[0]?1:2,f=1===c?h:f,c=1===c?C:0,m=f-g);g=t.identity(l.sm4d.get());t.rotateZ(g,g,c);t.scale(g,g,e.set(l.sv3d.get(),m,m,m));t.multiply(g,d,g);g[12]=0;g[13]=0;g[14]=0;a.modelTransform=g;a.renderLocation=p};q.updateRotateHeadingHandle=function(a,b,d,c){c=c.worldUpAtPosition(d.origin,l.sv3d.get());const f=O(d,0),h=t.identity(l.sm4d.get());t.rotateZ(h,
h,f.edge*Math.PI/2);t.rotateX(h,h,-(G.angleAroundAxis(c,d.basis2,d.basis1)+C));t.multiply(h,b,h);h[12]=0;h[13]=0;h[14]=0;a.modelTransform=h;a.renderLocation=f.position};q.updateRotateTiltHandle=function(a,b,d){d=O(d,1);const c=t.identity(l.sm4d.get());t.rotateZ(c,c,d.edge*Math.PI/2);t.rotateX(c,c,C);t.multiply(c,b,c);c[12]=0;c[13]=0;c[14]=0;a.modelTransform=c;a.renderLocation=d.position};q.updateShiftRestartHandle=function(a,b,d,c){var f=O(d,2);const h=l.sm4d.get();t.rotateZ(h,b,f.edge*Math.PI/2);
b=e.normalize(l.sv3d.get(),f.basis);b=e.scale(l.sv3d.get(),b,f.direction*c.computeScreenPixelSizeAt(f.position)*n.SHIFT_RESTART_OFFSET_DISTANCE);e.add(b,b,f.position);f=c.projectToRenderScreen(b,K.castRenderScreenPointArray3(l.sv3d.get()));{const [k,p,m,v]=c.viewport;var g=Math.min(m,v)/16;let r=!0;f[0]<k+g?(f[0]=k+g,r=!1):f[0]>k+m-g&&(f[0]=k+m-g,r=!1);f[1]<p+g?(f[1]=p+g,r=!1):f[1]>p+v-g&&(f[1]=p+v-g,r=!1);g=r}ea.fromRender(c,f,J);e.normalize(J.direction,J.direction);c=l.sv3d.get();!g&&y.intersectRay(d,
J,c)&&(b=c);h[12]=0;h[13]=0;h[14]=0;a.modelTransform=h;a.renderLocation=x.clone(b);a.state=g?a.state|32:a.state&-33};Object.defineProperty(q,"__esModule",{value:!0})});