// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/Logger ../../../../core/mathUtils ../../../../core/maybe ../../../../core/screenUtils ../../../../chunks/vec2 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../geometry/support/lineSegment ../../../../geometry/support/plane ../../support/buffer/InterleavedLayout ../lib/geometryDataUtils ../lib/GLMaterial ../lib/Material ../lib/Util ./VisualVariableMaterialParameters ./renderers/utils ../shaders/RibbonLineTechnique".split(" "),
function(aa,ba,R,S,P,L,ka,h,A,G,r,la,ma,na,ca,oa,pa,qa,T){function da(C,u,b,a,c){for(let k=0;k<c;k++)b[a++]=C[u++];return a}function U(C,u,b){u=u.get("position").data;b=b?b.get("position"):null;return C.isClosed?b?2<b.length:6<u.length:!1}const ra=R.getLogger("esri.views.3d.webgl-engine.materials.RibbonLineMaterial");R=function(C){function u(a){a=C.call(this,a,sa)||this;a._vertexAttributeLocations=T.ribbonVertexAttributeLocations;a.techniqueConfig=new T.RibbonLineTechniqueConfiguration;a.layout=a.createLayout();
return a}ba._inheritsLoose(u,C);var b=u.prototype;b.isClosed=function(a,c){return this.params.isClosed?c?2<c.length:6<a.length:!1};b.dispose=function(){};b.getPassParameters=function(){return this.params};b.getTechniqueConfig=function(a,c){this.techniqueConfig.output=a;a=P.isSome(c)&&23===c.slot;this.techniqueConfig.draped=a;a=P.isSome(this.params.stipplePattern);this.techniqueConfig.stippleEnabled=a;this.techniqueConfig.stippleIntegerRepeatsEnabled=a&&this.params.stippleIntegerRepeats;this.techniqueConfig.stippleOffColorEnabled=
a&&P.isSome(this.params.stippleOffColor);this.techniqueConfig.slicePlaneEnabled=this.params.slicePlaneEnabled;this.techniqueConfig.sceneHasOcludees=this.params.sceneHasOcludees;this.techniqueConfig.roundJoins="round"===this.params.join;this.techniqueConfig.roundCaps="round"===this.params.cap;this.techniqueConfig.transparent=this.params.transparent;this.techniqueConfig.polygonOffset=this.params.polygonOffset;this.techniqueConfig.writeDepth=this.params.writeDepth;this.techniqueConfig.vvColor=this.params.vvColorEnabled;
this.techniqueConfig.vvOpacity=this.params.vvOpacityEnabled;this.techniqueConfig.vvSize=this.params.vvSizeEnabled;this.techniqueConfig.innerColorEnabled=0<this.params.innerWidth&&P.isSome(this.params.innerColor);this.techniqueConfig.falloffEnabled=0<this.params.falloff;this.techniqueConfig.occluder=8===this.params.renderOccluded;this.techniqueConfig.transparencyPassType=c?c.transparencyPassType:3;this.techniqueConfig.multipassTerrainEnabled=c?c.multipassTerrainEnabled:!1;this.techniqueConfig.cullAboveGround=
c?c.cullAboveGround:!1;return this.techniqueConfig};b.intersect=function(a,c,k,e,d,g,f,l,q){q?this.intersectDrapedLineGeometry(a,e,g,f):this.intersectLineGeometry(a,c,k,e,this.params.width,f)};b.intersectDrapedLineGeometry=function(a,c,k,e){if(c.options.selectionMode){c=a.vertexAttributes.get("position").data;var d=a.vertexAttributes.get("size"),g=this.params.width;this.params.vvSizeEnabled?(d=a.vertexAttributes.get("sizeFeatureAttribute").data[0],g*=S.clamp(this.params.vvSizeOffset[0]+d*this.params.vvSizeFactor[0],
this.params.vvSizeMinSize[0],this.params.vvSizeMaxSize[0])):d&&(g*=d.data[0]);d=k[0];k=k[1];a=(g/2+4)*a.screenToWorldRatio;g=Number.MAX_VALUE;for(let m=0;m<c.length-5;m+=3){var f=c[m],l=c[m+1],q=d-f,t=k-l;f=c[m+3]-f;l=c[m+4]-l;const E=S.clamp((f*q+l*t)/(f*f+l*l),0,1);q=f*E-q;t=l*E-t;t=q*q+t*t;t<g&&(g=t)}g<a*a&&e()}};b.intersectLineGeometry=function(a,c,k,e,d,g){if(e.options.selectionMode&&!qa.isInstanceHidden(c))if(oa.isTranslationMatrix(k)){var f=a.vertexAttributes;c=f.get("position").data;if(this.params.vvSizeEnabled){var l=
f.get("sizeFeatureAttribute").data[0];d*=S.clamp(this.params.vvSizeOffset[0]+l*this.params.vvSizeFactor[0],this.params.vvSizeMinSize[0],this.params.vvSizeMaxSize[0])}else f.has("size")&&(d*=f.get("size").data[0]);l=e.camera;var q=ta;ka.copy(q,e.point);d=d*l.pixelRatio/2+4*l.pixelRatio;h.set(Q[0],q[0]-d,q[1]+d,0);h.set(Q[1],q[0]+d,q[1]+d,0);h.set(Q[2],q[0]+d,q[1]-d,0);h.set(Q[3],q[0]-d,q[1]-d,0);for(var t=0;4>t;t++)if(!l.unprojectFromRenderScreen(Q[t],F[t]))return;r.fromPoints(l.eye,F[0],F[1],V);r.fromPoints(l.eye,
F[1],F[2],W);r.fromPoints(l.eye,F[2],F[3],X);r.fromPoints(l.eye,F[3],F[0],Y);t=Number.MAX_VALUE;a=U(this.params,f,a.indices)?c.length-2:c.length-5;for(f=0;f<a;f+=3){y[0]=c[f]+k[12];y[1]=c[f+1]+k[13];y[2]=c[f+2]+k[14];var m=(f+3)%c.length;z[0]=c[m]+k[12];z[1]=c[m+1]+k[13];z[2]=c[m+2]+k[14];if(!(0>r.signedDistance(V,y)&&0>r.signedDistance(V,z)||0>r.signedDistance(W,y)&&0>r.signedDistance(W,z)||0>r.signedDistance(X,y)&&0>r.signedDistance(X,z)||0>r.signedDistance(Y,y)&&0>r.signedDistance(Y,z))){l.projectToRenderScreen(y,
H);l.projectToRenderScreen(z,I);if(0>H[2]&&0<I[2])h.subtract(D,y,z),m=l.frustum,m=-r.signedDistance(m[4],y)/h.dot(D,r.normal(m[4])),h.scale(D,D,m),h.add(y,y,D),l.projectToRenderScreen(y,H);else if(0<H[2]&&0>I[2])h.subtract(D,z,y),m=l.frustum,m=-r.signedDistance(m[4],z)/h.dot(D,r.normal(m[4])),h.scale(D,D,m),h.add(z,z,D),l.projectToRenderScreen(z,I);else if(0>H[2]&&0>I[2])continue;H[2]=0;I[2]=0;m=G.distance2(G.fromPoints(H,I,ea),q);m<t&&(t=m,h.copy(fa,y),h.copy(ha,z))}}k=e.rayBeginPoint;e=e.rayEndPoint;
t<d*d&&(c=Number.MAX_VALUE,G.closestLineSegmentPoint(G.fromPoints(fa,ha,ea),G.fromPoints(k,e,ua),J)&&(h.subtract(J,J,k),c=h.length(J),h.scale(J,J,1/c),c/=h.distance(k,e)),g(c,J))}else ra.error("intersection assumes a translation-only matrix")};b.computeAttachmentOrigin=function(a,c){const k=a.vertexAttributes;if(!k)return null;a=a.indices;const e=k.get("position");return ma.computeAttachmentOriginLines(e,a?a.get("position"):null,a&&U(this.params,k,a),c)};b.createLayout=function(){const a=la.newLayout().vec3f("position").f32("subdivisionFactor").vec2f("uv0").vec3f("auxpos1").vec3f("auxpos2");
this.params.vvSizeEnabled?a.f32("sizeFeatureAttribute"):a.f32("size");this.params.vvColorEnabled?a.f32("colorFeatureAttribute"):a.vec4f("color");this.params.vvOpacityEnabled&&a.f32("opacityFeatureAttribute");return a};b.createBufferWriter=function(){return new va(this.layout,this.params)};b.getGLMaterial=function(a){return 0===a.output||7===a.output||4===a.output||1===a.output?new wa(a):void 0};b.validateParameterValues=function(a){"miter"!==a.join&&(a.miterLimit=0);this.requiresTransparent(a)&&(a.transparent=
!0)};b.requiresTransparent=function(a){return!!(1>(a.color&&a.color[3])||0<a.innerWidth&&this.colorRequiresTransparent(a.innerColor)||a.stipplePattern&&this.colorRequiresTransparent(a.stippleOffColor)||0<a.falloff)};b.colorRequiresTransparent=function(a){return P.isSome(a)&&1>a[3]&&0<a[3]};return u}(ca.Material);let wa=function(C){function u(a){a=C.call(this,a)||this;a.updateParameters();return a}ba._inheritsLoose(u,C);var b=u.prototype;b.updateParameters=function(a){this._technique=this._techniqueRep.releaseAndAcquire(T.RibbonLineTechnique,
this._material.getTechniqueConfig(this._output,a),this._technique)};b.beginSlot=function(a){return 23===a?!0:this._technique.configuration.occluder?3===a||10===a||11===a:0===this._output||7===this._output?(this.targetSlot=this._technique.configuration.writeDepth?5:8,a===this.targetSlot):3===a};b._updateOccludeeState=function(a){a.hasOccludees!==this._material.params.sceneHasOcludees&&this._material.setParameterValues({sceneHasOcludees:a.hasOccludees})};b.ensureParameters=function(a){0!==this._output&&
7!==this._output||this._updateOccludeeState(a);this.updateParameters(a)};b.bind=function(a){this._technique.bindPass(this._material.getPassParameters(),a)};b.getPipelineState=function(a,c){return this._technique.getPipelineState(a,c)};return u}(na);const sa={width:0,color:[1,1,1,1],join:"miter",cap:"butt",miterLimit:5,writeDepth:!0,polygonOffset:!1,stipplePattern:null,stippleIntegerRepeats:!1,stippleOffColor:null,slicePlaneEnabled:!1,vvFastUpdate:!1,transparent:!1,isClosed:!1,falloff:0,innerWidth:0,
innerColor:null,sceneHasOcludees:!1,...ca.materialParametersDefaults,...pa.Default};let va=function(){function C(b,a){this.params=a;this.numJoinSubdivisions=0;this.vertexBufferLayout=b;switch(this.params.join){case "miter":case "bevel":this.numJoinSubdivisions=a.stipplePattern?1:0;break;case "round":this.numJoinSubdivisions=1}}var u=C.prototype;u.isClosed=function(b){return U(this.params,b.vertexAttributes,b.indices)};u.numCapSubdivisions=function(b){if(this.isClosed(b))return 0;switch(this.params.cap){case "butt":return 0;
case "square":return 1;case "round":return 3}};u.allocate=function(b){return this.vertexBufferLayout.createBuffer(b)};u.elementCount=function(b){var a=2*this.numCapSubdivisions(b)+2,c=b.indices.get("position").length/2+1;const k=this.isClosed(b);a=k?2:2*a;var e=k?0:1;c=k?c:c-1;if(b.vertexAttributes.has("subdivisions"))for(b=b.vertexAttributes.get("subdivisions").data;e<c;++e)a+=4+2*b[e];else a+=(c-e)*(2*this.numJoinSubdivisions+4);return a+2};u.write=function(b,a,c,k){const e=xa,d=ya,g=za;var f=a.vertexAttributes.get("position").data,
l=a.indices&&a.indices.get("position");const q=this.numCapSubdivisions(a);l&&l.length!==2*(f.length/3-1)&&console.warn("RibbonLineMaterial does not support indices");l=null;a.vertexAttributes.has("subdivisions")&&(l=a.vertexAttributes.get("subdivisions").data);let t=1,m=0;this.params.vvSizeEnabled?m=a.vertexAttributes.get("sizeFeatureAttribute").data[0]:a.vertexAttributes.has("size")&&(t=a.vertexAttributes.get("size").data[0]);let E=[1,1,1,1],ia=0;this.params.vvColorEnabled?ia=a.vertexAttributes.get("colorFeatureAttribute").data[0]:
a.vertexAttributes.has("color")&&(E=a.vertexAttributes.get("color").data);let ja=0;this.params.vvOpacityEnabled&&(ja=a.vertexAttributes.get("opacityFeatureAttribute").data[0]);const Z=f.length/3;b=b.transformation;const p=new Float32Array(c.buffer);c=this.vertexBufferLayout.stride/4;let n=k*c;k=n;let v=0;const x=(w,K,M,Aa,Ba,Ca,Da,Ea)=>{p[n++]=K[0];p[n++]=K[1];p[n++]=K[2];p[n++]=Aa;p[n++]=Ea;p[n++]=Ca+Ba/10;p[n++]=w[0];p[n++]=w[1];p[n++]=w[2];p[n++]=M[0];p[n++]=M[1];p[n++]=M[2];this.params.vvSizeEnabled?
p[n++]=m:p[n++]=t;this.params.vvColorEnabled?p[n++]=ia:(w=Math.min(4*Da,E.length-4),p[n++]=E[w+0],p[n++]=E[w+1],p[n++]=E[w+2],p[n++]=E[w+3]);this.params.vvOpacityEnabled&&(p[n++]=ja)};n+=c;h.set(d,f[0],f[1],f[2]);b&&h.transformMat4(d,d,b);if(a=this.isClosed(a)){var B=f.length-3;h.set(e,f[B],f[B+1],f[B+2]);b&&h.transformMat4(e,e,b)}else{h.copy(e,d);h.set(g,f[3],f[4],f[5]);b&&h.transformMat4(g,g,b);for(B=0;B<q;++B){var N=1-B/q;x(e,d,g,N,1,-4,0,v);x(e,d,g,N,1,4,0,v)}x(e,d,g,0,0,-4,0,v);x(e,d,g,0,0,4,
0,v);h.copy(e,d);h.copy(d,g)}N=a?0:1;B=a?Z:Z-1;for(let w=N;w<B;w++){var O=(w+1)%Z*3;h.set(g,f[O+0],f[O+1],f[O+2]);b&&h.transformMat4(g,g,b);v+=h.distance(e,d);x(e,d,g,0,1,-1,w,v);x(e,d,g,0,1,1,w,v);O=l?l[w]:this.numJoinSubdivisions;for(let K=0;K<O;++K){const M=(K+1)/(O+1);x(e,d,g,M,1,-2,w,v);x(e,d,g,M,1,2,w,v)}x(e,d,g,1,0,-2,w,v);x(e,d,g,1,0,2,w,v);h.copy(e,d);h.copy(d,g)}if(a)h.set(g,f[3],f[4],f[5]),b&&h.transformMat4(g,g,b),v+=h.distance(e,d),x(e,d,g,0,1,-1,N,v),x(e,d,g,0,1,1,N,v);else for(v+=h.distance(e,
d),x(e,d,g,0,1,-5,B,v),x(e,d,g,0,1,5,B,v),f=0;f<q;++f)l=(f+1)/q,x(e,d,g,l,1,-5,B,v),x(e,d,g,l,1,5,B,v);da(p,k+c,p,k,c);n=da(p,n-c,p,n,c)};return C}();const y=A.create(),z=A.create(),D=A.create(),J=A.create(),ta=A.create(),H=L.createRenderScreenPointArray3(),I=L.createRenderScreenPointArray3(),fa=A.create(),ha=A.create(),ea=G.create(),ua=G.create(),xa=A.create(),ya=A.create(),za=A.create(),Q=[L.createRenderScreenPointArray3(),L.createRenderScreenPointArray3(),L.createRenderScreenPointArray3(),L.createRenderScreenPointArray3()],
F=[A.create(),A.create(),A.create(),A.create()],V=r.create(),W=r.create(),X=r.create(),Y=r.create();aa.RibbonLineMaterial=R;Object.defineProperty(aa,"__esModule",{value:!0})});