// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../geometry ../../Graphic ../../intl ../../symbols ../../core/Handles ../../core/maybe ../../core/unitFormatUtils ../../core/unitUtils ../../core/watchUtils ../../core/accessorSupport/decorators/property ../../core/has ../../core/accessorSupport/ensureType ../../core/Logger ../../core/accessorSupport/decorators/subclass ../../geometry/geometryEngine ../../geometry/projection ../../geometry/support/geodesicUtils ../../layers/GraphicsLayer ../../layers/GroupLayer ../../views/draw/Draw ../../views/interactive/dragEventPipeline ../../views/interactive/GraphicManipulator ../../views/interactive/InteractiveToolBase ../../intl/messages ../../intl/locale ../../geometry/Point ../../symbols/CIMSymbol ../../symbols/TextSymbol ../../symbols/Font ../../symbols/SimpleMarkerSymbol ../../geometry/Polyline ../../geometry/SpatialReference".split(" "),
function(u,y,h,e,z,ca,da,O,v,A,P,E,l,ea,fa,ha,Q,B,n,p,F,R,S,C,T,U,G,V,H,W,X,Y,I,Z,J){function aa(c,d,b,a){const f=new I({style:"circle",color:a.handleColor,size:a.handleWidth,outline:{type:"simple-line",width:0}});a=new I({style:"circle",color:a.handleColor,size:1.5*a.handleWidth,outline:{type:"simple-line",width:0}});c=new z({geometry:c,symbol:f});return new T.GraphicManipulator({view:d,layer:b,graphic:c,focusedSymbol:a})}function K(c,d,b){c=new Z({paths:[c],spatialReference:d});if(d.isGeographic)if(p.isSupported(d))b=
p.geodesicLengths([c],"meters")[0],d=p.geodesicDensify(c,1E5);else{b=n.project(c,J.WGS84);var a=p.geodesicDensify(b,1E5);b=p.geodesicLengths([b],"meters")[0];d=n.project(a,d)}else d.isWebMercator?(b=B.geodesicLength(c,"meters"),d=B.geodesicDensify(c,1E5,"meters")):(a=B.planarLength(c,"meters"),a>=b?(b=n.project(c,J.WGS84),a=p.geodesicDensify(b,1E5),b=p.geodesicLengths([b],"meters")[0],d=n.project(a,d)):(b=a,d=c));return{measurement:{geometry:d,length:b},original:c,drawing:d}}function D(c){if(!c)return!1;
const {isGeographic:d,isWebMercator:b,isWGS84:a}=c;return d&&!a&&!p.isSupported(c)||!d&&!b}function L(c,d,b){if(!d||!c)return null;switch(b){case "metric":return A.formatMetricLength(c,d.length,"meters");case "imperial":return A.formatImperialLength(c,d.length,"meters");default:return A.formatDecimal(c,P.convertUnit(d.length,"meters",b),b)}}e=function(c){function d(){var a=c.apply(this,arguments)||this;a._drawActive=!1;a._handles=new O;a._polylineLayer=new F;a._manipulatorLayer=new F;a._groupLayer=
new R({layers:[a._polylineLayer,a._manipulatorLayer],listMode:"hide",visible:!1});a._vertices=[];a.geodesicDistanceThreshold=1E5;a.measurement=null;a.measurementLabel=null;return a}y._inheritsLoose(d,c);var b=d.prototype;b.initialize=function(){var a=this;G.fetchMessageBundle("esri/core/t9n/Units").then(f=>{this.messages=f});this._handles.add(V.onLocaleChange(y._asyncToGenerator(function*(){a.messages=yield G.fetchMessageBundle("esri/core/t9n/Units")})));this.startToolCreation()};b.destroy=function(){this._draw=
v.destroyMaybe(this._draw);this._handles=v.destroyMaybe(this._handles);this._polylineLayer=v.destroyMaybe(this._polylineLayer);this._manipulatorLayer=v.destroyMaybe(this._manipulatorLayer)};b.onActivate=function(){this._drawActive||0!==this._vertices.length||this._startSketch()};b.onAttach=function(){const a=this.view;this._draw=new S({view:a});a.map.add(this._groupLayer);a.focus();this._handles.add([E.init(this,["unit","geodesicDistanceThreshold","palette","messages"],()=>{0<this._vertices.length&&
this._updatePolylines()}),E.init(this,"view.spatialReference",f=>{D(f)&&!n.isLoaded()&&n.load()})]);this.finishToolCreation()};b.onDetach=function(){const {map:a}=this.view;this._draw.view=null;this._draw=v.destroyMaybe(this._draw);a.remove(this._groupLayer);this._handles.removeAll();this._polylineLayer.removeAll();this._manipulatorLayer.removeAll();this._set("measurement",null);this._set("measurementLabel",null)};b.onShow=function(){this._groupLayer.visible=!0};b.onHide=function(){this._groupLayer.visible=
!1};b.reset=function(){this._vertices=[];this._polylineLayer.removeAll();this._set("measurement",null);this._set("measurementLabel",null);this._draw.reset();this._drawActive=!1;this._updateSketch([])};b._startSketch=function(){this._drawActive=!0;const a=this._draw.create("polyline",{mode:"click"});a.on("vertex-add vertex-update vertex-remove cursor-update undo redo".split(" "),f=>this._updateSketch(f.vertices));a.on("draw-complete",()=>{this._stopSketch()})};b._stopSketch=function(){this.manipulators.forEach(a=>
{a.manipulator.interactive=!0});this._drawActive=!1;this.complete()};b._updateSketch=function(a){if(!D(this.view.spatialReference)||n.isLoaded())if(2>a.length)this._vertices=[],this.manipulators.removeAll(),this._polylineLayer.removeAll();else{this.finishToolCreation();for(var {spatialReference:f}=this.view;this._vertices.length>a.length;){var {manipulatorId:g}=this._vertices.pop();this.manipulators.remove(g)}for(let k=this._vertices.length;k<a.length;k++){const [x,w]=a[k];g=new H({x,y:w,spatialReference:f});
g=aa(g,this.view,this._manipulatorLayer,this.palette);var q=this.manipulators.add(g);C.createManipulatorDragEventPipeline(g,(M,ba)=>{ba.next(C.screenToMap(this.view)).next(C.dragGraphic(M.graphic,2)).next(()=>{const N=M.graphic.geometry;this._vertices[k].coord=[N.x,N.y];this._updatePolylines()})});this._vertices.push({manipulatorId:q,coord:[x,w]})}g=this._vertices.length-1;q=this._vertices[g];var [r,m]=a[g];if(q.coord[0]!==r||q.coord[1]!==m)q.coord=[r,m],a=new H({x:r,y:m,spatialReference:f}),this.manipulators.findById(q.manipulatorId).graphic.geometry=
a;var t=this._drawActive?this._vertices[g].manipulatorId:null;this.manipulators.forEach(k=>{k.manipulator.interactive=null==t||k.id!==t});this._updatePolylines()}};b._updatePolylines=function(){var a=this._vertices.map(k=>k.coord);const {measurement:f,drawing:g,original:q}=K(a,this.view.spatialReference,this.geodesicDistanceThreshold);this._set("measurement",f);a=L(this.messages,f,this.unit);this._set("measurementLabel",a);let r,m;const {graphics:t}=this._polylineLayer;if(2===t.length)r=t.getItemAt(0),
m=t.getItemAt(1);else{const {pathPrimaryColor:k,pathSecondaryColor:x,pathWidth:w}=this.palette;r=new z({symbol:new W({data:{type:"CIMSymbolReference",symbol:{type:"CIMLineSymbol",symbolLayers:[{type:"CIMSolidStroke",effects:[{type:"CIMGeometricEffectDashes",dashTemplate:[14,12],lineDashEnding:"FullGap",controlPointEnding:"NoConstraint"}],enable:!0,capStyle:"Butt",joinStyle:"Round",width:w-1.5,color:x},{type:"CIMSolidStroke",enable:!0,capStyle:"Butt",joinStyle:"Round",width:w,color:k}]}}})});m=new z({symbol:new X({color:[255,
255,255,1],haloColor:[0,0,0,.5],haloSize:2,font:new Y({size:14,family:"sans-serif"})})});t.removeAll();t.addMany([r,m])}r.geometry=g;m.geometry=q.extent.center;m.symbol.text=a};y._createClass(d,[{key:"cursor",get:function(){return this._drawActive?"crosshair":null}},{key:"editable",set:function(a){this._set("editable",a);a||this._draw.reset()}}]);return d}(U.InteractiveToolBase);h.__decorate([l.property()],e.prototype,"_drawActive",void 0);h.__decorate([l.property()],e.prototype,"cursor",null);h.__decorate([l.property({value:!0})],
e.prototype,"editable",null);h.__decorate([l.property({type:Number})],e.prototype,"geodesicDistanceThreshold",void 0);h.__decorate([l.property({readOnly:!0})],e.prototype,"measurement",void 0);h.__decorate([l.property({readOnly:!0})],e.prototype,"measurementLabel",void 0);h.__decorate([l.property()],e.prototype,"messages",void 0);h.__decorate([l.property()],e.prototype,"palette",void 0);h.__decorate([l.property()],e.prototype,"unit",void 0);h.__decorate([l.property({constructOnly:!0})],e.prototype,
"view",void 0);e=h.__decorate([Q.subclass("esri.widgets.DistanceMeasurement2D.DistanceMeasurement2DTool")],e);u.createDistanceMeasurementInfo2D=K;u.createDistanceMeasurementLabel=L;u["default"]=e;u.isSupported=function(c){return null!=c&&(!D(c)||n.isSupported())};Object.defineProperty(u,"__esModule",{value:!0})});