// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../intl ../../../core/Logger ../../../core/maybe ../../../core/string ../../../intl/date ../../../intl/number ../../../layers/support/fieldUtils ../../../popup/support/FieldInfoFormat ../../../support/arcadeOnDemand".split(" "),function(g,l,ja,M,p,q,m,A,N,O,P){function r(){r=l._asyncToGenerator(function*(a,b){return"function"===typeof a?a.call(null,b):a});return r.apply(this,arguments)}function B(a){return C.test(a)}function Q(a,b){if(!B(b)||
!a)return null;const c=b.replace(C,"").toLowerCase();let e;a.some(d=>d.name.toLowerCase()===c?(e=d,!0):!1);return e}function t(a,b){return(b=u(b,a))?b.name:a}function u(a,b){return a&&"function"===typeof a.getField?a.getField(b):null}function D({formattedAttributes:a,template:b,fieldInfoMap:c}){return`${q.replace(q.replace(b,e=>{{const d=c.get(e.toLowerCase());e=`{${d&&d.fieldName||e}}`}return e}),a).replace(R,"")}`.trim()}function S(a,b,c=!1){const e=b[a];"string"===typeof e&&(c=(c?encodeURIComponent(e):
e).replace(T,"%27"),b[a]=c)}function U(a,b=!1){const c={...a};Object.keys(c).forEach(e=>S(e,c,b));return c}function E(a,b){return a.replace(V,(c,e,d)=>(c=u(b,d))?`{${c.name}}`:e)}function W(a,b,c){return(a=E(a,c))?a.replace(X,(e,d,f)=>{d=`${d||f}`.trim();return q.replace(e,U(b,d&&"{"!==d[0]))}):a}function F(a,b){var c=b.fieldName,e=G(b.fieldInfos,c),d=null==e?void 0:e.clone();e=b.preventPlacesFormatting;b=b.layer;c=u(b,c);if(d&&"date"===(null==c?void 0:c.type)){c=d.format||new O;c.dateFormat=c.dateFormat||
"short-date-short-time";var f;if(!(f="feature"===(null==b?void 0:b.type)&&b.datesInUnknownTimezone)){if(f=!(null==b||!b.layer))f=b.layer,f="map-image"===(null==f?void 0:f.type);f=f&&b.layer.datesInUnknownTimezone}c.dateTimeFormatOptions=f?{timeZone:"UTC"}:null;d.format=c}d=d&&d.format;"string"!==typeof a||!d||null!=d.dateFormat||null==d.places&&null==d.digitSeparator||(b=Number(a),isNaN(b)||(a=b));return"string"===typeof a||null==a||null==d?a:e?A.formatNumber(a,{...A.convertNumberFormatToIntlOptions(d),
minimumFractionDigits:0,maximumFractionDigits:20}):d.format(a)}function G(a,b){if(a&&a.length&&b){var c=b.toLowerCase(),e=void 0;a.some(d=>d.fieldName&&d.fieldName.toLowerCase()===c?(e=d,!0):!1);return e}}function Y({fieldName:a,graphic:b,layer:c}){if(v(a)||!c||"function"!==typeof c.getFeatureType)return null;const {typeIdField:e}=c;return e&&a===e?(a=c.getFeatureType(b))?a.name:null:null}function Z({fieldName:a,value:b,graphic:c,layer:e}){return v(a)||!e||"function"!==typeof e.getFieldDomain?null:
(a=e.getFieldDomain(a,{feature:c}))&&"coded-value"===a.type?a.getName(b):null}function H(a){return"string"===typeof a?a.replace(aa,'\x3cbr class\x3d"esri-text-new-line" /\x3e'):a}function ba(a){const {value:b,fieldName:c,fieldInfos:e,fieldInfoMap:d,layer:f,graphic:h}=a;return null==b?"":(a=Z({fieldName:c,value:b,graphic:h,layer:f}))||(a=Y({fieldName:c,graphic:h,layer:f}))?a:d.get(c.toLowerCase())?F(b,{fieldInfos:e,fieldName:c,layer:f}):(a=f&&f.fieldsIndex)&&a.isDateField(c)?m.formatDate(b,w):H(b)}
function ca(a,b){return x.apply(this,arguments)}function x(){x=l._asyncToGenerator(function*(a,b){var c,e;const {layer:d,graphic:f,outFields:h,objectIds:k,returnGeometry:n,spatialReference:da}=a;a=k[0];if("number"!==typeof a&&"string"!==typeof a)return I.warn("Could not query required fields for the specified feature. The feature's ID is invalid.",{layer:d,graphic:f,objectId:a,requiredFields:h}),null;if(null==(c=d.capabilities)||null==(e=c.operations)||!e.supportsQuery)return I.warn("The specified layer cannot be queried. The following fields will not be available.",
{layer:d,graphic:f,requiredFields:h,returnGeometry:n}),null;c=d.createQuery();c.objectIds=k;c.outFields=null!=h&&h.length?h:[d.objectIdField];c.returnGeometry=!!n;c.returnZ=!!n;c.returnM=!!n;c.outSpatialReference=da;return(yield d.queryFeatures(c,b)).features[0]});return x.apply(this,arguments)}function ea(a){return y.apply(this,arguments)}function y(){y=l._asyncToGenerator(function*(a){var b;if(null==(b=a.expressionInfos)||!b.length)return!1;b=yield P.loadArcade();({arcadeUtils:{hasGeometryFunctions:b}}=
b);return b(a)});return y.apply(this,arguments)}function z(){z=l._asyncToGenerator(function*({graphic:a,popupTemplate:b,layer:c,spatialReference:e},d){if(c&&b&&("function"===typeof c.load&&(yield c.load(d)),a.attributes)){var f=a.attributes[c.objectIdField];if(null!=f){f=[f];var h=yield b.getRequiredFields(c.fieldsIndex),k=N.featureHasFields(h,a);h=k?[]:h;b=b.returnGeometry||(yield ea(b));if(!k||b)if(c=yield ca({layer:c,graphic:a,outFields:h,objectIds:f,returnGeometry:b,spatialReference:e},d))c.geometry&&
(a.geometry=c.geometry),c.attributes&&(a.attributes={...a.attributes,...c.attributes})}}});return z.apply(this,arguments)}function v(a=""){return a?-1!==a.indexOf("relationships/"):!1}function J({attributes:a,graphic:b,relatedInfo:c}){a&&b&&c&&Object.keys(b.attributes).forEach(e=>{var d={layerId:c.relation.id.toString(),fieldName:e};a[d?`${"relationships/"}${d.layerId}/${d.fieldName}`:""]=b.attributes[e]})}function fa(a,b){a&&b&&(b.relatedFeatures&&b.relatedFeatures&&b.relatedFeatures.forEach(c=>
J({attributes:a,graphic:c,relatedInfo:b})),b.relatedStatsFeatures&&b.relatedStatsFeatures&&b.relatedStatsFeatures.forEach(c=>J({attributes:a,graphic:c,relatedInfo:b})))}const I=M.getLogger("esri.widgets.Feature.support.featureUtils"),R=/href=(""|'')/gi,V=/(\{([^\{\r\n]+)\})/g,T=/'/g,C=/^\s*expression\//i,aa=/(\n)/gi,ha=/[\u00A0-\u9999<>&]/gim,X=/href\s*=\s*(?:"([^"]+)"|'([^']+)')/gi,ia=/^(?:mailto:|tel:)/,w=m.convertDateFormatToIntlOptions("short-date-short-time"),K=a=>{if(!a)return!1;a=a.toUpperCase();
return-1<a.indexOf("CURRENT_TIMESTAMP")||-1<a.indexOf("CURRENT_DATE")||-1<a.indexOf("CURRENT_TIME")},L=({layer:a,method:b,query:c,definitionExpression:e})=>{var d,f;null!=(d=a.capabilities)&&null!=(f=d.query)&&f.supportsCacheHint&&"attachments"!==b&&(a=p.isSome(c.where)&&c.where,b=p.isSome(c.geometry)&&c.geometry,K(e)||K(a)||"extent"===(null==b?void 0:b.type)||"tile"===c.resultType||(c.cacheHint=!0))};g.applyTextFormattingHTML=H;g.createfieldInfoMap=function(a,b){const c=new Map;a&&a.forEach(e=>{const d=
t(e.fieldName,b);e.fieldName=d;c.set(d.toLowerCase(),e)});return c};g.fixTokens=E;g.formatAttributes=function({fieldInfos:a,attributes:b,layer:c,graphic:e,fieldInfoMap:d,relatedInfos:f}){const h={...b};null==f?void 0:f.forEach(k=>fa(h,k));Object.keys(h).forEach(k=>{h[k]=ba({fieldName:k,fieldInfos:a,fieldInfoMap:d,layer:c,value:h[k],graphic:e})});return h};g.formatEditInfo=function(a,b){const {creatorField:c,creationDateField:e,editorField:d,editDateField:f}=a;if(b){a=b[f];if("number"===typeof a)return b=
b[d],{type:"edit",date:m.formatDate(a,w),user:b};a=b[e];return"number"===typeof a?(b=b[c],{type:"create",date:m.formatDate(a,w),user:b}):null}};g.formatValueToFieldInfo=F;g.getAllFieldInfos=function(a){const b=[];if(!a)return b;const {fieldInfos:c,content:e}=a;c&&b.push(...c);if(!e||!Array.isArray(e))return b;e.forEach(d=>{"fields"===d.type&&(d=d&&d.fieldInfos)&&b.push(...d)});return b};g.getFieldInfo=G;g.getFieldInfoLabel=function(a,b){return(b=Q(b,null==a?void 0:a.fieldName))?b.title||null:a?a.label||
a.fieldName:null};g.getFixedFieldName=t;g.getFixedFieldNames=function(a,b){return a&&a.map(c=>t(c,b))};g.getSourceLayer=function(a){if(!p.isNone(a))return a.get("sourceLayer")||a.get("layer")};g.graphicCallback=function(a,b){return r.apply(this,arguments)};g.htmlEntities=function(a){return a.replace(ha,b=>`&#${b.charCodeAt(0)};`)};g.isExpressionField=B;g.isRelatedField=v;g.preLayerQueryCallback=({query:a,layer:b,method:c})=>{L({layer:b,method:c,query:a,definitionExpression:`${b.definitionExpression} ${b.serviceDefinitionExpression}`})};
g.preRequestCallback=({queryPayload:a,layer:b,method:c})=>{L({layer:b,method:c,query:a,definitionExpression:`${b.definitionExpression} ${b.serviceDefinitionExpression}`})};g.queryUpdatedFeature=function(a,b){return z.apply(this,arguments)};g.shouldOpenInNewTab=function(a=""){if(a)return!ia.test(a.trim().toLowerCase())};g.substituteAttributes=D;g.substituteFieldsInLinksAndAttributes=function({attributes:a,globalAttributes:b,layer:c,text:e,expressionAttributes:d,fieldInfoMap:f}){return e?D({formattedAttributes:b,
template:W(e,{...b,...d,...a},c),fieldInfoMap:f}):""};Object.defineProperty(g,"__esModule",{value:!0})});