// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("require exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/maybe ../core/shaderLibrary/Slice.glsl ../core/shaderLibrary/output/OutputHighlight.glsl ../core/shaderLibrary/shading/MultipassTerrainTest.glsl ../core/shaderLibrary/shading/VisualVariables.glsl ../core/shaderLibrary/util/View.glsl ../core/shaderTechnique/ReloadableShaderModule ../core/shaderTechnique/ShaderTechnique ../core/shaderTechnique/ShaderTechniqueConfiguration ../lib/OrderIndependentTransparency ../lib/Program ../lib/StencilUtils ../../../../chunks/RibbonLine.glsl ../../../webgl/renderState".split(" "),
function(z,q,t,g,u,A,B,C,D,w,e,r,f,n,E,h,F,l){const x=new Map([["position",0],["subdivisionFactor",1],["uv0",2],["auxpos1",3],["auxpos2",4],["size",6],["sizeFeatureAttribute",6],["color",5],["colorFeatureAttribute",5],["opacityFeatureAttribute",7]]);r=function(m){function k(b,d,a){d=m.call(this,b,d,a)||this;d.stippleTextureRepository=b.stippleTextureRepository;return d}t._inheritsLoose(k,m);var c=k.prototype;c.initializeProgram=function(b){var d=k.shader.get();const a=this.configuration;d=d.build({OITEnabled:0===
a.transparencyPassType,output:a.output,slicePlaneEnabled:a.slicePlaneEnabled,sliceHighlightDisabled:!1,sliceEnabledForVertexPrograms:!1,draped:a.draped,stippleEnabled:a.stippleEnabled,stippleOffColorEnabled:a.stippleOffColorEnabled,stippleUVMaxEnabled:a.stippleIntegerRepeatsEnabled,stippleIntegerRepeatsEnabled:a.stippleIntegerRepeatsEnabled,roundCaps:a.roundCaps,roundJoins:a.roundJoins,vvColor:a.vvColor,vvSize:a.vvSize,vvInstancingEnabled:!0,vvOpacity:a.vvOpacity,falloffEnabled:a.falloffEnabled,innerColorEnabled:a.innerColorEnabled,
multipassTerrainEnabled:a.multipassTerrainEnabled,cullAboveGround:a.cullAboveGround});return new E.Program(b.rctx,d,x)};c.dispose=function(){m.prototype.dispose.call(this);this.stippleTextureRepository.release(this.stipplePattern);this.stippleTextureBind=this.stipplePattern=null};c.bindPass=function(b,d){w.bindProjectionMatrix(this.program,d.camera.projectionMatrix);4===this.configuration.output&&B.bindOutputHighlight(this.program,d);d.multipassTerrainEnabled&&(this.program.setUniform2fv("inverseViewport",
d.inverseViewport),C.bindMultipassTerrainTexture(this.program,d));this.program.setUniform1f("intrinsicWidth",b.width);this.program.setUniform4fv("intrinsicColor",b.color);this.program.setUniform1f("miterLimit","miter"!==b.join?0:b.miterLimit);this.program.setUniform2fv("cameraNearFar",d.camera.nearFar);this.program.setUniform1f("pixelRatio",d.camera.pixelRatio);this.program.setUniform2f("screenSize",d.camera.fullViewport[2],d.camera.fullViewport[3]);D.bindVisualVariablesUniformsWithOpacity(this.program,
b);if(this.stipplePattern!==b.stipplePattern){var a=b.stipplePattern;this.stippleTextureBind=this.stippleTextureRepository.swap(this.stipplePattern,a);this.stipplePattern=a}if(this.configuration.stippleEnabled){const {pixelSize:p,sdfNormalizer:v}=u.isSome(this.stippleTextureBind)?this.stippleTextureBind(this.program):{pixelSize:1,sdfNormalizer:1};this.program.setUniform1f("stipplePatternSDFNormalizer",v);this.configuration.draped?(this.program.setUniform1f("stipplePatternPixelSizeInv",1/p),this.program.setUniform1f("worldToScreenRatio",
1/d.screenToWorldRatio)):this.program.setUniform1f("stipplePatternPixelSizeInv",1/(p*d.camera.pixelRatio));this.configuration.stippleOffColorEnabled&&(a=u.unwrap(b.stippleOffColor),this.program.setUniform4f("stippleOffColor",a[0],a[1],a[2],3<a.length?a[3]:1))}this.configuration.falloffEnabled&&this.program.setUniform1f("falloff",b.falloff);this.configuration.innerColorEnabled&&(this.program.setUniform4fv("innerColor",u.unwrapOr(b.innerColor,b.color)),this.program.setUniform1f("innerWidth",b.innerWidth*
d.camera.pixelRatio))};c.bindDraw=function(b){w.bindView(this.program,b);A.bindSliceUniformsWithOrigin(this.program,this.configuration,b);this.program.rebindTextures()};c.setPipelineState=function(b,d){const a=this.configuration,p=3===b,v=2===b;return l.makePipelineState({blending:0===a.output||7===a.output?p?n.blendingDefault:n.OITBlending(b):null,depthTest:{func:n.OITDepthTest(b)},depthWrite:p?!a.transparent&&a.writeDepth&&l.defaultDepthWriteParams:n.OITDepthWrite(b),colorWrite:l.defaultColorWriteParams,
stencilWrite:a.sceneHasOcludees?h.stencilWriteMaskOn:null,stencilTest:a.sceneHasOcludees?d?h.stencilToolMaskBaseParams:h.stencilBaseAllZerosParams:null,polygonOffset:p||v?a.polygonOffset&&y:n.OITPolygonOffset})};c.initializePipeline=function(){const b=this.configuration,d=b.polygonOffset&&y;b.occluder&&(this._occluderPipelineTransparent=l.makePipelineState({blending:n.blendingDefault,polygonOffset:d,depthTest:h.depthCompareAlways,depthWrite:null,colorWrite:l.defaultColorWriteParams,stencilWrite:null,
stencilTest:h.stencilToolTransparentOccluderParams}),this._occluderPipelineOpaque=l.makePipelineState({blending:n.blendingDefault,polygonOffset:d,depthTest:h.depthCompareAlways,depthWrite:null,colorWrite:l.defaultColorWriteParams,stencilWrite:h.stencilWriteMaskOff,stencilTest:h.stencilToolMaskOccluderParams}),this._occluderPipelineMaskWrite=l.makePipelineState({blending:null,polygonOffset:d,depthTest:h.depthCompareLess,depthWrite:null,colorWrite:null,stencilWrite:h.stencilWriteMaskOn,stencilTest:h.stencilToolMaskBaseParams}));
this._occludeePipelineState=this.setPipelineState(this.configuration.transparencyPassType,!0);return this.setPipelineState(this.configuration.transparencyPassType,!1)};c.getPipelineState=function(b,d){return d?this._occludeePipelineState:this.configuration.occluder?11===b?this._occluderPipelineTransparent:10===b?this._occluderPipelineOpaque:this._occluderPipelineMaskWrite:this.pipeline};t._createClass(k,[{key:"primitiveType",get:function(){return 5}}]);return k}(r.ShaderTechnique);r.shader=new e.ReloadableShaderModule(F.RibbonLineShader,
()=>new Promise(function(m,k){z(["./RibbonLine.glsl"],m,k)}));const y={factor:0,units:-4};e=function(m){function k(){var c=m.apply(this,arguments)||this;c.output=0;c.occluder=!1;c.slicePlaneEnabled=!1;c.transparent=!1;c.polygonOffset=!1;c.writeDepth=!1;c.draped=!1;c.stippleEnabled=!1;c.stippleOffColorEnabled=!1;c.stippleIntegerRepeatsEnabled=!1;c.roundCaps=!1;c.roundJoins=!1;c.vvSize=!1;c.vvColor=!1;c.vvOpacity=!1;c.falloffEnabled=!1;c.innerColorEnabled=!1;c.sceneHasOcludees=!1;c.transparencyPassType=
3;c.multipassTerrainEnabled=!1;c.cullAboveGround=!1;return c}t._inheritsLoose(k,m);return k}(f.ShaderTechniqueConfiguration);g.__decorate([f.parameter({count:8})],e.prototype,"output",void 0);g.__decorate([f.parameter()],e.prototype,"occluder",void 0);g.__decorate([f.parameter()],e.prototype,"slicePlaneEnabled",void 0);g.__decorate([f.parameter()],e.prototype,"transparent",void 0);g.__decorate([f.parameter()],e.prototype,"polygonOffset",void 0);g.__decorate([f.parameter()],e.prototype,"writeDepth",
void 0);g.__decorate([f.parameter()],e.prototype,"draped",void 0);g.__decorate([f.parameter()],e.prototype,"stippleEnabled",void 0);g.__decorate([f.parameter()],e.prototype,"stippleOffColorEnabled",void 0);g.__decorate([f.parameter()],e.prototype,"stippleIntegerRepeatsEnabled",void 0);g.__decorate([f.parameter()],e.prototype,"roundCaps",void 0);g.__decorate([f.parameter()],e.prototype,"roundJoins",void 0);g.__decorate([f.parameter()],e.prototype,"vvSize",void 0);g.__decorate([f.parameter()],e.prototype,
"vvColor",void 0);g.__decorate([f.parameter()],e.prototype,"vvOpacity",void 0);g.__decorate([f.parameter()],e.prototype,"falloffEnabled",void 0);g.__decorate([f.parameter()],e.prototype,"innerColorEnabled",void 0);g.__decorate([f.parameter()],e.prototype,"sceneHasOcludees",void 0);g.__decorate([f.parameter({count:4})],e.prototype,"transparencyPassType",void 0);g.__decorate([f.parameter()],e.prototype,"multipassTerrainEnabled",void 0);g.__decorate([f.parameter()],e.prototype,"cullAboveGround",void 0);
q.RibbonLineTechnique=r;q.RibbonLineTechniqueConfiguration=e;q.ribbonVertexAttributeLocations=x;Object.defineProperty(q,"__esModule",{value:!0})});