// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/handleUtils ../../../../../core/maybe ../../../../../core/watchUtils ../../../../../core/accessorSupport/decorators/property ../../../../../core/has ../../../../../core/accessorSupport/ensureType ../../../../../core/Logger ../../../../../core/accessorSupport/decorators/subclass ../../../../../support/elevationInfoUtils ../../../../../symbols/support/ElevationInfo ../../SnappingVisualizer3D ../settings ../../visualElements/OutlineVisualElement ../../visualElements/VerticesVisualElement ../../../layers/graphics/GraphicState ../../../../draw/DrawGraphicTool ../../../../draw/DrawOperation ../../../../draw/drawSurfaces".split(" "),
function(c,r,g,h,d,t,k,C,D,E,u,v,w,x,f,y,m,z,n,A,p){c.DrawGraphicTool3D=function(q){function l(a){a=q.call(this,a)||this;a._activeVertexVisualElement=null;a._createGraphicState=null;a._outlineVisualElement=null;a._verticesVisualElement=null;a.geometryType=null;a.type="draw-3d";return a}r._inheritsLoose(l,q);var e=l.prototype;e.initialize=function(){const {mode:a,offset:b}=this.elevationInfo;this.internalGraphicsLayer.elevationInfo=new w({mode:a,offset:b})};e.normalizeCtorArgs=function(a){if(!a.elevationInfo){var b;
const B=null!=(b=a.hasZ)?b:!0;return{...a,elevationInfo:{mode:B?"absolute-height":"on-the-ground",offset:0}}}return a};e.initializeGraphic=function(a){this._createGraphicState=new z.GraphicState({graphic:a});return h.handlesGroup([this.view.maskOccludee(a),this.view.trackGraphicState(this._createGraphicState),t.init(this._createGraphicState,"isDraped",b=>{d.isSome(this._outlineVisualElement)&&(this._outlineVisualElement.isDraped=b)})])};e.makeDrawOperation=function(){return new A.DrawOperation({view:this.view,
manipulators:this.manipulators,geometryType:n.geometryTypeToDrawOperationGeometryType(this.geometryType),drawingMode:this.mode,hasZ:this.hasZ,defaultZ:this.defaultZ,snapToSceneEnabled:this.snapToScene,drawSurface:new p.SceneDrawSurface(this.view,this.elevationInfo,[this.internalGraphicsLayer]),elevationDrawSurface:new p.ElevationDrawSurface(this.elevationInfo,this.defaultZ,this.view,this.internalGraphicsLayer),hasM:!1,elevationInfo:this.elevationInfo,snappingManager:this.snappingManager,snappingVisualizer:new x.SnappingVisualizer3D})};
e.onActiveVertexChanged=function(a){if(d.isSome(this._activeVertexVisualElement))return this._activeVertexVisualElement.vertices=[a],null;this._activeVertexVisualElement=new m.VerticesVisualElement({view:this.view,spatialReference:this.view.spatialReference,vertices:[a],elevationInfo:this.internalGraphicsLayer.elevationInfo,renderOccluded:f.settings.reshapeManipulators.vertex.renderOccluded,attached:!1});this._activeVertexVisualElement.color=f.settings.colorToVec4(f.settings.reshapeManipulators.selected.color);
this._activeVertexVisualElement.attached=!0;return h.makeHandle(()=>{this._activeVertexVisualElement=d.destroyMaybe(this._activeVertexVisualElement)})};e.onOutlineChanged=function(a){if(d.isSome(this._outlineVisualElement))return this._outlineVisualElement.geometry=a,null;const b=this.internalGraphicsLayer.elevationInfo;this._outlineVisualElement=new y.OutlineVisualElement({view:this.view,geometry:a,elevationInfo:b,isDraped:d.isSome(this._createGraphicState)?this._createGraphicState.isDraped:"on-the-ground"===
v.getEffectiveElevationMode(this.hasZ,b),attached:!1});f.settings.visualElements.lineGraphics.outline.apply(this._outlineVisualElement);f.settings.visualElements.lineGraphics.shadowStyle.apply(this._outlineVisualElement);this._outlineVisualElement.attached=!0;this._outlineVisualElement.laserlineEnabled=!0;return h.makeHandle(()=>{this._outlineVisualElement=d.destroyMaybe(this._outlineVisualElement)})};e.onRegularVerticesChanged=function(a){if(d.isSome(this._verticesVisualElement))return this._verticesVisualElement.vertices=
a,null;this._verticesVisualElement=new m.VerticesVisualElement({view:this.view,spatialReference:this.view.spatialReference,vertices:a,elevationInfo:this.internalGraphicsLayer.elevationInfo,renderOccluded:f.settings.reshapeManipulators.vertex.renderOccluded,attached:!1});this._verticesVisualElement.attached=!0;return h.makeHandle(()=>{this._verticesVisualElement=d.destroyMaybe(this._verticesVisualElement)})};return l}(n.DrawGraphicTool);g.__decorate([k.property({constructOnly:!0})],c.DrawGraphicTool3D.prototype,
"elevationInfo",void 0);g.__decorate([k.property({constructOnly:!0})],c.DrawGraphicTool3D.prototype,"geometryType",void 0);g.__decorate([k.property({readOnly:!0})],c.DrawGraphicTool3D.prototype,"type",void 0);g.__decorate([k.property({constructOnly:!0,nonNullable:!0})],c.DrawGraphicTool3D.prototype,"view",void 0);c.DrawGraphicTool3D=g.__decorate([u.subclass("esri.views.3d.interactive.editingTools.draw.DrawGraphicTool3D")],c.DrawGraphicTool3D);Object.defineProperty(c,"__esModule",{value:!0})});