// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../core/Error ../../../core/events ../../../core/has ../../../core/maybe ../../../core/scheduling ../../../core/watchUtils ../../../chunks/common ../../../chunks/mat2d ../../../chunks/mat2df64 ../../../chunks/mat3f32 ../../../chunks/vec2 ../../../chunks/vec2f64 ../../webgl/BufferObject ../../webgl/FramebufferObject ../../webgl/checkWebGLError ../../webgl/enums ../../../chunks/builtins ../../webgl/programUtils ../../webgl/RenderingContext ../../webgl/Texture ../../webgl/VertexArrayObject ../../webgl/context-util ./Container ./TransformState ./webgl/enums ./webgl/Painter ./webgl/Profiler ./webgl/WebGLDriverTest ./webgl/shaders/StencilPrograms ../support/Timeline ../../support/screenshotUtils".split(" "),
function(B,t,O,P,I,Q,R,S,T,C,U,V,p,v,J,K,L,ea,fa,W,X,ha,Y,Z,M,D,w,aa,ba,ca,N,da,q){L=function(E){function x(a,c){var b=E.call(this)||this;b._trash=new Set;b._clipData=new Float32Array(8);b._upperLeft=v.create();b._upperRight=v.create();b._lowerLeft=v.create();b._lowerRight=v.create();b._mat2=U.create();b._clipRendererInitialized=!1;b._supersampleScreenshots=!0;b._renderRemainingTime=0;b._lastFrameRenderTime=0;b.renderRequested=!1;b.stage=t._assertThisInitialized(b);b._stationary=!0;const {canvas:d=
document.createElement("canvas"),alpha:f=!0,stencil:k=!0,supersampleScreenshots:e=!0,contextOptions:l={}}=c;b._canvas=d;const m=Z.createContextOrErrorHTML(d,1,{alpha:f,antialias:!1,depth:!0,stencil:k});b.context=new X(Q.isSome(m)?m:null,l);b.painter=new aa(b.context,t._assertThisInitialized(b));I("esri-2d-profiler")&&(b._debugOutput=document.createElement("div"),b._debugOutput.setAttribute("style","margin: 24px 64px; position: absolute; color: red;"),a.appendChild(b._debugOutput));b._renderParameters=
{drawPhase:0,state:D.createTransformState(b.state),pixelRatio:window.devicePixelRatio,stationary:!1,globalOpacity:1,blendMode:null,deltaTime:-1,time:0,inFadeTransition:!1,effects:null,context:b.context,painter:b.painter,timeline:c.timeline||new da.Timeline,renderingOptions:c.renderingOptions,requireFBO:!1,driverTestResult:ca.testWebGLDriver(b.context),profiler:new ba.Profiler(b.context,b._debugOutput),dataUploadCounter:0};b._taskHandle=R.addFrameTask({render:h=>b.renderFrame(h)});b._taskHandle.pause();
b._supersampleScreenshots=e;b._lostWebGLContextHandle=P.on(d,"webglcontextlost",()=>{b.emit("webgl-error",{error:new O("webgl-context-lost")})});d.setAttribute("style","width: 100%; height:100%; display:block;");a.appendChild(d);return b}t._inheritsLoose(x,E);var g=x.prototype;g.destroy=function(){this.removeAllChildren();this._emptyTrash();this._taskHandle.remove();this._boundFBO=this._taskHandle=null;this._clipFBO&&(this._clipFBO.dispose(),this._clipFBO=null);this._clipVAO&&(this._clipVAO.dispose(),
this._clipVBO=this._clipVAO=null);this._clipStencilProgram&&(this._clipStencilProgram.dispose(),this._clipStencilProgram=null);this._lostWebGLContextHandle&&(this._lostWebGLContextHandle.remove(),this._lostWebGLContextHandle=null);this._canvas.parentNode&&this._canvas.parentNode.removeChild(this._canvas);this._debugOutput&&this._debugOutput.parentNode&&this._debugOutput.parentNode.removeChild(this._debugOutput);this.highlightOptions=null;this.painter.dispose();this.context.dispose();this._canvas=
null};g.trashDisplayObject=function(a){this._trash.add(a);this.requestRender()};g.untrashDisplayObject=function(a){return this._trash.delete(a)};g.requestRender=function(){this._renderRemainingTime=2E3;this.renderRequested||(this.renderRequested=!0,this.emit("will-render"),this._taskHandle.resume())};g.renderFrame=function(a){this._renderRemainingTime-=this._lastFrameRenderTime?a.time-this._lastFrameRenderTime:0;0>=this._renderRemainingTime&&this._taskHandle.pause();this._lastFrameRenderTime=a.time;
this.renderRequested=!1;this._renderParameters.state=D.createTransformState(this._state);this._renderParameters.stationary=this.stationary;this._renderParameters.pixelRatio=window.devicePixelRatio;this._renderParameters.globalOpacity=1;this._renderParameters.time=a.time;this._renderParameters.deltaTime=a.deltaTime;this._renderParameters.effects=null;this.processRender(this._renderParameters);this._emptyTrash();this.emit("post-render")};g._createTransforms=function(){return{dvs:V.create()}};g.renderChildren=
function(a){for(const c of this.children)c.beforeRender(a);this._renderChildren(this.children,a);for(const c of this.children)c.afterRender(a)};g._renderChildren=function(a,c){const b=this.context;c.profiler.recordStart("drawLayers");c.dataUploadCounter=0;this._beforeRenderChildren(c);c.drawPhase=w.WGLDrawPhase.MAP;this.painter.beforeRenderLayers(b,this.background);for(const d of a)d.processRender(c);this.painter.renderLayers(b);c.drawPhase=w.WGLDrawPhase.HIGHLIGHT;this.painter.beforeRenderLayers(b);
for(const d of a)d.processRender(c);this.painter.renderLayers(b);if(this._isLabelDrawPhaseRequired(a)){c.drawPhase=w.WGLDrawPhase.LABEL;this.painter.beforeRenderLayers(b);for(const d of a)d.processRender(c);this.painter.renderLayers(b)}if(I("esri-tiles-debug")){c.drawPhase=w.WGLDrawPhase.DEBUG;this.painter.beforeRenderLayers(b);for(const d of a)d.processRender(c);this.painter.renderLayers(b)}c.profiler.recordEnd("drawLayers");this._afterRenderChildren()};g._beforeRenderChildren=function(a){const {context:c}=
this,{state:b,pixelRatio:d}=a;c.enforceState();c.setClearDepth(1);c.setClearColor(0,0,0,0);c.clear(c.gl.COLOR_BUFFER_BIT|c.gl.DEPTH_BUFFER_BIT);const {size:f,rotation:k}=b;var e=Math.round(f[0]*d);a=Math.round(f[1]*d);this._boundFBO=c.getBoundFramebufferObject();if(b.spatialReference&&(b.spatialReference._isWrappable?b.spatialReference._isWrappable():b.spatialReference.isWrappable)){var l=T.toRadian(k),m=Math.abs(Math.cos(l)),h=Math.abs(Math.sin(l)),n=Math.round(b.worldScreenWidth);if(Math.round(e*
m+a*h)<=n)this._clipFrame=!1;else{this._clipFBO&&this._clipFBO.width===e&&this._clipFBO.height===a||(this._clipFBO=new K(c,{colorTarget:0,depthStencilTarget:3,width:e,height:a}));var F=(this.state.padding.left-this.state.padding.right)/2,G=(this.state.padding.bottom-this.state.padding.top)/2,r=.5*e,H=.5*a,y=1/e,z=1/a;n=.5*n*d;var A=.5*(e*h+a*m);e=this._upperLeft;m=this._upperRight;h=this._lowerLeft;var u=this._lowerRight;p.set(e,-n,-A);p.set(m,n,-A);p.set(h,-n,A);p.set(u,n,A);C.identity(this._mat2);
C.translate(this._mat2,this._mat2,[r+F,H+G]);0!==k&&C.rotate(this._mat2,this._mat2,l);p.transformMat2d(e,e,this._mat2);p.transformMat2d(m,m,this._mat2);p.transformMat2d(h,h,this._mat2);p.transformMat2d(u,u,this._mat2);l=this._clipData;l.set([2*h[0]*y-1,2*(a-h[1])*z-1,2*u[0]*y-1,2*(a-u[1])*z-1,2*e[0]*y-1,2*(a-e[1])*z-1,2*m[0]*y-1,2*(a-m[1])*z-1]);this._clipRendererInitialized||this._initializeClipRenderer(c);this._clipVBO.setData(l);this._boundFBO=c.getBoundFramebufferObject();c.bindFramebuffer(this._clipFBO);
c.setDepthWriteEnabled(!0);c.setStencilWriteMask(255);c.setClearColor(0,0,0,0);c.setClearDepth(1);c.setClearStencil(0);c.clear(c.gl.COLOR_BUFFER_BIT|c.gl.DEPTH_BUFFER_BIT|c.gl.STENCIL_BUFFER_BIT);c.setDepthWriteEnabled(!1);this._clipFrame=!0}}else this._clipFrame=!1};g._afterRenderChildren=function(){const a=this.context;a.logIno();if(this._clipFrame&&this._clipRendererInitialized){a.bindFramebuffer(this._boundFBO);this._boundFBO=null;a.bindVAO(this._clipVAO);a.useProgram(this._clipStencilProgram);
a.setDepthWriteEnabled(!1);a.setDepthTestEnabled(!1);a.setStencilTestEnabled(!0);a.setBlendingEnabled(!1);a.setColorMask(!1,!1,!1,!1);a.setStencilOp(7680,7680,7681);a.setStencilWriteMask(255);a.setStencilFunction(519,1,255);a.drawElements(4,6,5123,0);a.bindVAO();a.setColorMask(!0,!0,!0,!0);if(null!=this.background){const {r:c,g:b,b:d,a:f}=this.background.color;a.setClearColor(f*c/255,f*b/255,f*d/255,f)}else a.setClearColor(0,0,0,0);a.clear(a.gl.COLOR_BUFFER_BIT);a.setBlendingEnabled(!0);a.setStencilFunction(514,
1,255);this.painter.blitTexture(a,this._clipFBO.colorTexture,9728,1);a.setStencilTestEnabled(!1)}};g.doRender=function(a){const c=this.context,{state:b,pixelRatio:d}=a;this._resizeCanvas(a);this.context.enforceState();c.setViewport(0,0,d*b.size[0],d*b.size[1]);c.setDepthWriteEnabled(!0);c.setStencilWriteMask(255);E.prototype.doRender.call(this,a)};g.takeScreenshot=function(){var a=t._asyncToGenerator(function*(c,b){var d=q.screenshotSuperSampleSettings(c,this._supersampleScreenshots,this._state.padding);
const {framebufferWidth:f,framebufferHeight:k}=d;var e=this.context,l=c.layers;let m=this.children;var h=this._state.clone();if(null!=c.rotation){var n=h.viewpoint;h.viewpoint.rotation=c.rotation;h.viewpoint=n}h={...this._renderParameters,drawPhase:null,globalOpacity:1,stationary:!0,state:D.createTransformState(h),pixelRatio:d.pixelRatio,time:Date.now(),deltaTime:0,blendMode:null,effects:null,inFadeTransition:!1};0<l.length&&(m=[],l.forEach(G=>{const r=b.find(H=>H.layer.id===G.id);r&&"container"in
r&&r.container&&m.push(r.container)}));const F=new K(e,{colorTarget:0,depthStencilTarget:3,width:f,height:k});l=e.getBoundFramebufferObject();n=e.getViewport();e.bindFramebuffer(F);e.setViewport(0,0,f,k);this._renderChildren(m,h);d=this._readbackScreenshot(d);e.bindFramebuffer(l);e.setViewport(n.x,n.y,n.width,n.height);this.requestRender();e=this._ensureScreenshotEncodeCanvas();return q.encodeResult(d,c,e,{flipY:!0,premultipliedAlpha:!0})});return function(c,b){return a.apply(this,arguments)}}();
g._ensureScreenshotEncodeCanvas=function(){this._screenshotEncodeCanvas||(this._screenshotEncodeCanvas=document.createElement("canvas"));return this._screenshotEncodeCanvas};g._readbackScreenshot=function(a){const {framebufferWidth:c,framebufferHeight:b,region:d,resample:f}=a;a=this.context.gl;if(f){var k=q.createEmptyImageData(c,b,this._ensureScreenshotEncodeCanvas());a.readPixels(0,0,c,b,6408,5121,new Uint8Array(k.data.buffer));a=q.createEmptyImageData(d.width,d.height,this._ensureScreenshotEncodeCanvas());
return q.resampleHermite(k,a,!0,f.region.x,b-(f.region.y+f.region.height),f.region.width,f.region.height)}k=q.createEmptyImageData(d.width,d.height,this._ensureScreenshotEncodeCanvas());a.readPixels(d.x,b-(d.y+d.height),d.width,d.height,6408,5121,new Uint8Array(k.data.buffer));return k};g._resizeCanvas=function(a){const c=this._canvas,b=c.style,{state:{size:d},pixelRatio:f}=a;a=d[0];const k=d[1],e=Math.round(a*f),l=Math.round(k*f);if(c.width!==e||c.height!==l)c.width=e,c.height=l;b.width=a+"px";b.height=
k+"px"};g._initializeClipRenderer=function(a){if(this._clipRendererInitialized)return!0;const c=N.stencil.attributes,b=W.createProgram(a,N.stencil);if(!b)return!1;const d=J.createVertex(a,35040,32);var f=new Uint16Array([0,1,2,2,1,3]);f=J.createIndex(a,35044,f);a=new Y(a,c,{geometry:[{name:"a_pos",count:2,type:5126,offset:0,stride:8,normalized:!1,divisor:0}]},{geometry:d},f);this._clipStencilProgram=b;this._clipVBO=d;this._clipVAO=a;return this._clipRendererInitialized=!0};g._emptyTrash=function(){for(;0<
this._trash.size;){const a=Array.from(this._trash);this._trash.clear();for(const c of a)c.processDetach()}};g._isLabelDrawPhaseRequired=function(a){let c=!1;for(const b of a){if(!(b instanceof M.Container)){c=c||!1;break}if(b.hasLabels)return!0;c=c||this._isLabelDrawPhaseRequired(b.children)}return c};t._createClass(x,[{key:"background",get:function(){return this._background},set:function(a){this._background=a;this.requestRender()}},{key:"highlightOptions",get:function(){return this._highlightOptions},
set:function(a){this._highlightOptionsHandle&&(this._highlightOptionsHandle.remove(),this._highlightOptionsHandle=null);if(this._highlightOptions=a)this._highlightOptionsHandle=S.init(this._highlightOptions,"version",()=>{this.painter.setHighlightOptions(a);this.requestRender()})}},{key:"renderingOptions",get:function(){return this._renderingOptions},set:function(a){this._renderingOptions=a;this.requestRender()}},{key:"state",get:function(){return this._state},set:function(a){this._state=a;this.requestRender()}},
{key:"stationary",get:function(){return this._stationary},set:function(a){this._stationary!==a&&(this._stationary=a,this.requestRender())}}]);return x}(M.Container);B.EXTRA_RENDER_TIME=2E3;B.Stage=L;Object.defineProperty(B,"__esModule",{value:!0})});