// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/Handles ../../core/Logger ../../core/maybe ../../core/reactiveUtils ../../core/unitUtils ../../core/watchUtils ../../core/accessorSupport/decorators/property ../../core/has ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ../../properties/defaultUnit ../../views/3d/interactive/measurementTools/directLineMeasurement3D/DirectLineMeasurement3DTool ../support/InteractiveToolViewModel".split(" "),
function(m,f,q,c,e,r,n,t,g,z,A,u,v,w,x){const y=c.getLogger("esri.widgets.DirectLineMeasurement3D.DirectLineMeasurement3DViewModel");c=function(p){function k(a){a=p.call(this,a)||this;a.logger=y;a.supportedViewType="3d";a.unsupportedErrorMessage="DirectLineMeasurement3DViewModel is only supported in 3D views.";a._handles=new q;a._userUnitOptions=null;a._userUnit=null;a.ready=!1;return a}m._inheritsLoose(k,p);var d=k.prototype;d.initialize=function(){this._handles.add([t.init(this,"unit",a=>{e.isSome(this.tool)&&
(this.tool.unit=a)}),r.react(()=>({view:this.view,ready:e.isSome(this.view)&&this.view.ready}),({view:a})=>{this._disconnectFromView();this._connectToView(a)},{sync:!0})]);this._connectToView(this.view)};d.destroy=function(){this._handles=e.destroyMaybe(this._handles)};d.start=function(){return this.createTool()};d.clear=function(){this.removeTool()};d.createToolParams=function(){return{toolConstructor:w,constructorArguments:()=>({unit:this.unit})}};d._findSelectableUnit=function(a,b){const l=this.unitOptions;
return-1!==l.indexOf(a)?a:b?this._findSelectableUnit(b):l[0]};d._filteredOrAllUnits=function(a){if(!a)return n.measurementLengthUnits.slice();a=a.filter(b=>-1!==n.measurementLengthUnits.indexOf(b));return 0===a.length?n.measurementLengthUnits.slice():a};d._connectToView=function(){var a=m._asyncToGenerator(function*(b){e.isSome(b)&&b.ready&&"3d"===b.type&&(this.ready=!0)});return function(b){return a.apply(this,arguments)}}();d._disconnectFromView=function(){this.ready=!1};m._createClass(k,[{key:"state",
get:function(){return this.disabled?"disabled":e.isNone(this.tool)?"ready":this.tool.state}},{key:"measurement",get:function(){if(e.isNone(this.tool))return null;const a={mode:"euclidean",directDistance:{text:null,state:"unavailable"},horizontalDistance:{text:null,state:"unavailable"},verticalDistance:{text:null,state:"unavailable"}};var b=this.tool.measurementView.analysisView;if(e.isNone(b))return a;const l=b.actualVisualizedMeasurement,h=this.tool.measurementView;b=e.isSome(b.result)?"available":
"unavailable";switch(l){case 1:return{mode:"euclidean",directDistance:{text:h.directLabelText,state:b},horizontalDistance:{text:h.horizontalLabelText,state:b},verticalDistance:{text:h.verticalLabelText,state:b}};case 2:return{mode:"geodesic",directDistance:{text:null,state:"unavailable"},horizontalDistance:{text:h.horizontalLabelText,state:b},verticalDistance:{text:h.verticalLabelText,state:b}};default:return a}}},{key:"unitOptions",get:function(){return this._filteredOrAllUnits(this._userUnitOptions)},
set:function(a){this._userUnitOptions=a;this._set("unitOptions",this._filteredOrAllUnits(this._userUnitOptions))}},{key:"unit",get:function(){return this._userUnit?this._userUnit=this._findSelectableUnit(this._userUnit,this.defaultUnit):this._findSelectableUnit(this.defaultUnit)},set:function(a){this._userUnit=a?this._findSelectableUnit(a,this._userUnit):null;this.notifyChange("unit")}}]);return k}(x.InteractiveToolViewModel);f.__decorate([g.property()],c.prototype,"ready",void 0);f.__decorate([g.property({readOnly:!0})],
c.prototype,"state",null);f.__decorate([g.property({readOnly:!0})],c.prototype,"measurement",null);f.__decorate([g.property(v.defaultUnitPropertyMetadata)],c.prototype,"defaultUnit",void 0);f.__decorate([g.property()],c.prototype,"unitOptions",null);f.__decorate([g.property()],c.prototype,"unit",null);return c=f.__decorate([u.subclass("esri.widgets.DirectLineMeasurement3D.DirectLineMeasurement3DViewModel")],c)});