// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/CircularArray ../../../../core/has ../../../../core/maybe ../../../../chunks/mat2d ../../../../chunks/mat2df32 ../../../../chunks/vec2 ../../../../chunks/vec2f32 ./enums ./Utils ./WGLTile ./collisions/MetricReader ./cpuMapped/Geometry".split(" "),function(n,p,q,r,e,k,v,w,x,y,t,z,A,B){let C=0;r=function(g){function h(a,b,c,f){a=g.call(this,a,b,c)||this;a.instanceId=C++;a.patchCount=0;a._renderState={current:{geometry:new Map,
metrics:null},next:null,swap:!1,swapFrames:0,locked:!1};a._patches=new q(100);a._bufferPatches=new q(100);a._lastCommitTime=0;a._lastMessageWasClear=!1;a.transforms.labelMat2d=v.create();a._store=f;return a}p._inheritsLoose(h,g);var d=h.prototype;d.destroy=function(){g.prototype.destroy.call(this);this._renderState.current.geometry.forEach(a=>a.destroy())};d.getGeometry=function(a){return this._renderState.current.geometry.get(a)};d.setTransform=function(a,b){g.prototype.setTransform.call(this,a,
b);const c=this.transforms.labelMat2d;b=a.getScreenTransform(c,b);const f=x.create();w.transformMat2d(f,[this.x,this.y],b);k.identity(c);k.translate(c,c,f);k.multiply(c,a.viewMat2d,c)};d.patch=function(a,b){this.patchCount++;if(!a.clear||!this._lastMessageWasClear){(this._lastMessageWasClear=a.clear)&&50<=this._patches.size&&this._dropPatches();var c=a.addOrUpdate&&this.key.id!==a.addOrUpdate.tileKeyOrigin;b&&c?this._bufferPatches.enqueue(a):(a.sort=a.sort&&!b,this._patches.enqueue(a));this.requestRender()}};
d.commit=function(a){if(this._lastCommitTime!==a.time){this._lastCommitTime=a.time;for(a=0;4>a;a++)this._updateMesh(),this.isReady&&this._updateBufferMesh();this._renderState.swap&&(this._swapRenderStates(),this.requestRender())}};d.lock=function(){this._renderState.locked=!0};d.unlock=function(){this._renderState.locked=!1;this._flushUpdates();this._swap()};d._swapRenderStates=function(){this._renderState.next&&(this._renderState.locked?(this._renderState.swap=!0,this.requestRender()):(this._renderState.swap=
!0,0===this._renderState.swapFrames?(this._renderState.swapFrames=8,this.requestRender()):1!==this._renderState.swapFrames--?this.requestRender():this._swap()))};d._swap=function(){this._renderState.swap&&(this._renderState.swap=!1,e.isSome(this._renderState.next)&&(this._renderState.current.geometry.forEach(a=>a.destroy()),this._renderState.current=this._renderState.next,this._renderState.next=null))};d._flushUpdates=function(){let a=this._patches.maxSize;for(;this._patches.size&&a--;)this._updateMesh(),
this._swap()};d._updateBufferMesh=function(){var a=this._bufferPatches.peek();if(!e.isSome(a)||!a.clear||null===this._renderState.next)for(;this._bufferPatches.size;)a=this._bufferPatches.dequeue(),e.isSome(a)&&this._patchBuffer(a)};d._updateMesh=function(){var a=this._patches.peek();e.isSome(a)&&a.clear&&null!==this._renderState.next||(a=this._patches.dequeue(),e.isSome(a)&&(!0===a.clear?this.isReady&&(this._renderState.next={geometry:new Map,metrics:null}):(this.requestRender(),this._patch(a),a.end&&
(this.ready(),this._swapRenderStates()))))};d._patch=function(a){t.forEachGeometryType(b=>{this._remove(b,a.remove);this._insert(b,a,!1)})};d._patchBuffer=function(a){t.forEachGeometryType(b=>{this._insert(b,a,!0)})};d._insert=function(a,b,c){try{var f;const u=e.unwrapOr(this._renderState.next,this._renderState.current),l=null==(f=b.addOrUpdate)?void 0:f.data[a],m=u.geometry;e.isNone(l)||(m.has(a)||m.set(a,new B.Geometry(a,this.stage)),m.get(a).insert(l,b.sort,c),a===y.WGLGeometryType.LABEL&&this._insertLabelMetrics(b.type,
l.metrics,b.clear))}catch(u){}};d._insertLabelMetrics=function(a,b,c){c=e.unwrapOr(this._renderState.next,this._renderState.current);if(!e.isNone(b))if(b=A.MetricReader.from(b),e.isNone(c.metrics))c.metrics=b;else{if("update"===a)for(a=b.getCursor();a.next();)c.metrics.delete(a.id);c.metrics.link(b)}};d._remove=function(a,b){a=e.unwrapOr(this._renderState.next,this._renderState.current).geometry.get(a);b&&b.length&&a&&(a.remove(b),this._removeLabelMetrics(b))};d._removeLabelMetrics=function(a){const {metrics:b}=
e.unwrapOr(this._renderState.next,this._renderState.current);if(!e.isNone(b)&&a.length)for(const c of a)for(;b.delete(c););};d._dropPatches=function(){const a=[];let b=!1;for(;this._patches.size;){const c=this._patches.dequeue();if(e.isNone(c))break;if(c.clear){if(b)break;b=!0}a.push(c)}this._patches.clear();a.forEach(c=>this._patches.enqueue(c))};p._createClass(h,[{key:"labelMetrics",get:function(){return this._renderState.current.metrics}},{key:"hasData",get:function(){return!!this._renderState.current.geometry.size}}]);
return h}(z.WGLTile);n.FeatureTile=r;Object.defineProperty(n,"__esModule",{value:!0})});