// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.21/esri/copyright.txt for details.
//>>built
define("../../../../chunks/_rollupPluginBabelHelpers ../../../../config ../../../../request ../../../../core/Error ../../../../core/Logger ../../../../core/maybe ../../../../core/promiseUtils ../../../../core/screenUtils ../../../../chunks/vec2 ../../../../chunks/vec2f32 ../../../../symbols/cim/Rasterizer ./definitions ./enums ./fontUtils ./GlyphMosaic ./GlyphSource ./SDFConverter ./SpriteMosaic ./animatedFormats/apng ./animatedFormats/gif ./util/BidiText ./util/Result ./util/symbolUtils ../../../support/QueueProcessor".split(" "),
function(m,I,D,n,J,K,p,w,E,L,M,r,t,N,O,P,Q,R,x,y,S,z,T,U){function V(f){switch(f.type){case "CIMSolidStroke":case "CIMSolidFill":return!0;case "esriSFS":return"esriSFSSolid"===f.style||"esriSFSNull"===f.style;case "esriSLS":return"esriSLSSolid"===f.style||"esriSLSNull"===f.style;default:return!1}}function u(f){switch(f.type){case "esriSMS":case "esriPMS":case "CIMPointSymbol":case "CIMVectorMarker":case "CIMPictureMarker":case "CIMCharacterMarker":return!1;default:return!0}}function F(f){const g=
"maxVVSize"in f&&f.maxVVSize;return g?g:f.width}function W(f,g){return A.apply(this,arguments)}function A(){A=m._asyncToGenerator(function*(f,g){f=f.imageData?`data:${f.contentType};base64,${f.imageData}`:f.url;var e;if(-1!==f.indexOf(";base64,")){g=f.indexOf(";base64,")+8;g=f.substring(g);g=atob(g);f=new Uint8Array(g.length);for(e=0;e<g.length;e++)f[e]=g.charCodeAt(e);e=f.buffer}else try{const {data:a}=yield D(f,{responseType:"array-buffer",...g});e=a}catch(a){if(!p.isAbortError(a))return new n("mapview-invalid-resource",
`Could not fetch requested resource at ${f}`)}return e});return A.apply(this,arguments)}function G(f,g){g=Math.round(w.pt2px(g)*window.devicePixelRatio);return Math.min(f,g*(128<=g?2:4))}const H=L.create(),v=J.getLogger("esri.views.2d.engine.webgl.TextureManager");let X=function(){function f(g,e,a){this.mosaicType=g;this.page=e;this.sdf=a}f.fromMosaic=function(g,e){return new f(g,e.page,e.sdf)};return f}();return function(){function f(e){this._invalidFontsMap=new Map;this._sdfConverter=new Q(126);
this._bindingInfos=[];this._hashToBindingIndex=new Map;this._rasterizer=new M;this._ongoingRasterizations=new Map;this._imageRequestQueue=new U.QueueProcessor({concurrency:10,process:function(){var a=m._asyncToGenerator(function*(b,c){p.throwIfAborted(c);try{return yield D(b,{responseType:"image",signal:c})}catch(d){if(!p.isAbortError(d))throw new n("mapview-invalid-resource",`Could not fetch requested resource at ${b}`,d);throw d;}});return function(b,c){return a.apply(this,arguments)}}()});this._spriteMosaic=
new R(e,2048,2048,500);this._glyphSource=new P(`${I.fontsUrl}/{fontstack}/{range}.pbf`);this._glyphMosaic=new O(1024,1024,this._glyphSource)}var g=f.prototype;g.dispose=function(){this._spriteMosaic.dispose();this._glyphMosaic.dispose();this._rasterizer.dispose();this._sdfConverter.dispose();this._sdfConverter=this._rasterizer=this._glyphMosaic=this._spriteMosaic=null;this._hashToBindingIndex.clear();this._bindingInfos=this._hashToBindingIndex=null;this._ongoingRasterizations.clear();this._ongoingRasterizations=
null;this._imageRequestQueue.clear();this._imageRequestQueue=null};g.rasterizeItem=function(){var e=m._asyncToGenerator(function*(a,b,c,d){if(K.isNone(a))return v.error(new n("mapview-null-resource","Unable to rasterize null resource",void 0)),null;switch(a.type){case "CIMTextSymbol":case "esriTS":return a=yield this._rasterizeText(a,c,d),a.forEach(h=>this._setTextureBinding(t.MosaicType.GLYPH,h)),{glyphMosaicItems:a};default:if(a.type&&-1!==a.type.toLowerCase().indexOf("3d"))return v.error(new n("mapview-invalid-type",
`MapView does not support symbol type: ${a.type}`,a)),null;a=yield this._rasterizeSpriteSymbol(a,b,d);z.ok(a)&&a&&this._setTextureBinding(t.MosaicType.SPRITE,a);return{spriteMosaicItem:a}}});return function(a,b,c,d){return e.apply(this,arguments)}}();g.bindTextures=function(e,a,b,c=!1){if(0!==b.textureBinding){var d=this._bindingInfos[b.textureBinding-1];b=d.page;c=c?9987:9729;switch(d.mosaicType){case t.MosaicType.SPRITE:{d=this.sprites.getWidth(b);const h=this.sprites.getHeight(b);d=E.set(H,d,h);
this._spriteMosaic.bind(e,c,b,r.TEXTURE_BINDING_SPRITE_ATLAS);a.setUniform1i("u_texture",r.TEXTURE_BINDING_SPRITE_ATLAS);a.setUniform2fv("u_mosaicSize",d);break}case t.MosaicType.GLYPH:d=E.set(H,this.glyphs.width,this.glyphs.height);this._glyphMosaic.bind(e,c,b,r.TEXTURE_BINDING_GLYPH_ATLAS);a.setUniform1i("u_texture",r.TEXTURE_BINDING_GLYPH_ATLAS);a.setUniform2fv("u_mosaicSize",d);break;default:v.error("mapview-texture-manager",`Cannot handle unknown type ${d.mosaicType}`)}}};g._hashMosaic=function(e,
a){return 1|e<<1|(a.sdf?1:0)<<2|a.page<<3};g._setTextureBinding=function(e,a){const b=this._hashMosaic(e,a);this._hashToBindingIndex.has(b)||(e=X.fromMosaic(e,a),this._hashToBindingIndex.set(b,this._bindingInfos.length+1),this._bindingInfos.push(e));a.textureBinding=this._hashToBindingIndex.get(b)};g._rasterizeText=function(){var e=m._asyncToGenerator(function*(a,b,c){const d=N.getFullyQualifiedFontName(a.font),h=this._invalidFontsMap.has(d);if(b)a=b;else{a=S.bidiText(a.text)[0];b=[];for(let k=0;k<
a.length;k++)b.push(a.charCodeAt(k));a=b}try{return yield this._glyphMosaic.getGlyphItems(h?"arial-unicode-ms-regular":d,a,c)}catch(k){return v.error(new n("mapview-invalid-resource",`Couldn't find font ${d}. Falling back to Arial Unicode MS Regular`,void 0)),this._invalidFontsMap.set(d,!0),this._glyphMosaic.getGlyphItems("arial-unicode-ms-regular",a,c)}});return function(a,b,c){return e.apply(this,arguments)}}();g._rasterizeSpriteSymbol=function(){var e=m._asyncToGenerator(function*(a,b,c){if(V(a))return null;
b=T.keyFromSymbol(a);if(this._spriteMosaic.has(b))return this._spriteMosaic.getSpriteItem(b);if("esriSMS"===a.type&&a.path||a.url||a.imageData)return this._handleAsyncResource(b,a,c);if(c=this._rasterizer.rasterizeJSONResource(a,1)){const {size:d,image:h,sdf:k,simplePattern:l}=c;return this._addItemToMosaic(b,d,{type:"static",data:h},u(a),k,l)}return new n("TextureManager","unrecognized or null rasterized image")});return function(a,b,c){return e.apply(this,arguments)}}();g._handleAsyncResource=function(){var e=
m._asyncToGenerator(function*(a,b,c){if(this._ongoingRasterizations.has(a))return this._ongoingRasterizations.get(a);b="esriSMS"===b.type&&b.path?this._handleSVG(b,a,c):this._handleImage(b,a,c);this._ongoingRasterizations.set(a,b);try{yield b,this._ongoingRasterizations.delete(a)}catch{this._ongoingRasterizations.delete(a)}return b});return function(a,b,c){return e.apply(this,arguments)}}();g._handleSVG=function(){var e=m._asyncToGenerator(function*(a,b,c){a=yield this._sdfConverter.draw(a.path,c);
return this._addItemToMosaic(b,[126,126],{type:"static",data:new Uint32Array(a.buffer)},!1,!0,!0)});return function(a,b,c){return e.apply(this,arguments)}}();g._handleGIFOrPNG=function(){var e=m._asyncToGenerator(function*(a,b,c){var d=yield W(a,c);if(z.ok(d)){var h=y.isGIF(d);const k=x.isPNG(d);if(!h&&!k)return new n("mapview-invalid-resource","Image data is neither GIF nor PNG!");let l;try{h&&y.isAnimatedGIF(d)?l=yield y["default"].create(d,c):k&&x.isAnimatedPNG(d)&&(l=yield x["default"].create(d,
c))}catch(q){if(!p.isAbortError(q))return new n("mapview-invalid-resource","Could not fetch requested resource!")}if(l&&z.ok(l))return this._addItemToMosaic(b,[l.width,l.height],{type:"animated",data:l},u(a),!1,!1);c=new Blob([d],{type:h?"image/gif":"image/png"});if((c=yield this._imageFromBlob(c))&&c instanceof HTMLImageElement){d=c.width;h=c.height;"esriPMS"===a.type&&(d=Math.round(G(c.width,F(a))),h=Math.round(d/c.width*c.height));const {size:q,sdf:B,image:C}=this._rasterizer.rasterizeImageResource(d,
h,c,a.colorSubstitutions);return this._addItemToMosaic(b,q,{type:"static",data:C},u(a),B,!1)}}return new n("mapview-invalid-resource","Could not handle resource!")});return function(a,b,c){return e.apply(this,arguments)}}();g._handleImage=function(){var e=m._asyncToGenerator(function*(a,b,c){var d;(d=a.url&&-1!==a.url.indexOf(".gif")||a.contentType&&"image/gif"===a.contentType||a.imageData&&-1!==a.imageData.indexOf("data:image/gif"))||(d=a.url&&-1!==a.url.indexOf(".png")||a.contentType&&"image/png"===
a.contentType||a.imageData&&-1!==a.imageData.indexOf("data:image/png"));if(d)return this._handleGIFOrPNG(a,b,c);d=a.imageData?`data:${a.contentType};base64,${a.imageData}`:a.url;try{const {data:h}=yield this._imageRequestQueue.push(d,{...c});-1!==d.indexOf("data:image/svg+xml")&&(h.width=w.pt2px(a.width),h.height=w.pt2px(a.height));let k=h.width,l=h.height;"esriPMS"===a.type&&(k=Math.round(G(h.width,F(a))),l=Math.round(k/h.width*h.height));const {size:q,sdf:B,image:C}=this._rasterizer.rasterizeImageResource(k,
l,h,a.colorSubstitutions);return this._addItemToMosaic(b,q,{type:"static",data:C},u(a),B,!1)}catch(h){if(!p.isAbortError(h))return new n("mapview-invalid-resource",`Could not fetch requested resource at ${d}. ${h.message}`)}});return function(a,b,c){return e.apply(this,arguments)}}();g._imageFromBlob=function(){var e=m._asyncToGenerator(function*(a){a=window.URL.createObjectURL(a);try{const {data:b}=yield this._imageRequestQueue.push(a);window.URL.revokeObjectURL(a);return b}catch(b){window.URL.revokeObjectURL(a);
if(!p.isAbortError(b))return new n("mapview-invalid-resource",`Could not fetch requested resource at ${a}`);throw b;}});return function(a){return e.apply(this,arguments)}}();g._addItemToMosaic=function(e,a,b,c,d,h){return this._spriteMosaic.addSpriteItem(e,a,b,c,d,h)};m._createClass(f,[{key:"sprites",get:function(){return this._spriteMosaic}},{key:"glyphs",get:function(){return this._glyphMosaic}}]);return f}()});